### PR TITLE
Fix AbstractRelations::buildUniqueKeyForAppending()

### LINKED ISSUE #16397: [Bug]: Batch action in grid not working anymore with "advanced relations" fields
### Pimcore version

11.1.3

### Steps to reproduce

1) Open any grid
2) Use a advanced relation field, and select "Batch action" (like add a relation to all selected elemens)
image

3) Add a new element as relation
4) Apply changes

### Actual Behavior

Fails with hard php error:
`Uncaught Error: Pimcore\Model\DataObject\ClassDefinition\Data\AdvancedManyToManyObjectRelation::buildUniqueKeyForAppending(): Argument #1 ($item) must be of type Pimcore\Model\Element\ElementInterface, Pimcore\Model\DataObject\Data\ObjectMetadata given, called in /php/vendor/pimcore/pimcore/models/DataObject/ClassDefinition/Data/Relations/AbstractRelations.php on line 268`

### Expected Behavior

Working, appending data to advanced relation fields.

The problem is "appendData" using relation Models "ObjectMetaaata" but  "buildUniqueKeyForAppending" allowing only objects
Starting point in application is: \Pimcore\Bundle\AdminBundle\Controller\Admin\DataObject\DataObjectHelperController::batchAction

### PR DESCRIPTION
**Pull request by blankse**
## Changes in this pull request  
Resolves https://github.com/pimcore/pimcore/issues/16397
Alternative to https://github.com/pimcore/pimcore/pull/16405

### CODE REVIEW

File: models/DataObject/ClassDefinition/Data.php [hunk 1]
```diff
@@ -1232,12 +1232,18 @@ public function adoptMainDefinition(DataObject\ClassDefinition\Data $mainDefinit
...
+    public function appendData(?array $existingData, array $additionalData): array
     {
         return $existingData;
     }
 
-    public function removeData(mixed $existingData, mixed $removeData): mixed
+    /**
+     * @throws \LogicException
+     */
+    public function removeData(?array $existingData, array $removeData): array
```
Comment (kingjia90) [inline models/DataObject/ClassDefinition/Data.php]: looks fine for return type, but for parameters, should we keep `mixed` and trigger a deprecation first?

File: models/DataObject/ClassDefinition/Data.php [hunk 2]
```diff
@@ -1232,12 +1232,18 @@ public function adoptMainDefinition(DataObject\ClassDefinition\Data $mainDefinit
         }
     }
 
-    public function appendData(?array $existingData, array $additionalData): ?array
+    /**
+     * @throws \LogicException
+     */
+    public function appendData(?array $existingData, array $additionalData): array
```
Comment (kingjia90) [inline models/DataObject/ClassDefinition/Data.php]: isn't the return type change a BC-break?

**Review by kingjia90 — COMMENTED** [review]
The rest LGTM

File: models/DataObject/ClassDefinition/Data.php (hunk 1 above)
Comment (blankse) [reply models/DataObject/ClassDefinition/Data.php]: @kingjia90 mixed isn't possible, because of the usage of foreach, right? Or did you mean when someone overwrite the method? Than this should also possible with mixed instead of array, right?

File: models/DataObject/ClassDefinition/Data.php (hunk 2 above)
Comment (blankse) [reply models/DataObject/ClassDefinition/Data.php]: It always returns array. We can keep `?array` for BC reason and add a TODO to change it in Pimcore 12.

File: models/DataObject/ClassDefinition/Data.php (hunk 1 above)
Comment (kingjia90) [reply models/DataObject/ClassDefinition/Data.php]: Yes, i was thinking about overwritten methods, devs won't be able to detect this change "in time" and correct it accordingly, but doesn't seem a big deal.

File: models/DataObject/ClassDefinition/Data.php (hunk 2 above)
Comment (kingjia90) [reply models/DataObject/ClassDefinition/Data.php]: In case of custom classes extending this method (still having `?array`), it would crash due the declaration incompatibility

Comment (blankse) [reply models/DataObject/ClassDefinition/Data.php]: I changed it back and add a TODO: https://github.com/pimcore/pimcore/pull/16458/commits/6281f48ae71ebbd27ef9b2bab0a21cad09e0bdee

File: models/DataObject/ClassDefinition/Data.php (hunk 1 above)
Comment (blankse) [reply models/DataObject/ClassDefinition/Data.php]: But when the dev have a overwrite method, a deprecation warning in this method won't work either.

Comment (kingjia90) [reply models/DataObject/ClassDefinition/Data.php]: Mhh true, then nevermind, it should be fine as is
