### PR TITLE
PageSippet: set/remove editable loses existing elements on save

### LINKED ISSUE #6992: PageSippet: set/remove editable loses existing elements on save
Steps to reproduce:

```
$doc = Document::getById(99);
$doc->setEditable("somekey", "somedata");    // it doesn't check if existing editables are already loaded, so overwrites them ...
$doc->save();
```

see also https://github.com/pimcore/pimcore/pull/6982

### PR DESCRIPTION
**Pull request by weisswurstkanone**
resolves #6992

### CODE REVIEW

File: models/Document/PageSnippet.php [hunk 1]
```diff
@@ -604,6 +606,7 @@ public function getElements()
     public function getEditables(): array
     {
         if ($this->editables === null) {
+            $this->editables = [];
```
Comment (brusch) [inline models/Document/PageSnippet.php:609]: This shouldn't be necessary since `$this->getDao()->getEditables()` always returns an array, right?

**Review by brusch — CHANGES_REQUESTED** [review]

File: models/Document/PageSnippet.php (hunk 1 above)
Comment (weisswurstkanone) [reply models/Document/PageSnippet.php:609]: Yes, but since $this->editables is not initialized (i.e. null) and getEditables calls setEditable this will result in an endless recursion otherwise. See https://github.com/pimcore/pimcore/pull/6991#issue-473165647

Comment (jdreesen) [reply models/Document/PageSnippet.php:609]: No, it doesn't call `setEditable` but `setEditables` which just sets the field. I don't see why this should result in an endless loop.

Comment (brusch) [reply models/Document/PageSnippet.php:609]: @weisswurstkanone is right, with this PR `setEditable()` is again calling `getEditables()` which would result in an endless loop.

Comment (brusch) [reply models/Document/PageSnippet.php:609]: But I'm wondering why this is happening, ... it should be sufficient if `\Pimcore\Model\Document\PageSnippet\Dao::getEditables()` just returns the editables ... calling `setEditable()` first and then calling `PageSnippet::setEditables()` with the return value of `Dao::getEditables()` sounds a bit weird to me.

**Comment by weisswurstkanone** [comment]
image

File: models/Document/PageSnippet.php (hunk 1 above)
Comment (msphn) [reply models/Document/PageSnippet.php:609]: why not initialise editables as an empty array? otherwise the strict type change will fail here anyway

**Comment by weisswurstkanone** [comment]
$this->editable === null currently indicates that the editabes haven't been loaded and this still needs to be done.
I can think of a dedicated flag instead ....

File: models/Document/PageSnippet/Dao.php [hunk 2]
```diff
@@ -54,9 +54,10 @@ public function getEditables()
             $editable->setDataFromResource($editableRaw['data']);
 
             $editables[$editableRaw['name']] = $editable;
-            $this->model->setEditable($editableRaw['name'], $editable);
         }
 
+        $this->model->setEditables($editables);
```
Comment (brusch) [inline models/Document/PageSnippet/Dao.php:59]: I guess this can go as well ... since the caller uses the return value anyway: 
https://github.com/pimcore/pimcore/blob/338cd24e38090c8a13e0580228aa32b62f5bc860/models/Document/PageSnippet.php#L608

Comment (jdreesen) [reply models/Document/PageSnippet/Dao.php:59]: In line 77/78 `$this->model->setVersions($versions);` should be removed, too, as it's the same.

Comment (jdreesen) [reply models/Document/PageSnippet/Dao.php:59]: But actually... this pattern of setting the value on the from from inside the DAO is used in most of the DAO implementations... so maybe it should still be done - consistency wise - even if it's redundant...

Comment (brusch) [reply models/Document/PageSnippet/Dao.php:59]: But then we should remove it from the other place, ... calling the same thing twice for nothing doesn't make sense 😉

Comment (jdreesen) [reply models/Document/PageSnippet/Dao.php:59]: That's right. But maybe in a follow-up PR as it's not really related to this fix and might be a bigger changeset.

Comment (brusch) [reply models/Document/PageSnippet/Dao.php:59]: you're right, this doesn't belong to this PR
