### PR TITLE
[Bug] Classification Store - Call to undefined function

### LINKED ISSUE #14983: [Bug]: Classification Store - Call to undefined function
### Expected behavior

Saving the `name` field should work without errors

### Actual behavior

Saving throws an error: 
`Call to undefined method set____pimcore_cache_item__ in class Pimcore\Model\DataObject\Classificationstore\CollectionConfig`

### Steps to reproduce

1. Create a `collection`, `group` or `key`
2. give it a name (only [a-z] chars)
3. ---- see that saving works ----
4. add a special char (or integer) to the name 
5. saving will fail now with the following error: `Call to undefined method set____pimcore_cache_item__ in class Pimcore\Model\DataObject\Classificationstore\CollectionConfig`

### PR DESCRIPTION
**Pull request by mcop1**
Resolves #14983

`getById` can and will return a classification store config from the cache. Since we returned the whole object to the front end the cache key was included. To fix this, we just return the necessary values instead of the whole configuration object.

### CODE REVIEW

**Comment by Corepex** [comment]
@mcop1 we should do the same here: 

https://github.com/pimcore/pimcore/blob/8d217cc7f1948eb6eb0a9b973630c0a1e4973109/bundles/AdminBundle/Controller/Admin/DataObject/ClassificationstoreController.php#L539

**Comment by NiklasBr** [comment]
Is `$config->getObjectVars()` usable here?

**Comment by mcop1** [comment]
> Is `$config->getObjectVars()` usable here?

Unfortunately not, same problem

File: bundles/AdminBundle/Controller/Admin/DataObject/ClassificationstoreController.php [hunk 1]
```diff
@@ -1403,6 +1393,28 @@ protected function getConfigItem($config): array
         return $item;
     }
 
+    /**
+     * @param Classificationstore\KeyConfig $config
+     *
+     * @return array
+     */
+    protected function getKeyConfigItem($config): array
```
Comment (blankse) [inline bundles/AdminBundle/Controller/Admin/DataObject/ClassificationstoreController.php]: Why not use type hint for param?

Comment (mcop1) [reply bundles/AdminBundle/Controller/Admin/DataObject/ClassificationstoreController.php]: Good point, added them for both methods, since the class is internal and the methods are protected anyways

**Comment by dvesh3** [comment]
@mcop1 please provide changes on https://github.com/pimcore/admin-ui-classic-bundle

**Comment by lukmzig** [comment]
> @mcop1 please provide changes on https://github.com/pimcore/admin-ui-classic-bundle
PR is here:
https://github.com/pimcore/admin-ui-classic-bundle/pull/75
