### PR TITLE
[Tags] server side filtering

### LINKED ISSUE #4725: Tag filter in assets search
# Bug Report

### Expected behavior
Being able to search for tags lower than the 5th level.

### Actual behavior
ext-all.js throwing an error in the console and no results are shown.
```
too much recursion
```
Furthermore the admin site has to be refreshed when closing the "Search Asset"-panel after the error occured, because the admin site isn't usable afterwards.
The same error occurs when using the "Search Documents" or "Search Objects"-panel.

### Steps to reproduce
1. create tags down to the 5th level:
grafik
2. open the "Filter for Tags" in "Search Assets"-panel
3. search for the tag on the 5th level:
grafik

**Edit:** I just noticed that the error only occurs when the tag-tree wasn't opened before. And it fails when opening the 3rd level.

### PR DESCRIPTION
**Pull request by dvesh3**
## Changes in this pull request  
Resolves #4725

also considered https://github.com/pimcore/pimcore/issues/4195 https://github.com/pimcore/pimcore/issues/4473

### CODE REVIEW

File: bundles/AdminBundle/Controller/Admin/TagsController.php [hunk 1]
```diff
@@ -125,9 +126,30 @@ public function treeGetChildrenByIdAction(Request $request)
         }
         $tagList->setOrderKey('name');
 
+        if(!empty($request->get('filter'))) {
+            $filterIds = [0];
+            $filterTagList = new Tag\Listing();
+            $filterTagList->setCondition('`name` LIKE "%'.$request->get('filter').'%"');
```
Comment (weisswurstkanone) [inline bundles/AdminBundle/Controller/Admin/TagsController.php]: SQL injection possible. Please properly quote the filter.
Example: http://pimcore-demo-basic.pim.zone/admin/tags/tree-get-children-by-id?_dc=1580295370027&showSelection=false&assignmentCId=&assignmentCType=&node=0&filter=%22;%20DROP%20TABLE%20objects;%20SELECT%20*%20FROM%20users%20WHERE%20name%20LIKE%20%22

will drop the objects table
