### PR TITLE
[DataObjects] Fix adding multiple objectbricks on update

### LINKED ISSUE #15547: [Bug]: When I try to add a new object brick to a published object and click on publish i get the error "Call to a member function getClass() on null"
### Pimcore version

version 11.0

### Steps to reproduce

Create a new Object
Add an object brick to it
Click on save and publish
Add another object brick
Click on save and publish it throws an error

### Expected / actual behavior

_No response_

### PR DESCRIPTION
**Pull request by dvesh3**
## Changes in this pull request  
Resolves #15547

## Additional info
tests will be fixed by https://github.com/pimcore/pimcore/pull/15543

### <samp>🤖 Generated by Copilot at ad414fa</samp>

Added support for loading object bricks from serialized data in `Objectbrick` class and improved code readability and consistency in `Dao` class.

### <samp>🤖 Generated by Copilot at ad414fa</samp>

> _Oh we are the coders of the `Objectbrick` class_
> _We load and save our data with a bit of sass_
> _We use the `??` operator and cast to boolean_
> _And format our SQL queries to make them clean_

### <samp>🤖 Generated by Copilot at ad414fa</samp>

*  Change type of `object` property and `setObject` parameter to allow `ElementDescriptor` in `Objectbrick` class ([link](https://github.com/pimcore/pimcore/pull/15548/files?diff=unified&w=0#diff-0a5b70799b5caaa32011d78d907e4156d1b627d54d9411f5c58e0e6c3fb257c2L47-R49))
*  Convert `ElementDescriptor` to `Concrete` object in `setObject` method of `Objectbrick` class ([link](https://github.com/pimcore/pimcore/pull/15548/files?diff=unified&w=0#diff-0a5b70799b5caaa32011d78d907e4156d1b627d54d9411f5c58e0e6c3fb257c2L198-R203))
*  Refactor and format SQL query in `save` method of `Dao` class in `models/DataObject/Objectbrick/Data/Dao.php` ([link](https://github.com/pimcore/pimcore/pull/15548/files?diff=unified&w=0#diff-172fd2de1642339e0d8ad96ad20217a17e710da22ba9457e3a431f1ecfcc1b89L96-R106))

### CODE REVIEW

File: models/DataObject/Objectbrick.php [hunk 1]
```diff
@@ -195,8 +195,12 @@ public function getObject(): ?Concrete
         return $this->object;
     }
 
-    public function setObject(?Concrete $object): static
+    public function setObject(Concrete|Model\Element\ElementDescriptor|null $object): static
     {
+        if ($object instanceof Model\Element\ElementDescriptor) {
+            $object = Service::getElementById($object->getType(), $object->getId());
```
Comment (fashxp) [inline models/DataObject/Objectbrick.php]: please don't load data objects inside containers via getById ... see also https://github.com/pimcore/pimcore/issues/14090

that has to be injected properly from the outside

**Review by fashxp — CHANGES_REQUESTED** [review]
