### PR TITLE
Restricted the option to set pages as content master document to each other

### LINKED ISSUE #12765: [Bug]: Two pages can have each other as the content master document
### Expected behavior

When trying to set a document as a content master document, Pimcore should throw an exception if the inheritance chain ever lands on the current document again. Currently, an exception `You cannot use the current document as a master document, please choose a different one.` is raised by this piece of code in the `setContentMasterDocumentId` method in `models/Document/PageSnippet.php`:

```PHP
if ($contentMasterDocumentId && $contentMasterDocumentId == $this->getId()) {
    throw new \Exception('You cannot use the current document as a master document, please choose a different one.');
}
```

However, this does not prevent a longer chain where, for example, the content master document refers back to the current document. I'd like to add a second check that traverses the inheritance chain and tries to find `$this->getId()` in it. If found, it will raise an exception, similar to the already existing one. This should be able to work as a drop in replacement for the existing if-statement:

```PHP

// Prevent an endless loop where the master document chain points back to the current document.
// We must not find $this->getId() in the master document's inheritance chain.
if(!empty($contentMasterDocumentId)) {
    $maxDepth = 20;
    $currentDocument = Document::getById($contentMasterDocumentId);

    while ($currentDocument && $maxDepth-- > 0) {
        if ($currentDocument->getId() === $this->getId()) {
            throw new \Exception('This document is already part of the master document chain, please choose a different one.');
        }

        $currentDocument = $currentDocument->getContentMasterDocument();
    }
}
```

This is mostly the same as the existing check except for these factors:
* I use `$contentMasterDocument->getId()` for the comparison
* `===` instead of `==`
* I don't check if $currentDocument is an `instanceof self` but I don't think it can ever turn out to something that does not have the `getId()` method I call.

I don't know if any of this could lead to problems, so I refrained from creating a pull request for now. I'd be happy to create one but am a bit short on time for testing.

### Actual behavior

Pimcore does not prevent a longer chain than 1. An out of memory exception is raised because of a resulting endless loop in `PageSnippet::getEditable()`

### Steps to reproduce

1. Create two documents. Let's call them /first and /second
2. Use /second as the content master document for /first
3. Use /first as the content master document for /second
4. Save and reload the document
5. Opening the document should throw an OutOfMemory exception

The chain can be arbitrarily long: /first pointing to /second, /second pointing to /third and /third pointing back to /first, for example

### PR DESCRIPTION
**Pull request by aryaantony92**
Restricted the option to set pages as content master document to each other

  
  

## Changes in this pull request  
Resolves #12765

### CODE REVIEW

**Review by aashan10 — APPROVED** [review]
Works fine!

File: models/Document/PageSnippet.php [hunk 1]
```diff
@@ -412,12 +412,11 @@ public function getEditable(string $name)
 
     /**
      * @param int|string|null $contentMasterDocumentId
-     *
      * @return $this
      *
      * @throws \Exception
      */
-    public function setContentMasterDocumentId($contentMasterDocumentId)
+    public function setContentMasterDocumentId($contentMasterDocumentId, bool $validate=false)
```
Comment (dvesh3) [inline models/Document/PageSnippet.php]: BC Break! since this could be extended in custom document types e.g. `headlessdocuments`.

Comment (dvesh3) [reply models/Document/PageSnippet.php]: Add a property instead for the checks then it is up to the custom implementations to adapt it.

Comment (brusch) [reply models/Document/PageSnippet.php]: Or additionally you can use `func_get_args()` and comment the additional parameter `/* , bool $validate=false */`

**Review by dvesh3 — APPROVED** [review]

**Comment by NiklasBr** [comment]
After update from 10.4.4 to 10.5.3 we are seeing a lot of errors like this now:

```
13:41:19 EMERGENCY [pimcore] ErrorException: Warning: Undefined variable $contentMasterDocument in /var/www/pimcore/vendor/pimcore/pimcore/models/Document/PageSnippet.php:440
Stack trace:
#0 /var/www/pimcore/vendor/pimcore/pimcore/lib/Model/AbstractModel.php(205): Pimcore\Model\Document\PageSnippet->setContentMasterDocumentId(16)
#1 /var/www/pimcore/vendor/pimcore/pimcore/lib/Model/AbstractModel.php(187): Pimcore\Model\AbstractModel->setValue('contentMasterDo...', 16)
#2 /var/www/pimcore/vendor/pimcore/pimcore/lib/Model/Dao/DaoTrait.php(45): Pimcore\Model\AbstractModel->setValues(Array)
#3 /var/www/pimcore/vendor/pimcore/pimcore/models/Document/Page/Dao.php(53): Pimcore\Model\Dao\AbstractDao->assignVariablesToModel(Array)
#4 /var/www/pimcore/vendor/pimcore/pimcore/models/Document.php(279): Pimcore\Model\Document\Page\Dao->getById(5562)
#5 /var/www/pimcore/vendor/pimcore/pimcore/models/Document/Listing/Dao.php(46): Pimcore\Model\Document::getById(5562)
#6 [internal function]: Pimcore\Model\Document\Listing\Dao->load()
#7 /var/www/pimcore/vendor/pimcore/pimcore/lib/Model/AbstractModel.php(246): call_user_func_array(Array, Array)
#8 /var/www/pimcore/vendor/pimcore/pimcore/models/Document.php(660): Pimcore\Model\AbstractModel->__call('load', Array)
#9 /var/www/pimcore/vendor/pimcore/pimcore/lib/Sitemap/Document/DocumentTreeGenerator.php(160): Pimcore\Model\Document->getChildren()
#10 /var/www/pimcore/vendor/pimcore/pimcore/lib/Sitemap/Document/DocumentTreeGenerator.php(103): Pimcore\Sitemap\Document\DocumentTreeGenerator->visit(Object(Pimcore\Model\Document\Page), Object(Pimcore\Sitemap\Document\DocumentGeneratorContext))
#11 /var/www/pimcore/vendor/pimcore/pimcore/lib/Sitemap/Document/DocumentTreeGenerator.php(92): Pimcore\Sitemap\Document\DocumentTreeGenerator->populateCollection(Object(Presta\SitemapBundle\Service\Dumper), Object(Pimcore\Model\Document\Page), 'site_5', Object(Pimcore\Model\Site))
#12 /var/www/pimcore/vendor/pimcore/pimcore/lib/Sitemap/EventListener/SitemapGeneratorListener.php(57): Pimcore\Sitemap\Document\DocumentTreeGenerator->populate(Object(Presta\SitemapBundle\Service\Dumper), 'site_5')
#13 /var/www/pimcore/vendor/symfony/event-dispatcher/Debug/WrappedListener.php(117): Pimcore\Sitemap\EventListener\SitemapGeneratorListener->onPopulateSitemap(Object(Presta\SitemapBundle\Event\SitemapPopulateEvent), 'presta_sitemap....', Object(Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher))
#14 /var/www/pimcore/vendor/symfony/event-dispatcher/EventDispatcher.php(230): Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke(Object(Presta\SitemapBundle\Event\SitemapPopulateEvent), 'presta_sitemap....', Object(Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher))
#15 /var/www/pimcore/vendor/symfony/event-dispatcher/EventDispatcher.php(59): Symfony\Component\EventDispatcher\EventDispatcher->callListeners(Array, 'presta_sitemap....', Object(Presta\SitemapBundle\Event\SitemapPopulateEvent))
#16 /var/www/pimcore/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php(154): Symfony\Component\EventDispatcher\EventDispatcher->dispatch(Object(Presta\SitemapBundle\Event\SitemapPopulateEvent), 'presta_sitemap....')
#17 /var/www/pimcore/vendor/presta/sitemap-bundle/src/Service/AbstractGenerator.php(166): Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch(Object(Presta\SitemapBundle\Event\SitemapPopulateEvent), 'presta_sitemap....')
#18 /var/www/pimcore/vendor/presta/sitemap-bundle/src/Service/Dumper.php(84): Presta\SitemapBundle\Service\AbstractGenerator->populate('site_5')
#19 /var/www/pimcore/vendor/presta/sitemap-bundle/src/Command/DumpSitemapsCommand.php(140): Presta\SitemapBundle\Service\Dumper->dump('public/var/tmp/...', 'https://melbyef...', 'site_5', Array)
#20 /var/www/pimcore/vendor/symfony/console/Command/Command.php(298): Presta\SitemapBundle\Command\DumpSitemapsCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /var/www/pimcore/vendor/symfony/console/Application.php(1042): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /var/www/pimcore/vendor/symfony/framework-bundle/Console/Application.php(96): Symfony\Component\Console\Application->doRunCommand(Object(Presta\SitemapBundle\Command\DumpSitemapsCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /var/www/pimcore/vendor/symfony/console/Application.php(299): Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand(Object(Presta\SitemapBundle\Command\DumpSitemapsCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 /var/www/pimcore/vendor/symfony/framework-bundle/Console/Application.php(82): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 /var/www/pimcore/vendor/symfony/console/Application.php(171): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 /var/www/pimcore/bin/console(49): Symfony\Component\Console\Application->run()
#27 {main}
```

It appears that it is trying to fetch Content Master Documents which have been deleted and are no longer in the Bin either. Was that intentional?

**Comment by NiklasBr** [comment]
Changing the `do-while` to this appears to work:
```php
while ($currentContentMasterDocument && --$maxDepth > 0 && $validate) {
    if ($currentContentMasterDocument->getId() === $this->getId()) {
        throw new \Exception('This document is already part of the master document chain, please choose a different one.');
    }
    $currentContentMasterDocument = $currentContentMasterDocument->getContentMasterDocument();
}
```

**Comment by blankse** [comment]
@NiklasBr There is also an Issue: https://github.com/pimcore/pimcore/issues/12915 and I created a PR: https://github.com/pimcore/pimcore/pull/12921
Can you test it?

**Comment by dvesh3** [comment]
> Changing the `do-while` to this appears to work:
> 
> ```
> while ($currentContentMasterDocument && --$maxDepth > 0 && $validate) {
>     if ($currentContentMasterDocument->getId() === $this->getId()) {
>         throw new \Exception('This document is already part of the master document chain, please choose a different one.');
>     }
>     $currentContentMasterDocument = $currentContentMasterDocument->getContentMasterDocument();
> }
> ```

@NiklasBr could you please check if this [PR ](https://github.com/pimcore/pimcore/pull/12921) fixes the problem ? thanks!

**Comment by NiklasBr** [comment]
Thanks! Will test it on Monday.

**Comment by NiklasBr** [comment]
LGTM
