### PR TITLE
[ControllerDataProvider] Fix bundle templates in getTemplates() calls

### LINKED ISSUE #9453: Template path for external bundles is invalid
# Bug Report

### Expected behavior

Template selection drop down should display all templates from configured template paths as follows: @<namespace>/<template_path>/<twig_template>. Otherwise all templates from third party bundles has to be manually edited and the drop down is useless.

### Actual behavior

On documents the template selection drop down shows the wrong path in the settings path. For example the CMF templates are shown as follows:

image

Preview shows the following error because the namespace is not correctly used:

image

### PR DESCRIPTION
**Pull request by dvesh3**
## Changes in this pull request  
Resolves #9453

### CODE REVIEW

File: lib/Controller/Config/ControllerDataProvider.php [hunk 1]
```diff
@@ -203,29 +200,14 @@ private function findTemplates(string $path, string $bundleName = null): array
             $finder->name($namePattern);
         }
 
+        if ($bundleName && 'Bundle' === substr($bundleName, -6)) {
```
Comment (jdreesen) [inline lib/Controller/Config/ControllerDataProvider.php]:
```suggestion
        if ($bundleName && str_ends_with($bundleName, 'Bundle')) {
```
