### PR TITLE
[Documents] Fix Not possible to save documents

### LINKED ISSUE #11987: [Documents] Not possible to save documents
### Expected behavior

Documents should be saved

### Actual behavior

throwing exception Doctrine\DBAL\Connection::fetchOne(): Argument #2 ($params) must be of type array, null given

### Steps to reproduce

1. Open Document
2. Click save / save & publish.

### PR DESCRIPTION
**Pull request by dvesh3**
## Changes in this pull request  
Resolves  #11987

### CODE REVIEW

File: models/Document/Service/Dao.php [hunk 1]
```diff
@@ -124,7 +124,7 @@ public function addTranslation(Document $document, Document $translation, $langu
     public function removeTranslation(Document $document)
     {
         // if $document is a source-document, we need to move them over to a new document
-        $newSourceId = $this->db->fetchOne('SELECT id FROM documents_translations WHERE sourceId = ?', $document->getId());
+        $newSourceId = $this->db->fetchOne('SELECT id FROM documents_translations WHERE sourceId = ?', [$this->model->getId()]);
```
Comment (blankse) [inline models/Document/Service/Dao.php]:
```suggestion
        $newSourceId = $this->db->fetchOne('SELECT id FROM documents_translations WHERE sourceId = ?', [$document->getId()]);
```
