### PR TITLE
[Document] Fix missing info for only save new version

### LINKED ISSUE #6951: Document: Missing publish icon in version tab when only saving new version
# Bug Report

There are no publish icons in documents which have newer unpublished versions

### Steps to reproduce

1. Open a document
2. Save and publish
3. Only save new version
4. Reload
5. No publish icon
demo-pimcore-fun-Pimcore

### PR DESCRIPTION
**Pull request by dvesh3**
## Changes in this pull request  
Resolves #6951

## Additional info  

Fixes 2 issues:
- Publish icon on Version Tab list
- "This is a newer not published version" Notification on documents.

### CODE REVIEW

File: bundles/AdminBundle/Controller/Admin/Document/EmailController.php [hunk 1]
```diff
@@ -74,14 +74,14 @@ public function getDataByIdAction(Request $request)
...
 
-        if (!$email) {
+        if (!$emailFromDatabase) {
             throw $this->createNotFoundException('Email not found');
         }
 
-        $email = clone $email;
-        $email = $this->getLatestVersion($email);
+        $emailFromDatabase = clone $emailFromDatabase;
+        $email = $this->getLatestVersion($emailFromDatabase);
```
Comment (brusch) [inline bundles/AdminBundle/Controller/Admin/Document/EmailController.php:84]: Maybe we should move this functionality directly to `\Pimcore\Bundle\AdminBundle\Controller\Admin\Document\DocumentControllerBase::preSendDataActions()`

See my code suggestion there. 
Then I think we don't have to touch all the controllers and have it in a central place. wdyt?

File: bundles/AdminBundle/Controller/Admin/Document/DocumentControllerBase.php [hunk 2]
```diff
@@ -38,7 +38,9 @@ abstract class DocumentControllerBase extends AdminController implements Evented
 
     protected function preSendDataActions(&$data, Model\Document $document)
     {
-        $data['versionDate'] = $document->getModificationDate();
+        $documentFromDatabase = Model\Document::getById($document->getId(), true);
+
```
Comment (brusch) [inline bundles/AdminBundle/Controller/Admin/Document/DocumentControllerBase.php:42]:
```suggestion
$data['documentFromVersion'] = ($document->getVersionCount() != $documentFromDatabase->getVersionCount());
```

**Review by brusch — CHANGES_REQUESTED** [review]
