### PR TITLE
[Bug, EC]: Follow-up to #17814, add more brickprefixes to avoid ambiguity

### LINKED ISSUE #17830: [Bug, EC]: Follow-up to #17814, add more brickprefixes to avoid ambiguity
### Pimcore version

11.x

### Steps to reproduce

See  https://github.com/pimcore/pimcore/issues/17814

### Actual Behavior

See  https://github.com/pimcore/pimcore/issues/17814

### Expected Behavior

It works also for 

- Many-To-Many-Object-Relation
- Advanced-Many-To-Many-Relation
- Advanced-Many-To-Many-Object-Relation
- Many-To-Many-Relation
 
See https://github.com/pimcore/pimcore/pull/17815

### PR DESCRIPTION
**Pull request by kingjia90**
## Changes in this pull request  
Resolves https://github.com/pimcore/pimcore/issues/17830

## Additional info
workaround-ish, to avoid to couple tying this fix with an exact version of admin ui classic (from there it could be passed an unquoted table name/alias)
https://github.com/pimcore/admin-ui-classic-bundle/blob/2a129aa07f2f20c365f88c205d60d244468ff711/src/Helper/GridHelperService.php#L325-L327
also the method is called `getFilterConditionExt` which suffix suggest it used just for `ExtJS`

### CODE REVIEW

File: models/DataObject/ClassDefinition/Data/ManyToManyObjectRelation.php [hunk 1]
```diff
@@ -728,9 +728,16 @@ public function addListingFilter(DataObject\Listing $listing, float|array|int|st
      */
     public function getFilterConditionExt(mixed $value, string $operator, array $params = []): string
     {
+        $prefix = '';
         $name = $params['name'] ?: $this->name;
 
-        return $this->getRelationFilterCondition($value, $operator, $name);
+        if ($params['brickPrefix']) {
+            // The brick prefix is always quoted and with a dot suffix, so removing the first
+            // and second last character to unquote
```
Comment (kingjia90) [inline models/DataObject/ClassDefinition/Data/ManyToManyObjectRelation.php:736]: The exact pattern can be seen on https://github.com/pimcore/admin-ui-classic-bundle/blob/2a129aa07f2f20c365f88c205d60d244468ff711/src/Helper/GridHelperService.php#L302-L310
