### PR TITLE
"owner missing" error after upgrading from 6.0.x/6.6.9 to current 6.7.2

### LINKED ISSUE #7226: "owner missing" error after upgrading from 6.0.x/6.6.9 to current 6.7.2
# Bug-Report

We updated 2 pimcore instances (one from 6.0.x and one from 6.6.9) to the current version of pimcore.
After this update the "owner missing" error appears, when opening an object with blocks.
After a "cache clear" the error disappears for a random time, but then comes back again.

Maybe a regression of #6280 ?

### PR DESCRIPTION
**Pull request by weisswurstkanone**
resolves #7226

### CODE REVIEW

File: models/DataObject/ClassDefinition/Data/Block.php [hunk 1]
```diff
@@ -1058,6 +1058,8 @@ public function delete($object, $params = [])
     public function preGetData($object, $params = [])
     {
         $data = null;
+        $params['owner'] = $object;
+        $params["fieldname"] = $this->getName();
```
Comment (dvesh3) [inline models/DataObject/ClassDefinition/Data/Block.php:1062]: Issue still exists as params are not passed in load() call below.

**Review by dvesh3 — CHANGES_REQUESTED** [review]
Also fix for Blocks inside localizedfields container
