### PR TITLE
[Documents] Blocks Editable - Ignore adding extra indices on required check and xliff export

### LINKED ISSUE #10443: [Bug]: Required fields in Blocks fail serverside check
### Expected behavior

In more complex sites, validating required fields within block elements fails.

This is checked in:
vendor/pimcore/pimcore/models/Document/PageSnippet.php:664

Here, we get the list of used editable names. The issue is that, for some block elements, a non-existing ediable name is added with the number of 1000000

I have come so far, as to see, this is added in:
vendor/pimcore/pimcore/lib/Event/Model/Document/EditableNameEvent.php:117
although when you look at the page object, there is no editable with that name.

There will be, for example an editable:
stage_imageset_block:1.stage_image
but this ediable name will also be added to the list:
stage_imageset_block:1000000.stage_image

I will add some screenshots and object dumps.

### Actual behavior

Validation works properly.

### Steps to reproduce

No easy way found yet, to reproduce, will look further.

### PR DESCRIPTION
**Pull request by dvesh3**
## Changes in this pull request  
Resolves #10443

### CODE REVIEW

File: models/Document/Editable/Block.php [hunk 1]
```diff
@@ -437,4 +439,14 @@ private function getBlockAttributes(): string
...
     }
+
+    /**
+     * @return bool
+     */
+    private function isIgnoreEditmodeIndices(): bool
+    {
+        $requestStack = \Pimcore::getContainer()->get('request_stack');
+
+        return $requestStack->getCurrentRequest()->get(self::IGNORE_EDITMODE_INDICES, false);
```
Comment (brusch) [inline models/Document/Editable/Block.php]: Just to be sure, I'd add a check here if `getCurrentRequest() !== null` .

**Review by brusch — CHANGES_REQUESTED** [review]

File: models/Document/Editable/Block.php (hunk 1 above)
Comment (dvesh3) [reply models/Document/Editable/Block.php]: Returning `false` on `getCurrentRequest() === null`

**Review by brusch — APPROVED** [review]
