### PR TITLE
[Bug]: Deleting a classificationstore group doesn't delete assigned data from an object

### LINKED ISSUE #13694: [Bug]: Deleting a classificationstore group doesn't delete assigned data from an object
### Expected behavior

Deleting a group 
1. should also lead to the deletion of all assigned classification values of keys in that group, or - 
2. if this isn't done by intent, at least prevent he affected objects to throw an exception when `$object->getClassification()->getGroups()` is called.
 

### Actual behavior

After deleting the group, the relation still exists in the `object_classificationstore_data_<object_identifier>` table, referencing a non existent groupId.

Calling `$object->getClassification()->getGroups()` throws an Exception, since activeGroups still references to a group that doesn't exist anymore:

`Pimcore\Model\DataObject\Classificationstore::createGroup(): Argument #2 ($groupConfig) must be of type Pimcore\Model\DataObject\Classificationstore\GroupConfig, null given, called in /var/www/html/vendor/pimcore/pimcore/models/DataObject/Classificationstore.php on line 511
`

### Steps to reproduce

1. Create a classification key, e.g. an input field
2. Create a classification group
3. Assign the key to the group
4. Assign the group to a dataobject, enter a value and save the object
5. Delete the the group
6. Either call `$object->getClassification()` which throws an exception, or simply check your relational table `object_classificationstore_data_<object_identifier>`

### PR DESCRIPTION
**Pull request by robertSt7**
resolves #13694

### CODE REVIEW

**Review by mcop1 — COMMENTED** [review]
@robertSt7 

**For up-migration:** 
When I try to run the migration I get the following error:

` Cannot add or update a child row: a foreign key constraint fails` 

This is because there is already an deleted entry in the `object_classificationstore_groups_xx` table. We need to clean up those tables before we add the foreign key.

**For down-migration:** 
We need to drop the foreign keys first, then change the datatype back to `bigint`. You can´t change the datatype of a column which is still referenced in a foreign key.

File: bundles/CoreBundle/Migrations/Version20221222181745.php [hunk 1]
```diff
@@ -0,0 +1,92 @@
...
+            FROM `object_classificationstore_groups_{$tableNumber}`
+            LEFT JOIN `classificationstore_groups` ON object_classificationstore_groups_{$tableNumber}.groupId = classificationstore_groups.id
+            WHERE classificationstore_groups.id = NULL;");
+
+            $this->addSql("DELETE `object_classificationstore_data_{$tableNumber}`
+            FROM `object_classificationstore_data_{$tableNumber}`
+            LEFT JOIN `$theTableGroups` ON object_classificationstore_data_{$tableNumber}.o_id = $theTableGroups.o_id AND
+            object_classificationstore_data_{$tableNumber}.fieldname = $theTableGroups.fieldname AND
+            object_classificationstore_data_{$tableNumber}.groupId = $theTableGroups.groupId
+            WHERE $theTableGroups.o_id = NULL AND  $theTableGroups.fieldname = NULL AND $theTableGroups.groupId = NULL;");
```
Comment (mcop1) [inline bundles/CoreBundle/Migrations/Version20221222181745.php]:
```suggestion
            WHERE $theTableGroups.o_id IS NULL AND  $theTableGroups.fieldname IS NULL AND $theTableGroups.groupId IS NULL;");
```

File: bundles/CoreBundle/Migrations/Version20221222181745.php [hunk 2]
```diff
@@ -0,0 +1,92 @@
...
+            $tableArray = explode('_', $theTableGroups);
+            $tableNumber = end($tableArray);
+            if(!is_numeric($tableNumber)){
+                continue;
+            }
+
+            $this->addSql("DELETE `object_classificationstore_groups_{$tableNumber}`
+            FROM `object_classificationstore_groups_{$tableNumber}`
+            LEFT JOIN `classificationstore_groups` ON object_classificationstore_groups_{$tableNumber}.groupId = classificationstore_groups.id
+            WHERE classificationstore_groups.id = NULL;");
```
Comment (mcop1) [inline bundles/CoreBundle/Migrations/Version20221222181745.php]:
```suggestion
            WHERE classificationstore_groups.id IS NULL;");
```

**Review by mcop1 — COMMENTED** [review]
Please have a look at the migrations again.
Other than that it looks good.
