### PR TITLE
Fix for validation errors with subItems without context stack

### LINKED ISSUE #10339: Error message when trying to save a data object with empty mandatory fields
### Expected behavior

No error message, but standard validation dialog should be shown:
image

### Actual behavior

Error Message:

image

### Steps to reproduce

Only happens with classification store fields

1.) Add Classification store containing mandatory field(s)
2.) Add Classification store to class
image
3.) Create new data object containing the created classification store
4.) Leave mandatory field empty
5.) Click save button
image

### PR DESCRIPTION
**Pull request by BabovicT**
Resolves #10339

### CODE REVIEW

File: models/DataObject/Concrete.php [hunk 1]
```diff
@@ -183,7 +183,10 @@ protected function update($isUpdate = null, $params = [])
                         foreach ($subItems as $subItem) {
                             $subItemMessage = $subItem->getMessage();
                             if ($subItem instanceof Model\Element\ValidationException) {
-                                $subItemMessage .= '[ ' . $subItem->getContextStack()[0] . ' ]';
+                                $contextStack = $subItem->getContextStack();
+                                if ($contextStack) {
+                                    $subItemMessage .= '[ ' . $subItem->getContextStack()[0] . ' ]';
```
Comment (blankse) [inline models/DataObject/Concrete.php]:
```suggestion
                                    $subItemMessage .= '[ ' . $contextStack[0] . ' ]';
```

**Comment by weisswurstkanone** [comment]
@BabovicT sorry, didn't see this one, but it doesn't hurt anyway. Root cause is actually here:
https://github.com/pimcore/pimcore/pull/10372

Thanks a lot!
