### PR TITLE
[Bug, EC] PEES-839: Fix Static Page generation not working properly via CLI

### LINKED ISSUE #17570: [Bug]: Static Page generation not working properly via cli
### Pimcore version

v11.3.2

### How to reproduce
1. create multiple documents in Pimcore and enable server side static rendering in each
2. run `bin/console pimcore:maintenance --job=documents_static_page_generate` or `bin/console pimcore:documents:generate-static-pages` and have a look at the generated static files (located under /`public/var/tmp/pages/{path-to-document}`)

## Problems
Usage of the static page generation is not working properly, when done via maintenance `StaticPageGenerationTask` or `GenerateStaticPagesCommand`. 

### Issue 1: Resetting Services
**Problem:**
Many services do not operate statelessly. They employ a pattern similar to this:
```php
public function getTitle(): string
{
    if (!$this->title) {
        $this->title = 'do something';
    }
    return $this->title;
}
```
This pattern causes issues as seen in https://github.com/pimcore/pimcore/issues/16220, where the `$returnedFiles` variable stores the already returned files and does not reset when generating multiple static pages in one session.

**Proposed Solution:**
I can propose a solution by resetting all services using the `service_resetter`. Please refer to the following commit in my Pimcore fork: https://github.com/melissakittl/pimcore/commit/33c06e6082e462aad32aa07f564a450dc091dd11

### Issue 2: HTTPS Request Scheme for Static Pages

**Problem:**
When static pages are generated via the CLI, the request scheme defaults to http, because `$_SERVER['HTTPS']` server variable isn't set in CLI, resulting in all links being generated with `http` even if the site actually operates under https. Consequently, the static pages cannot be used as intended because they do not contain the correct document links.

**Possible Solution:**
I don't have a solution at hand. Maybe it's possible to add a configuration for the used scheme in static page generation.
The alternative would be avoiding the generation of static pages through CLI (via `StaticPageGenerationTask` and `GenerateStaticPagesCommand`) and creating static pages on-demand when a page is accessed. The `StaticPageGenerationTask` could then be limited to deleting expired files without regenerating them, but the `GenerateStaticPagesCommand` would be obsolete.

### Issue 3: Request Pathinfo

**Problem 3.1:**
At this line in the code https://github.com/pimcore/pimcore/blob/11.3/lib/Document/Renderer/DocumentRenderer.php#L102, a request with context is created in the catch block, because no current request exists in the CLI. However, this does not include a URI, which means the pathinfo is not set. If anywhere in the code the current request or main request from the request stack is used with pathinfo, it generates URLs like: `http://testdomain.com/_fragment`.

**Proposed Solution:**
The pathinfo could be set using the following commit from my pimcore fork: https://github.com/melissakittl/pimcore/commit/a6d54d9d7ab98b2690ad10468b4305e14791a910

**Problem 3.2:**
However, this new request should also be pushed onto the request stack, to be used as current / main request. If pushed, it must be popped off before processing the next document to avoid conflicts as there would already be an existing request in use.

**Proposed Solution:**
Unfortunately, I cannot offer a clean solution for this issue either.
As with Issue 2, my intention is to discontinue the generation of static pages through the CLI altogether.

## Note:
It does not make sense to address Issues 1, 2 and 3.1 if the decision is made to avoid CLI generation as described in Issue 2.
Until these issues are fixed, my way to go will be, to disable the `StaticPageGenerationTask` and never run the `GenerateStaticPagesCommand` to be able to use static pages.

### Expected Behavior

Static Pages generated via cli do not contain the correct content, due to explained reasons.

### PR DESCRIPTION
**Pull request by kingjia90**
## Changes in this pull request  
Resolves https://github.com/pimcore/pimcore/issues/17570, https://github.com/pimcore/pimcore/issues/16220, https://github.com/pimcore/service-operations/issues/290

## Additional info
I've collected the fix and tips on this matter, credits to @melissakittl  and @jdreesen

### CODE REVIEW

File: lib/Document/StaticPageGenerator.php [hunk 1]
```diff
@@ -25,14 +25,16 @@
...
+use Symfony\Component\HttpKernel\KernelInterface;
 use Symfony\Component\Lock\LockFactory;
 
 class StaticPageGenerator
 {
     public function __construct(
         protected DocumentRendererInterface $documentRenderer,
         private LockFactory $lockFactory,
-        protected SystemSettingsConfig $settingsConfig
+        protected SystemSettingsConfig $settingsConfig,
```
Comment (kingjia90) [inline lib/Document/StaticPageGenerator.php]: ugh.. this is bc-breaky, need to inject differently
wrong line highlighted, meant https://github.com/pimcore/pimcore/pull/18835/commits/ee4aedcc69ba1f32c9115d660e96ea9d56a7297b#diff-d457906ebd50f5e7051931d821a79d12970959978069590f47ee8f203de98d67R37
