### PR TITLE
Fix Document link marshalling

### LINKED ISSUE #15348: [Bug]: It is not possible to delete a document link
### Pimcore version

11.0.0

### Steps to reproduce

Create a document link
Try to delete the document link

Pimcore tries to add a recyclebin entry with:

curl "https://****/admin/recyclebin/add" -X POST -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/113.0" -H "Accept: */*" -H "Accept-Language: de-DE,de;q=0.8,en;q=0.5,en-US;q=0.3" -H "Accept-Encoding: gzip, deflate, br" -H "X-pimcore-csrf-token: 1f4269a5815d1ac8dd9d3bf858e3878f44e25955" -H "X-pimcore-extjs-version-major: 7" -H "X-pimcore-extjs-version-minor: 0" -H "Content-Type: application/x-www-form-urlencoded; charset=UTF-8" -H "X-Requested-With: XMLHttpRequest" -H "Origin: https://****" -H "Connection: keep-alive" -H "Referer: https://****/admin/" -H "Cookie: teaser=1; PHPSESSID=316b0f97f1f996643b6007ff6a0a40ed" -H "Sec-Fetch-Dest: empty" -H "Sec-Fetch-Mode: cors" -H "Sec-Fetch-Site: same-origin" -H "Pragma: no-cache" -H "Cache-Control: no-cache" -H "TE: trailers" --data-raw "type=document&id=62"

but this request is not working an ends with the error:

"in /var/www/html/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php:266\n#0 /var/www/html/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php(266): ReflectionProperty->setValue(Object(Pimcore\\Model\\Document\\Link), Object(Pimcore\\Model\\Element\\ElementDescriptor))\n#1 ....
message	"Cannot assign Pimcore\\Model\\Element\\ElementDescriptor to property Pimcore\\Model\\Document\\Link::$object of type ?Pimcore\\Model\\Element\\ElementInterface"

### Expected / actual behavior

_No response_

### PR DESCRIPTION
**Pull request by dvesh3**
## Changes in this pull request  
 Resolves #15348

### <samp>🤖 Generated by Copilot at 8e83273</samp>

Updated type annotation of `Link::$object` to support lazy loading of linked elements. Part of a performance and memory optimization refactoring of the `Link` class and its related classes.

### <samp>🤖 Generated by Copilot at 8e83273</samp>

> _`Link` class refactored_
> _Lazy loading elements now_
> _A breeze in summer_

### <samp>🤖 Generated by Copilot at 8e83273</samp>

*  Update the type annotation of the `object` property of the `Link` class to allow lazy loading of linked elements ([link](https://github.com/pimcore/pimcore/pull/15524/files?diff=unified&w=0#diff-846d942949cbc1aa247a67f632de47fdd9d3e0affe63dec1755f3a5a16097fabL54-R56))

### CODE REVIEW

File: models/Document/Link.php [hunk 1]
```diff
@@ -268,7 +268,7 @@ public function setInternalType(?string $type): static
         return $this;
     }
 
-    public function getElement(): ?Model\Element\ElementInterface
+    public function getElement(): Model\Element\ElementInterface|Model\Element\ElementDescriptor|null
```
Comment (blankse) [inline models/Document/Link.php]: I think getElement() shouldn't return a ElementDescriptor. When the object attribute is a ElementDescriptor it should be reloaded.

**Comment by aryaantony92** [comment]
I checked and for me, the object in $data is null here https://github.com/pimcore/pimcore/blob/bdc9a2dcd6d75403a3a1750c4c117fc8e1ea541e/models/Element/Recyclebin/Item.php#L291. So, we have to investigate it further.

File: models/Document/Link.php [hunk 2]
```diff
@@ -270,13 +271,15 @@ public function setInternalType(?string $type): static
 
     public function getElement(): ?Model\Element\ElementInterface
     {
+        if ($this->object instanceof Model\Element\ElementDescriptor) {
+            return Element\Service::getElementById($this->object->getType(), $this->object->getId());
```
Comment (dvesh3) [inline models/Document/Link.php]:
```suggestion
            $this->object = Element\Service::getElementById($this->object->getType(), $this->object->getId());
```
