### PR TITLE
[Admin] Documents Tree - Fix AdminStyle on save

### LINKED ISSUE #7047: Text is not struck through after unpublishing document
Open published document, click "unpublish" => the document in the tree should be struck through, but it's not

image

### PR DESCRIPTION
**Pull request by dvesh3**
## Changes in this pull request  
Resolves #7047

## Additional info  
AdminStyle should be updated for tree node on all document type save

### CODE REVIEW

File: bundles/AdminBundle/Controller/Admin/Document/DocumentController.php [hunk 1]
```diff
@@ -48,6 +48,7 @@
 class DocumentController extends ElementControllerBase implements EventedControllerInterface
 {
     use AdminStyleTrait;
```
Comment (weisswurstkanone) [inline bundles/AdminBundle/Controller/Admin/Document/DocumentController.php:50]: Is the AdminStyleTrait still needed here ?

Comment (dvesh3) [reply bundles/AdminBundle/Controller/Admin/Document/DocumentController.php:50]: yes, still calling here: https://github.com/pimcore/pimcore/blob/969f4efbc7c9a480690e366dc0d0e1a9b5940440/bundles/AdminBundle/Controller/Admin/Document/DocumentController.php#L106

https://github.com/pimcore/pimcore/blob/969f4efbc7c9a480690e366dc0d0e1a9b5940440/bundles/AdminBundle/Controller/Admin/Document/DocumentController.php#L785

Comment (dvesh3) [reply bundles/AdminBundle/Controller/Admin/Document/DocumentController.php:50]: oh, you are right. we don't need it, since it is already used in DocumentTreeConfigTrait
