### PR TITLE
[Data Objects] ManyToMany Relation Types should proper validate multiple assignments

### LINKED ISSUE #5951: [Data Objects] ManyToMany Relation Types should proper validate multiple assignments
- use validation instead of silently filtering duplicates
- throw a proper exception of validation fails 
- undo changes made in #5918 and #5852

### PR DESCRIPTION
**Pull request by weisswurstkanone**
resolves #5951

### CODE REVIEW

**Comment by dpfaffenbauer** [comment]
re checking items with no ID: you could use spl_object_hash to get the instance id. When an Item has no ID, the spl_object_hash should be the ideal way to check for it's uniqueness.

File: models/DataObject/ClassDefinition/Data/Relations/AbstractRelations.php [hunk 1]
```diff
@@ -420,75 +420,44 @@ public function loadLazyBrickField(DataObject\Objectbrick\Data\AbstractData $ite
...
-                }
 
-                if ($elementHash === null) {
-                    $relationItems[] = $item; //do not filter if element hash fails
-                } elseif (!isset($relationItems[$elementHash])) {
-                    $relationItems[$elementHash] = $item;
-                } else {
-                    throw new \Exception(sprintf('Passing relations multiple times is not allowed: %s in field %s of object id: %s', $elementHash, $fieldName, $objectId));
+                    if ($elementHash === null) {
+                        $relationItems[] = $item;
```
Comment (weisswurstkanone) [inline models/DataObject/ClassDefinition/Data/Relations/AbstractRelations.php:447]: throw new \Exception('Passing relations without ID or type not allowed anymore!);

Comment (dvesh3) [reply models/DataObject/ClassDefinition/Data/Relations/AbstractRelations.php:447]: 👍  for this change, since it is not possible to save relations without ID. please see https://github.com/pimcore/pimcore/issues/5953

File: tests/Model/Relations/MultipleAssigmentTest.php [hunk 2]
```diff
@@ -77,7 +75,11 @@ public function testMultipleAssignmentsOnSingleManyToMany()
 
         $object->setOnlyOneManyToMany($metaDataList);
 
-        $object->save();
+        try {
+            $object->save();
+            $this->fail("TODO move this up multiple assignment not allowed, expected an exception");
```
Comment (dvesh3) [inline tests/Model/Relations/MultipleAssigmentTest.php:80]:
```suggestion
            $this->fail("only one assignment allowed but validation accepted duplicate items");
```

File: models/DataObject/ClassDefinition/Data/Relations/AbstractRelations.php [hunk 3]
```diff
@@ -420,75 +420,44 @@ public function loadLazyBrickField(DataObject\Objectbrick\Data\AbstractData $ite
...
-                }
 
-                if ($elementHash === null) {
-                    $relationItems[] = $item; //do not filter if element hash fails
-                } elseif (!isset($relationItems[$elementHash])) {
-                    $relationItems[$elementHash] = $item;
-                } else {
-                    throw new \Exception(sprintf('Passing relations multiple times is not allowed: %s in field %s of object id: %s', $elementHash, $fieldName, $objectId));
+                    if ($elementHash === null) {
+                        throw new \Exception('Passing relations without ID or type not allowed anymore!);
```
Comment (dvesh3) [inline models/DataObject/ClassDefinition/Data/Relations/AbstractRelations.php:447]:
```suggestion
                        throw new \Exception('Passing relations without ID or type not allowed anymore!');
```

File: models/DataObject/ClassDefinition/Data/Relations/AbstractRelations.php [hunk 4]
```diff
@@ -420,75 +420,44 @@ public function loadLazyBrickField(DataObject\Objectbrick\Data\AbstractData $ite
...
-                } else {
-                    throw new \Exception(sprintf('Passing relations multiple times is not allowed: %s in field %s of object id: %s', $elementHash, $fieldName, $objectId));
+                    if ($elementHash === null) {
+                        throw new \Exception('Passing relations without ID or type not allowed anymore!');
+                    } elseif (!isset($relationItems[$elementHash])) {
+                        $relationItems[$elementHash] = $item;
+                    } else {
+                        throw new \Exception(
+                            'Passing relations multiple times not allowed anymore: ' . $elementHash
+                            . ' multiple times in field' . $fieldName
```
Comment (dvesh3) [inline models/DataObject/ClassDefinition/Data/Relations/AbstractRelations.php:453]:
```suggestion
                            . ' multiple times in field ' . $fieldName
```

File: models/DataObject/ClassDefinition/Data/Relations/AbstractRelations.php [hunk 5]
```diff
@@ -420,75 +420,44 @@ public function loadLazyBrickField(DataObject\Objectbrick\Data\AbstractData $ite
...
+                        );
+                    }
```
Comment (dvesh3) [inline models/DataObject/ClassDefinition/Data/Relations/AbstractRelations.php:455]:
```suggestion
                    } else {
                        $message = "Passing relations multiple times not allowed anymore: " . $elementHash
                            . ' multiple times in field' . $fieldName;

                        if (method_exists($this, 'getAllowMultipleAssignments')) {
                            $message .= ", Reason: 'Allow Multiple Assignments' setting is disabled in class definition. ";
                        }

                        throw new \Exception($message);
                    }
```
