### PR TITLE
Fix Service::copyRecursive()

### LINKED ISSUE #16302: [Bug]: DataObject/Service copyRecursive crashes
### Pimcore version

11.1.2

### Steps to reproduce

Call method copyRecursive

### Actual Behavior

Crashes with 
Typed property Pimcore\Model\DataObject\Service::$_copyRecursiveIds must not be accessed before initialization

### Expected Behavior

`
if (!$this->_copyRecursiveIds) {
            $this->_copyRecursiveIds = [];
}
`
should be
        
`if (!isset($this->_copyRecursiveIds)) {
            $this->_copyRecursiveIds = [];
}
`

### PR DESCRIPTION
**Pull request by blankse**
## Changes in this pull request  
Resolves https://github.com/pimcore/pimcore/issues/16302

### CODE REVIEW

File: models/DataObject/Service.php [hunk 1]
```diff
@@ -47,8 +47,14 @@
  */
 class Service extends Model\Element\Service
 {
-    protected array $_copyRecursiveIds;
+    /**
+     * @internal
+     */
```
Comment (robertSt7) [inline models/DataObject/Service.php:52]: Hi @blankse the PR looks good, but why do you want to add this internal notations?

Comment (blankse) [reply models/DataObject/Service.php:52]: @robertSt7 The _ prefix in the name is a old convention for internal attributes, right? Otherwise it is also set in the Asset Service. I think this should be consistent in all 3 Services.

**Comment by robertSt7** [comment]
@blankse Thanks a lot for your contribution
