### PR TITLE
Fix maintenance task for ObjectBricks and FieldCollections on DB with lower_case_table_names

### LINKED ISSUE #10427: [Bug]: CleanupBrickTables maintenance task does not recognize bricks with capitalization in name
### Expected behavior

CleanupBrickTables runs smoothly, without any errors.

### Actual behavior

I've managed to reproduce the problem from #5824.  
Our devops used [this manual](https://github.com/pimcore/pimcore/edit/10.x/doc/Development_Documentation/23_Installation_and_Upgrade/03_System_Setup_and_Hosting/05_DB_Setup.md) and added lower_case_table_names=1 in accordance with it.  
Unfortunately, he did it on the production DB, on Linux and on AWS, so I didn't even have access to mysql system settings and I wasn't aware of the changes.  
My next morning started with shouts of angry users, who were completely unable to work with the website. After some research, I changed the actual table names to lower case (luckily, I had access to mysqldump/mysql on production).  
So I appreciate the decision taken in Mysql 8 to disallow changing this setting if DB directory has already been initialized.  
But now we're getting the error with CleanupBrickTables mentioned in #5824, and I was able to reproduce it on a fresh installation, see the steps to reproduce.

### Steps to reproduce

Use Linux, set lower_case_table_names=1 in Mysql config. Create a new DataObject class, named with a capital letter. This creates tables with lower_case, but actual class files are still created case-sensitive. So CleanupBrickTables gets lower_cased Mysql table name and tries to look up a class with a lower_cased filename on a case-sensitive linux filesystem.
But even if we lower_case the filename of the class, datatype definitions (which are string literals in Pimcore) cannot be lower_cased - and Pimcore on Linux still tries to look them up in case-sensitive mode. It should not be a problem on Windows, though - datatype definitions and filenames can be CamelCased there, but CleanupBrickTables should still be able to get them, because the filesystem is case-insensitive there.

I've made a test using fresh & clean Pimcore installation, the result is shown [here](https://raw.githubusercontent.com/CountZero1981/pimcore/image/Untitled.png)

### PR DESCRIPTION
**Pull request by APochmann**
This PR referes to bug #10427 which is caused by getting type names of ObjectBricks and FieldCollections from database table names and using these names for checking if the ObjectBricks and FieldCollections exist. When databases are created with `lower_case_table_names` the name to be checked will be with lowercase letters only although the definition of ObjectBricks and FieldCollections might have uppercase characters too.

We need somehow a possibility to get from the lowercase stringto the one used to create the ObjectBricks and FieldCollections. The best way I could find is to create a mapping table to find the correct name with uppercase letters for names with only lowercase based on the class files which ensures that all relevant classes are considered, not only the ones currently loaded.

The error can be reproduced by
- using databse with `lower_case_table_names` set
- creating an ObjectBrick and a FieldCollection with uppercase letter in the name
- run maintenance job

As a result you will see error messages in the log file complaining missing types:
- `app.ERROR: Brick 'brickname' not found. Please check table object_brick_query_brickname_objectname`
- `app.ERROR: Fieldcollection 'collectionname' not found. Please check table object_collection_collectionname_objectname`

  
  

## Changes in this pull request  
Resolves #10427

### CODE REVIEW

File: lib/Maintenance/Tasks/CleanupBrickTablesTask.php [hunk 1]
```diff
@@ -30,13 +30,23 @@ class CleanupBrickTablesTask implements TaskInterface
...
+    private $mapLowerToCamelCase = [];
 
     /**
      * @param LoggerInterface $logger
      */
     public function __construct(LoggerInterface $logger)
     {
         $this->logger = $logger;
+        
+        $obPath = PIMCORE_CLASS_DIRECTORY . '/DataObject/Objectbrick/Data';
```
Comment (jdreesen) [inline lib/Maintenance/Tasks/CleanupBrickTablesTask.php]: Should this be a constant?

File: lib/Maintenance/Tasks/CleanupFieldcollectionTablesTask.php [hunk 2]
```diff
@@ -29,13 +29,23 @@ class CleanupFieldcollectionTablesTask implements TaskInterface
...
+    private $mapLowerToCamelCase = [];
 
     /**
      * @param LoggerInterface $logger
      */
     public function __construct(LoggerInterface $logger)
     {
         $this->logger = $logger;
+        
+        $fcPath = PIMCORE_CLASS_DIRECTORY . '/DataObject/Fieldcollection/Data';
```
Comment (jdreesen) [inline lib/Maintenance/Tasks/CleanupFieldcollectionTablesTask.php]: Should this be a constant?

File: lib/Maintenance/Tasks/CleanupBrickTablesTask.php (hunk 1 above)
Comment (APochmann) [reply lib/Maintenance/Tasks/CleanupBrickTablesTask.php]: Yes, defined in Bootstrap.php:
\Pimcore\Bootstrap::defineConstants()
```
...
        $resolveConstant('PIMCORE_CLASS_DIRECTORY', PIMCORE_PRIVATE_VAR . '/classes');
...
```

File: lib/Maintenance/Tasks/CleanupFieldcollectionTablesTask.php (hunk 2 above)
Comment (APochmann) [reply lib/Maintenance/Tasks/CleanupFieldcollectionTablesTask.php:41]: Yes, defined in Bootstrap.php:
\Pimcore\Bootstrap::defineConstants()
```
...
        $resolveConstant('PIMCORE_CLASS_DIRECTORY', PIMCORE_PRIVATE_VAR . '/classes');
...
```

File: lib/Maintenance/Tasks/CleanupBrickTablesTask.php (hunk 1 above)
Comment (jdreesen) [reply lib/Maintenance/Tasks/CleanupBrickTablesTask.php]: I mean, if we should define `PIMCORE_CLASS_DIRECTORY . '/DataObject/Objectbrick/Data'` as a class constant instead of a variable in the method.

Comment (APochmann) [reply lib/Maintenance/Tasks/CleanupBrickTablesTask.php]: Sorry, misunderstood you comment. Yes, there is no variable part in it, constant would be better.

Comment (APochmann) [reply lib/Maintenance/Tasks/CleanupBrickTablesTask.php]: Updated PR to use class constant

**Comment by brusch** [comment]
We'd classify this as an improvement, as the `lower_case_table_names` situation is documented. 
Therefore we'd like to have this on `11.x` - @APochmann can you please rebase your PR? 

Thanks a lot! 😊

File: lib/Maintenance/Tasks/CleanupFieldcollectionTablesTask.php [hunk 3]
```diff
@@ -26,11 +26,22 @@
  */
 class CleanupFieldcollectionTablesTask implements TaskInterface
 {
+    const PIMCORE_FIELDCOLLECTION_CLASS_DIRECTORY = PIMCORE_CLASS_DIRECTORY . '/DataObject/Fieldcollection/Data';
```
Comment (lukmzig) [inline lib/Maintenance/Tasks/CleanupFieldcollectionTablesTask.php]:
```suggestion
    private const PIMCORE_FIELDCOLLECTION_CLASS_DIRECTORY = PIMCORE_CLASS_DIRECTORY . '/DataObject/Fieldcollection/Data';
```

File: lib/Maintenance/Tasks/CleanupFieldcollectionTablesTask.php [hunk 4]
```diff
@@ -26,11 +26,22 @@
...
+
     private LoggerInterface $logger;
+    private $mapLowerToCamelCase = [];
```
Comment (lukmzig) [inline lib/Maintenance/Tasks/CleanupFieldcollectionTablesTask.php]:
```suggestion
    private array $mapLowerToCamelCase = [];
```

File: lib/Maintenance/Tasks/CleanupFieldcollectionTablesTask.php [hunk 5]
```diff
@@ -26,11 +26,22 @@
...
     public function __construct(LoggerInterface $logger)
     {
         $this->logger = $logger;
+        
+        $files = array_diff(scandir(self::PIMCORE_FIELDCOLLECTION_CLASS_DIRECTORY), array('..', '.'));
+        foreach ($files as $file) {
+            $classname = str_replace('.php','',$file);
+            $class = '\\Pimcore\\Model\\DataObject\\Fieldcollection\\Data\\' . $classname;
+            $object = new $class();
+            $this->mapLowerToCamelCase[strtolower($classname)] = $object->getType();
```
Comment (lukmzig) [inline lib/Maintenance/Tasks/CleanupFieldcollectionTablesTask.php]:
```suggestion
            $classname = str_replace('.php','',$file);
            $this->mapLowerToCamelCase[strtolower($classname)] = $classname;
```
Can the class name be different than the type?

File: lib/Maintenance/Tasks/CleanupBrickTablesTask.php [hunk 6]
```diff
@@ -27,11 +27,22 @@
  */
 class CleanupBrickTablesTask implements TaskInterface
 {
+    const PIMCORE_OBJECTBRICK_CLASS_DIRECTORY = PIMCORE_CLASS_DIRECTORY . '/DataObject/Objectbrick/Data';
```
Comment (lukmzig) [inline lib/Maintenance/Tasks/CleanupBrickTablesTask.php]:
```suggestion
   private const PIMCORE_OBJECTBRICK_CLASS_DIRECTORY = PIMCORE_CLASS_DIRECTORY . '/DataObject/Objectbrick/Data';
```

File: lib/Maintenance/Tasks/CleanupBrickTablesTask.php [hunk 7]
```diff
@@ -27,11 +27,22 @@
...
+
     private LoggerInterface $logger;
+    private $mapLowerToCamelCase = [];
```
Comment (lukmzig) [inline lib/Maintenance/Tasks/CleanupBrickTablesTask.php]:
```suggestion
    private array $mapLowerToCamelCase = [];
```

File: lib/Maintenance/Tasks/CleanupBrickTablesTask.php [hunk 8]
```diff
@@ -27,11 +27,22 @@
...
     public function __construct(LoggerInterface $logger)
     {
         $this->logger = $logger;
+        
+        $files = array_diff(scandir(self::PIMCORE_OBJECTBRICK_CLASS_DIRECTORY), array('..', '.'));
+        foreach ($files as $file) {
+            $classname = str_replace('.php','',$file);
+            $class = '\\Pimcore\\Model\\DataObject\\Objectbrick\\Data\\' . $classname;
+            $object = new $class(new \Pimcore\Model\DataObject\Concrete());
+            $this->mapLowerToCamelCase[strtolower($classname)] = $object->getType();
```
Comment (lukmzig) [inline lib/Maintenance/Tasks/CleanupBrickTablesTask.php]:
```suggestion
            $classname = str_replace('.php','',$file);
            $this->mapLowerToCamelCase[strtolower($classname)] = $classname ;
```
I think the class name (file name) is identical to the type? Or am I missing something?

**Comment by APochmann** [comment]
Hi @lukmzig , I accepted your suggestions (including the one you had the questions about if file name is always equal to class type name where I'm 100% sure for Linux, was not so convinced for Windows systems. But you are right, without manual manipulation on the files this will not be possible so your suggestion is better and more efficient). Now we run into failed checks which I currently don't understand. Any idea?

**Comment by lukmzig** [comment]
Hi @APochmann, thank you for your fast reply and implementation of the suggestions.
Regarding the failing Codeception tests, this is a known issue right now, unfortunately introduced by some changes in the Symfony 6.3. We already opened an issue ticket in the Symfony repository and are waiting for their response. I will keep you updated, best case we can just re-run the tests and merge your PR.

------
Short update: as these tests are flagged as experimental (and it might take some time for Symfony to response) we will merge the PR
