### PR TITLE
[Bug] Fixed regex validation issue

### LINKED ISSUE #14639: [Bug]: RegExp validation throws error
### Expected behavior

Regexp validation with `global` flag i Class Definition should work.

### Actual behavior

`Warning: preg_match(): Unknown modifier 'g'`

With delimiter specified the error message changes to:
`Warning: preg_match(): Unknown modifier '\'`

### Steps to reproduce

Add a rule like the following:
Screenshot 2023-03-13 at 16 57 50

Click *Save & publish*  on a DataObject with the field.

### PR DESCRIPTION
**Pull request by Corepex**
## Changes in this pull request  
Resolves #14639

## Additional info  
https://www.designcise.com/web/tutorial/how-to-fix-warning-preg-match-unknown-modifier-g-in-php

### CODE REVIEW

File: models/DataObject/ClassDefinition/Data/Input.php [hunk 1]
```diff
@@ -327,7 +327,20 @@ public function getQueryColumnType()
...
+                $flags = str_replace('g', '', implode('', $this->getRegexFlags()));
+                if (!preg_match_all('#' . $this->getRegex() . '#' . $flags, $data)) {
+                    $throwException = true;
+                }
+            }
+            else{
+                if (!preg_match('#' . $this->getRegex() . '#' . implode('', $this->getRegexFlags()), $data)) {
+                    $throwException = true;
+                }
+            }
```
Comment (jdreesen) [inline models/DataObject/ClassDefinition/Data/Input.php:341]: This should be enough, right?

```suggestion
            $flags = str_replace('g', '', implode('', $this->getRegexFlags()));
            if (!preg_match_all('#' . $this->getRegex() . '#' . $flags, $data)) {
                $throwException = true;
            }
```

File: models/DataObject/ClassDefinition/Data/Input.php [hunk 2]
```diff
@@ -327,7 +327,20 @@ public function getQueryColumnType()
...
+
+            if($throwException) {
```
Comment (jdreesen) [inline models/DataObject/ClassDefinition/Data/Input.php:343]: This should be enough, right?

```suggestion
            $flags = str_replace('g', '', implode('', $this->getRegexFlags()));
            if (!preg_match_all('#' . $this->getRegex() . '#' . $flags, $data)) {
```

Comment (Corepex) [reply models/DataObject/ClassDefinition/Data/Input.php:343]: @jdreesen, thanks for your suggestion. 

I think that will cause errors since `preg_match_all` will always act like there is a "g" flag, and since the class editor lets you choose if you want to have the global flag, we shouldn't override that decision.

Or did I miss something?

Comment (jdreesen) [reply models/DataObject/ClassDefinition/Data/Input.php:343]: Ooh, I didn't look carefully enough. Forget it, your code is right! Sorry for the noise.

Comment (Corepex) [reply models/DataObject/ClassDefinition/Data/Input.php:343]: @jdreesen no problem 🥇
