### PR TITLE
Fix CsvFormulaFormatter breaks with league/csv:9.11

### LINKED ISSUE #15998: CsvFormulaFormatter breaks with league/csv:9.11
### Improvement description

Fix type hints for extended method:
```
Fatal error: Declaration of Pimcore\Helper\CsvFormulaFormatter::unEscapeField(string $field): string must be compatible with League\Csv\EscapeFormula::unescapeField(mixed $cell): mixed in /var/www/html/vendor/pimcore/pimcore/lib/Helper/CsvFormulaFormatter.php on line 22
```

### PR DESCRIPTION
**Pull request by dvesh3**
## Changes in this pull request  
Resolves #15998

### <samp>🤖 Generated by Copilot at dac19b9</samp>

Simplified and fixed CSV export of data objects with formulas. Used parent class method for `unEscapeField` in `CsvFormulaFormatter.php`.

### <samp>🤖 Generated by Copilot at dac19b9</samp>

> _`unEscapeField` changed_
> _uses parent class method_
> _bug fixed in autumn_

### <samp>🤖 Generated by Copilot at dac19b9</samp>

*  Simplify the `unEscapeField` method in the `CsvFormulaFormatter` class to use the parent class method and fix a bug with CSV export of data objects with formulas ([link](https://github.com/pimcore/pimcore/pull/15999/files?diff=unified&w=0#diff-cbd1d9c0567d80b312e5c5685b32f87fea4a3566d4df159f6ecda2b558e5f438L22-R24))
* Update the type hint of the `$field` parameter in the `unEscapeField` method to `mixed` to match the parent class signature ([link](https://github.com/pimcore/pimcore/pull/15999/files?diff=unified&w=0#diff-cbd1d9c0567d80b312e5c5685b32f87fea4a3566d4df159f6ecda2b558e5f438L22-R24))

### CODE REVIEW

File: lib/Helper/CsvFormulaFormatter.php [hunk 1]
```diff
@@ -19,15 +19,8 @@
...
-        if (isset($field[0], $field[1])
-            && $field[0] === $this->getEscape()
-            && in_array($field[1], $this->getSpecialCharacters())
-        ) {
-            return ltrim($field, $field[0]);
-        }
-
-        return $field;
+        return parent::unescapeField($field);
     }
```
Comment (jdreesen) [inline lib/Helper/CsvFormulaFormatter.php]: Do we actually need this, if it's just calling the parent method?

Comment (dvesh3) [reply lib/Helper/CsvFormulaFormatter.php]: Reverted in bugfix. We should mark this deprecated in 11.1 and suggest to use the one from League\Csv

**Comment by jhormel** [comment]
As just mentioned here #15998

I guess we still don't match the parent class signature.

Parameter type has been fixed
Return type has **not** been fixed

Please correct me if I'm wrong :)

**Comment by jdreesen** [comment]
It does match the parent signature because of [covariance](https://www.php.net/manual/en/language.oop5.variance.php): return types of child classes are allowed to be more specific.

File: lib/Helper/CsvFormulaFormatter.php (hunk 1 above)
Comment (aryaantony92) [reply lib/Helper/CsvFormulaFormatter.php]: Done in https://github.com/pimcore/pimcore/pull/16002/

**Comment by skygatewitt** [comment]
Could you merge this fix into the 10.x branch as well? The cache clear command silently (ok, logged to file but still) fails, when called from Admin UI and prevents changes to the system.yml or other Symfony cached files from being put into effect. Symfony creates an underscored warmup folder (e.g. prod > pro_) and fails critically before switching. I used the dac19b9 commit above as a patch, but I'm sure a lot of people don't realise the caching problems until it's to late.

**Comment by blankse** [comment]
@skygatewitt Pimcore 10.x has reached EOL. You can add a conflict to your composer.json so the composer doesn't load the incompatible package.

See https://github.com/orgs/pimcore/discussions/16006

**Comment by skygatewitt** [comment]
@blankse Oh, I missed that threat. Will do, thank you!
