### PR TITLE
[Bug] Fix  Classification Store inheritance 

### LINKED ISSUE #14874: [Classification Store] Inheritance not working properly on the metadata
I think this PR https://github.com/pimcore/pimcore/pull/14477 is breaking something else related to inherited flag on the metadata

See also for more info: https://github.com/pimcore/pimcore/pull/14477#issuecomment-1498669306

_Originally posted by @flamadrid-jsmdg in https://github.com/pimcore/pimcore/issues/14477#issuecomment-1495048903_

### PR DESCRIPTION
**Pull request by procnet0**
## Changes in this pull request  
Resolves #14874 

### <samp>🤖 Generated by Copilot at 46dcb94</samp>

This pull request enhances the `Classificationstore` class with type declarations, return types, and inheritance options, and fixes a typo and a logic issue. These changes improve the code quality and functionality of the class, which handles data storage and retrieval for data objects.

### <samp>🤖 Generated by Copilot at 46dcb94</samp>

> _Oh we're the coders of the `Classificationstore`_
> _We type and test and refactor with care_
> _We add declarations, return types, and inheritance_
> _And fix the bugs that lurk in there_

### <samp>🤖 Generated by Copilot at 46dcb94</samp>

*  Add `use Exception` statement and replace `\Exception` with `Exception` to simplify the code ([link](https://github.com/pimcore/pimcore/pull/14948/files?diff=unified&w=0#diff-08971fa2cb1531e8fd9723c4ac947cdc8cfee491e2fee2294b57f92f4eb8dc8eR18), [link](https://github.com/pimcore/pimcore/pull/14948/files?diff=unified&w=0#diff-08971fa2cb1531e8fd9723c4ac947cdc8cfee491e2fee2294b57f92f4eb8dc8eL188-R202), [link](https://github.com/pimcore/pimcore/pull/14948/files?diff=unified&w=0#diff-08971fa2cb1531e8fd9723c4ac947cdc8cfee491e2fee2294b57f92f4eb8dc8eL374-R383))
*  Add type declarations to properties, parameters, and return values to make the code more consistent and explicit about the expected data types ([link](https://github.com/pimcore/pimcore/pull/14948/files?diff=unified&w=0#diff-08971fa2cb1531e8fd9723c4ac947cdc8cfee491e2fee2294b57f92f4eb8dc8eL39-R40), [link](https://github.com/pimcore/pimcore/pull/14948/files?diff=unified&w=0#diff-08971fa2cb1531e8fd9723c4ac947cdc8cfee491e2fee2294b57f92f4eb8dc8eL60-R61), [link](https://github.com/pimcore/pimcore/pull/14948/files?diff=unified&w=0#diff-08971fa2cb1531e8fd9723c4ac947cdc8cfee491e2fee2294b57f92f4eb8dc8eL67-R68), [link](https://github.com/pimcore/pimcore/pull/14948/files?diff=unified&w=0#diff-08971fa2cb1531e8fd9723c4ac947cdc8cfee491e2fee2294b57f92f4eb8dc8eL74-R80), [link](https://github.com/pimcore/pimcore/pull/14948/files?diff=unified&w=0#diff-08971fa2cb1531e8fd9723c4ac947cdc8cfee491e2fee2294b57f92f4eb8dc8eL90-R91), [link](https://github.com/pimcore/pimcore/pull/14948/files?diff=unified&w=0#diff-08971fa2cb1531e8fd9723c4ac947cdc8cfee491e2fee2294b57f92f4eb8dc8eL97-R102), [link](https://github.com/pimcore/pimcore/pull/14948/files?diff=unified&w=0#diff-08971fa2cb1531e8fd9723c4ac947cdc8cfee491e2fee2294b57f92f4eb8dc8eL110-R118), [link](https://github.com/pimcore/pimcore/pull/14948/files?diff=unified&w=0#diff-08971fa2cb1531e8fd9723c4ac947cdc8cfee491e2fee2294b57f92f4eb8dc8eL122-R127), [link](https://github.com/pimcore/pimcore/pull/14948/files?diff=unified&w=0#diff-08971fa2cb1531e8fd9723c4ac947cdc8cfee491e2fee2294b57f92f4eb8dc8eL147-R152), [link](https://github.com/pimcore/pimcore/pull/14948/files?diff=unified&w=0#diff-08971fa2cb1531e8fd9723c4ac947cdc8cfee491e2fee2294b57f92f4eb8dc8eL171-R179), [link](https://github.com/pimcore/pimcore/pull/14948/files?diff=unified&w=0#diff-08971fa2cb1531e8fd9723c4ac947cdc8cfee491e2fee2294b57f92f4eb8dc8eL266-R271), [link](https://github.com/pimcore/pimcore/pull/14948/files?diff=unified&w=0#diff-08971fa2cb1531e8fd9723c4ac947cdc8cfee491e2fee2294b57f92f4eb8dc8eL274-R279), [link](https://github.com/pimcore/pimcore/pull/14948/files?diff=unified&w=0#diff-08971fa2cb1531e8fd9723c4ac947cdc8cfee491e2fee2294b57f92f4eb8dc8eL282-R287), [link](https://github.com/pimcore/pimcore/pull/14948/files?diff=unified&w=0#diff-08971fa2cb1531e8fd9723c4ac947cdc8cfee491e2fee2294b57f92f4eb8dc8eL290-R295), [link](https://github.com/pimcore/pimcore/pull/14948/files?diff=unified&w=0#diff-08971fa2cb1531e8fd9723c4ac947cdc8cfee491e2fee2294b57f92f4eb8dc8eL296-R312), [link](https://github.com/pimcore/pimcore/pull/14948/files?diff=unified&w=0#diff-08971fa2cb1531e8fd9723c4ac947cdc8cfee491e2fee2294b57f92f4eb8dc8eL321-R330), [link](https://github.com/pimcore/pimcore/pull/14948/files?diff=unified&w=0#diff-08971fa2cb1531e8fd9723c4ac947cdc8cfee491e2fee2294b57f92f4eb8dc8eL340-R349), [link](https://github.com/pimcore/pimcore/pull/14948/files?diff=unified&w=0#diff-08971fa2cb1531e8fd9723c4ac947cdc8cfee491e2fee2294b57f92f4eb8dc8eL460-R469), [link](https://github.com/pimcore/pimcore/pull/14948/files?diff=unified&w=0#diff-08971fa2cb1531e8fd9723c4ac947cdc8cfee491e2fee2294b57f92f4eb8dc8eL466-R482), [link](https://github.com/pimcore/pimcore/pull/14948/files?diff=unified&w=0#diff-08971fa2cb1531e8fd9723c4ac947cdc8cfee491e2fee2294b57f92f4eb8dc8eL485-R498), [link](https://github.com/pimcore/pimcore/pull/14948/files?diff=unified&w=0#diff-08971fa2cb1531e8fd9723c4ac947cdc8cfee491e2fee2294b57f92f4eb8dc8eL497-R510), [link](https://github.com/pimcore/pimcore/pull/14948/files?diff=unified&w=0#diff-08971fa2cb1531e8fd9723c4ac947cdc8cfee491e2fee2294b57f92f4eb8dc8eL505-R520))
*  Add `bool` parameters `$withInheritance` to methods that fetch data from the classification store, to allow the option to include the inherited data from the parent objects in the result ([link](https://github.com/pimcore/pimcore/pull/14948/files?diff=unified&w=0#diff-08971fa2cb1531e8fd9723c4ac947cdc8cfee491e2fee2294b57f92f4eb8dc8eL110-R118), [link](https://github.com/pimcore/pimcore/pull/14948/files?diff=unified&w=0#diff-08971fa2cb1531e8fd9723c4ac947cdc8cfee491e2fee2294b57f92f4eb8dc8eL296-R312), [link](https://github.com/pimcore/pimcore/pull/14948/files?diff=unified&w=0#diff-08971fa2cb1531e8fd9723c4ac947cdc8cfee491e2fee2294b57f92f4eb8dc8eL466-R482), [link](https://github.com/pimcore/pimcore/pull/14948/files?diff=unified&w=0#diff-08971fa2cb1531e8fd9723c4ac947cdc8cfee491e2fee2294b57f92f4eb8dc8eL505-R520))
*  Simplify the logic of the `getGroups` method by calling the `getActiveGroupsWithConfig` method directly with the current object and the inheritance option, instead of using the `getAllDataFromField` method with a closure ([link](https://github.com/pimcore/pimcore/pull/14948/files?diff=unified&w=0#diff-08971fa2cb1531e8fd9723c4ac947cdc8cfee491e2fee2294b57f92f4eb8dc8eL505-R520))
*  Fix a typo in the variable name `$fieldDefintions` to `$fieldDefinitions` in the `getAllDataFromField` method, and add a condition to check if the current field name matches the field name of the classification store data object in the loop, to avoid unnecessary calls to the getter methods of other fields ([link](https://github.com/pimcore/pimcore/pull/14948/files?diff=unified&w=0#diff-08971fa2cb1531e8fd9723c4ac947cdc8cfee491e2fee2294b57f92f4eb8dc8eL515-R530))

### CODE REVIEW

**Comment by brusch** [comment]
@procnet0 Thanks a lot for your PR, however, we can't merge that as a bug-fix since it includes breaking changes such as adding native types - this happend already in `11.x` so this PR should just focus on fixing an actual issue. 

Thanks!

**Comment by procnet0** [comment]
Hello , @brusch Thanks for the review, I've removed changes on Native Types.

Let me know if something's still blocking.

Thanks!

File: models/DataObject/Classificationstore.php [hunk 1]
```diff
@@ -107,10 +108,14 @@ public function setItems($items)
     }
 
     /**
+     * @param bool $withInheritance
      * @return array
      */
-    public function getItems()
+    public function getItems($withInheritance = false)
```
Comment (jdreesen) [inline models/DataObject/Classificationstore.php]: Those additional parameters on public functions are still breaking changes. It has to be done in a non-BC-breaking way.

File: models/DataObject/Classificationstore.php [hunk 2]
```diff
@@ -504,24 +516,23 @@ public function getGroupCollectionMapping($groupId)
...
     {
         $fieldsArray = $mergeFunction($this, []);
         $object = $this->getObject();
         while (!is_null($object) && ($parent = Service::hasInheritableParentObject($object)) !== null) {
-            $fieldDefintions = $parent->getClass()->getFieldDefinitions();
-            foreach ($fieldDefintions as $key => $fd) {
-                if ($fd instanceof Model\DataObject\ClassDefinition\Data\Classificationstore) {
+            $fieldDefinitions = $parent->getClass()->getFieldDefinitions();
+            foreach ($fieldDefinitions as $key => $fd) {
+                if ($fd instanceof Model\DataObject\ClassDefinition\Data\Classificationstore && $key == $this->getFieldname()) {
```
Comment (procnet0) [inline models/DataObject/Classificationstore.php]: to handle the case of multiple classification store field on the same object.

File: models/DataObject/Classificationstore.php [hunk 3]
```diff
@@ -297,7 +301,11 @@ public function setFieldname($fieldname)
      */
     public function getActiveGroups()
     {
-        return $this->activeGroups;
+        $doGetInheritedValues = Model\DataObject::doGetInheritedValues();
```
Comment (procnet0) [inline models/DataObject/Classificationstore.php:304]: using DataObject:doGetInheritedValues(); to avoid breaking Changes

 has it is done in getLocalizedKeyValue()

File: models/DataObject/Classificationstore.php [hunk 4]
```diff
@@ -467,6 +475,10 @@ public static function doGetFallbackValues()
      */
     public function getGroupCollectionMappings(): array
     {
+        $doGetInheritedValues = Model\DataObject::doGetInheritedValues();
```
Comment (procnet0) [inline models/DataObject/Classificationstore.php:478]: using DataObject:doGetInheritedValues(); to avoid breaking Changes

 has it is done in getLocalizedKeyValue()

File: models/DataObject/Classificationstore.php [hunk 5]
```diff
@@ -111,6 +111,10 @@ public function setItems($items)
      */
     public function getItems()
     {
+        $doGetInheritedValues = Model\DataObject::doGetInheritedValues();
```
Comment (procnet0) [inline models/DataObject/Classificationstore.php:114]: using DataObject:doGetInheritedValues(); to avoid breaking Changes

 has it is done in getLocalizedKeyValue()

**Comment by procnet0** [comment]
Hello, @brusch  can you please Review the changes I Made.

Proper Inheritance over ClassificationStore  is an important requirement an a Datasolution Project (version 10.5.X).

Thanks a lot. 

Have a good Day.

**Comment by brusch** [comment]
@procnet0 thanks for adapting your PR - looks already much better 😊 We'll review it as soon as possible. Thanks for being patience.

File: models/DataObject/Classificationstore.php [hunk 6]
```diff
@@ -504,24 +516,23 @@ public function getGroupCollectionMapping($groupId)
...
         while (!is_null($object) && ($parent = Service::hasInheritableParentObject($object)) !== null) {
-            $fieldDefintions = $parent->getClass()->getFieldDefinitions();
-            foreach ($fieldDefintions as $key => $fd) {
-                if ($fd instanceof Model\DataObject\ClassDefinition\Data\Classificationstore) {
+            $fieldDefinitions = $parent->getClass()->getFieldDefinitions();
+            foreach ($fieldDefinitions as $key => $fd) {
+                if ($fd instanceof Model\DataObject\ClassDefinition\Data\Classificationstore && $key == $this->getFieldname()) {
                     $getter = 'get' . ucfirst($key);
                     $fieldsArray = $mergeFunction($parent->$getter(), $fieldsArray);
                 }
```
Comment (brusch) [inline models/DataObject/Classificationstore.php]:
```suggestion
            $fieldsArray = $mergeFunction($parent->{"get" . $this->getFieldname()}(), $fieldsArray);
```

File: models/DataObject/Classificationstore.php [hunk 7]
```diff
@@ -504,24 +516,18 @@ public function getGroupCollectionMapping($groupId)
...
         $object = $this->getObject();
         while (!is_null($object) && ($parent = Service::hasInheritableParentObject($object)) !== null) {
-            $fieldDefintions = $parent->getClass()->getFieldDefinitions();
-            foreach ($fieldDefintions as $key => $fd) {
-                if ($fd instanceof Model\DataObject\ClassDefinition\Data\Classificationstore) {
-                    $getter = 'get' . ucfirst($key);
-                    $fieldsArray = $mergeFunction($parent->$getter(), $fieldsArray);
-                }
+            $fieldsArray = $mergeFunction($parent->{"get" . $this->getFieldname()}(), $fieldsArray);
             }
```
Comment (robertSt7) [inline models/DataObject/Classificationstore.php]:
```suggestion
            
```

File: models/DataObject/Classificationstore.php [hunk 8]
```diff
@@ -504,24 +516,18 @@ public function getGroupCollectionMapping($groupId)
...
         $object = $this->getObject();
         while (!is_null($object) && ($parent = Service::hasInheritableParentObject($object)) !== null) {
-            $fieldDefintions = $parent->getClass()->getFieldDefinitions();
-            foreach ($fieldDefintions as $key => $fd) {
-                if ($fd instanceof Model\DataObject\ClassDefinition\Data\Classificationstore) {
-                    $getter = 'get' . ucfirst($key);
-                    $fieldsArray = $mergeFunction($parent->$getter(), $fieldsArray);
-                }
-            }
+            $fieldsArray = $mergeFunction($parent->{"get" . $this->getFieldname()}(), $fieldsArray);
```
Comment (robertSt7) [inline models/DataObject/Classificationstore.php]:
```suggestion
            $fieldsArray = $mergeFunction($parent->{"get" . ucfirst($this->getFieldname())}(), $fieldsArray);
```

**Comment by robertSt7** [comment]
@procnet0 Thanks a lot for the PR
