### PR TITLE
[Bug]: Fix DontEnv installer variables

### LINKED ISSUE #16891: [Bug, EC]: Impossible to install pimcore with variables inside config.yaml
### Pimcore version

11.2.2

### Steps to reproduce

- Init a new project: ``docker run -u `id -u`:`id -g` --rm -v `pwd`:/var/www/html pimcore/pimcore:php8.2-latest composer create-project pimcore/skeleton my-project``
- Add in config.yaml:
  ````yaml
  framework:
      cache:
          pools:
              pimcore.cache.pool:
                  public: true
                  default_lifetime: 31536000
                  adapter: cache.adapter.redis_tag_aware
                  provider: '%env(string:REDIS_HOST)%'
              cache.adapter.system:
                  default_lifetime: 31536000  # 1 year
                  adapter: cache.adapter.redis_tag_aware
                  provider: '%env(string:REDIS_HOST_SYSTEM)%'
  ````
- Add in .env:
  ````
  REDIS_HOST=redis://redis/1
  REDIS_HOST_SYSTEM=redis://redis/2
  ````
- Run `sed -i "s|#user: '1000:1000'|user: '$(id -u):$(id -g)'|g" docker-compose.yaml` to set the correct user id and group id.
- Start the needed services with `docker compose up -d`
-  `docker compose exec php vendor/bin/pimcore-install`
- Enter admin/password and answer no to extra bundles
- See error

### Actual Behavior

Since Pimcore 11.2.2 we can't install a project with variables inside config.yaml.

We get the following error:
image

It's seem that env values are not loaded anymore.

### Expected Behavior

Before 11.2.X we where able to install a new project with variables inside config.yaml.

### PR DESCRIPTION
**Pull request by kingjia90**
## Changes in this pull request  
Resolves https://github.com/pimcore/pimcore/issues/16891

### CODE REVIEW

**Comment by kingjia90** [comment]
putting into a "visual schema", hope it helps and it's correct and clear 
image
the [isCli change](https://github.com/pimcore/pimcore/pull/16911/commits/903e83748a17b9ad8f29a90c5ef3906700f81a24) fix es the ones with 🔷 but introduces problem with🟨 which need some workaround see https://github.com/pimcore/pimcore/pull/16911/commits/4a629cba4a579e5059c2fca92aeac79c95b65115

**Comment by kingjia90** [comment]
It seems that the current changes might work. Leaving some notes before weekend memory wipe 😅 

I've noticed a further potential case, if devs may have "rightfully missed" to apply https://github.com/pimcore/skeleton/pull/183 ~(highlighted in yellow)~
~Still have to check all the effects of latest PR commits~

image
Update: in that case, it would perform the dotenv twice, which is bad but doesn't bc-break or so, so it's just not recommended to not apply PR 183

File: lib/Bootstrap.php [hunk 1]
```diff
@@ -27,6 +27,8 @@
 
 class Bootstrap
 {
+    public static bool $isInstaller = false;
```
Comment (jdreesen) [inline lib/Bootstrap.php:33]: Should this be marked as `@internal`?
