### PR TITLE
Fixed object relations loading

### LINKED ISSUE #13736: Many-To-One Relation within a field collection is not saved when triggering workflow when the object is in draft
### Expected behavior

Having a field-collection that is composed by a localized field that has a Many-To-One and it is used in a data object that has a workflow, I expect an object to be saved after triggering the workflow with an object in draft state. 

### Actual behavior

If an object using the field-collection with a localized Many-To-One relation in a Data Object that is in draft state, after the workflow is triggered, the object relation get's rolled back to the previous last published state, however the other fields are saved correctly. _(Using Pimcore 10.5.11)_

### Steps to reproduce

1. Create a field collection that has 2 localized fields a Text for example and a Many-to-One relation:
Screenshot 2022-12-05 at 11 32 43

2. Create a data object that uses the previous field collection:
Screenshot 2022-12-05 at 11 32 01

3. Giving the data object with the initial (published) state:
Screenshot 2022-12-05 at 11 30 25

4. Now, create a new draft by changing Text field to something different and changing the the Many-to-One relation field (Page) to pointing to a different object.
Screenshot 2022-12-05 at 11 30 49

5. While the Data object is in draft state, trigger a workflow change.
Screenshot 2022-12-05 at 11 31 06

6. After the workflow is triggered, the text field has been saved correctly as "Name 2", however the Many-To-One field relation now points back to the original object rather than the object specified in the draft version.
Screenshot 2022-12-05 at 11 31 26

### PR DESCRIPTION
**Pull request by fashxp**
Relations of field collections, object bricks and localized fields need to point to the actual object version, not the version stored in DB. Otherwise there are some strange issues when saving elements or loading them from cache. 

That means, they must be set when loading the data object and must not be overwritten with values got with `getById`. 

This PR fixes #13736

Related to #12588
Might need to be reconsidered with #13874

### CODE REVIEW

File: models/Element/Service.php [hunk 1]
```diff
@@ -875,6 +876,13 @@ public static function renewReferences($data, $initial = true, $key = null)
             if ($data instanceof Model\AbstractModel) {
                 $properties = $data->getObjectVars();
                 foreach ($properties as $name => $value) {
+
+                    //do not renew object reference of ObjectAwareFieldInterface - as object might point to a
+                    //specific version of the object and must not be reloaded with DB version of object
+                    if(($data instanceof ObjectAwareFieldInterface || $data instanceof DataObject\Localizedfield) && $name === 'object') {
```
Comment (brusch) [inline models/Element/Service.php:882]: @fashxp I think  `Localizedfield` should also implement `ObjectAwareFieldInterface`.  That should be safe as it's a `final` class, we can also change the signature of `setObject()` (remove `$markAsDirty` parameter).  `markAllLanguagesAsDirty()` is public and can be called separately if necessary. Additionally `__objectAwareFields` would need to be filled accordingly by the localized field. 
WDYT?

**Review by brusch — CHANGES_REQUESTED** [review]

File: models/Element/Service.php (hunk 1 above)
Comment (brusch) [reply models/Element/Service.php:882]: Sorry, already covered in #13874 (PR) and #12598 (issue).
