### PR TITLE
[Admin] DataObject - Fix only save last filled localizedfields in Objectbricks/Blocks

### LINKED ISSUE #7059: [Admin] DataObject - only save last filled localizedfields in Objectbricks/Blocks
# Bug Report

### Steps to reproduce
- Create Class with Objectbrick:

- Create Objectbrick with 2 localizedfields
image

- Fill both localizedfields and save

- Reload

### Expected behavior
- Both localizedfields are filled

### Actual behavior
- Only the second localizedfield is filled

### PR DESCRIPTION
**Pull request by dvesh3**
## Changes in this pull request  
Resolves #7059

## Additional info  
Similar fix like fieldcollections https://github.com/pimcore/pimcore/issues/1764

### CODE REVIEW

File: models/DataObject/ClassDefinition/Data/Block.php [hunk 1]
```diff
@@ -684,7 +684,15 @@ public function doGetFieldDefinitions($def = null, $fields = [])
         }
 
         if ($def instanceof DataObject\ClassDefinition\Data) {
-            $fields[$def->getName()] = $def;
+            $existing = $fields[$def->getName()];
```
Comment (blankse) [inline models/DataObject/ClassDefinition/Data/Block.php:687]:
```suggestion
            $existing = $fields[$def->getName()] ?? null;
```

Comment (dvesh3) [reply models/DataObject/ClassDefinition/Data/Block.php]: already pushed..thanks!

**Review by blankse — APPROVED** [review]
