### PR TITLE
Model::getById() ::getByPath() ... shouldn't catch any exceptions

### LINKED ISSUE #7322: Model::getById() ::getByPath() ::getByName() ...  shouldn't catch any Exceptions

### PR DESCRIPTION
**Pull request by weisswurstkanone**
resolves #7322

### CODE REVIEW

File: models/Element/Exception/ElementNotFoundException.php [hunk 1]
```diff
@@ -0,0 +1,22 @@
...
+ * @category   Pimcore
+ * @package    Element
+ *
+ * @copyright  Copyright (c) Pimcore GmbH (http://www.pimcore.org)
+ * @license    http://www.pimcore.org/license     GPLv3 and PEL
+ */
+
+namespace Pimcore\Model\Element\Exception;
+
+class ElementNotFoundException extends \Exception
```
Comment (jdreesen) [inline models/Element/Exception/ElementNotFoundException.php:20]: This should extend the [`RuntimeException`](https://www.php.net/manual/de/class.runtimeexception.php) class, as this only occurs on runtime.

```suggestion
class ElementNotFoundException extends \RuntimeException
```

File: models/Asset.php [hunk 2]
```diff
@@ -232,7 +232,7 @@ public static function getByPath($path, $force = false)
             $asset->getDao()->getByPath($path);
 
             return static::getById($asset->getId(), $force);
-        } catch (ElementNotFoundException $e) {
+        } catch (NotFoundExceptio $e) {
```
Comment (jdreesen) [inline models/Asset.php]:
```suggestion
        } catch (NotFoundException $e) {
```

**Review by jdreesen — CHANGES_REQUESTED** [review]
