### PR TITLE
Deprecate callback support in thumbnail transformations

### LINKED ISSUE #14054: [Bug]: Cropped image auto generated name fails
### Expected behavior

Set up a thumbnail config item as a closure. Crop the image in an image editable and dont receive a serialization error.

### Actual behavior

Setting up an thumbnail config item as an closure and cropping the image in an image editable throws the following exception:

Serialization of 'Closure' is not allowed File: /var/www/html/vendor/pimcore/pimcore/lib/Tool/Serialize.php Line: 32

### Steps to reproduce

1. Setup thumbnail config item as closure. For Example:
As it is possible => https://github.com/pimcore/pimcore/blob/11.x/models/Asset/Image/Thumbnail/Processor.php#L400
```
  $items = $config->getItems();
  $items[] = [
      'method' => function ($image) {
          if (method_exists($image, 'copyrightDisclaimer')) {
              $image->copyrightDisclaimer();
          }
      },
      'arguments' => [],
  ];
  $config->setItems($items);
```

3. Crop one image in an image editable:
4. https://github.com/pimcore/pimcore/blob/11.x/models/Document/Editable/Image.php#L267 creates the exception as the serialization fails for an closure

### PR DESCRIPTION
**Pull request by dvesh3**
## Changes in this pull request  
Resolves #14054

### CODE REVIEW

File: models/Asset/Image/Thumbnail/Config.php [hunk 1]
```diff
@@ -965,4 +963,19 @@ public function getAutoFormatThumbnailConfigs(): array
...
         return $autoFormatThumbnails;
     }
+
+    /**
+     * @internal
+     */
+    public function generateAutoName(): void
+    {
+        try {
+            $serialized = Serialize::serialize($this->getItems());
```
Comment (brusch) [inline models/Asset/Image/Thumbnail/Config.php]: Isn't that dangerous as it would generate new files again and again?

**Review by brusch — CHANGES_REQUESTED** [review]

File: models/Asset/Image/Thumbnail/Config.php (hunk 1 above)
Comment (dvesh3) [reply models/Asset/Image/Thumbnail/Config.php]: you are right, this will generate auto thumbnails on every request. I'll fix it.

Comment (dvesh3) [reply models/Asset/Image/Thumbnail/Config.php]: fixed with `opis/closure` to serialize thumbnail closure items.

File: composer.json [hunk 2]
```diff
@@ -160,7 +160,8 @@
     "knplabs/knp-paginator-bundle": "^5.4.2",
     "masterminds/html5" : "^2.7",
     "league/flysystem-bundle" : "^2.0",
-    "spatie/image-optimizer": "^1.6.2"
+    "spatie/image-optimizer": "^1.6.2",
+    "opis/closure": "^3.5"
```
Comment (jdreesen) [inline composer.json]: Note that this library is **not** compatible with PHP 8.1 (even if the `composer.json` states otherwise) and probably never will be (even if there's an experimental `v4` using FFI)! It looks like the entire project is not actively developed anymore, so I doubt that it'll add support for PHP 8.2 and up.

You can use [Laravel's fork](https://github.com/laravel/serializable-closure) or the [experimental FFI version](https://github.com/opis/closure/issues/59) of this package (I'm not sure if it's actively developed, though).

See: opis/closure#128, opis/closure#127, opis/closure#125, opis/closure#124, opis/closure#120, opis/closure#114, opis/closure#107, opis/closure#104, ...

File: models/Asset/Image/Thumbnail/Config.php (hunk 1 above)
Comment (jdreesen) [reply models/Asset/Image/Thumbnail/Config.php]: Careful, as this library is not compatible with PHP 8.1. See note below.

**Comment by brusch** [comment]
Just an idea, what if we leave it as it is for Pimcore `10.x` because it's anyway not frequently used and we fix that for `11.x` where using this features requires to set a unique key for the thumbnail? If not given it throws an exception.

**Comment by dvesh3** [comment]
@brusch nice idea! can't we set a unique key internally whenever you try to set a closure item and then if the unique keys exists, use this instead of serializing items. 

We can even introduce this on 10 since this internal (still requires same step to set closure items) and it even support cache busting in thumbnail names.

**Comment by brusch** [comment]
@dvesh3 But when using a unique random key  would result in different filenames for the same config. So when calling the same action from different processes it will always generate a different key, resulting in generating the thumbnail again and again and filling up the storage. 
I'm even wondering if there's an actual need for this feature or if we should just deprecate it completely and offer an event instead, where you can then do whatever you want. 

I'd go for the latter, so deprecating in `10.6` and removing the functionality in `11.x`. 
If there's demand we can then think about introducing events for thumbnails in a later minor version of v11.

File: tests/Model/Asset/AssetTest.php [hunk 3]
```diff
@@ -257,4 +258,23 @@ public function testAssetFullPath()
         $this->assertMatchesRegularExpression('@^(https?|data):@', $thumbnailFullUrl);
         $this->assertStringContainsString($thumbnail->getPath(), $thumbnailFullUrl);
     }
+
+    public function testAssetThumbnailWithClosureItem()
```
Comment (blankse) [inline tests/Model/Asset/AssetTest.php]:
```suggestion
    public function testAssetThumbnailWithClosureItem(): void
```

Comment (dvesh3) [reply tests/Model/Asset/AssetTest.php]: Kicked test for deprecated functionality 😉

**Comment by martineiber** [comment]
@dvesh3 can you please merge the latest changes into the branch, and check the codeception tests?

**Comment by dvesh3** [comment]
@martineiber Done. Tests are ✔️

**Review by martineiber — APPROVED** [review]
LGTM!
