### PR TITLE
Fix: Blocking Events recursion

### LINKED ISSUE #11526: [Bug]: Calling certain methods in EventListener can cause an infinite recursion
### Expected behavior

No infinite recursion

### Actual behavior

Calling certain methods, like `$asset->getThumbnail($name)`, in postUpdate Eventlistener can cause an infinite recursion. 
If the thumbnail is not already existing, the method will call `$asset->save()` and therefore the EventListener will be fired again. Thus getThumbnail() gets called again, asset will be saved again and so on.

Possible solutions:

1. Implement a method, that prevents the events from being fired. Similiar to Version::disable()
2. Provide a method, that only saves the custom settings/metadata, without really saving the asset (without events, without versioning, etc...)
3. Rethink the whole approach, since most of the functionality can be replaced by checking for the existence of the file in the filesystem (file_exists method)

### Steps to reproduce

1.) Register an Eventlistener for postUpdate on assets
2.) call ` $asset->getThumbnail($name);`  and make sure that the thumbnail doesn´t exist already

### PR DESCRIPTION
**Pull request by kingjia90**
fixes #11526

### CODE REVIEW

**Review by jdreesen — COMMENTED** [review]
What about creating a new function for dispatching events, like:

```php
protected function dispatchEvent(Event $event, string $name): void {
	if ($this->isAllowedEvent($name)){
		\Pimcore::getEventDispatcher()->dispatch($event, $name);
	}
}
```

Then you wouldn't have to wrap every single dispatch into an `if` check.

---

Maybe everything (including `$disabledEvents`, `disableEvents()` and `isAllowedEvent()`) can even be put into a trait and be reused.

**Comment by kingjia90** [comment]
@jdreesen Thank you for the feedback! I will surely follow your suggestion, the code would look much cleaner

**Comment by brusch** [comment]
Probably it would also make sense to put that code into a trait that can be used anywhere necessary 🤔

File: lib/Event/Traits/DisableEventTrait.php [hunk 1]
```diff
@@ -0,0 +1,63 @@
...
+     */
+    protected static $disabledEvents = [];
+
+    /**
+     * Sets the list of disabled events
+     *
+     * @param array $events
+     * @return void
+     */
+    public static function disableEvents(array $events = []): void
```
Comment (brusch) [inline lib/Event/Traits/DisableEventTrait.php]: This is not used anywhere? I think we can kick it anyway.

File: lib/Event/Traits/DisableEventTrait.php [hunk 2]
```diff
@@ -0,0 +1,63 @@
...
+
+use Symfony\Contracts\EventDispatcher\Event;
+
+trait DisableEventTrait
+{
+
+    /**
+     * @var array
+     */
+    protected static $disabledEvents = [];
```
Comment (brusch) [inline lib/Event/Traits/DisableEventTrait.php]:
```suggestion
    private $activeDispatchingEvents = [];
```
I guess we need to consider this here as well then? 
https://github.com/pimcore/pimcore/blob/9859aacdc0653090182c1d403bcc4b60226bf4e8/models/Element/AbstractElement.php#L391

File: lib/Event/Traits/DisableEventTrait.php [hunk 3]
```diff
@@ -0,0 +1,63 @@
...
+ *
+ * @copyright  Copyright (c) Pimcore GmbH (http://www.pimcore.org)
+ * @license    http://www.pimcore.org/license     GPLv3 and PCL
+ */
+
+namespace Pimcore\Event\Traits;
+
+use Symfony\Contracts\EventDispatcher\Event;
+
+trait DisableEventTrait
```
Comment (brusch) [inline lib/Event/Traits/DisableEventTrait.php]:
```suggestion
trait RecursionBlockingEventDispatchHelperTrait
```
Maybe a more meaningful class name?

File: lib/Event/Traits/DisableEventTrait.php [hunk 4]
```diff
@@ -0,0 +1,63 @@
...
+    /**
+     * Checks if an event is not currently disabled
+     *
+     * @param string $eventName
+     * @return bool
+     */
+    private function isAllowedEvent(string $eventName): bool
+    {
+        return !in_array($eventName, self::$disabledEvents);
+    }
```
Comment (brusch) [inline lib/Event/Traits/DisableEventTrait.php]:
```suggestion
```
We just need that once, so we don't need an extra method for that imho. 😉

File: lib/Event/Traits/DisableEventTrait.php [hunk 5]
```diff
@@ -0,0 +1,63 @@
...
+     * @param Event $event
+     * @param string $name
+     * @return void
+     */
+    protected function dispatchEvent(Event $event, string $name): void
+    {
+        if ($this->isAllowedEvent($name)) {
+            \Pimcore::getEventDispatcher()->dispatch($event, $name);
+        }
+    }
```
Comment (brusch) [inline lib/Event/Traits/DisableEventTrait.php]:
```suggestion
    protected function dispatchEvent(object $event, string $eventName = null): ?object
    {
        $eventName = $eventName ?? \get_class($event);
        if (!isset($this->activeDispatchingEvents[$eventName])) {
            $this->activeDispatchingEvents[$eventName] = true;
            \Pimcore::getEventDispatcher()->dispatch($event, $eventName);
            unset($this->activeDispatchingEvents[$eventName]);
        }
    }
```
I'd use the same method signature as `\Symfony\Contracts\EventDispatcher\EventDispatcherInterface::dispatch

**Review by brusch — CHANGES_REQUESTED** [review]

File: lib/Event/Traits/DisableEventTrait.php (hunk 5 above)
Comment (kingjia90) [reply lib/Event/Traits/DisableEventTrait.php]: i've tested it, nice approach, works simply fine for the purpose. 

The main differences are that:
- `activeDispatchingEvents` approach is automatical (like by default in the system), while `disableEvents` is more manual, up to the developer and situational
- the `activeDispatchingEvents` stops the same event that was called by the parent event, but doesn't have control over stopping/preventing any other events from firing. In other words, it won't help to stop PRE_UPDATE in a recursive POST_UPDATE. With `disableEvents`, it would allow to manually decide to stop any other ones before that
-  `disableEvents` could be used in other circumstances beside from preventing recursion.

Not sure if these could be some valid points to consider, but the recommendation was to follow the `Version::disable()` approach, that's why it looks like that (like `disableEvents` not used anywhere in the PR).

Comment (brusch) [reply lib/Event/Traits/DisableEventTrait.php]: As discussed, we only want to block recursion for the same object at the moment (as this is a bug). 
Can you please update the PR accordingly? Thanks a lot 😊

File: lib/Event/Traits/RecursionBlockingEventDispatchHelperTrait.php [hunk 6]
```diff
@@ -0,0 +1,42 @@
...
+    /**
+     * Dispatches an event, avoids recursion by checking if the active dispatch event is the same
+     *
+     * @param object $event
+     * @param string|null $eventName
+     * @return void
+     */
+    protected function dispatchEvent(object $event, string $eventName = null): void
+    {
+        $eventName = $eventName ?? \get_class($event);
```
Comment (jdreesen) [inline lib/Event/Traits/RecursionBlockingEventDispatchHelperTrait.php]:
```suggestion
        $eventName ??= \get_class($event);
```

**Comment by brusch** [comment]
@kingjia90 thanks for updating the PR, however, one thing u missed: 😉
> I guess we need to consider this here as well then? 
https://github.com/pimcore/pimcore/blob/9859aacdc0653090182c1d403bcc4b60226bf4e8/models/Element/AbstractElement.php#L391

File: lib/Event/Traits/RecursionBlockingEventDispatchHelperTrait.php [hunk 7]
```diff
@@ -0,0 +1,42 @@
...
+ * Full copyright and license information is available in
+ * LICENSE.md which is distributed with this source code.
+ *
+ * @copyright  Copyright (c) Pimcore GmbH (http://www.pimcore.org)
+ * @license    http://www.pimcore.org/license     GPLv3 and PCL
+ */
+
+namespace Pimcore\Event\Traits;
+
+trait RecursionBlockingEventDispatchHelperTrait
```
Comment (brusch) [inline lib/Event/Traits/RecursionBlockingEventDispatchHelperTrait.php:21]:
```suggestion
/**
 * @internal
 */
trait RecursionBlockingEventDispatchHelperTrait
```
One last thing, I guess we should keep this trait `@internal` 😉

**Comment by brusch** [comment]
I'm just thinking ... we should probably do this for other entities as well to be consistent, right, so this would be: 
```
DataObjectClassDefinitionEvents
DataObjectClassificationStoreEvents
DataObjectCustomLayoutEvents
DataObjectQuantityValueEvents
NotificationEvents
RedirectEvents
SearchBackendEvents
TagEvents
TargetGroupEvents
TranslationEvents
UserRoleEvents
VersionEvents
```

@kingjia90 Can you please update the PR accordingly?

File: lib/Event/Traits/RecursionBlockingEventDispatchHelperTrait.php [hunk 8]
```diff
@@ -0,0 +1,45 @@
...
+     * @param object $event
+     * @param string|null $eventName
+     * @return void
+     */
+    protected function dispatchEvent(object $event, string $eventName = null): void
+    {
+        $eventName ??= \get_class($event);
+        if (!isset($this->activeDispatchingEvents[$eventName])) {
+            $this->activeDispatchingEvents[$eventName] = true;
+            \Pimcore::getEventDispatcher()->dispatch($event, $eventName);
```
Comment (dpfaffenbauer) [inline lib/Event/Traits/RecursionBlockingEventDispatchHelperTrait.php:41]: that is not good. You are going from a Container injected Event Dispatcher to a statically called injector with `\Pimcore::getContainer`. That is a step back..

Comment (dpfaffenbauer) [reply lib/Event/Traits/RecursionBlockingEventDispatchHelperTrait.php:41]: (In the context of controllers)

Comment (brusch) [reply lib/Event/Traits/RecursionBlockingEventDispatchHelperTrait.php:41]: We not gonna use that in the context of controllers 😉But thanks for the hint. 
As soon as #6808 is done, we're going to change `dispatchEvent()` to `@required` and remove the static getter - so it's already peparing for the good 😉

Comment (brusch) [reply lib/Event/Traits/RecursionBlockingEventDispatchHelperTrait.php:41]: Ah, I've just seen that it was used in a controller ... that's not needed anyway as far as I can see, so this can reverted 😉

File: bundles/AdminBundle/Controller/Admin/TargetingController.php [hunk 9]
```diff
@@ -240,7 +249,7 @@ public function targetGroupAddAction(Request $request, CoreCacheHandler $cache,
         $targetGroup->save();
 
         $event = new TargetGroupEvent($targetGroup);
-        $eventDispatcher->dispatch($event, TargetGroupEvents::POST_ADD);
+        $this->dispatchEvent($event, TargetGroupEvents::POST_ADD);
```
Comment (brusch) [inline bundles/AdminBundle/Controller/Admin/TargetingController.php]: This is a bit out of context, but we should also consider this in this PR. 
The `TargetGroupEvents` should be dispatched in the `save()` method of the model and not in the controller -> similar to other models. 
@kingjia90 can you change that accordingly? Thanks

**Review by brusch — CHANGES_REQUESTED** [review]

File: models/Tool/Targeting/TargetGroup.php [hunk 10]
```diff
@@ -192,4 +192,24 @@ public function getActive()
...
+     * @return void
+     */
+    public function save(): void
+    {
+        if ($this->getId()) {
+            $this->dispatchEvent(new TargetGroupEvent($this), TargetGroupEvents::POST_UPDATE);
+        }else{
+            $this->dispatchEvent(new TargetGroupEvent($this), TargetGroupEvents::POST_ADD);
+        }
+    }
```
Comment (jdreesen) [inline models/Tool/Targeting/TargetGroup.php]: The actual action is missing here. You should call `delete()` and `save()` on the `dao`, I think.

File: lib/Event/Traits/RecursionBlockingEventDispatchHelperTrait.php [hunk 11]
```diff
@@ -0,0 +1,45 @@
...
+     * Dispatches an event, avoids recursion by checking if the active dispatch event is the same
+     *
+     * @param object $event
+     * @param string|null $eventName
+     * @return void
+     */
+    protected function dispatchEvent(object $event, string $eventName = null): void
+    {
+        $eventName ??= \get_class($event);
+        if (!isset($this->activeDispatchingEvents[$eventName])) {
```
Comment (dpfaffenbauer) [inline lib/Event/Traits/RecursionBlockingEventDispatchHelperTrait.php:39]: What if you have depending events? So if you have a listener that saves another DataObject that should then trigger the same event just for the other object? That might not work with that solution right?

Comment (brusch) [reply lib/Event/Traits/RecursionBlockingEventDispatchHelperTrait.php:39]: That should work, since the dispatching is just blocked for the originating object as it isn't a static variable.

File: models/Tool/Targeting/TargetGroup/Dao.php [hunk 12]
```diff
@@ -83,6 +85,7 @@ public function save()
     public function delete()
     {
         $this->db->delete('targeting_target_groups', ['id' => $this->model->getId()]);
+        $this->model->dispatchEvent(new TargetGroupEvent($this->model), TargetGroupEvents::POST_DELETE);
```
Comment (jdreesen) [inline models/Tool/Targeting/TargetGroup/Dao.php]: Hmm, not sure if the DAO should dispatch the events... I think it should be the responsibility of the model (like everywhere else).

Comment (brusch) [reply models/Tool/Targeting/TargetGroup/Dao.php]: @jdreesen I agree - @kingjia90 so you can revert your last change and just add `$this->getDao()->save/delete()` to the methods instead.

File: lib/Model/AbstractModel.php [hunk 13]
```diff
@@ -29,6 +30,7 @@
 abstract class AbstractModel implements ModelInterface
 {
     use ObjectVarTrait;
+    use RecursionBlockingEventDispatchHelperTrait;
```
Comment (brusch) [inline lib/Model/AbstractModel.php]: Since `RecursionBlockingEventDispatchHelperTrait` isn't used for all implementations that use `AbstractModel` I wouldn't include it here, but rather use it individually on the classes that make use of `dispatchEvent()`.

**Review by brusch — CHANGES_REQUESTED** [review]

File: lib/Model/AbstractModel.php (hunk 13 above)
Comment (kingjia90) [reply lib/Model/AbstractModel.php]: What about the __sleep? can i keep it in `AbstractModel`?

```
public function __sleep()
    {
        $blockedVars = ['dao', 'o_dirtyFields', 'activeDispatchingEvents'];
```

or should i also add
```
   public function __sleep()
    {
        $parentVars = parent::__sleep();
        $blockedVars = ['activeDispatchingEvents'];

        return array_diff($parentVars, $blockedVars);
    }
```
in each class?

Comment (brusch) [reply lib/Model/AbstractModel.php]: the `__sleep` we can leave as it is, as it doesn't hurt 😉

File: models/Asset.php [hunk 14]
```diff
@@ -52,6 +53,7 @@ class Asset extends Element\AbstractElement
 {
     use ScheduledTasksTrait;
     use TemporaryFileHelperTrait;
+    use RecursionBlockingEventDispatchHelperTrait;
```
Comment (brusch) [inline models/Asset.php]:
```suggestion
```
This is not needed, as we have the trait already on `AbstractElement`.

File: models/Asset.php [hunk 15]
```diff
@@ -22,6 +22,7 @@
 use Pimcore\Event\AssetEvents;
 use Pimcore\Event\FrontendEvents;
 use Pimcore\Event\Model\AssetEvent;
+use Pimcore\Event\Traits\RecursionBlockingEventDispatchHelperTrait;
```
Comment (brusch) [inline models/Asset.php]:
```suggestion
```

File: models/Element/AbstractElement.php [hunk 16]
```diff
@@ -388,7 +390,7 @@ public function getVersions()
     public function __sleep()
     {
         $parentVars = parent::__sleep();
-        $blockedVars = ['dependencies'];
+        $blockedVars = ['dependencies','activeDispatchingEvents'];
```
Comment (brusch) [inline models/Element/AbstractElement.php]:
```suggestion
        $blockedVars = ['dependencies'];
```
This is redundant, as we have it already on `AbstractModel`.

**Review by brusch — CHANGES_REQUESTED** [review]
Just some more cosmetics, the rest looks good to me ☺️
