### PR TITLE
Fix: Pimcore X by default displays deprecations directly in output (e…

### LINKED ISSUE #11870: [Bug]: Pimcore X by default displays deprecations directly in output (even in prod mode), breaking JSON etc
### Expected behavior

Logs and error handling managed in a streamlined way, through Symfony's features (ErrorHandler, Monolog integration, etc).

### Actual behavior

Logs managed in all sorts of different ways, including PHP's legacy error log.

### Steps to reproduce

Run Pimcore X on PHP 8.1, you'll get all sorts of deprecations. This is OK in principle because [deprecations are not errors](https://wouterj.nl/2021/11/deprecations-are-not-errors).

What's not OK is that Pimcore basically forces you to have some specific logging / error handling settings enabled, namely:

https://github.com/pimcore/pimcore/blob/c13fb850a024ca7b81f3c940f186cfb9e10aeb56/lib/Bootstrap.php#L79-L80

https://github.com/pimcore/pimcore/blob/c13fb850a024ca7b81f3c940f186cfb9e10aeb56/lib/Bootstrap.php#L126-L127

This is by default basically incompatible with "12 factor" app architecture (which I've wrote about before in #8531), but also makes things difficult to debug and fix, like **deprecations being displayed in prod env** in API responses (breaking JSON) and frontend rendered pages.

This applies specifically to `var/log/php.log`, but perhaps to

```
var/log/loginerror.log
var/log/usagelog.log
```

also? In short, all of these things should be deprecated in favor of them being setup in "the Symfony way", which allows the developers to reconfigure them (for example, Sentry, Logwatch, etc).

### PR DESCRIPTION
**Pull request by robertSt7**
resolves #11870

### CODE REVIEW

File: lib/Bootstrap.php [hunk 1]
```diff
@@ -121,7 +117,6 @@ public static function bootstrap(): void
         \Pimcore::setAutoloader($loader);
         self::autoload();
 
-        ini_set('error_log', PIMCORE_PHP_ERROR_LOG);
```
Comment (lukmzig) [inline lib/Bootstrap.php:124]: Hi @robertSt7 is this also causing some issue? Is it not just logging the error into the log file itself?

Comment (lukmzig) [reply lib/Bootstrap.php:124]: Clarified via call
