### PR TITLE
Prematurely exit pimcore:bundle:install with success code if bundle is already installed

### LINKED ISSUE #17029: [Improvement]: pimcore:bundle:install should no-op if a bundle is already installed
### Improvement description

Currently, when running `bin/console pimcore:bundle:install` with a bundle that is already installed, an error is generated: `[ERROR] Bundle BundleName can not be installed.` This is a problem in Docker-based and continuous integration/deployment scenarios, as we regularly run (and re-run) such commands as part of the init operations of our applications. In order to workaround this issue, we have to use the `--fail-without-error` flag (which may ignore legitimate problems with the bundle installation), or choose to ignore errors altogether in the init script (e.g. by _not_ setting `set -e` in the entrypoint of a container, which is not ideal as this will cause the script to skip other legitimate errors)

In my view, trying to install a bundle that is already installed is not an error situation, and the default behaviour of this command should be to no-op and continue without error. **Alternatively**, if the behaviour of the current command is desirable, I suggest adding an optional flag to the command to ignore bundles that are already installed.

### PR DESCRIPTION
**Pull request by evanjamesjackson**
## Changes in this pull request  
Resolves #https://github.com/pimcore/pimcore/issues/17029

## Additional info
Choosing to first check if the given bundle is already installed, and if true prematurely exit with success. If it is preferred to provide an optional "ignore" flag instead, this PR can be closed in favour of that solution.

### CODE REVIEW

**Comment by evanjamesjackson** [comment]
I have read the CLA Document and I hereby sign the CLA

File: bundles/CoreBundle/src/Command/Bundle/InstallCommand.php [hunk 1]
```diff
@@ -49,6 +49,11 @@ protected function execute(InputInterface $input, OutputInterface $output): int
     {
         $bundle = $this->getBundle();
 
+        if ($this->bundleManager->isInstalled($bundle)) {
+            $this->io->success(sprintf('Bundle "%s" is already installed', $bundle->getName()));
+            return 0;
```
Comment (jdreesen) [inline bundles/CoreBundle/src/Command/Bundle/InstallCommand.php]: I think we should start using `Command::SUCCESS`, etc. in Pimcore.

See: https://symfony.com/blog/new-in-symfony-5-1-misc-improvements-part-1#added-constants-for-command-exit-codes

Comment (evanjamesjackson) [reply bundles/CoreBundle/src/Command/Bundle/InstallCommand.php]: Thanks @jdreesen, I've adjusted based on your suggestion

**Review by mattamon — APPROVED** [review]
LGTM! Thank you for your contribution! Have a nice weekend!
