### PR TITLE
[DataObject] Link: Attributes can be null

### LINKED ISSUE #15629: [Bug]: Change in type system cause serialized data objects to throw type error when updating to Pimcore 11
### Pimcore version

11.0.3

### Steps to reproduce

I have a pimcore 10.6 instance that I am trying to update to pimcore 11.
It has a data object with a `website` field which is a link, which is not a mandatory field.

Screenshot 2023-07-26 at 15 30 04

Now, up until pimcore 10.6, the types were nullable as in 
https://github.com/pimcore/pimcore/blob/89d0af7753f242378c22aab19ec00f678be3d780/models/DataObject/Data/Link.php#L35-L102

So the actual value for this field was stored serialized in database in a format 

```
O:34:"Pimcore\Model\DataObject\Data\Link":17:{s:7:"�*�text";s:0:"";s:15:"�*�internalType";N;s:11:"�*�internal";N;s:9:"�*�direct";s:24:"https://some-domain.com/";s:11:"�*�linktype";s:6:"direct";s:9:"�*�target";N;s:13:"�*�parameters";s:0:"";s:9:"�*�anchor";s:0:"";s:8:"�*�title";s:0:"";s:12:"�*�accesskey";s:0:"";s:6:"�*�rel";s:0:"";s:11:"�*�tabindex";s:0:"";s:8:"�*�class";s:0:"";s:13:"�*�attributes";s:0:"";s:9:"�*�_owner";N;s:13:"�*�_fieldname";s:0:"";s:12:"�*�_language";N;}
```

But as the `string` type hints were added in Pimcore 11, now the objects can't be unserialized and throw type error.

### Actual Behavior

The data objects stored in the database prior to pimcore 11 should be unserialized 

### Expected Behavior

An exception is thrown when trying to unserialize the objects

Screenshot 2023-07-26 at 15 40 12

### PR DESCRIPTION
**Pull request by blankse**
I have errors after update to Pimcore 11 with Link field types. The attributes can be null.

```
Cannot assign null to property Pimcore\Model\DataObject\Data\Link::$target of type string
```
```
Cannot assign null to property Pimcore\Model\DataObject\Data\Link::$text of type string
```

### CODE REVIEW

File: models/DataObject/Data/Link.php [hunk 1]
```diff
@@ -124,119 +139,156 @@ public function setLinktype(?string $linktype): static
...
+    public function getTarget(): ?string
     {
         return $this->target;
     }
 
-    public function setTarget(string $target): static
+    /**
+     * @return $this
+     */
+    public function setTarget(?string $target): static
```
Comment (jdreesen) [inline models/DataObject/Data/Link.php:150]: Making the parameter nullable is a breaking change, right? (see: https://3v4l.org/TLtr7)

Comment (blankse) [reply models/DataObject/Data/Link.php:150]: But it was nullable before. Its a bug of Pimcore 11. The serialized data in the db have null in the attributes. So whats your idea to fix this?

Comment (jdreesen) [reply models/DataObject/Data/Link.php:150]: I don't know... release Pimcore 12? :grin:

Comment (jdreesen) [reply models/DataObject/Data/Link.php:150]: If it's a bug, we should fix it, even if it's breaking (not sure if there's a way to circumvent it). But we should probably add a changelog entry...

**Review by aashan10 — COMMENTED** [review]
@blankse 
https://github.com/blankse/pimcore/blob/8935aeed8fe3403201100b9f7c17047ef183ecfb/models/DataObject/Data/Link.php#L278-L290

This might be related as well.

If you see here, in the else condition, 
the `$this->getDirect()` is nullable and if it ever is null, it will change the `$path = '';` to `$path = null;` which violates the return type signature of the method

**Comment by blankse** [comment]
@aashan10 Good catch :)
I fixed it here: https://github.com/pimcore/pimcore/pull/15577/commits/75ecf710de69b2a9007e71fb35372791f83f42d8

File: models/DataObject/Data/Link.php (hunk 1 above)
Comment (kingjia90) [reply models/DataObject/Data/Link.php:150]: what about replacing not set values in the serialized string before it deserialized here 
https://github.com/pimcore/pimcore/blob/67b064e83c439b72d9d90bbff22ebc82cd56afc2/models/DataObject/ClassDefinition/Data/Link.php#L94 
🤔 not cleanest solution but thinking something to avoid the bc break
put all the non-nullable properties in an array, loop each eg. `text` regex to find 
`:8:{s:7:" * text";s:15:" * `
and replace with
`:8:{s:7:" * text";s:0:"";s:15:" * ` or int

Comment (kingjia90) [reply models/DataObject/Data/Link.php:150]: nevermind on changing the serialized data, if it's a bug, it would be better bc-breaking than be broken.
The chance that some project would extend this Link object might be low.

So before merging, we would need a line in the upgrade notes like as suggested by Jacob

Comment (blankse) [reply models/DataObject/Data/Link.php:150]: @kingjia90 Done https://github.com/pimcore/pimcore/pull/15577/commits/2cfecdacb6705e755d2ff6be30383c8a4ac1a3a6

File: models/DataObject/Data/Link.php [hunk 2]
```diff
@@ -283,7 +332,7 @@ public function getPath(): string
                 $path = $this->getElement()->getFullPath();
             }
         } else {
-            $path = $this->getDirect();
+            $path = $this->getDirect() ?? '';
```
Comment (kingjia90) [inline models/DataObject/Data/Link.php:335]: Just wondering, would it be worth to have the property and the setter parameter nullable but keep the getter without 'null' in return and returning the empty value instead? 
This would avoiding all these null coalescing to empty string cases and "cause" fewer breaking changes.

Comment (blankse) [reply models/DataObject/Data/Link.php:335]: But `getDirect()` wasn't changed by this PR. That would be a new BC break

Comment (kingjia90) [reply models/DataObject/Data/Link.php:335]: Ahh ok, took the wrong null coalesce as placeholder for this review comment, but would that be ideal for the other properties that got changed?

Comment (blankse) [reply models/DataObject/Data/Link.php:335]: @kingjia90 It is enough to only make the property nullable. The admin interface only set empty strings to the setters. I think the null values are the result of imports, because the properties had no default value.

I changed it https://github.com/pimcore/pimcore/pull/15577/commits/a7f39758c86c3eb1f8c38e4e15e12405bbb13309

Comment (dvesh3) [reply models/DataObject/Data/Link.php:335]: "_The admin interface only set empty strings to the setters_" ~ not always true for `target` field as you can skip selecting the null value in data type "Allowed Targets" specific settings and this doesn't set the empty string anymore on opening the link editor and not selecting target:
image

Comment (blankse) [reply models/DataObject/Data/Link.php:335]: @dvesh3 Yes that is right. I changed it https://github.com/pimcore/pimcore/pull/15577/commits/f80554a7a3a8de73c5885f21fdd64f2dba52f2f6

**Comment by kingjia90** [comment]
it seems that
```
    public function __unserialize($data){
        if (is_null($data["\0*\0".'text'])){
            $this->text = '';
        }
        ...
    }
```
in Link.php would also work, would that be bad practice?

**Comment by blankse** [comment]
@kingjia90 I don't know. We would then have to set all attributes via this method, the original mechanism is then overwritten, right?
So your example must be (otherwise the text is a emtpy string, when it is filled):
```
    public function __unserialize(array $data): void
    {
        $this->text = $data["\0*\0".'text'] ?? '';
        ...
    }
```

**Comment by dvesh3** [comment]
I would be careful here as this can impact the nullable properties, where it is allowed to have null.

**Comment by kingjia90** [comment]
It seems so, that we need to define the `$this->text = $data["\0*\0".'text'] ?? ''` for each property.
Only `target` seems `nullable` from admin interface, the rest could be just stay empty string, if the phpdoc were right, i guess/hope we have all empty string check rather than null check

**Comment by blankse** [comment]
What is with the attributes of OwnerAwareFieldTrait? Must we set these attributes also in this method? This can be a much bigger BC because if someone really extend this class with attributes he must also extend this method...

**Comment by kingjia90** [comment]
Ahh then nevermind 😰  merging the current PR
