### PR TITLE
Fixed checking if file exist when restoring from recycle bin with empty

### LINKED ISSUE #18645: [Bug]: Restore from Recyclebin not working when using azure blob or potentially other systems except the local disk
### Pimcore version

11, 12

### Steps to reproduce

1. Setup for example azure blob as flysystem where the assets will be stored
2.  Upload Asset
3. Delete id
4. Go to recycle bin and restore it

### Actual Behavior

An error is thrown: 
pimcore.ERROR: InvalidArgumentException: 'blob' can't be NULL or empty. in /var/www/html/vendor/microsoft/azure-storage-common/src/Common/Internal/Validate.php:105

### Expected Behavior

Restore should work normally. 

Stacktrace is: 

Image

Easy fix should be to check if $dbPath is not empty

`if (!empty($dbPath) && $dbPath !== $path && $storage->fileExists($dbPath)) {`

instead 

`if ($dbPath !== $path && $storage->fileExists($dbPath)) {`

### PR DESCRIPTION
**Pull request by cuca24**
## Changes in this pull request  
Resolves #18645

### CODE REVIEW

File: models/Asset.php [hunk 1]
```diff
@@ -737,7 +737,7 @@ protected function update(array $params = []): void
 
                 // delete old legacy file if exists
                 $dbPath = $this->getDao()->getCurrentFullPath();
-                if ($dbPath !== $path && $storage->fileExists($dbPath)) {
+                if (!empty($dbPath) && $dbPath !== $path && $storage->fileExists($dbPath)) {
```
Comment (kingjia90) [inline models/Asset.php]: Thank you for your PR!
LGTM, just suggesting

```suggestion
                if ($dbPath && $dbPath !== $path && $storage->fileExists($dbPath)) {
```
see also https://localheinz.com/articles/2023/05/10/avoiding-empty-in-php/ as seen on https://github.com/pimcore/pimcore/pull/14799#discussion_r1279528727
