### PR TITLE
[Bug] Add object as fallback if no version is available

### LINKED ISSUE #18080: [Bug]: Version studio-preview needs to use data object as fallback
Follow-up to #18037 

### Pimcore version

12.x

### Steps to reproduce

* Call the studio preview without a data object auto saved draft

### Actual Behavior

* Preview controller will not receive the data object

### Expected Behavior

* Preview controller should receive the default data object from the database.

### PR DESCRIPTION
**Pull request by mattamon**
## Changes in this pull request  
Resolves #18080 

## Additional info
Use dataobject as fallback if no version is available

### CODE REVIEW

**Comment by mattamon** [comment]
@markus-moser This should already do the trick right?

File: bundles/CoreBundle/src/EventListener/Frontend/ElementListener.php [hunk 1]
```diff
@@ -260,6 +260,7 @@ private function handleStudioPreview(int $id, UserInterface $user): void
 
     private function getLatestVersion(int $id, UserInterface $user): ?Concrete
     {
+        /** @var Concrete|null $dataObject */
         $dataObject = Service::getElementById('object', $id);
 
         if ($dataObject === null) {
```
Comment (blankse) [inline bundles/CoreBundle/src/EventListener/Frontend/ElementListener.php]: I would change the if and remove the phpdoc, the getElementById() can also return Folders.
```suggestion
        if (!$dataObject instanceof Concrete) {
```

Comment (mattamon) [reply bundles/CoreBundle/src/EventListener/Frontend/ElementListener.php]: True! Thank you for the review! Applied the change!

File: bundles/CoreBundle/src/EventListener/Frontend/ElementListener.php [hunk 2]
```diff
@@ -260,16 +260,17 @@ private function handleStudioPreview(int $id, UserInterface $user): void
 
     private function getLatestVersion(int $id, UserInterface $user): ?Concrete
     {
+        /** @var Concrete|null $dataObject */
```
Comment (blankse) [inline bundles/CoreBundle/src/EventListener/Frontend/ElementListener.php]:
```suggestion
```
can be removed now.

**Comment by markus-moser** [comment]
@mattamon Sorry, I missed your comment - yes this should be fine, thanks a lot 👍
