### PR TITLE
[Bug]: Prevent Document Link targeting itself causing redirection loop

### LINKED ISSUE #12599: [Bug]: Dragging a Document Link onto itself breaks the document tree
### Expected behavior

Pimcore continues to not be broken. It shouldn't be possible for a link to link to itself.

### Actual behavior

The Document tree won't expand the parent node of the link and gets stuck in an endless loop.

### Steps to reproduce

1. Right click on any node in the document tree and "Add Link". /testing-links in this example:
image
2. Name the link, open and "Save & Publish" it. /testing-links/test in this example:
image
3. Take the same link, drag it onto itself and "Save & Publish" again.
image
5. The document tree is now stuck loading and won't expand /testing-links. Eventually, it fails with an out of memory exception.
image

Deleting the parent node also does not work for the same reason, I assume. A quick and easy fix is to either manually delete the database entry of the link in the `documents` table or change its target ID in the `documents_link` table.

It's a pretty easy thing to mess up on accident, so I think there should be some protection.

Tested on two different installs of 10.4.4

### PR DESCRIPTION
**Pull request by kingjia90**
## Changes in this pull request  
Resolves #12599

## Additional info  
In the Link model, it silently log an error if the link target is the same id and nullifies the `id`.
On Frontend, it doesn't show it's droppable when the same document is dragged over. 
When using the search, it throws an error if you select the link itself.

## To reproduce

Create some custom implementation that tries to change a link target path to be the same as itself (same as in the provided tests)
Create a link and try to link itself by drag and drop (from folder tree)
Create a link and use the search function to assign itself to the redirection target

### CODE REVIEW

**Comment by kingjia90** [comment]
I have a problem, the test provided actually "cannot fail": it gets into a infinite loop until it eventually crashes/times-out. Any suggestion on improving this?

At ther moment, i've just added a debug line to give a hint of potential problem
image

File: models/Document/Link.php [hunk 1]
```diff
@@ -369,6 +369,11 @@ private function setObjectFromId()
             if ($this->internal) {
                 if ($this->internalType == 'document') {
                     $this->object = Document::getById($this->internal);
+
+                    if ($this->getId() == $this->internal){
```
Comment (dvesh3) [inline models/Document/Link.php]: check and throw exception before loading the object
