### PR TITLE
[Bug] Unescape already escaped csv character

### LINKED ISSUE #15249: [Bug]: Shared Translations Import & Merge CSV does not unescape CSV
### Pimcore version

v10.6.1

### Steps to reproduce

Add a translation message having e.g. a "+" as value. The export adds a "'" to the "+". When re-importing the exported file, the escape character ("'") doesn't get removed.

The function for escaping CSV was added here: https://github.com/pimcore/pimcore/pull/9992/files

### Expected / actual behavior

The characters should get removed so the correct translations get imported.

### PR DESCRIPTION
**Pull request by martineiber**
## Changes in this pull request  
Resolves #15249

## Additional info

Check that the first two characters are an escape character and a special character. If this is the case, we remove the escape character.

### <samp>🤖 Generated by Copilot at aab021a</samp>

This pull request adds a new helper class `CsvFormulaFormatter` that can unescape CSV fields that may contain formulas or commands. It also updates the `Service` and `Translation` classes to use this class for importing translations from CSV files. Additionally, it adds a unit test file `CsvFormulaTest` to test the new class and method.

### <samp>🤖 Generated by Copilot at aab021a</samp>

> _Unleash the power of the CSV_
> _Escape the formulas of doom_
> _Unescape the fields of fire_
> _Import the translations of truth_

### <samp>🤖 Generated by Copilot at aab021a</samp>

*  Add a new class `CsvFormulaFormatter` that extends `League\Csv\EscapeFormula` and provides a method `unEscapeField` to remove the escape character from CSV fields that may contain formulas or commands ([link](https://github.com/pimcore/pimcore/pull/15310/files?diff=unified&w=0#diff-cbd1d9c0567d80b312e5c5685b32f87fea4a3566d4df159f6ecda2b558e5f438R1-R37))
* Replace the use of `League\Csv\EscapeFormula` with `Pimcore\Helper\CsvFormulaFormatter` in the `Service` class of the `models/Element/Service.php` file ([link](https://github.com/pimcore/pimcore/pull/15310/files?diff=unified&w=0#diff-f1c5d50aa07c3685f76a2947c0c3859e2582f8b683ebadf175679eb4aae78785L25-R25))
* Update the type and instantiation of the `self::$formatter` property in the `Service` class to use the new class ([link](https://github.com/pimcore/pimcore/pull/15310/files?diff=unified&w=0#diff-f1c5d50aa07c3685f76a2947c0c3859e2582f8b683ebadf175679eb4aae78785L57-R59), [link](https://github.com/pimcore/pimcore/pull/15310/files?diff=unified&w=0#diff-f1c5d50aa07c3685f76a2947c0c3859e2582f8b683ebadf175679eb4aae78785L1653-R1653))
* Add a new method `unEscapeCsvField` to the `Service` class that calls the `unEscapeField` method of the `self::$formatter` property and returns the unescaped string ([link](https://github.com/pimcore/pimcore/pull/15310/files?diff=unified&w=0#diff-f1c5d50aa07c3685f76a2947c0c3859e2582f8b683ebadf175679eb4aae78785R1663-R1679))
* Use the `Service` class and the `unEscapeCsvField` method in the `Translation` class of the `models/Translation.php` file to unescape the CSV fields before importing them as translations ([link](https://github.com/pimcore/pimcore/pull/15310/files?diff=unified&w=0#diff-d0dc6d8e60e668f42bd2013951b548bf2c28f63b0a6a2cf0dd1a0d9ecb0a8425R24), [link](https://github.com/pimcore/pimcore/pull/15310/files?diff=unified&w=0#diff-d0dc6d8e60e668f42bd2013951b548bf2c28f63b0a6a2cf0dd1a0d9ecb0a8425R526))
* Add a new test file `tests/Unit/Helper/CsvFormulaTest.php` that contains a test class `CsvFormulaTest` and a test method `testUnEscapeFormula` that asserts the expected and actual results of unescaping different CSV fields ([link](https://github.com/pimcore/pimcore/pull/15310/files?diff=unified&w=0#diff-3f4b453f98d8208d6cb0088f81c007c49e14252a636b44bfa35089432c78b514R1-R36))

### CODE REVIEW

File: tests/Unit/Helper/CsvFormulaTest.php [hunk 1]
```diff
@@ -0,0 +1,36 @@
...
+use Pimcore\Helper\CsvFormulaFormatter;
+use Pimcore\Tests\Test\TestCase;
+
+class CsvFormulaTest extends TestCase
+{
+    public function testUnEscapeFormula()
+    {
+        $formatter = new CsvFormulaFormatter("'", ['=', '-', '+', '@']);
+
+        $this->assertEquals("=1+1", $formatter->unEscapeField("'=1+1"));
```
Comment (dvesh3) [inline tests/Unit/Helper/CsvFormulaTest.php]: should we just use the formatter to escape the string as well (maybe also adding some asserts for checking escaped string)?

Comment (martineiber) [reply tests/Unit/Helper/CsvFormulaTest.php]: Good idea! I'll add this.

File: lib/Helper/CsvFormulaFormatter.php [hunk 2]
```diff
@@ -0,0 +1,39 @@
...
+
+namespace Pimcore\Helper;
+
+class CsvFormulaFormatter extends \League\Csv\EscapeFormula
+{
+    /**
+     * @param string $field
+     *
+     * @return string
+     */
```
Comment (blankse) [inline lib/Helper/CsvFormulaFormatter.php]: The PhpDocs are redundant.
```suggestion
```

File: models/Element/Service.php [hunk 3]
```diff
@@ -54,9 +54,9 @@
 class Service extends Model\AbstractModel
 {
     /**
```
Comment (blankse) [inline models/Element/Service.php]:
```suggestion
```

File: models/Element/Service.php [hunk 4]
```diff
@@ -54,9 +54,9 @@
...
-     * @var EscapeFormula|null
+     * @var CsvFormulaFormatter|null
      */
```
Comment (blankse) [inline models/Element/Service.php]:
```suggestion
```

File: models/Element/Service.php [hunk 5]
```diff
@@ -1650,13 +1650,30 @@ function ($currentValue) {
...
 
         return $rowData;
     }
 
+    /**
+     * @internal
+     *
+     * @param string $value
+     *
+     * @return string
```
Comment (blankse) [inline models/Element/Service.php]:
```suggestion
```

File: tests/Unit/Helper/CsvFormulaTest.php [hunk 6]
```diff
@@ -0,0 +1,36 @@
...
+ * @license    http://www.pimcore.org/license     GPLv3 and PCL
+ */
+
+
+use Pimcore\Helper\CsvFormulaFormatter;
+use Pimcore\Tests\Test\TestCase;
+
+class CsvFormulaTest extends TestCase
+{
+    public function testUnEscapeFormula()
```
Comment (blankse) [inline tests/Unit/Helper/CsvFormulaTest.php]:
```suggestion
    public function testUnEscapeFormula(): void
```

**Review by blankse — CHANGES_REQUESTED** [review]

**Review by dvesh3 — APPROVED** [review]
