### PR TITLE
Hotspotimage does not use crop data when medias are available

### LINKED ISSUE #4891: Hotspotimage does not use crop data when medias are availabel
# Bug Report
When cropping an image in the Pimcore Backend, using a `Hotspotimage` with `media` in the thumbnail config, the image is not being cropped.

### Expected behavior
The image should be cropped.

### Actual behavior
The image is not cropped.

### Steps to reproduce
1. Create a thumbnail with a media query.
2. Render a `Hotspotimage`, using the thumbnail.
3. Compare image on desktop with same image on mobile.

### PR DESCRIPTION
**Pull request by mcuenez**
Fixes #4891

### CODE REVIEW

File: models/DataObject/Data/Hotspotimage.php [hunk 1]
```diff
@@ -181,6 +181,19 @@ public function getThumbnail($thumbnailName = null, $deferred = true)
         }
 
         if ($crop) {
+            if ($thumbConfig->hasMedias()) {
+                $medias = $thumbConfig->getMedias() ?: [];
+
+                foreach ($medias as $mediaName => $mediaConfig) {
+                    $thumbConfig->addItemAt(0, 'cropPercent', [
```
Comment (brusch) [inline models/DataObject/Data/Hotspotimage.php]: Shouldn't be this `$mediaConfig` instead of ` $thumbConfig`?

Comment (ultramegatom) [reply models/DataObject/Data/Hotspotimage.php]: Should be fine ```addItemAt``` handles this correctly with the last param

Comment (brusch) [reply models/DataObject/Data/Hotspotimage.php]: Ah, thanks, have overssen the last param, thanks for clarifying!
