### PR TITLE
[DataObject] Do not update search backend when auto save or only saving version

### LINKED ISSUE #11475: [Bug] Searchbackend messages are dispatched when autosaving elements
### Expected behavior

do not dispatch searchbackend messages when autosave since they are useless (because handler loads published version of element anyway).

also related to https://github.com/pimcore/pimcore/issues/11474

### Actual behavior

searchbackend messages are dispatched on every autosave

### Steps to reproduce

open data object and change data -> autosave is triggered -> searchbackend message is dispatched

### PR DESCRIPTION
**Pull request by dvesh3**
## Changes in this pull request  
Resolves #11475

### CODE REVIEW

**Comment by brusch** [comment]
@dvesh3 should be handled for documents as well, right?

**Comment by dvesh3** [comment]
> @dvesh3 should be handled for documents as well, right?

@brusch you are right, pushed the changes for Documents as well 😉

File: bundles/CoreBundle/EventListener/SearchBackendListener.php [hunk 1]
```diff
@@ -49,8 +49,8 @@ public static function getSubscribedEvents()
             DocumentEvents::PRE_DELETE => 'onPreDeleteElement',
             AssetEvents::PRE_DELETE => 'onPreDeleteElement',
 
-            DataObjectEvents::POST_UPDATE => 'onPostUpdateElement',
-            DocumentEvents::POST_UPDATE => 'onPostUpdateElement',
+            DataObjectEvents::POST_UPDATE => 'onPostUpdateDataObjectDocument',
+            DocumentEvents::POST_UPDATE => 'onPostUpdateDataObjectDocument',
```
Comment (jdreesen) [inline bundles/CoreBundle/EventListener/SearchBackendListener.php]: A bit strange, that the listener method for `DocumentEvents::POST_UPDATE` is `onPostUpdateDataObjectDocument`.

File: bundles/CoreBundle/EventListener/SearchBackendListener.php [hunk 2]
```diff
@@ -87,4 +87,21 @@ public function onPostUpdateElement(ElementEventInterface $e)
...
+    {
+        //do not update index when auto save or only saving version
+        if (
+            ($e->hasArgument('isAutoSave') && $e->getArgument('isAutoSave')) ||
+            ($e->hasArgument('saveVersionOnly') && $e->getArgument('saveVersionOnly'))
+        ) {
+            return;
+        }
+
+        $this->onPostAddElement($e);
```
Comment (jdreesen) [inline bundles/CoreBundle/EventListener/SearchBackendListener.php]: Why does `onPostUpdateDataObjectDocument` call `onPostAddElement` and not `onPostUpdateElement`?

Comment (jdreesen) [reply bundles/CoreBundle/EventListener/SearchBackendListener.php]: Hmm, maybe because `onPostAddElement` and `onPostUpdateElement` are the same...

What about having only one method for `onPostAddElement`, `onPostUpdateElement` and `onPostUpdateDataObjectDocument` as all three are basically the same?

File: bundles/CoreBundle/EventListener/SearchBackendListener.php (hunk 1 above)
Comment (dvesh3) [reply bundles/CoreBundle/EventListener/SearchBackendListener.php]: suggestion?

File: bundles/CoreBundle/EventListener/SearchBackendListener.php (hunk 2 above)
Comment (dvesh3) [reply bundles/CoreBundle/EventListener/SearchBackendListener.php]: Changed it `onPostAddUpdateElement` for all elements.
