### PR TITLE
[Task]: Fix possible errors after applying php native types 

### LINKED ISSUE #13656: [Task]: Fix possible errors after applying php native types
### Improvement description

Follow up to #12240

### PR DESCRIPTION
**Pull request by mcop1**
Part of #13656

### CODE REVIEW

File: lib/Workflow/SupportStrategy/ExpressionSupportStrategy.php [hunk 1]
```diff
@@ -54,7 +54,8 @@ public function supports(WorkflowInterface $workflow, $subject): bool
             return false;
         }
 
-        return $this->expressionService->evaluateExpression($workflow, $subject, $this->expression);
+        $ret = $this->expressionService->evaluateExpression($workflow, $subject, $this->expression);
+        return is_bool($ret) ? (bool)$ret : false;
```
Comment (jdreesen) [inline lib/Workflow/SupportStrategy/ExpressionSupportStrategy.php]: Why cast it to bool when it already is bool?

Comment (mcop1) [reply lib/Workflow/SupportStrategy/ExpressionSupportStrategy.php]: To be honest, since `evaluateExpression` returns mixed, I think we should just go for

`return (bool)$this->expressionService->evaluateExpression($workflow, $subject, $this->expression);`

Comment (mcop1) [reply lib/Workflow/SupportStrategy/ExpressionSupportStrategy.php]: Or use `filter_var` instead of `is_bool`
