### PR TITLE
fix: check is stream not local in createXlsxExportFile

### LINKED ISSUE #15225: [Bug]: Export grid to xlsx file with S3 storage dosn't work
### Pimcore version

10.5.23

### Steps to reproduce

Setup storages `pimcore.asset.storage` and `pimcore.temp.storage` to S3 and push button "XLSX Export"

image

### Expected / actual behavior

Expected: File is downloading without issuses  
Actual behavior: After pushing button "XLSX Export" we have error:
image

### PR DESCRIPTION
**Pull request by MasterOfDeath**
## Changes in this pull request  
Resolves #15225

### <samp>🤖 Generated by Copilot at 97b28ad</samp>

Fix XLSX export bug for remote CSV files and remove outdated comment. Use different methods of loading the spreadsheet from the CSV stream depending on whether it is local or not in `GridHelperService.php`.

### <samp>🤖 Generated by Copilot at 97b28ad</samp>

> _CSV stream check_
> _`loadFromContent` if remote_
> _Winter bug is fixed_

### <samp>🤖 Generated by Copilot at 97b28ad</samp>

*  Add a check for local or remote CSV stream and load the spreadsheet accordingly ([link](https://github.com/pimcore/pimcore/pull/15227/files?diff=unified&w=0#diff-784ceb6fcd03ce729cee15284714f611451fdbca75047cdae68a9d6a127ed37dL862-R868))

### CODE REVIEW

**Comment by dvesh3** [comment]
@MasterOfDeath could you please check why stan is failing? thanks!

**Comment by MasterOfDeath** [comment]
> @MasterOfDeath could you please check why stan is failing? thanks!

@dvesh3 Done

File: bundles/AdminBundle/Helper/GridHelperService.php [hunk 1]
```diff
@@ -859,10 +860,24 @@ public function createXlsxExportFile(FilesystemOperator $storage, string $fileHa
...
-        $tempMetaData = stream_get_meta_data($csvStream);
-        //TODO: use this method and storage->read() to avoid the extra temp file, is not available in the current version. See: https://github.com/PHPOffice/PhpSpreadsheet/pull/2792
-        //$spreadsheet = $csvReader->loadSpreadsheetFromString($storage->read($csvFile));
-        $spreadsheet = $csvReader->load($tempMetaData['uri']);
+        if (stream_is_local($csvStream)) {
+            $tempMetaData = stream_get_meta_data($csvStream);
+            $spreadsheet = $csvReader->load($tempMetaData['uri']);
+        } else {
+            //TODO: use this method and storage->read() to avoid the extra temp file, is not available in the current version. See: https://github.com/PHPOffice/PhpSpreadsheet/pull/2792
+            //$spreadsheet = $csvReader->loadSpreadsheetFromString($storage->read($csvFile));
```
Comment (kingjia90) [inline bundles/AdminBundle/Helper/GridHelperService.php]:
```suggestion
```
removing this TODO comment, since it's already applied in [Pimcore 11](https://github.com/pimcore/pimcore/pull/12736)

**Review by kingjia90 — CHANGES_REQUESTED** [review]
LGTM 
thank you for the fix!
