### PR TITLE
Fix: Create asset of correct class type (#16363)

### LINKED ISSUE #16363: [Bug]: Creating a folder under the Assets section leads to an element type of `Pimcore\Model\Asset\Unknown`
### Pimcore version

11.0.12

### Steps to reproduce

Create a new folder in the Pimcore Admin Assets section.

### Actual Behavior

 The type of the created object (folder) in "Pimcore\Model\Assets::create" is of type 'unknown'.

### Expected Behavior

 The type of the created object (folder) in "Pimcore\Model\Assets::create" should be of type 'folder'.

### PR DESCRIPTION
**Pull request by youwe-petervanderwal**
## Changes in this pull request  
Resolves #16363

## Additional info
Error: `Asset::create(data: ['type' => 'folder'])` returned a `\Pimcore\Model\Asset\Unknown` instead of `\Pimcore\Model\Asset\Folder`
Caused by: The type was only used when detected by the binary file data
Resolved with: Adding a type check on the $data array

## Side effects of bug
The bug caused other effects such as the DataHub Simple Rest API Indexer not being able to process Asset Folders created via the Classic Admin (using `Asset::create`) as it checked on the asset `instanceof` within `getEntityTypeForElement` ( https://github.com/pimcore/data-hub-simple-rest/blob/3.x/src/Service/AbstractService.php#L258 )

### CODE REVIEW

File: models/Asset.php [hunk 1]
```diff
@@ -380,9 +380,13 @@ public static function create(int $parentId, array $data = [], bool $save = true
...
                 unset($data['type']);
             }
+        } elseif (array_key_exists('type', $data)) {
+            $type = $data['type'];
+            unset($data['type']);
         }
 
-        $className = Pimcore::getContainer()->get('pimcore.class.resolver.asset')->resolve($type);
+        $className = Pimcore::getContainer()->get('pimcore.class.resolver.asset')->resolve($type)
+            ?? throw new InvalidArgumentException('Invalid asset type provided');
```
Comment (youwe-petervanderwal) [inline models/Asset.php:389]: This can happen when someone passes on a wrong `$data['type']` value. It's just throwing the exception a bit earlier, without the changes in this PR, the asset was saved to the database as it was provided (thus with a wrong type) and then you got an exception when loading the asset.

Comment (mcop1) [reply models/Asset.php:389]: Technically one could say this is a change of behavior. But otherwise we save something to the database that will make problems later on, the change looks good to me and can be considered a bug fix.

**Review by mcop1 — APPROVED** [review]
Thank you, looks good to me.
