### PR TITLE
Drag'n'Drop of PDF / Excel / Word etc... to the editor doesn't work

### LINKED ISSUE #18168: [Bug]: Drag & Drop of images with whitespace characters in key or path does not work for WYSIWYG editor
### Pimcore version

11.5.3

### Steps to reproduce

Drap & drop an image (with whitespace characters in the key or path) to a WYSIWYG editor field (DataObject or Document) and save and publish it.

In my opinion the following change in symfony (https://github.com/symfony/symfony/blob/8b008510a48adba218d6358a3ab52141daacbaa8/src/Symfony/Component/HtmlSanitizer/TextSanitizer/UrlSanitizer.php#L99) could be the cause. It check the url for whitespace characters.

### Actual Behavior

After Saving and Publishing the DataObject or Document, the image is not visible.

### Expected Behavior

After Saving and Publishing the DataObject or Document, the image is visible.

### PR DESCRIPTION
**Pull request by robertSt7**
resolves https://github.com/pimcore/quill-bundle/issues/15

### CODE REVIEW

File: lib/Tool/Text.php [hunk 1]
```diff
@@ -176,7 +176,10 @@ public static function wysiwygText(?string $text, array $params = []): ?string
                         if (!empty($additionalAttributes)) {
                             $replacement .= ' ' . array_to_html_attribute_string($additionalAttributes);
                         }
-                        $newTag = preg_replace($pattern, $replacement, $oldTag);
+
+                        $newTag = self::addHrefAttributeToTag($oldTag);
```
Comment (brusch) [inline lib/Tool/Text.php]: We need to consider `src=""` attribute from `<img` tags here as well, so probably we need to make the code a bit more generic 😊

We should also explain why we're doing this here, because there's no obvious reason for doing this 😉

**Review by brusch — CHANGES_REQUESTED** [review]
