### PR TITLE
Gracefully handle cases in which the storage adapter fails to calculate a file's checksum.

### LINKED ISSUE #17438: [Bug]: Generating Checksum on Azure May Fail After Upload
### Pimcore version

11.3.1

### Steps to reproduce

Upload certain asset files, in this case the file is > 44MBs. Certain files reliably trigger the issue.
I was able to get this to trigger with a file generated using `mkfile -n 44m ~/Downloads/44mb` (on MacOS)

### Actual Behavior

Get error message like:
image
file is uploaded to Blob but not shown in Pimcore.

### Expected Behavior

We try to get the checksum right after uploading: https://github.com/pimcore/pimcore/blob/9f901b1d3056239258a0416cc2506348bf2f743a/models/Asset.php#L737-L738

however that checksum might not be available on Azure:
https://github.com/thephpleague/flysystem-azure-blob-storage/blob/7856cc57ae74b0cf673b924e05c236c4f5dbdcb0/AzureBlobStorageAdapter.php#L365-L367

I suggest that the `UnableToProvideChecksum` exception is caught and we fallback to the old behavior of just not saving the checksum.

### PR DESCRIPTION
**Pull request by cancan101**
@fashxp @brusch @cuca24 

  
  

## Changes in this pull request  
Resolves #17438

## Additional info
I chose not to widen the return type of `getChecksum`. Alternatively it could be changed to return `string | null` and then to handle the null in the one location that calls `getChecksum`.

### CODE REVIEW

File: models/Asset.php [hunk 1]
```diff
@@ -1144,15 +1145,22 @@ public function getChecksum(): string
...
      * @internal
      */
     public function generateChecksum(): void
     {
-        $this->setCustomSetting('checksum', Storage::get('asset')->checksum($this->getRealFullPath()));
+        try {
+            $this->setCustomSetting('checksum', Storage::get('asset')->checksum($this->getRealFullPath()));
+        } catch(UnableToProvideChecksum $e) {
+            // There are circumstances in which the adapter is unable to calculate the checksum for a given file.
+            // In those cases, we ignore the exception.
```
Comment (mattamon) [inline models/Asset.php:1161]: Should we also add a log entry? Just silently ignoring does not do the trick for me :)

File: models/Asset.php [hunk 2]
```diff
@@ -1144,15 +1145,24 @@ public function getChecksum(): string
...
 
     /**
      * @internal
      */
     public function generateChecksum(): void
     {
-        $this->setCustomSetting('checksum', Storage::get('asset')->checksum($this->getRealFullPath()));
+        try {
+            $this->setCustomSetting('checksum', Storage::get('asset')->checksum($this->getRealFullPath()));
+        } catch(UnableToProvideChecksum $e) {
```
Comment (mattamon) [inline models/Asset.php]:
```suggestion
        } catch (UnableToProvideChecksum $e) {
```

**Review by mattamon — CHANGES_REQUESTED** [review]

**Review by mattamon — APPROVED** [review]
@cancan101 Thank you! Looks good to me now!
