### PR TITLE
Fix getChildren/hasChildren/getSiblings/hasSiblings on unsaved new models

### LINKED ISSUE #11104: [Bug]: getChildren() method of AbstractObject results in doctrine SyntaxErrorException error when object has null id
### Expected behavior

when calling `->getChildren()` on newly created object (before the first save), empty array should be returned.

### Actual behavior

In version 10.2.7 (not sure in which version exactly this change happened) newly created objects have `id=null` before the first save. As a result, Doctrine\DBAL\Exception\SyntaxErrorException exception is thrown.

### Steps to reproduce

Create a new object of class that inherits from AbstractObject class. Do not save that object. Call `->getChildren()` method on it.

### PR DESCRIPTION
**Pull request by blankse**
## Changes in this pull request  
Resolves https://github.com/pimcore/pimcore/issues/11104

### CODE REVIEW

File: models/User/UserRole/Folder.php [hunk 1]
```diff
@@ -75,11 +79,13 @@ public function getChildren()
...
-            $this->hasChildren = true;
-        } else {
-            $this->hasChildren = false;
+        if (is_array($children)) {
+            $this->children = $children;
+            if (count($children) > 0) {
+                $this->hasChildren = true;
+            } else {
+                $this->hasChildren = false;
+            }
```
Comment (jdreesen) [inline models/User/UserRole/Folder.php]:
```suggestion
            $this->hasChildren = count($children) > 0;
```

**Comment by mcop1** [comment]
Thanks!
