### PR TITLE
[Admin Translations] Translations keys should be wrapped with + sign if translated value is missing

### LINKED ISSUE #9482: [Admin Translations] Debug Admin-Translations not working properly
`+` signs are only shown reliably when translation keys are not added to admin translations table. 
As soon as they are already added to the table (but still not translated), only some of them are shown.

### Steps to reproduce
- open admin translations and cleanup 
- reload pimcore admin ... all translation keys are wrapped in `+` signs
- reload pimcore admin once more ... not all translation keys are wrapped anymore

### PR DESCRIPTION
**Pull request by dvesh3**
## Changes in this pull request  
Resolves #9482

## Additional info  
and debug is enabled

### CODE REVIEW

File: lib/Translation/Translator.php [hunk 1]
```diff
@@ -216,6 +217,11 @@ public function lazyInitialize($domain, $locale)
 
                         if (empty($translationTerm)) {
                             $translationTerm = $translationKey;
+
+                            //wrap non-translated keys with "+", if debug admin translations is enabled
+                            if  ($debugAdminTranslations) {
+                                $translationKey = '+' . $translationKey . '+';
```
Comment (dvesh3) [inline lib/Translation/Translator.php]:
```suggestion
                                $translationTerm = '+' . $translationTerm. '+';
```

**Review by fashxp — APPROVED** [review]
