### PR TITLE
[Bug]: XLIFF Export type error.

### LINKED ISSUE #14598: [Bug]: XLIFF Export type error.
### Expected behavior

Export should work. 

### Actual behavior

When trying to export a xliff file, following error appears: `Pimcore\\Bundle\\XliffBundle\\ExportDataExtractorService\\DataExtractor\\DataObjectDataExtractor::extractRawAttributeSet(): Argument #4 ($exportAttributes) must be of type array, null given`

`null` as default value war removed in #14534

### Steps to reproduce

Go to Settings -> Translation -> XLIFF Export/import, add a Data Object and try to export a xliff file.

### PR DESCRIPTION
**Pull request by martineiber**
## Changes in this pull request  
Resolves #14598

## Additional info  
Regression of https://github.com/pimcore/pimcore/pull/14534

### CODE REVIEW

File: bundles/XliffBundle/src/ExportDataExtractorService/DataExtractor/DataObjectDataExtractor.php [hunk 1]
```diff
@@ -72,7 +72,7 @@ public function extract(TranslationItem $translationItem, string $sourceLanguage
      *
      * @throws \Exception
      */
-    private function extractRawAttributeSet(TranslationItem $translationItem, string $sourceLanguage, array $targetLanguages, array $exportAttributes, bool $inherited): AttributeSet
+    private function extractRawAttributeSet(TranslationItem $translationItem, string $sourceLanguage, array $targetLanguages, array|null $exportAttributes, bool $inherited): AttributeSet
```
Comment (blankse) [inline bundles/XliffBundle/src/ExportDataExtractorService/DataExtractor/DataObjectDataExtractor.php]: We should constantly use the question mark.
```suggestion
    private function extractRawAttributeSet(TranslationItem $translationItem, string $sourceLanguage, array $targetLanguages, ?array $exportAttributes, bool $inherited): AttributeSet
```
