### PR TITLE
[Task]: Fix possible errors after applying php native types

### LINKED ISSUE #13656: [Task]: Fix possible errors after applying php native types
### Improvement description

Follow up to #12240

### PR DESCRIPTION
**Pull request by mcop1**
Part of #13656

### CODE REVIEW

File: models/DataObject/ClassDefinition/CustomLayout.php [hunk 1]
```diff
@@ -311,14 +311,14 @@ public function setName(string $name): static
...
     }
 
-    public function getDefault(): int
+    public function getDefault(): bool
     {
         return $this->default;
     }
 
-    public function setDefault(int $default): static
+    public function setDefault(bool $default): static
```
Comment (blankse) [inline models/DataObject/ClassDefinition/CustomLayout.php:322]:
```suggestion
    /**
     * @return $this
     */
    public function setDefault(bool $default): static
```
