### PR TITLE
[Bug]: "Preview not available: PDF is being scanned" after update to 11.1.2

### LINKED ISSUE #16318: [Bug]: "Preview not available: PDF is being scanned" after update to 11.1.2
### Pimcore version

11.1.2

### Steps to reproduce

After update to 11.1.2, click on a PDF file in the Assets folder

### Actual Behavior

image

Got the message "Preview not available: PDF is being scanned. This may take a while."

### Expected Behavior

Preview the PDF.

### PR DESCRIPTION
**Pull request by robertSt7**
resolves #16318

### CODE REVIEW

File: bundles/CoreBundle/src/DependencyInjection/Configuration.php [hunk 1]
```diff
@@ -604,6 +604,10 @@ private function addAssetNode(ArrayNodeDefinition $rootNode): void
                                 ->defaultTrue()
                                 ->info('Scan PDF documents for unsafe JavaScript.')
                             ->end()
+                            ->enumNode('open_pdf_in_new_tab')
+                                ->values(['all-pdfs', 'only-unsafe', 'none'])
+                                ->defaultValue('all-pdfs')
```
Comment (brusch) [inline bundles/CoreBundle/src/DependencyInjection/Configuration.php]:
```suggestion
                                ->defaultValue('only-unsafe')
```
I'd prefer to have a security fist default value here.

**Review by brusch — CHANGES_REQUESTED** [review]
