### PR TITLE
[Bug]: The events "preSaveObject" is not working properly.

### LINKED ISSUE #13010: [Bug]: The events "preSaveObject" is not working properly.
### Expected behavior

The Object is not saved when Cancel is clicked.

The result of the event is not awaited or the context is lost.
This means that it is always saved, even if a check is intended to prevent this.

### Actual behavior

The Object is always saved.

### Steps to reproduce

**File startup.js:**

```
document.addEventListener(pimcore.events.preSaveObject, (e) => {

    let userAnswer = confirm(`Are you sure you want to save ${e.detail.object.data.general.o_className}?`);

    if (!userAnswer) {

        throw new pimcore.error.ActionCancelledException('Cancelled by user');
    }
});

```

**File vendor/pimcore/pimcore/bundles/AdminBundle/Resources/public/js/pimcore/object/object.js:**

```
758:    const preSaveObject = new CustomEvent(pimcore.events.preSaveObject, {
759:        detail: {
760:            object: this,
761:            type: "object"
762:        }
763:    });
764:    document.dispatchEvent(preSaveObject);

```

With the "old method" it works:

**File startup.js:**

```
    preSaveObject: function ( object , type , task ) {

        if ( task == 'publish' ) {

            let userAnswer = confirm( `Are you sure you want to save ${object.data.general.o_className}?` );

            if ( !userAnswer ) {

                throw new pimcore.error.ActionCancelledException( 'Cancelled by user' );
            }
        }
    },

```

**File vendor/pimcore/pimcore/bundles/AdminBundle/Resources/public/js/pimcore/object/object.js:**

`758:    pimcore.plugin.broker.fireEvent('preSaveObject', this, 'object');
`

Or better: If the "task" parameter is passed to the event, the check can be prevented for auto_save.

`758:    pimcore.plugin.broker.fireEvent('preSaveObject', this, 'object', task);
`

### PR DESCRIPTION
**Pull request by robertSt7**
resolve #13010

### CODE REVIEW

File: bundles/AdminBundle/Resources/public/js/pimcore/object/object.js [hunk 1]
```diff
@@ -754,27 +754,19 @@ pimcore.object.object = Class.create(pimcore.object.abstract, {
...
-            } catch (e) {
-                if (e instanceof pimcore.error.ValidationException) {
-                    this.tab.unmask();
-                    pimcore.helpers.showPrettyError('object', t("error"), t("saving_failed"), e.message);
-                    return false;
-                }
+            const preSaveObject = new CustomEvent(pimcore.events.preSaveObject, {
+                detail: {
+                    object: this,
+                    type: "object"
```
Comment (mcop1) [inline bundles/AdminBundle/Resources/public/js/pimcore/object/object.js]:
```suggestion
                    type: "object",
                    task: task
```

File: bundles/AdminBundle/Resources/public/js/pimcore/asset/asset.js [hunk 2]
```diff
@@ -363,28 +363,20 @@ pimcore.asset.asset = Class.create(pimcore.element.abstract, {
...
-            document.dispatchEvent(preSaveAsset);
-        } catch (e) {
-            if (e instanceof pimcore.error.ValidationException) {
-                this.tab.unmask();
-                pimcore.helpers.showPrettyError('asset', t("error"), t("saving_failed"), e.message);
-                return false;
-            }
+        const preSaveAsset = new CustomEvent(pimcore.events.preSaveAsset, {
+            detail: {
+                id: this.id
```
Comment (mcop1) [inline bundles/AdminBundle/Resources/public/js/pimcore/asset/asset.js]:
```suggestion
                id: this.id,
                task: task
```

**Review by mcop1 — COMMENTED** [review]
It would be good to add the task here. The js events can then check if an autosave is happening or not
