### PR TITLE
[Bug] Don't cast to int before rounding data

### LINKED ISSUE #15324: [Bug]: Numeric trims all decimal places
### Pimcore version

11.0.0

### Steps to reproduce

- Create a class with a Number editable. Set `Decimal size` to 10 and `Decimal precision` to 2.
- Create an object of the class.
- Enter a value with decimal places, e.g. 1234.56.
- Reload the object.
- Decimal places are gone.

This is caused by casting $data to int in the preSetData method of Numeric
```
    public function preSetData(mixed $container, mixed $data, array $params = []): mixed
    {
        if (!is_null($data) && $this->getDecimalPrecision()) {
            $data = round((int)$data, $this->getDecimalPrecision());
        }

        return $data;
    }
```

### Expected / actual behavior

_No response_

### PR DESCRIPTION
**Pull request by jdreesen**
## Changes in this pull request
Rounding an int doesn't make sense. This is a regression of #13474

Resolves #15324

### <samp>🤖 Generated by Copilot at 9503852</samp>

Fix decimal precision loss for numeric data objects. Remove redundant integer casting in `Numeric.php` before rounding.

### <samp>🤖 Generated by Copilot at 9503852</samp>

> _No need to cast `data`_
> _Rounding preserves decimals_
> _Winter bug is fixed_

### <samp>🤖 Generated by Copilot at 9503852</samp>

* Fix rounding bug for numeric data objects by removing unnecessary integer casting ([link](https://github.com/pimcore/pimcore/pull/15325/files?diff=unified&w=0#diff-4697436a17e4bad9daa8ba079fa63f28620d2b530a0ed67cf9bf7ad901c9269cL489-R489))

### CODE REVIEW

File: models/DataObject/ClassDefinition/Data/Numeric.php [hunk 1]
```diff
@@ -486,7 +486,7 @@ private function toNumeric(mixed $value): float|int|string
     public function preSetData(mixed $container, mixed $data, array $params = []): mixed
     {
         if (!is_null($data) && $this->getDecimalPrecision()) {
-            $data = round((int)$data, $this->getDecimalPrecision());
+            $data = round($data, $this->getDecimalPrecision());
```
Comment (robertSt7) [inline models/DataObject/ClassDefinition/Data/Numeric.php]:
```suggestion
            $data = round(floatval($data), $this->getDecimalPrecision());
```

**Review by robertSt7 — CHANGES_REQUESTED** [review]
We have to convert it to an int or float, otherwise we get a type error

**Comment by jdreesen** [comment]
We should cast to `float` then.

**Comment by jdreesen** [comment]
Codeception failure is unrelated. 
Not sure what's wrong with psalm.

**Comment by robertSt7** [comment]
> Codeception failure is unrelated. Not sure what's wrong with psalm.

@jdreesen Could you please merge 11.0 in your branch? Thanks

**Comment by jdreesen** [comment]
I rebased it. Codeception failure still seems unrelated.

**Comment by robertSt7** [comment]
@jdreesen Thanks for the PR. The failed Codeception tests are only for a dev-build.
