### PR TITLE
[Bug] Removed serverside html sanitizer

### LINKED ISSUE #15101: [Bug]: Website Settings value get html encoded
### Pimcore version

10.5.21

### Steps to reproduce

Create a website setting and add an value with special symbols (e.g. a json string: {"key": "value"})

### Expected / actual behavior

Actual behavior: 
The value get html encoded and the json string is invalid:
`{"key": "value"} get replaced/encoded with {&quot;key&quot;: &quot;value&quot;}`

### PR DESCRIPTION
**Pull request by Corepex**
## Changes in this pull request  
Resolves #15101

### <samp>🤖 Generated by Copilot at edfa449</samp>

This pull request fixes a XSS vulnerability and improves code quality in the website settings feature. It applies HTML encoding to the `name` column in the `website.js` grid, and removes it from the `setName` and `setData` methods in the `WebsiteSetting.php` model.

### <samp>🤖 Generated by Copilot at edfa449</samp>

> _To make the website settings grid secure_
> _They encoded the `name` column for sure_
> _But they also removed_
> _The encoding they loved_
> _From the `setName` and `setData` methods pure_

### <samp>🤖 Generated by Copilot at edfa449</samp>

*  Prevent XSS attacks and improve consistency by encoding website setting name and data in the JavaScript layer ([link](https://github.com/pimcore/pimcore/pull/15111/files?diff=unified&w=0#diff-1e95577ba95a2ffabb4b289d97e4f0a7b06d872a87adb84ddce4da3297cf3cc4L119-R120), [link](https://github.com/pimcore/pimcore/pull/15111/files?diff=unified&w=0#diff-1e95577ba95a2ffabb4b289d97e4f0a7b06d872a87adb84ddce4da3297cf3cc4L145-R150))
*  Remove HTML encoding from the setter methods for name and data in the `WebsiteSetting` PHP model class to avoid double encoding ([link](https://github.com/pimcore/pimcore/pull/15111/files?diff=unified&w=0#diff-9dff0d944b4fab5155a5a49e0e5125cccb25a836e4f5f98f3ab069ca4f24c9a6L187-R187), [link](https://github.com/pimcore/pimcore/pull/15111/files?diff=unified&w=0#diff-9dff0d944b4fab5155a5a49e0e5125cccb25a836e4f5f98f3ab069ca4f24c9a6L232-R232))

### CODE REVIEW

**Review by robertSt7 — APPROVED** [review]

**Comment by brusch** [comment]
@Corepex imho we should remove it here as well and handle this in the frontend, because escaping shouldn't take place in models, it's a frontend topic: 

https://github.com/pimcore/pimcore/blob/0bec0dca6a979ffa4992472c0aba86d2c5599846/bundles/EcommerceFrameworkBundle/PricingManager/Rule.php#L208
https://github.com/pimcore/pimcore/blob/6946f8a5a0a93b516c49f17a5b45044eebd73480/lib/DataObject/GridColumnConfig/Operator/AbstractOperator.php#L45
https://github.com/pimcore/pimcore/blob/6946f8a5a0a93b516c49f17a5b45044eebd73480/lib/DataObject/GridColumnConfig/Operator/AbstractOperator.php#L95
https://github.com/pimcore/pimcore/blob/6946f8a5a0a93b516c49f17a5b45044eebd73480/lib/DataObject/GridColumnConfig/Operator/AnyGetter.php#L68
https://github.com/pimcore/pimcore/blob/6946f8a5a0a93b516c49f17a5b45044eebd73480/lib/DataObject/GridColumnConfig/Operator/AnyGetter.php#L186
https://github.com/pimcore/pimcore/blob/6946f8a5a0a93b516c49f17a5b45044eebd73480/lib/DataObject/GridColumnConfig/Operator/AnyGetter.php#L202
https://github.com/pimcore/pimcore/blob/07a2c95be524c7e20105cef58c5767d4ebb06091/models/Staticroute.php#L308 (multiple usages)

File: lib/DataObject/GridColumnConfig/Operator/AnyGetter.php [hunk 1]
```diff
@@ -199,7 +199,7 @@ public function getParam1()
      */
     public function setParam1($param1)
     {
-        $this->param1 = SecurityHelper::convertHtmlSpecialChars($param1);
```
Comment (dvesh3) [inline lib/DataObject/GridColumnConfig/Operator/AnyGetter.php:202]: Do we still need `SecurityHelper::convertHtmlSpecialChars`?

Comment (Corepex) [reply lib/DataObject/GridColumnConfig/Operator/AnyGetter.php:202]: Do you mean the Helper method itself?
Yes, I would say so. It's used in several controllers and helpers ...  I just removed it from models.

File: bundles/AdminBundle/Resources/public/js/pimcore/object/quantityvalue/unitsettings.js [hunk 2]
```diff
@@ -105,9 +105,9 @@ pimcore.object.quantityValue.unitsettings = Class.create({
 
         var typesColumns = [
             {flex: 1, dataIndex: 'id', text: t("id"), filter: 'string'},
-            {flex: 1, dataIndex: 'abbreviation', text: t("abbreviation"), editor: new Ext.form.TextField({listeners: {change: pimcore.helpers.htmlEncodeTextField}}), filter: 'string'},
-            {flex: 2, dataIndex: 'longname', text: t("longname"), editor: new Ext.form.TextField({listeners: {change: pimcore.helpers.htmlEncodeTextField}}), filter: 'string'},
-            {flex: 1, dataIndex: 'group', text: t("group"), editor: new Ext.form.TextField({listeners: {change: pimcore.helpers.htmlEncodeTextField}}), filter: 'string', hidden: true},
+            {flex: 1, dataIndex: 'abbreviation', text: t("abbreviation"), editor: new Ext.form.TextField(), filter: 'string'},
```
Comment (brusch) [inline bundles/AdminBundle/Resources/public/js/pimcore/object/quantityvalue/unitsettings.js:108]: we don't need `renderer: Ext.util.Format.htmlEncode` here? 
Also all the following fields?

File: bundles/AdminBundle/Resources/public/js/pimcore/settings/metadata/predefined.js [hunk 3]
```diff
@@ -138,13 +138,13 @@ pimcore.settings.metadata.predefined = Class.create({
                 sortable: true
             },
             {text: t("name"), width: 200, sortable: true, dataIndex: 'name',
-                getEditor: function() { return new Ext.form.TextField({ listeners: {'change': pimcore.helpers.htmlEncodeTextField } }); }
+                getEditor: function() { return new Ext.form.TextField(); }
```
Comment (brusch) [inline bundles/AdminBundle/Resources/public/js/pimcore/settings/metadata/predefined.js:141]: What about adding the renderer here?

File: bundles/AdminBundle/Resources/public/js/pimcore/settings/properties/predefined.js [hunk 4]
```diff
@@ -108,26 +108,63 @@ pimcore.settings.properties.predefined = Class.create({
...
 
         var propertiesColumns = [
-            {text: t("name"), flex: 100, sortable: true, dataIndex: 'name', editor: new Ext.form.TextField({listeners: {'change': pimcore.helpers.htmlEncodeTextField}})},
-            {text: t("description"), sortable: true, dataIndex: 'description', editor: new Ext.form.TextArea({listeners: {'change': pimcore.helpers.htmlEncodeTextField}}),
+            {
+                text: t("name"),
+                flex: 100,
+                sortable: true,
+                dataIndex: 'name',
+                editor: new Ext.form.TextField()
```
Comment (brusch) [inline bundles/AdminBundle/Resources/public/js/pimcore/settings/properties/predefined.js:116]: Renderer?

File: bundles/AdminBundle/Resources/public/js/pimcore/settings/staticroutes.js [hunk 5]
```diff
@@ -96,11 +96,11 @@ pimcore.settings.staticroutes = Class.create({
 
         var typesColumns = [
             {text:t("name"), flex:50, sortable:true, dataIndex:'name',
-                editor:new Ext.form.TextField({listeners: {'change': pimcore.helpers.htmlEncodeTextField}})},
+                editor:new Ext.form.TextField()},
```
Comment (brusch) [inline bundles/AdminBundle/Resources/public/js/pimcore/settings/staticroutes.js:99]: Renderer?

File: bundles/AdminBundle/Resources/public/js/pimcore/settings/website.js [hunk 6]
```diff
@@ -112,11 +112,7 @@ pimcore.settings.website = Class.create({
                 flex: 100,
                 editable: true,
                 sortable: true,
-                editor: new Ext.form.TextField({
-                    listeners: {
-                        'change': pimcore.helpers.htmlEncodeTextField
-                    }
-                })
+                editor: new Ext.form.TextField()
```
Comment (brusch) [inline bundles/AdminBundle/Resources/public/js/pimcore/settings/website.js:115]: Renderer?

**Review by brusch — CHANGES_REQUESTED** [review]

File: bundles/AdminBundle/Resources/public/js/pimcore/object/quantityvalue/unitsettings.js (hunk 2 above)
Comment (Corepex) [reply bundles/AdminBundle/Resources/public/js/pimcore/object/quantityvalue/unitsettings.js:108]: no since its set as default a few lines below :) 

https://github.com/pimcore/pimcore/blob/26a76f97ecac56645b96720b40d0d565598b0e33/bundles/AdminBundle/Resources/public/js/pimcore/object/quantityvalue/unitsettings.js#L201-L203

Comment (brusch) [reply bundles/AdminBundle/Resources/public/js/pimcore/object/quantityvalue/unitsettings.js:108]: Ah yes 👍

File: bundles/AdminBundle/Resources/public/js/pimcore/settings/metadata/predefined.js (hunk 3 above)
Comment (Corepex) [reply bundles/AdminBundle/Resources/public/js/pimcore/settings/metadata/predefined.js:141]: same as above: 

https://github.com/pimcore/pimcore/blob/26a76f97ecac56645b96720b40d0d565598b0e33/bundles/AdminBundle/Resources/public/js/pimcore/settings/metadata/predefined.js#L287-L289

File: bundles/AdminBundle/Resources/public/js/pimcore/settings/properties/predefined.js (hunk 4 above)
Comment (Corepex) [reply bundles/AdminBundle/Resources/public/js/pimcore/settings/properties/predefined.js:116]: see: 
https://github.com/pimcore/pimcore/blob/26a76f97ecac56645b96720b40d0d565598b0e33/bundles/AdminBundle/Resources/public/js/pimcore/settings/properties/predefined.js#L289-L291

File: bundles/AdminBundle/Resources/public/js/pimcore/settings/staticroutes.js (hunk 5 above)
Comment (Corepex) [reply bundles/AdminBundle/Resources/public/js/pimcore/settings/staticroutes.js:99]: see: https://github.com/pimcore/pimcore/blob/26a76f97ecac56645b96720b40d0d565598b0e33/bundles/AdminBundle/Resources/public/js/pimcore/settings/staticroutes.js#L226-L228

File: bundles/AdminBundle/Resources/public/js/pimcore/settings/website.js (hunk 6 above)
Comment (Corepex) [reply bundles/AdminBundle/Resources/public/js/pimcore/settings/website.js:115]: see: https://github.com/pimcore/pimcore/blob/26a76f97ecac56645b96720b40d0d565598b0e33/bundles/AdminBundle/Resources/public/js/pimcore/settings/website.js#L313-L315

File: lib/DataObject/GridColumnConfig/Operator/AnyGetter.php (hunk 1 above)
Comment (dvesh3) [reply lib/DataObject/GridColumnConfig/Operator/AnyGetter.php:202]: we should also remove it from [Link Editable](https://github.com/pimcore/pimcore/blob/b159e547830b19f41d16d29c816c56a0a0facc29/models/Document/Editable/Link.php#L383)..right? and then i don't see any other usages of `convertHtmlSpecialChars` in the controllers and helpers. please double check this 😊

Comment (Corepex) [reply lib/DataObject/GridColumnConfig/Operator/AnyGetter.php:202]: I think we messed something up here 🤣 let me clarify:

The link editable uses the `sanitizeHtmlAttributes` method. This is only used by the editable and could be removed if we remove it from the link editable.

The other method is the `convertHtmlSpecialChars`. This method is used in some other placed. (eg. `DataObjectHelperController` or `ClassificationstoreController`)

Comment (dvesh3) [reply lib/DataObject/GridColumnConfig/Operator/AnyGetter.php:202]: Ohh sorry, i was referring to the `sanitizeHtmlAttributes` later 😆. I think we should remove the sanitization from this model as well and kick the method from helper.

Comment (Corepex) [reply lib/DataObject/GridColumnConfig/Operator/AnyGetter.php:202]: If we remove the sanitizer here, we also have to rethink the frontend part. Afaik we only print out the saved string - that would open the door for HTML injects - right? 

Or did I miss something?

Comment (brusch) [reply lib/DataObject/GridColumnConfig/Operator/AnyGetter.php:202]: In link editable we still need it, because there it's used for the frontend part ( `frontend()` method). There's no way to do it in frontend, so imho it's fine.

Comment (dvesh3) [reply lib/DataObject/GridColumnConfig/Operator/AnyGetter.php:202]: yes, we still need to remove it from the getters.
