### PR TITLE
[Thumbnails] Fix accessing the deferred thumbnail URL doesn't add it to cache

### LINKED ISSUE #15233: [Bug]: accessing the deferred thumbnail URL doesn't add it to the thumbnail cache
### Pimcore version

10.6

### Steps to reproduce

We've discussed this before in https://github.com/pimcore/pimcore/issues/12055 and other related issues / PRs.

Basically, this situation will never fix itself:

1. asset last modified M
2. thumbnail file exists on storage, last modified M + 1
3. `assets_image_thumbnail_cache` entry doesn't exist

In this case, the thumbnail URL will always be the deferred one. When I access it, it will read from storage as is:

https://github.com/pimcore/pimcore/blob/ec3e8a2abe625f2ade45ee1b62cd79947b90f58f/models/Asset/Image/Thumbnail/Processor.php#L196-L200

but it will never add it to the cache. This means the cache will be broken until we rerun `pimcore:thumbnail:image` which explicitly fixes this case.

### Expected / actual behavior

Accessing deferred thumbnail URL is the worst case scenario because you want it to trigger as little as possible. If it's accessed, the cache entry for the thumbnail **must** be up to date. It being in cache also enables it to serve the CDN version of the URL.

Note: this was quite difficult to debug because of #15231 which has the same symptom, but caused by totally different cause.

### PR DESCRIPTION
**Pull request by dvesh3**
## Changes in this pull request  
Resolves #15233

### <samp>🤖 Generated by Copilot at 0f13178</samp>

This pull request fixes a bug with thumbnail caching and refactors the `Processor` class. It adds a new method `addOrUpdateThumbnailCache` to `models/Asset/Image/Thumbnail/Processor.php` that updates the cache for a given asset and config.

### <samp>🤖 Generated by Copilot at 0f13178</samp>

> _Oh, we are the coders of the sea, me hearties_
> _We fix the bugs and refactor the code_
> _We heave and ho and `addOrUpdateThumbnailCache`_
> _To make the assets look as good as gold_

### <samp>🤖 Generated by Copilot at 0f13178</samp>

*  Add a new method `addOrUpdateThumbnailCache` to refresh the thumbnail cache for an asset and a config ([link](https://github.com/pimcore/pimcore/pull/15351/files?diff=unified&w=0#diff-16840b1fd40929e8fda46a67eae733c84fc71dc91da6a38097ba58b5da0c321cR477-R497))
*  Call `addOrUpdateThumbnailCache` when generating a thumbnail from a stream or a file to ensure the cache is updated when the original asset is modified ([link](https://github.com/pimcore/pimcore/pull/15351/files?diff=unified&w=0#diff-16840b1fd40929e8fda46a67eae733c84fc71dc91da6a38097ba58b5da0c321cR208-R212), [link](https://github.com/pimcore/pimcore/pull/15351/files?diff=unified&w=0#diff-16840b1fd40929e8fda46a67eae733c84fc71dc91da6a38097ba58b5da0c321cL433-R438))
*  Refactor the code in `models/Asset/Image/Thumbnail/Processor.php` to avoid duplication and simplify the logic for adding thumbnails to the cache ([link](https://github.com/pimcore/pimcore/pull/15351/files?diff=unified&w=0#diff-16840b1fd40929e8fda46a67eae733c84fc71dc91da6a38097ba58b5da0c321cL433-R438), [link](https://github.com/pimcore/pimcore/pull/15351/files?diff=unified&w=0#diff-16840b1fd40929e8fda46a67eae733c84fc71dc91da6a38097ba58b5da0c321cR477-R497))

### CODE REVIEW

File: models/Asset/Image/Thumbnail/Processor.php [hunk 1]
```diff
@@ -472,6 +475,27 @@ public static function process(Asset $asset, Config $config, $fileSystemPath = n
...
+    /**
+     * @throws \Exception
+     */
+    private static function addOrUpdateThumbnailCache(
+        Asset $asset,
+        Config $config,
+        string $filename
+    ): void
+    {
+        $tmpFsPath = $asset->getLocalFile();
```
Comment (brusch) [inline models/Asset/Image/Thumbnail/Processor.php]: I think we need to move this to a public service method, because we need to consider the changes made in #15323 as well. 
Because actually `getimagesize()` would fail here as well for AVIF images.

Comment (brusch) [inline models/Asset/Image/Thumbnail/Processor.php]: This is not doing the same as it was before, because it always get's the dimensions from the original asset and not from the thumbnail ...

File: models/Asset/Image/Thumbnail/Processor.php [hunk 2]
```diff
@@ -205,6 +205,11 @@ public static function process(Asset $asset, Config $config, $fileSystemPath = n
                     // the local tmp-file to the real storage a bit further down doesn't work, as it has a
                     // check for race-conditions & locking, so it needs to check for the existence of the thumbnail
                     $storage->delete($storagePath);
+
+                    // refresh the thumbnail cache, if the asset modification date is modified
+                    // this is necessary because the thumbnail cache is not cleared automatically
+                    // when the original asset is modified
+                    self::addOrUpdateThumbnailCache($asset, $config, $filename);
```
Comment (brusch) [inline models/Asset/Image/Thumbnail/Processor.php]: When an asset is updated, the thumbnail cache get's cleared as well, so this shouldn't be necessary imho. 
See https://github.com/pimcore/pimcore/blob/d982fa8d96dc775e49a04017cfa657882cedf148/models/Asset.php#L1606

But we could still do `$asset->getDao()->deleteFromThumbnailCache($config-getName());` here, as it doesn't hurt.

**Review by brusch — CHANGES_REQUESTED** [review]
I think we need to consider the thumbnail cache here as well: 
https://github.com/pimcore/pimcore/blob/be8eb3faa9d5e2b0517574acdb9fd6de5157e04e/models/Asset/Image/Thumbnail/Processor.php#L187

That's the case described in #15233

**Comment by dvesh3** [comment]
> I think we need to consider the thumbnail cache here as well:
> 
> https://github.com/pimcore/pimcore/blob/be8eb3faa9d5e2b0517574acdb9fd6de5157e04e/models/Asset/Image/Thumbnail/Processor.php#L187
> 
> That's the case described in #15233

@brusch This way, it will always refresh the cache on accessing the thumbnail from cache..isn't it? the actual case is point 3 here https://github.com/pimcore/pimcore/issues/15233#issuecomment-1578228199

**Comment by brusch** [comment]
@dvesh3 you're right, sorry, but we need to do it here I guess: 
https://github.com/pimcore/pimcore/blob/be8eb3faa9d5e2b0517574acdb9fd6de5157e04e/models/Asset/Image/Thumbnail/Processor.php#L235 

That's the case when the thumbnail exists and it's still valid and not in the cache, right? 
The other comments should be also still relevant.

File: models/Asset/Image/Thumbnail/Processor.php (hunk 1 above)
Comment (dvesh3) [reply models/Asset/Image/Thumbnail/Processor.php]: changed visibility of `readDimensionsFromFile` to public and marked as internal and this is then called in the processor now.

Comment (dvesh3) [reply models/Asset/Image/Thumbnail/Processor.php]: fixed with new approach

File: models/Asset/Image/Thumbnail/Processor.php (hunk 2 above)
Comment (dvesh3) [reply models/Asset/Image/Thumbnail/Processor.php]: done

**Comment by dvesh3** [comment]
@brusch should we also rebase it on 10.6 as per the reported issue?

File: models/Asset/Thumbnail/ImageThumbnailTrait.php [hunk 3]
```diff
@@ -180,7 +180,12 @@ public function getRealHeight()
         return $this->realHeight;
     }
 
-    private function readDimensionsFromFile(): array
+    /**
+     * @internal
+     *
+     * @return array
```
Comment (blankse) [inline models/Asset/Thumbnail/ImageThumbnailTrait.php]:
```suggestion
     * @return array{width?: int, height?: int}
```
Otherwise it is redundant

File: models/Asset/Image/Thumbnail/Processor.php [hunk 4]
```diff
@@ -430,10 +435,8 @@ public static function process(Asset $asset, Config $config, $fileSystemPath = n
                     fclose($stream);
                 }
 
-                if ($statusCacheEnabled) {
-                    if ($imageInfo = @getimagesize($tmpFsPath)) {
-                        $asset->getDao()->addToThumbnailCache($config->getName(), $filename, filesize($tmpFsPath), $imageInfo[0], $imageInfo[1]);
-                    }
+                if ($statusCacheEnabled && $asset instanceof Asset\Image) {
+                    $asset->getThumbnail($config->getName())->readDimensionsFromFile(); //update thumbnail dimensions to cache
```
Comment (brusch) [inline models/Asset/Image/Thumbnail/Processor.php]: I'm wondering if this is really a good idea, since this is calling the whole generation again, although we have already a local file at this point. 
Maybe it's better if we do something like that on the `Asset` class: 

```php
/**
     * @internal
     */
    public function addThumbnailFileToCache(string $localFile, string $filename, ?Config $config): void 
    {
        if ($imageInfo = @getimagesize($localFile)) {
            $dimensions = [
                'width' => $imageInfo[0],
                'height' => $imageInfo[1],
            ];
            
            if ($config) {
                $this->getDao()->addToThumbnailCache(
                    $config->getName(),
                    $filename,
                    filesize($localFile),
                    $dimensions['width'],
                    $dimensions['height']
                );
            }
        }
    }
```

it's then generic, we can use it in `readDimensionsFromFile()` and in `Processor` and we don't need to make some extra miles, WDYT?

**Review by brusch — CHANGES_REQUESTED** [review]

**Comment by brusch** [comment]
@dvesh3 I'd keep it on `10.5` as it is affected as well.

File: models/Asset/Image/Thumbnail/Processor.php (hunk 4 above)
Comment (dvesh3) [reply models/Asset/Image/Thumbnail/Processor.php]: yes, agree that we don't need to re-generate the local file on `process`. I refactored it as per the suggestion.

**Review by brusch — APPROVED** [review]
