### PR TITLE
[issue-13984] Fix error message for duplicate URL slug

### LINKED ISSUE #13984: [Bug]: Error message for duplicate URL slug is not helpful
### Steps to reproduce

Prerequisites: You have an object class that contains a URL Slug field (let's call it "exampleSlug"). 

One object has a certain value set for the slug. On a different object you want to set the same value for the slug. This produces an error message, which is of course correct.

### Actual behavior

The error message reads: "Unique constraint violated. Slug alreay used by object exampleSlug, fieldname: exampleSlug."

### Expected behavior

The error message should read: "Unique constraint violated. Slug alreay used by object [id], fieldname: exampleSlug."

### PR DESCRIPTION
**Pull request by woellundwoell**
## Changes in this pull request  
Resolves #13984

### CODE REVIEW

File: models/DataObject/ClassDefinition/Data/UrlSlug.php [hunk 1]
```diff
@@ -276,8 +276,8 @@ public function save($object, $params = [])
                             }
 
                             // if now exception is thrown then the slug is owned by a diffrent object/field
-                            throw new \Exception('Unique constraint violated. Slug alreay used by object '
-                                . $existingSlug->getFieldname() . ', fieldname: ' . $existingSlug->getFieldname());
+                            throw new \Exception('Unique constraint violated. Slug already used by object '
```
Comment (kingjia90) [inline models/DataObject/ClassDefinition/Data/UrlSlug.php]: what about adding also the slug in the output?
```suggestion
                            throw new \Exception('Unique constraint violated. Slug "' . $slug['slug'] . '" is already used by object '
```
