### PR TITLE
[Bug]: Deleted components in Custom Layouts

### LINKED ISSUE #12268: [Bug]: Deleted components in Custom Layouts
### Expected behavior

When deleting components in the class, they are also deleted in the custom layout

### Actual behavior

component is in Custom Layout after deleting it

### Steps to reproduce

- create a Class 
- add some components
- save Class
- create a Custom Layout with these components
- delete components
- look into the Custom Layout

### PR DESCRIPTION
**Pull request by robertSt7**
resolves #12268

### CODE REVIEW

File: models/DataObject/ClassDefinition.php [hunk 1]
```diff
@@ -1404,4 +1431,79 @@ public function setGenerateTypeDeclarations($generateTypeDeclarations)
...
+        }
+
+        for ($i = 0; $i < count($component->getChildren()); $i++) {
+            $tempKeyArray = $keyArray;
+            array_push($tempKeyArray, $i);
+            $i -= $this->deleteDeletedDataComponentsInLayoutDefinition($layoutDefinition, $component->getChildren()[$i], $tempKeyArray);
+        }
+
+        return 0;
+    }
```
Comment (mcop1) [inline models/DataObject/ClassDefinition.php]:
```suggestion
private function deleteDeletedDataComponentsInLayoutDefinition(ClassDefinition\Layout $layoutDefinition): void
    {
        $componentsToDelete = $this->getDeletedDataComponents();
        $componentDeleted = false;

        $children = &$layoutDefinition->getChildrenByRef();
        $count = count($children);
        for($i = 0; $i < $count; $i++) {
            $component = $children[$i];
            if(in_array($component, $componentsToDelete)) {
                unset($children[$i]);
                $componentDeleted = true;
            }
            if($component instanceof ClassDefinition\Layout) {
                $this->deleteDeletedDataComponentsInLayoutDefinition($component);
            }
        }
        if($componentDeleted) {
            $children = array_values($children);
        }
    }
```

File: models/DataObject/ClassDefinition.php [hunk 2]
```diff
@@ -1404,4 +1431,79 @@ public function setGenerateTypeDeclarations($generateTypeDeclarations)
...
+        if(empty($this->getDeletedDataComponents())) {
+            return;
+        }
+        $customLayouts = new ClassDefinition\CustomLayout\Listing();
+        $customLayouts->setCondition('classId = ?', $this->getId());
+        $customLayouts = $customLayouts->load();
+
+        foreach ($customLayouts as $customLayout) {
+            $layoutDefinition = $customLayout->getLayoutDefinitions();
+            $this->deleteDeletedDataComponentsInLayoutDefinition($layoutDefinition, $layoutDefinition);
```
Comment (mcop1) [inline models/DataObject/ClassDefinition.php]:
```suggestion
            $this->deleteDeletedDataComponentsInLayoutDefinition($layoutDefinition);
```

**Review by mcop1 — CHANGES_REQUESTED** [review]

**Review by mcop1 — APPROVED** [review]

**Review by mcop1 — APPROVED** [review]
