### PR TITLE
[Bug]: Fix BC-Break: Default value on multiselect object type introduced by #15871

### LINKED ISSUE #16777: BC-Break: Default value on multiselect object type introduced by #15871
### Pimcore version

11.2

### Steps to reproduce

See https://github.com/pimcore/pimcore/pull/15871#issuecomment-1992050364

### Actual Behavior

https://github.com/pimcore/pimcore/pull/15871#issuecomment-1992050364

### Expected Behavior

https://github.com/pimcore/pimcore/pull/15871#issuecomment-1992050364

### PR DESCRIPTION
**Pull request by kingjia90**
## Changes in this pull request  
Resolves https://github.com/pimcore/pimcore/issues/16777

### CODE REVIEW

File: models/DataObject/ClassDefinition/Data/Multiselect.php [hunk 1]
```diff
@@ -122,8 +122,13 @@ public function getRenderType(): ?string
         return $this->renderType;
     }
 
-    public function setDefaultValue(array $defaultValue): static
+    public function setDefaultValue(array|string|null $defaultValue): static
```
Comment (blankse) [inline models/DataObject/ClassDefinition/Data/Multiselect.php:128]:
```suggestion
    /**
     * @return $this
     */
    public function setDefaultValue(array|string|null $defaultValue): static
```

**Comment by kingjia90** [comment]
@NiklasBr Thank you for the prompt report of the bc-break related to this topic, could you please have a look and try if this PR could also solve it?

File: models/DataObject/ClassDefinition/Data/Multiselect.php [hunk 2]
```diff
@@ -122,8 +122,13 @@ public function getRenderType(): ?string
...
     {
+        if (empty($defaultValue)) {
```
Comment (blankse) [inline models/DataObject/ClassDefinition/Data/Multiselect.php]: The variable always exists
```suggestion
        if (!$defaultValue) {
```

Comment (jdreesen) [reply models/DataObject/ClassDefinition/Data/Multiselect.php]: Is `'0'` not allowed as default value?

File: models/DataObject/ClassDefinition/Data/Multiselect.php [hunk 3]
```diff
@@ -122,8 +122,16 @@ public function getRenderType(): ?string
...
     }
 
-    public function setDefaultValue(array $defaultValue): static
+    /**
+     * @return $this
+     */
+    public function setDefaultValue(array|string|null $defaultValue): static
     {
+        if (!$defaultValue) {
+            $defaultValue = null;
```
Comment (jdreesen) [inline models/DataObject/ClassDefinition/Data/Multiselect.php]: Is `'0'` not allowed as default value?

File: models/DataObject/ClassDefinition/Data/Multiselect.php (hunk 2 above)
Comment (kingjia90) [reply models/DataObject/ClassDefinition/Data/Multiselect.php]: mhh true @jdreesen , should be `== null` then?

File: models/DataObject/ClassDefinition/Data/Multiselect.php [hunk 4]
```diff
@@ -122,8 +122,16 @@ public function getRenderType(): ?string
...
+        }elseif (is_string($defaultValue)){
+            $defaultValue = [$defaultValue];
+        }
```
Comment (blankse) [inline models/DataObject/ClassDefinition/Data/Multiselect.php]: Maybe this? When it is null, it must not be changed, Empty Array should also no problem or?
```suggestion
        if (is_string($defaultValue)) {
            $defaultValue = $defaultValue !== '' ? [$defaultValue] : null;
        }
```

Comment (NiklasBr) [reply models/DataObject/ClassDefinition/Data/Multiselect.php]: My current project has `null` and `""` and `somestring` values which broke, I would suspect that perhaps some integers could have made it's way into the default value storage as well. Maybe check for scalar values would make it more forgiving?

And for v12.0 create a migration which forces array type for all while making the type stricter again?

Comment (blankse) [reply models/DataObject/ClassDefinition/Data/Multiselect.php]: Where did these defaultValues came from? 
Was the field type a single select in the past? 
So after the convert in the backend the default value from the single select still exists? 

If this is the case, I think we could not make it type strict. This can also possible in v12. We should than also check the case when someone convert the multi select in a single select.

Comment (NiklasBr) [reply models/DataObject/ClassDefinition/Data/Multiselect.php]: They were created using v6 or v10, some could possibly have been selects or other field types at one point as well.

**Comment by kingjia90** [comment]
@blankse are you familiar with this Phpstan error? 🥲 i don't get it 
https://github.com/pimcore/pimcore/actions/runs/8264606720/job/22608554375#step:7:21

**Comment by blankse** [comment]
@kingjia90 I think we need no if there. The trait is only used on this two classes. So we can remove it. I created a PR to check this:
https://github.com/pimcore/pimcore/pull/16782

**Comment by kingjia90** [comment]
Should be ready for tagging a release, despite i am still having issues when using it with multiselect within classification stores, but opened a new issue
https://github.com/pimcore/pimcore/issues/16785
