### PR TITLE
[Bug]: Fix url of a sub-site document dragged in wysiywg

### LINKED ISSUE #16595: [Bug]: links do not resolve correctly on multi-site environment
### Pimcore version

11.1.5

### Steps to reproduce

1. Make sure that you have a multi-site environment (one installation with two different sites).
2. Create a document with a WYSIWYG text field.
3. Type somthing into this field.
4. Link a word of this text via drag and drop from the document tree.

### Actual Behavior

1. The site is part of the link, for example: /sitename/de/foo
2. When you click on the link, it resolves to domain-of-the-site.com/**sitename**/de/foo

(Please note the bold highlight, that's the important difference to the expected behavior.)

### Expected Behavior

1. The site is part of the link, for example: /sitename/de/foo (just /de/foo would be better, but that's the same behavior as in Pimcore 10, therefore I don't see that as a bug)
2. When you click on the link, it resolves to domain-of-the-site.com/de/foo (without the site name)

This is how it worked in my projects with Pimcore 10. With Pimcore 11, there is still the site name in the link and therefore all internal links are broken until you manually remove the site name from the path.

### PR DESCRIPTION
**Pull request by kingjia90**
## Changes in this pull request  
Resolves #16595

### CODE REVIEW

File: lib/Tool/Text.php [hunk 1]
```diff
@@ -77,6 +79,12 @@ public static function wysiwygText(?string $text, array $params = []): ?string
                                     $path .= '#' . $urlParts['fragment'];
                                 }
                             }
+
+                            $site = Frontend::getSiteForDocument($element);
+                            if ($site instanceof Site) {
+                                $path = Tool::getRequestScheme() . '://' . $site->getMainDomain() . preg_replace('~^' . $site->getRootPath().'~','', $path);
```
Comment (jdreesen) [inline lib/Tool/Text.php]: Should we escape it?
```suggestion
                                $path = Tool::getRequestScheme() . '://' . $site->getMainDomain() . preg_replace('~^' . preg_quote($site->getRootPath(), '~') . '~', '', $path);
```

Comment (kingjia90) [reply lib/Tool/Text.php]: mhh that's a good point
