### PR TITLE
[Translations] follow up to #10979

### LINKED ISSUE #11139: [Bug] Admin/Shared Translations not working
### Expected behavior

can edit translations

### Actual behavior

cannot edit translations

### Steps to reproduce

open admin translations and try to edit a translation after filtered ... 

image

### PR DESCRIPTION
**Pull request by brusch**
Resolves #11139
Related to #10979

Changed to row editing to: 

If the value is neither multiline plain text or HTML markup you can choose between 2 additional options or inline edit the single line content: 
image

if the existing value is already different from plain single line text, the options are limited based on the value type: 

image

### CODE REVIEW

File: bundles/AdminBundle/Resources/public/js/pimcore/settings/translation.js [hunk 1]
```diff
@@ -167,6 +165,7 @@ pimcore.settings.translation.domain = Class.create({
                     pimcore.layout.refresh();
 
                 } catch (e) {
+                    console.log(e);
```
Comment (jdreesen) [inline bundles/AdminBundle/Resources/public/js/pimcore/settings/translation.js]:
```suggestion
                    console.error(e);
```

File: bundles/CoreBundle/Resources/translations/en.extended.json [hunk 2]
```diff
@@ -672,6 +672,5 @@
   "sites": "Sites",
   "show_hide_areablock": "Show or Hide on frontend",
   "asset_type_changed": "Asset type was changed in the meantime. Please reload the admin interface to see the latest changes.",
-  "translation_domain": "Domain",
-  "translations": "Translations"
+  "translation_domain": "Domain"
```
Comment (dvesh3) [inline bundles/CoreBundle/Resources/translations/en.extended.json]: Not used anywhere
```suggestion
```

**Review by dvesh3 — APPROVED** [review]
