### PR TITLE
[Task] Add @param and @return php doc types to /models/<REST>

### LINKED ISSUE #12215: [Task] Add @param and @return php doc types to /models/<REST>
### Improvement description

- [x] Add @param php doc types for all public/protected classes/methods/properties in /models/Exception (excl. Dao and @internal) 
- [x] Add @return php doc types for all public/protected classes/methods/properties in /models/Exception (excl. Dao and @internal) 
- [x] Add @param php doc types for all public/protected classes/methods/properties in /models/Glossary (excl. Dao and @internal) 
- [x] Add @return php doc types for all public/protected classes/methods/properties in /models/Glossary (excl. Dao and @internal) 
- [x] Add @param php doc types for all public/protected classes/methods/properties in /models/GridConfig (excl. Dao and @internal) 
- [x] Add @return php doc types for all public/protected classes/methods/properties in /models/GridConfig  (excl. Dao and @internal) 
- [x] Add @param php doc types for all public/protected classes/methods/properties in /models/GridConfigFavourite (excl. Dao and @internal) 
- [x] Add @return php doc types for all public/protected classes/methods/properties in /models/GridConfigFavourite (excl. Dao and @internal) 
- [x] Add @param php doc types for all public/protected classes/methods/properties in /models/Metadata (excl. Dao and @internal) 
- [x] Add @return php doc types for all public/protected classes/methods/properties in /models/Metadata (excl. Dao and @internal) 
- [x] Add @param php doc types for all public/protected classes/methods/properties in /models/Notification (excl. Dao and @internal) 
- [x] Add @return php doc types for all public/protected classes/methods/properties in /models/Notification (excl. Dao and @internal) 
- [x] Add @param php doc types for all public/protected classes/methods/properties in /models/Property (excl. Dao and @internal) 
- [x] Add @return php doc types for all public/protected classes/methods/properties in /models/Property (excl. Dao and @internal) 
- [x] Add @param php doc types for all public/protected classes/methods/properties in /models/Redirect (excl. Dao and @internal) 
- [x] Add @return php doc types for all public/protected classes/methods/properties in /models/Redirect (excl. Dao and @internal) 
- [x] Add @param php doc types for all public/protected classes/methods/properties in /models/Schedule (excl. Dao and @internal) 
- [x] Add @return php doc types for all public/protected classes/methods/properties in /models/Schedule (excl. Dao and @internal) 
- [x] Add @param php doc types for all public/protected classes/methods/properties in /models/Search (excl. Dao and @internal) 
- [x] Add @return php doc types for all public/protected classes/methods/properties in /models/Search (excl. Dao and @internal) 
- [x] Add @param php doc types for all public/protected classes/methods/properties in /models/Site (excl. Dao and @internal) 
- [x] Add @return php doc types for all public/protected classes/methods/properties in /models/Site (excl. Dao and @internal) 
- [x] Add @param php doc types for all public/protected classes/methods/properties in /models/Staticroute (excl. Dao and @internal) 
- [x] Add @return php doc types for all public/protected classes/methods/properties in /models/Staticroute (excl. Dao and @internal) 
- [x] Add @param php doc types for all public/protected classes/methods/properties in /models/Translation (excl. Dao and @internal) 
- [x] Add @return php doc types for all public/protected classes/methods/properties in /models/Translation (excl. Dao and @internal) 
- [x] Add @param php doc types for all public/protected classes/methods/properties in /models/WebsiteSetting (excl. Dao and @internal) 
- [ ]Add @return php doc types for all public/protected classes/methods/properties in /models/WebsiteSetting (excl. Dao and @internal) 
- [x] Add @param php doc types for all public/protected classes/methods/properties in /models/Workflow (excl. Dao and @internal) 
- [x] Add @return php doc types for all public/protected classes/methods/properties in /models/Workflow (excl. Dao and @internal) 

- [x] Make sure phpstan tests still run through

### PR DESCRIPTION
**Pull request by dvesh3**
## Changes in this pull request  
Resolves #12215

### CODE REVIEW

File: models/WebsiteSetting/Listing.php [hunk 1]
```diff
@@ -16,31 +16,32 @@
 namespace Pimcore\Model\WebsiteSetting;
 
 use Pimcore\Model;
+use Pimcore\Model\WebsiteSetting;
 
 /**
  * @method \Pimcore\Model\WebsiteSetting\Listing\Dao getDao()
```
Comment (jdreesen) [inline models/WebsiteSetting/Listing.php]: Could be changed, too, as `WebsiteSetting` is imported now.

```suggestion
 * @method WebsiteSetting\Listing\Dao getDao()
```

Comment (dvesh3) [reply models/WebsiteSetting/Listing.php]: yes, thanks!

File: models/Property.php [hunk 2]
```diff
@@ -129,6 +129,8 @@ public function getCid()
     }
 
     /**
+     * enum('document','asset','object')
+     *
      * @return string
```
Comment (jdreesen) [inline models/Property.php:134]: What about using PHPStan's type annotations for this? [Like this:](https://phpstan.org/writing-php-code/phpdoc-types#literals-and-constants)
```suggestion
     * @return 'document'|'asset'|'object'
```

Or maybe even [with an alias](https://phpstan.org/writing-php-code/phpdoc-types#local-type-aliases), which can be used for the property and its getters/setters.

Comment (dvesh3) [reply models/Property.php:134]: @jdreesen This needs more refactoring so not the priority for us. we would be happy to receive a PR for this improvement. thanks for your suggestion 😉

Comment (jdreesen) [reply models/Property.php:134]: I'm afraid I won't have time for that in the near future :/

File: models/Notification.php [hunk 3]
```diff
@@ -212,39 +212,39 @@ public function setSender(?User $sender): self
     }
 
     /**
-     * @return User|null
+     * @return User
```
Comment (blankse) [inline models/Notification.php]: Why it cannot be null? If I create a new Notification it is null, right?
```
$notification = new Notification();
$notification->getRecipient();
```
In addition, the return type hint is still nullable

Comment (aryaantony92) [reply models/Notification.php]: @blankse Thanks, I will change the typehint.  It cannot be null because it doesn't make sense to create/send a new notification with an empty recipient.

Comment (blankse) [reply models/Notification.php]: Yes, but I think that should check the save method. Until the setRecipient() method is called, the attribute is still null. So why shouldn't the user be able to use getRecipient to check whether it's already set?

File: models/Glossary.php [hunk 4]
```diff
@@ -27,7 +27,7 @@ class Glossary extends AbstractModel
     /**
      * @internal
      *
-     * @var int|null
+     * @var int
      */
     protected $id;
```
Comment (blankse) [inline models/Glossary.php]: Can be null for new unsaved models. Also for the getter and other models.
```
$glossary = new Glossary();
var_dump($glossary->getId());
```

File: models/Notification.php (hunk 3 above)
Comment (aryaantony92) [reply models/Notification.php]: @blankse I have added the null check before the save() method. But, we decided to follow an approach where the  properties type would match with the db column types. That's why we made it to not null.

Comment (blankse) [reply models/Notification.php]: For setter typehints I agree. But getter/properties can be null for new unsaved models. When you really want to change this its a BC break I think, because no getter could be called now until the setter is called.

Comment (dvesh3) [reply models/Notification.php]: yes, you are right. Reverted the changes for BC reasons. thanks!

File: models/Glossary.php (hunk 4 above)
Comment (dvesh3) [reply models/Glossary.php]: yes, you are right. Reverted the changes for BC reasons. thanks!

File: models/Translation.php [hunk 5]
```diff
@@ -93,7 +93,7 @@ public static function IsAValidLanguage(string $domain, string $locale): bool
     }
 
     /**
-     * @return string|null
```
Comment (aryaantony92) [inline models/Translation.php]: @dvesh3 Should n't we keep this getter also as nullable ?

Comment (dvesh3) [reply models/Translation.php]: good catch! changed it 😊
