### PR TITLE
[Bug]: Remove user from runtime cache on user deletion

### LINKED ISSUE #13616: [Improvement]: Dangerous feature on user class
### Improvement description

The scenario is simple:
1. High traffic on the site 
2. Log into the admin panel
3. We delete any user
4. The server goes down due to high load 
https://github.com/pimcore/pimcore/blob/v6.9.6/models/User/AbstractUser.php#L248

### PR DESCRIPTION
**Pull request by kingjia90**
## Changes in this pull request  
(Indirectly) Resolves https://github.com/pimcore/pimcore/issues/13616

## Additional info
Tried to check if the Cache Clear All removal has any purpose but didn't find any.
Found instead that RuntimeCache should be cleared.
eg:
```
        $current = User::getById($id);
        $cached  = RuntimeCache::get('user_'.$id);
        $user->delete();
        $cached2  = RuntimeCache::get('user_'.$id);
```
without this PR, the $cached2 would contain the former info.

Due 
https://github.com/pimcore/pimcore/blob/5c929b093b07f9533589d99f55c02528a3d41fc9/models/User/AbstractUser.php#L58-L68
and "lack" of `force` optional parameter in `getById`

### <samp>🤖 Generated by Copilot at 5c929b0</samp>

Fix cache invalidation bug when deleting a user. Clear the runtime cache for the deleted user in `models/User/AbstractUser.php`.

### <samp>🤖 Generated by Copilot at 5c929b0</samp>

> _`runtime` cache cleared_
> _user deletion bug is fixed_
> _autumn leaves fall fast_

### <samp>🤖 Generated by Copilot at 5c929b0</samp>

* Clear the runtime cache for the deleted user to prevent stale data and errors ([link](https://github.com/pimcore/pimcore/pull/15609/files?diff=unified&w=0#diff-33922f1600adee6c57d7b56216b6fc1188e2ffef899a5ee79eaed8414edb352fL263-R267) in `models/User/AbstractUser.php`)

### CODE REVIEW

File: models/User/AbstractUser.php [hunk 1]
```diff
@@ -260,7 +261,11 @@ public function delete()
 
         // now delete the current user
         $this->getDao()->delete();
-        \Pimcore\Cache::clearAll();
+        
+        $cacheKey = 'user_' . $this->getId();
+        if (RuntimeCache::isRegistered($cacheKey)) {
```
Comment (dvesh3) [inline models/User/AbstractUser.php:267]: should we also clear parent cache(if exists) here? as this examples generates wrong result:
```
        $parent = User\Folder::getById($id);
        $parent->getChildren(); //count: 1
        
        $child = User::getById($cid);
        $child->delete();
        
        $parent = User\Folder::getById($id);
        $parent->getChildren(); //count: 1
```

File: models/User/AbstractUser.php [hunk 2]
```diff
@@ -261,12 +262,19 @@ public function delete()
...
         // now delete the current user
         $this->getDao()->delete();
-        
+
         $cacheKey = 'user_' . $this->getId();
         if (RuntimeCache::isRegistered($cacheKey)) {
             RuntimeCache::set($cacheKey, null);
         }
 
+        if ($parentUserId && $parentUserId > 1) {
```
Comment (dvesh3) [inline models/User/AbstractUser.php:271]: why this check `$parentUserId > 1`?

Comment (kingjia90) [reply models/User/AbstractUser.php:271]: to avoid clearing the system user, seeing 
https://github.com/pimcore/pimcore/pull/15609/files?w=1#diff-33922f1600adee6c57d7b56216b6fc1188e2ffef899a5ee79eaed8414edb352fR242-R243
