### PR TITLE
Advanced Many To Many Objects metadata column names get "strtolowered…

### LINKED ISSUE #5908: Advanced Many To Many Objects metadata column names  get "strtolowered"
# Bug Report

I think this isn't supposed to be a feature, but if it's the case please forgive me. 

### Expected behavior & actual behaviours

As an admin, when I design DataObjects and create an Advanced Many To Many Object relation property, I want my metadata column names to take into account the correct capitalization of the names I input. 

For example, when I type `productionCost`, I expect that the name displayed and saved in the database to be `productionCost`, and not `productioncost`. I also expect the Metadata object to have a magic getter `$metadata->getProductionCost()` instead of `$metadata->getProductioncost()`.

### Steps to reproduce

DataObject > Classes > Add an Advanced M2M relation and create a column with a custom capitalization. Save the Class and reload definition.

### PR DESCRIPTION
**Pull request by weisswurstkanone**
Resolves #5908

### CODE REVIEW

File: models/DataObject/ClassDefinition/Data/AdvancedManyToManyObjectRelation.php [hunk 1]
```diff
@@ -845,7 +845,7 @@ public function setColumns($columns)
         $this->columns = [];
         $this->columnKeys = [];
         foreach ($columns as $c) {
-            $c['key'] = strtolower($c['key']);
+            $c['key'] = $c['key'];
```
Comment (dvesh3) [inline models/DataObject/ClassDefinition/Data/AdvancedManyToManyObjectRelation.php]: this can go away

Comment (weisswurstkanone) [reply models/DataObject/ClassDefinition/Data/AdvancedManyToManyObjectRelation.php]: done
