### PR TITLE
Fixes missing usage of webp_auto_support for console command

### LINKED ISSUE #7357: webp_auto_support: false does not work
### Expected behavior

According to the documentation [it should be possible to disable](https://pimcore.com/docs/pimcore/current/Development_Documentation/Assets/Working_with_Thumbnails/Image_Thumbnails.html#page_WebP-Support) to disable WebP. Deleting the temproary files, and then running the `bin/console pimcore:thumbnails:image` command should not generate any WebP files.

### Actual behavior

WebP images are generated, both on disk and in the HTML markup.

### Steps to reproduce

Pimcore 6.8.2
PHP 7.4.11
Imagemagick 7.0.10-34

Update the config, clear the cache, delete the temporary files. Re-process all assets.

### Code example
File pimcore/app/config/config.yml:
```yml
pimcore:
    assets:
        image:
            thumbnails:
                webp_auto_support: false
```

File pimcore/var/config/image-thumbnails.php:
```php
return [
//...
    "detail" => [
        "items" => [
            [
                "method" => "cover",
                "arguments" => [
                    "width" => 540,
                    "height" => 700,
                    "positioning" => "topcenter",
                    "forceResize" => FALSE
                ]
            ]
        ],
        "medias" => [

        ],
        "name" => "detail",
        "description" => "",
        "group" => "Product",
        "format" => "SOURCE",
        "quality" => 85,
        "highResolution" => 0.0,
        "preserveColor" => FALSE,
        "preserveMetaData" => TRUE,
        "rasterizeSVG" => FALSE,
        "downloadable" => TRUE,
        "modificationDate" => 1603118890,
        "creationDate" => 1590420641,
        "forcePictureTag" => FALSE,
        "id" => "detail"
    ],
//...
```

Example output:
```bash
$ ls -l pimcore/web/var/tmp/image-thumbnails/assortment/16060/*
pimcore/web/var/tmp/image-thumbnails/assortment/16060/image-thumb__3811__detail:
-rw-rw-r-- 1 niklas niklas 27600 Oct 19 19:26  100577.jpg
-rw-rw-r-- 1 niklas niklas 17052 Oct 19 19:26  100577.webp
-rw-rw-r-- 1 niklas niklas 61545 Oct 19 19:26 '100577@2x.jpg'
-rw-rw-r-- 1 niklas niklas 15738 Oct 19 19:26 '100577@2x.webp'

pimcore/web/var/tmp/image-thumbnails/assortment/16060/image-thumb__3811__hero:
-rw-rw-r-- 1 niklas niklas  70416 Oct 19 19:26  100577.jpg
-rw-rw-r-- 1 niklas niklas  39778 Oct 19 19:26  100577.webp
-rw-rw-r-- 1 niklas niklas 104289 Oct 19 19:26 '100577@2x.jpg'
-rw-rw-r-- 1 niklas niklas  26342 Oct 19 19:26 '100577@2x.webp'

pimcore/web/var/tmp/image-thumbnails/assortment/16060/image-thumb__3811__list:
-rw-rw-r-- 1 niklas niklas 1781 Oct 19 19:26  100577.jpg
-rw-rw-r-- 1 niklas niklas 1118 Oct 19 19:26  100577.webp
-rw-rw-r-- 1 niklas niklas 3680 Oct 19 19:26 '100577@2x.jpg'
-rw-rw-r-- 1 niklas niklas 2478 Oct 19 19:26 '100577@2x.webp'

pimcore/web/var/tmp/image-thumbnails/assortment/16060/image-thumb__3811__mini:
-rw-rw-r-- 1 niklas niklas 2556 Oct 19 19:26  100577.jpg
-rw-rw-r-- 1 niklas niklas 1640 Oct 19 19:26  100577.webp
-rw-rw-r-- 1 niklas niklas 5644 Oct 19 19:26 '100577@2x.jpg'
-rw-rw-r-- 1 niklas niklas 3700 Oct 19 19:26 '100577@2x.webp'

pimcore/web/var/tmp/image-thumbnails/assortment/16060/image-thumb__3811__nav_icon:
-rw-rw-r-- 1 niklas niklas 1569 Oct 19 19:26  100577.jpg
-rw-rw-r-- 1 niklas niklas  886 Oct 19 19:26  100577.webp
-rw-rw-r-- 1 niklas niklas 3067 Oct 19 19:26 '100577@2x.jpg'
-rw-rw-r-- 1 niklas niklas 2046 Oct 19 19:26 '100577@2x.webp'

pimcore/web/var/tmp/image-thumbnails/assortment/16060/image-thumb__3811__page:
-rw-rw-r-- 1 niklas niklas  7303 Oct 19 19:26  100577.jpg
-rw-rw-r-- 1 niklas niklas  4942 Oct 19 19:26  100577.webp
-rw-rw-r-- 1 niklas niklas 19180 Oct 19 19:26 '100577@2x.jpg'
-rw-rw-r-- 1 niklas niklas 12012 Oct 19 19:26 '100577@2x.webp'
```

### PR DESCRIPTION
**Pull request by NiklasBr**
## Changes in this pull request  
Resolves #7357

### CODE REVIEW

File: bundles/CoreBundle/Command/ThumbnailsImageCommand.php [hunk 1]
```diff
@@ -188,7 +188,8 @@ private function fetchThumbnailConfigs(InputInterface $input): array
                         $resConfig->setHighResolution($resolution);
                         $thumbnailsToGenerate[] = $resConfig;
 
-                        if (!$input->getOption('skip-webp') && $resConfig->getFormat() === 'SOURCE') {
+                        $isWebPAutoSupport = \Pimcore::getContainer()->getParameter('pimcore.config')['assets']['image']['thumbnails']['webp_auto_support'];
```
Comment (dvesh3) [inline bundles/CoreBundle/Command/ThumbnailsImageCommand.php:191]:
```suggestion

                        $config = \Pimcore\Config::getSystemConfiguration();
                        $isWebPAutoSupport = $config['assets']['image']['thumbnails']['webp_auto_support'] ?? false;
```

Comment (dvesh3) [reply bundles/CoreBundle/Command/ThumbnailsImageCommand.php]: @NiklasBr one last change please (sorry, forgot in my suggestion)...since we just need asset config, we can pass offset to getSystemConfiguration() i.e. `\Pimcore\Config::getSystemConfiguration('asset');`

Comment (NiklasBr) [reply bundles/CoreBundle/Command/ThumbnailsImageCommand.php]: No worries. Didn't I do it already in d7a71bd2ca0ac20b8c86253eb28143b7bffbf9e2?

File: models/Asset/Image/Thumbnail.php [hunk 2]
```diff
@@ -320,8 +320,10 @@ public function getHtml($options = [], $removeAttributes = [])
         // $this->getConfig() can be empty, the original image is returned
         if ($this->getConfig() && ($this->getConfig()->hasMedias() || $this->getConfig()->getForcePictureTag())) {
             // output the <picture> - element
-            $isWebPAutoSupport = \Pimcore::getContainer()->getParameter('pimcore.config')['assets']['image']['thumbnails']['webp_auto_support'];
-            $isAutoFormat = (strtolower($this->getConfig()->getFormat()) === 'source' && $isWebPAutoSupport) ? true : false;
+            $config = \Pimcore\Config::getSystemConfiguration();
```
Comment (dvesh3) [inline models/Asset/Image/Thumbnail.php:323]: remove unused declaration

Comment (brusch) [inline models/Asset/Image/Thumbnail.php:323]:
```suggestion
```

**Comment by dvesh3** [comment]
@NiklasBr thanks a lot!
