### PR TITLE
Remove document from mail object before sending

### LINKED ISSUE #9824: [Bug]:  Circular reference error when sending emails using Symfony Messenger
### Expected behavior

When using a messenger transport the given object should be serializable with the default symfony serializer to whatever transport you have defined. In my case this is the `symfony/doctrine-messenger`

### Actual behavior

Because Symfony tries to serialize the `\Pimcore\Mail` class and this class contains the property `$document` of type `\Pimcore\Model\Document\Email` it fails to serialize the class because the document has a `$dao` property which has `$model` property which is the same as the `$document` property as before.

### Steps to reproduce

Use the Symfony serializer to serialize a `\Pimcore\Mail` object OR Setup the Symfony messenger to send `Symfony\Component\Mailer\Messenger\SendEmailMessage` class over a transport that needs to serialize the class.

See documentation on how to do this here: https://symfony.com/doc/current/mailer.html#sending-messages-async

### PR DESCRIPTION
**Pull request by rubanooo**
## Changes in this pull request  
Resolves  #9824

## Additional info  

This is not an optimal solution, but probably the best solution until Pimcore supports serializing objects using the Symfony serializer.

### CODE REVIEW

File: lib/Mail.php [hunk 1]
```diff
@@ -488,6 +488,10 @@ public function send(MailerInterface $mailer = null)
 
         $this->subject($this->getSubjectRendered());
 
+        // Remove the document property because it is no longer needed and makes it difficult
+        // to serialize the Mail object when using the Symfony Messenger component
+        $this->setDocument(null);
```
Comment (dvesh3) [inline lib/Mail.php:493]: please adapt `setDocument()` method to nullify `$this->document` property. At the moment, it will throw exception `document is not an instance of Pimcore\Model\Document\Email` https://github.com/pimcore/pimcore/blob/e814e9cb0ae8300a2cf27d1b78db391168a0c0c9/lib/Mail.php#L769-L774

Comment (rubanooo) [reply lib/Mail.php:493]: Ah, I added this to my local test version but forgot to add it to the PR

**Comment by dvesh3** [comment]
thanks!
