### PR TITLE
[Bug]: Fix picture source tag intrisic size 

### LINKED ISSUE #15243: [Bug]: getSourceTagHtml produces wrong with and height
### Pimcore version

10 & 11

### Steps to reproduce

can be reproduced in the pimcore demo:

1. Open a existing pimcore Thumbnail (for example "Areas" > "portalCarousel")
2. Check the different sizes from the media-queries
3. open the demo pimcore website (https://demo.pimcore.com/) and check the source of the website

### Expected / actual behavior

**Expected behaviour:**

Current browsers allow to set the width and height attribute not only on the img-Tag but also on the source-Tag. Which pimcore does. The sizes on the source-Tags can be used by the browser to compute the aspect ratio on the different media queries (for example on chrome: https://chromestatus.com/feature/5737185317748736)
Normally Pimcore should use the width and height set on the different media queries.

**Actual Behaviour:**

The with and height attribute on the source tag is always the same as on the default-image. This makes the widht and height on the source-tag useless because the browser always uses the aspect-ratio of the default image element.

### PR DESCRIPTION
**Pull request by kingjia90**
## Changes in this pull request  
Resolves https://github.com/pimcore/pimcore/issues/15243

### <samp>🤖 Generated by Copilot at 1f3adb0</samp>

Add support for custom thumbnail options in `Thumbnail.php`. This enables passing an array of config items to the thumbnail constructor and setter methods.

### <samp>🤖 Generated by Copilot at 1f3adb0</samp>

> _`thumbnailConfig` set_
> _custom options for images_
> _autumn leaves crisp, clear_

### <samp>🤖 Generated by Copilot at 1f3adb0</samp>

* Add more flexibility to the thumbnail API by allowing custom options to be passed to the thumbnail generation ([link](https://github.com/pimcore/pimcore/pull/15253/files?diff=unified&w=0#diff-c1144c6a30525acb9f7006167ec8142edec7f4e974123db8824f11af57cfb4e6R276))

### CODE REVIEW

**Comment by kingjia90** [comment]
Weird how `$config` was never used
After PR it displays 
image
Prior PR, it is always 1920 x 600

File: models/Asset/Image/Thumbnail.php [hunk 1]
```diff
@@ -273,6 +273,7 @@ public function getHtml($options = [])
             array_push($mediaConfigs, $thumbConfig->getItems()); //add the default config at the end - picturePolyfill v4
 
             foreach ($mediaConfigs as $mediaQuery => $config) {
+                $thumbConfig->setItems($config);
```
Comment (dvesh3) [inline models/Asset/Image/Thumbnail.php]: I would be careful not to override the default config. It was cloned and used until this PR #11632 so optimal change would be to use the cloned object like [here](https://github.com/pimcore/pimcore/pull/11632/files#diff-c1144c6a30525acb9f7006167ec8142edec7f4e974123db8824f11af57cfb4e6L226-L227)

Comment (kingjia90) [reply models/Asset/Image/Thumbnail.php]: ahh, thank you for the heads-up! 
Did i got it right on https://github.com/pimcore/pimcore/pull/15253/commits/f8f144d5bfe9ec7178fc61640698bc518d9ada11 ?

Comment (dvesh3) [reply models/Asset/Image/Thumbnail.php]: could you please try cloning outside loop and selecting media inside `$thumbConfigRes->selectMedia($mediaQuery);`?

**Review by dvesh3 — APPROVED** [review]
