### PR TITLE
[Documents] Editable Dialog Box - destroy dialog box on removing editable from areablock

### LINKED ISSUE #10474: [Bug]: Wrong Content In Editable Dialog Box
### Expected behavior

A correct editable dialog should open, even after replacing the brick at the same index.

### Actual behavior

First placed brick dialog config shows up, even if I'm replacing it.

### Steps to reproduce

Screen Capture

### PR DESCRIPTION
**Pull request by dvesh3**
## Changes in this pull request  
Resolves #10474

### CODE REVIEW

**Review by brusch — APPROVED** [review]

File: bundles/AdminBundle/Resources/public/js/pimcore/document/editables/areablock.js [hunk 1]
```diff
@@ -851,19 +851,20 @@ pimcore.document.editables.areablock = Class.create(pimcore.document.area_abstra
 
     removeBlock: function (element) {
         let container = Ext.get(element);
+
+        let dialogBoxDiv = container.query('.pimcore_block_dialog[data-name="' + this.name + '"]')[0];
+        if (dialogBoxDiv) {
+            let dialogBoxId = dialogBoxDiv.dataset.dialogId;
+            this.removeEditableDialogbox(dialogBoxId);
```
Comment (brusch) [inline bundles/AdminBundle/Resources/public/js/pimcore/document/editables/areablock.js:858]: @dvesh3 JFI: I've moved that code block to the beginning, because actually `container.remove();` removed the `.pimcore_block_dialog` container as well, because it's a child. Your code worked for whatever reason, however I thought it might be a bit confusing 😉
