### PR TITLE
[Bug, EC]: ClassificationStore inheritance is not working

### LINKED ISSUE #16775: [Bug, EC]: ClassificationStore inheritance is not working
### Pimcore version

> 11

### Steps to reproduce

- create classification store with a few keys and groups
- add inheriting object structure in object key
- add a few values on parent object in same group
- add other values on child object in same group
- call getItems() on child using PHP API

### Actual Behavior

- only the values of the child in the group are returned

### Expected Behavior

- a merged array with values from children and (all) parents should be returned

### PR DESCRIPTION
**Pull request by robertSt7**
resolves #16775

### CODE REVIEW

File: models/DataObject/Classificationstore.php [hunk 1]
```diff
@@ -478,4 +483,21 @@ private function getGroupConfigById(int $groupId): ?Classificationstore\GroupCon
     {
         return Classificationstore\GroupConfig::getById($groupId);
     }
+
+    private function mergeArrays(array $a1, array $a2): array
```
Comment (kingjia90) [inline models/DataObject/Classificationstore.php:487]: LGTM and works, just maybe rename to
```suggestion
    private function mergeArraysByUnion(array $a1, array $a2): array
```
and add a phpdoc comment on why this method is needed (to merge without resetting numeric keys or so)

Comment (kingjia90) [reply models/DataObject/Classificationstore.php:487]: nvm on this, he who seeks finds 😄
