### PR TITLE
Objectbricks mandatory fields are not validated correctly

### LINKED ISSUE #5172: Objectbricks mandatory fields are not validated correctly
# Bug Report
Objectbreaks mandatory fields are not validated correctly

### Expected behavior
All mandatory fields in objectbricks are validated correctly 

### Actual behavior
The second added objectbrick is not validated correctly. Object can be published although mandatory fields are empty

### Steps to reproduce
Create a objectbrick with mandatory fields and use it in objects
Add a objectbrick then publish the object. 
image
After publishing add a second objectbrick to the same object. Do not enter any data in the required fields and publish the object. The object can be published although mandatory empty fields
image

### PR DESCRIPTION
**Pull request by weisswurstkanone**
resolves #5172

### CODE REVIEW

File: models/DataObject/ClassDefinition/Data/Objectbricks.php [hunk 1]
```diff
@@ -740,39 +740,46 @@ public function checkValidity($data, $omitMandatoryCheck = false)
             if ($data instanceof DataObject\Objectbrick) {
                 $validationExceptions = [];
 
-                $items = $data->getItems();
```
Comment (brusch) [inline models/DataObject/ClassDefinition/Data/Objectbricks.php]: @weisswurstkanone I'm wondering why the empty brick isn't included in `getItems()` shouldn't it be there as well?

Comment (weisswurstkanone) [reply models/DataObject/ClassDefinition/Data/Objectbricks.php]: @brusch at that point of time items is not set for the newly created brick
