### PR TITLE
[Translation] Allow trans to support plurals & Fix transChoice

### LINKED ISSUE #4587: [Pimcore6] Undefined method "choose" in IdentityTranslator
Because of changing the MessageSelector class to IdentityTranslator, the `choose` method here:

https://github.com/pimcore/pimcore/blob/16c1d538462ca4b348aa447abd4ba0cc41d0242c/lib/Translation/Translator.php#L154

does not exist anymore:

```
  [Error] Call to undefined method Symfony\Component\Translation\IdentityTranslator::choose()  
```

### PR DESCRIPTION
**Pull request by dvesh3**
## Changes in this pull request  
Resolves #4587

### CODE REVIEW

File: lib/Translation/Translator.php [hunk 1]
```diff
@@ -24,10 +24,16 @@
 use Symfony\Component\Translation\MessageCatalogue;
 use Symfony\Component\Translation\MessageCatalogueInterface;
 use Symfony\Component\Translation\TranslatorBagInterface;
-use Symfony\Component\Translation\TranslatorInterface;
+use Symfony\Contracts\Translation\TranslatorInterface;
+use Symfony\Contracts\Translation\LocaleAwareInterface;
+use Symfony\Contracts\Translation\TranslatorTrait;
 
-class Translator implements TranslatorInterface, TranslatorBagInterface
+class Translator implements TranslatorInterface, TranslatorBagInterface, LocaleAwareInterface
```
Comment (brusch) [inline lib/Translation/Translator.php]: We should also additionally implement the legacy interface `Symfony\Component\Translation\TranslatorInterface` here, same as Symfony does, see: 
https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Translation/Translator.php#L32

Otherwise it would be a proper BC break :)

**Comment by dpfaffenbauer** [comment]
does this also work properly with Symfony 3.4? Does the Contract exist there as well? Not sure about that...

**Comment by dpfaffenbauer** [comment]
is it also possible to add a test for that? So it can fail in the future if symfony changes something here again
