### PR TITLE
[Bug]: Hotspotimage cannot save object with empty relational field inside marker

### LINKED ISSUE #17486: [Bug]: Hotspotimage cannot save object with empty relational field inside marker
### Pimcore version

Platform Version: 2024.2
Version: v11.3.0

### Steps to reproduce

- add marker to Hotpotimage with data asset, document or object
- do not set a value
- save data object

### Actual Behavior

Cannot save object exception:

`Message: Handling "Pimcore\Messenger\ElementDependenciesMessage" failed: Pimcore\Model\Element\Service::getElementById(): Argument #2 ($id) must be of type string|int, null given, called in ***/vendor/pimcore/pimcore/models/Element/Data/MarkerHotspotItem.php on line 89
`

Another exception:

`Pimcore\Model\Element\Service::getElementByPath(): Argument #2 ($path) must be of type string, null given, called in ***/vendor/pimcore/pimcore/models/DataObject/ClassDefinition/Data/Hotspotimage.php on line 252`

### Expected Behavior

Use-case:
Marker with text has an optional CTA -> build with a document and an input field.

User should be able to save the object.

### PR DESCRIPTION
**Pull request by hadl**
## Changes in this pull request  

Added checks if the values is not empty before calling Model\Element\Service::getElementById 

Resolves #17486

### CODE REVIEW

File: models/DataObject/ClassDefinition/Data/Hotspotimage.php [hunk 1]
```diff
@@ -248,7 +248,7 @@ public function getDataFromEditmode(mixed $data, DataObject\Concrete $object = n
                 if (array_key_exists('data', $element) && is_array($element['data']) && count($element['data']) > 0) {
                     foreach ($element['data'] as &$metaData) {
                         $metaData = new Element\Data\MarkerHotspotItem($metaData);
-                        if (in_array($metaData['type'], ['object', 'asset', 'document'])) {
+                        if (in_array($metaData['type'], ['object', 'asset', 'document']) && !empty($metaData->getValue())) {
                             $el = Element\Service::getElementByPath($metaData['type'], $metaData->getValue());
                             $metaData['value'] = $el;
                         }
```
Comment (kingjia90) [inline models/DataObject/ClassDefinition/Data/Hotspotimage.php]: Thank you for the PR!

It seems that could be replacing
```
    if (in_array($metaData['type'], ['object', 'asset', 'document'])) {
        $el = Element\Service::getElementByPath($metaData['type'], $metaData->getValue());
        $metaData['value'] = $el;
    }
```
with 
`$metadata['value'] = $metaData->offsetGet('value');`

BUT here is `getElementByPath` while in the other method is [getElementById](https://github.com/pimcore/pimcore/blob/68f198d32add713f2e4025b5dcb6414754133145/models/Element/Data/MarkerHotspotItem.php#L89), could it be a potential bug? 

In other words, both places are doing the same thing but in one place is working with `$this->value` being an id and in the other as a path and that is unlikely right

**Review by kingjia90 — DISMISSED** [review]

File: models/DataObject/ClassDefinition/Data/Hotspotimage.php (hunk 1 above)
Comment (hadl) [reply models/DataObject/ClassDefinition/Data/Hotspotimage.php]: As far as i am right:

The Hotspotimage::getDataFromEditmode is used for the editmode.

MarkerHotspotItem::offsetGet will be the "normal" API to get the selected object.

There should be everything ok. These calls where added in 2015 by brusch.

Comment (kingjia90) [reply models/DataObject/ClassDefinition/Data/Hotspotimage.php]: ah, i've double-checked with xdebug, indeed it works, so all good, thank you also for the confirmation

File: models/DataObject/ClassDefinition/Data/Hotspotimage.php [hunk 2]
```diff
@@ -248,7 +248,7 @@ public function getDataFromEditmode(mixed $data, DataObject\Concrete $object = n
                 if (array_key_exists('data', $element) && is_array($element['data']) && count($element['data']) > 0) {
                     foreach ($element['data'] as &$metaData) {
                         $metaData = new Element\Data\MarkerHotspotItem($metaData);
-                        if (in_array($metaData['type'], ['object', 'asset', 'document'])) {
+                        if (in_array($metaData['type'], ['object', 'asset', 'document']) && !empty($metaData->getValue())) {
```
Comment (blankse) [inline models/DataObject/ClassDefinition/Data/Hotspotimage.php]:
```suggestion
                        if (in_array($metaData['type'], ['object', 'asset', 'document']) && $metaData->getValue()) {
```

File: models/Element/Data/MarkerHotspotItem.php [hunk 3]
```diff
@@ -85,7 +85,7 @@ public function offsetExists($offset): bool
     public function offsetGet($offset): mixed
     {
         if ($this->offsetExists($offset)) {
-            if ($offset === 'value' && in_array($this->type, ['object', 'asset', 'document'])) {
+            if ($offset === 'value' && in_array($this->type, ['object', 'asset', 'document']) && !empty($this->value)) {
```
Comment (blankse) [inline models/Element/Data/MarkerHotspotItem.php]:
```suggestion
            if ($offset === 'value' && in_array($this->type, ['object', 'asset', 'document']) && $this->value) {
```

**Review by blankse — COMMENTED** [review]
empty() is not necessary because the variable/method always exists

**Comment by hadl** [comment]
> empty() is not necessary because the variable/method always exists

@blankse but with the wrong value/type. Check the exceptions in #17486

File: models/DataObject/ClassDefinition/Data/Hotspotimage.php (hunk 2 above)
Comment (hadl) [reply models/DataObject/ClassDefinition/Data/Hotspotimage.php]: resolved in 17159cde

File: models/Element/Data/MarkerHotspotItem.php (hunk 3 above)
Comment (hadl) [reply models/Element/Data/MarkerHotspotItem.php]: resolved in 17159cde
