### PR TITLE
[Bug]: NotificationService is internal but docs says we should use it 

### LINKED ISSUE #17803: [Bug]: NotificationService is internal but docs says we should use it
### Pimcore version

11.4.2

### Steps to reproduce

1. Follow the documentation at https://pimcore.com/docs/platform/Pimcore/Tools_and_Features/Notifications/#working-with-notifications-via-api
2. See that you get warnings that `NotificationService` is marked as `@internal`

### Actual Behavior

Image

https://github.com/pimcore/studio-backend-bundle/blob/3aa25d518d992dfaa44f75f9ce2157140fe72a2b/src/Notification/Service/NotificationService.php#L33-L36

https://github.com/pimcore/pimcore/blob/322366f2d0d7613a0ce7ac796092f733b165008f/models/Notification/Service/NotificationService.php#L30-L35

### Expected Behavior

It should not be internal, or the documentation should change to the _actual_ public service. This is also the case for the new Studio UI Bundle.

### PR DESCRIPTION
**Pull request by kingjia90**
## Changes in this pull request  
Resolves https://github.com/pimcore/pimcore/issues/17803

### CODE REVIEW

File: models/Notification/Service/NotificationService.php [hunk 1]
```diff
@@ -28,9 +28,7 @@
 use UnexpectedValueException;
 
 /**
- * @internal
- * With the end of Classic-UI this service will be deprecated.
```
Comment (jdreesen) [inline models/Notification/Service/NotificationService.php:32]: So maybe you should `@deprecate` it instead of `@internal`?

Comment (kingjia90) [reply models/Notification/Service/NotificationService.php:32]: Thank you for your input.

It feels a little too early for a deprecation, looks like the interface in the studio would be moved here and both should be extending that instead.. I don't know exactly how and when, but for the moment, removing the internal seems right due to the documentation.
