### PR TITLE
[Bug][SeoBundle] Redirect logging should log into channel redirect

### LINKED ISSUE #14939: [Bug][SeoBundle] Redirect logging should log into channel redirect
### Expected behavior

Redirect logging should log into channel `redirect`

### Actual behavior

Redirects are logged into channel `routing`

### Steps to reproduce

see [that line](https://github.com/pimcore/pimcore/blob/53449686033cdb9dd10f5c64c9636b8c725e2a35/bundles/SeoBundle/src/Redirect/RedirectHandler.php#L225)

## TODO

- [ ] Inject additional logger into `RedirectHandler` that logs into channel `redirect` and modify line linked above.
- [ ] Also update upgrade notes again

### PR DESCRIPTION
**Pull request by robertSt7**
resolves #14939

### CODE REVIEW

File: bundles/SeoBundle/src/Redirect/RedirectHandler.php [hunk 1]
```diff
@@ -38,13 +37,15 @@
...
-final class RedirectHandler implements LoggerAwareInterface
+final class RedirectHandler
 {
-    use LoggerAwareTrait;
     use RecursionBlockingEventDispatchHelperTrait;
 
     const RESPONSE_HEADER_NAME_ID = 'X-Pimcore-Redirect-ID';
 
+    private ?LoggerInterface $logger = null;
+    private ?LoggerInterface $redirectLogger = null;
```
Comment (blankse) [inline bundles/SeoBundle/src/Redirect/RedirectHandler.php:47]: Can't be nullable, because it is always set in the constructor

Comment (robertSt7) [reply bundles/SeoBundle/src/Redirect/RedirectHandler.php:47]: @blankse Thanks for reporting it :) It will be fixed by https://github.com/pimcore/pimcore/pull/15177
