### PR TITLE
[Bug]: Fix wysiwyg max character, soften the warning and add visual helper

### LINKED ISSUE #16630: [Bug]: Wysiwyg editors all use the same max length (max characters)
### Pimcore version

11.1.5

### Steps to reproduce

1. Create a new or open an existing data object class definition
2. Edit or add a new wysiwyg field
3. Add some max characters value (eg. 10)
4. Add one more wysiwyg field without a max length
5. Visit the data object or create a new one
6. Try to enter more than 10 chars to the field and you will see an error (which is fine, by the way ESC should close this window, which it doesn't) 
7. Try to enter more than 10 chars in the second field and you will see the same error.
8. ONE MORE THING: this same error will now also occur in any other wysiwyg in any other editor.

### Actual Behavior

It seems like the max chars config is used for all wysiwyg fields across the page.

This leads to the issue, that there is a max length error in all wysiwyg fields no matter if a max length is defined for them or not.

### Expected Behavior

Only the wysiwyg field with a defined max length should throw the error.

### PR DESCRIPTION
**Pull request by kingjia90**
## Changes in this pull request  
Resolves https://github.com/pimcore/pimcore/issues/16630

## Additional info
Before PR
image

After PR 
image
which is more similar to textArea
image

### CODE REVIEW

File: bundles/TinymceBundle/public/js/editor.js [hunk 1]
```diff
@@ -83,6 +85,8 @@ pimcore.bundle.tinymce.editor = Class.create({
             defaultConfig = pimcore[e.detail.context][subSpace].wysiwyg ? pimcore[e.detail.context][subSpace].wysiwyg.defaultEditorConfig : {};
         }
 
+        let maxChars = this.maxChars;
```
Comment (robertSt7) [inline bundles/TinymceBundle/public/js/editor.js]:
```suggestion
        const maxChars = this.maxChars;
```
