### PR TITLE
Data Object: consider unpublished state for reverse object relation

### LINKED ISSUE #17449: [Bug]: ReverseObjectRelation | publish state is not evaluated
### Pimcore version

11.3.1

### Steps to reproduce

Build two class definitions (ClassA and ClassB) with a many to many object relation in the first definition and a reverse object relation in the second class definition.

### Actual Behavior

Unpublished related objects are filtered out correctly when accessing objects via (classA->getObjectRelation()).
The following method call (classB->getReverseRelation()) still returns unpublished objects.

### Expected Behavior

Both relation data types should filter out unpublished data objects.

Here's the code to filter out unpublished objects in ManyToManyObjectRelation::preGetData()
```
        if (DataObject::doHideUnpublished() && is_array($data)) {
            $publishedList = [];
            foreach ($data as $listElement) {
                if (Element\Service::isPublished($listElement)) {
                    $publishedList[] = $listElement;
                }
            }

            return $publishedList;
        }
```

### PR DESCRIPTION
**Pull request by brusch**
Fixes #17453 
Fixes #17449

### CODE REVIEW

File: models/DataObject/ClassDefinition/Data/Relations/ManyToManyRelationTrait.php [hunk 1]
```diff
@@ -58,4 +60,20 @@ public function save(Localizedfield|AbstractData|\Pimcore\Model\DataObject\Objec
 
         parent::save($object, $params);
     }
+
+    protected function filterUnpublishedElements(mixed $data): array
+    {
+        if (DataObject::doHideUnpublished() && is_array($data)) {
```
Comment (kingjia90) [inline models/DataObject/ClassDefinition/Data/Relations/ManyToManyRelationTrait.php]: codewise LGTM (haven't tested it yet)

just a micro-optimization to reduce one `is_array()`

```suggestion
        if (!is_array($data)){ return [];}
        if (DataObject::doHideUnpublished()) {
```
and at the bottom replacing with 
`return $data`


or maybe the check should be outside and keep it strict parameter `array $data` instead of `mixed`?

Comment (brusch) [reply models/DataObject/ClassDefinition/Data/Relations/ManyToManyRelationTrait.php]: @kingjia90 good point, just pushed it (was just copy & pasting it 😉 ) Thanks!
