### PR TITLE
get admin locales / consider locale fallback

### LINKED ISSUE #16090: [Bug]: Locale Fallback is not considered during language selection
### Pimcore version

11.x

### Steps to reproduce

Define a admin language e.g. de_CH but do not provide a translation file for this locale.
Try to select this language in the Pimcore back-end user interface.

Some more information:
This PR added a fallback logic from country specific locales to primary language: https://github.com/pimcore/pimcore/issues/14092
The language selection still checks for a existing translation file but does not consider the fallback.

PR is on the way.

### Actual Behavior

Locale Fallback is not considered during language selection

### Expected Behavior

Locale Fallback is considered during language selection

### PR DESCRIPTION
**Pull request by hethehe**
## Changes in this pull request  
Resolves #16090

### <samp>🤖 Generated by Copilot at 51ddfe3</samp>

Improved readability and functionality of `Admin.php` by renaming variables, simplifying a condition, and filtering translated languages by admin languages.

### <samp>🤖 Generated by Copilot at 51ddfe3</samp>

> _`Admin.php` is the tool of doom_
> _Renaming variables, simplifying rules_
> _Filtering languages, no more fools_
> _`Admin.php` is the tool of doom_

### <samp>🤖 Generated by Copilot at 51ddfe3</samp>

*  Rename variables to improve readability and consistency ([link](https://github.com/pimcore/pimcore/pull/16093/files?diff=unified&w=0#diff-d8b1f4ffbedfa132c950644f445ac215fb6adc74e16e35ae6f5c1a98de5a2aeaL43-R47))
*  Simplify condition to check language code and file name ([link](https://github.com/pimcore/pimcore/pull/16093/files?diff=unified&w=0#diff-d8b1f4ffbedfa132c950644f445ac215fb6adc74e16e35ae6f5c1a98de5a2aeaL61-R63))
*  Filter translated languages by admin languages and handle regional variants and fallback cases ([link](https://github.com/pimcore/pimcore/pull/16093/files?diff=unified&w=0#diff-d8b1f4ffbedfa132c950644f445ac215fb6adc74e16e35ae6f5c1a98de5a2aeaR71-R81))

### CODE REVIEW

File: lib/Tool/Admin.php [hunk 1]
```diff
@@ -58,18 +58,27 @@ public static function getLanguages(): array
...
+        foreach ($adminLanguages as $adminLanguage) {
+            if (in_array($adminLanguage, $translatedLanguages, true) || in_array(\Locale::getPrimaryLanguage($adminLanguage), $translatedLanguages, true)) {
+                $languages[] = $adminLanguage;
+            }
+        }
+        
+        if (empty($languages)) {
+            $languages = $translatedLanguages;
+        }
+
```
Comment (kingjia90) [inline lib/Tool/Admin.php:81]: LGTM, just unsure if it should be considered as a bug, but definitely need some documentation update.

The documentation is clearly saying that the `translation file`'s presence decides what are the valid options, even an empty file would be fine.
https://github.com/pimcore/pimcore/blob/cf8b278b7cba96c60e74976b2a4b0982e508cf46/doc/06_Multi_Language_i18n/07_Admin_Translations.md?plain=1#L44

At the same time,the  `pimcore_admin.admin_languages` usage is not properly documented anywhere. Need to add somewhere that it can be used to limit the selectable languages along of adding new ones.

It would also need to explain something like that "sub-locale defined in this config can work even without an empty file, as long as the primary locale translation file is detected."
