### PR TITLE
[Bug]: Fix migration Version20230321133700 by adding a PHP conversion fallback when CONVERT_TZ is not working

### LINKED ISSUE #18784: [Bug]: migration `Version20230321133700` is broken and may "null" the data
### Pimcore version

11.5

### Steps to reproduce

Run the migration with data present in the `application_logs` and `notifications` tables.

#### Column types
 
Although the description states that columns of type `DATETIME` are converted to type `TIMESTAMP`, this is not happening. 

The corresponding columns in the `notifications` table are already of type `TIMESTAMP`, so this is fine. 
However, the column `application_logs.timestamp` table is not.

#### Conversion of the data

`CONVERT_TZ()` is used to convert the data. However, this requires that the `mysql.time_zone_name` table is filled, which is apparently **not** the case by default, *and* that the user has access to this table!

> [!TIP]
> To fill the table, you have to run:
> ```sh
> > mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root -p mysql
> ```

Unfortunately, this has resulted in `0000-00-00 00:00:00` now appearing everywhere in `application_logs.timestamp`. 
The column `notifications.creationDate` contains the time when the migration ran, as it is set to `DEFAULT CURRENT_TIMESTAMP`. 
The column `notifications.modificationDate`, on the other hand, is `NULL` everywhere.

#### Column types

Since `DATETIME` and `TIMESTAMP` differ in that `DATETIME` does not store time zone information, while `TIMESTAMP` is always stored in UTC and converted to the session time zone when queried, I'd expect `application_logs.timestamp` to be converted (as the name of the column already suggests 😉).

#### Conversion of the data

The data gets converted correctly instead of being `NULL` or the current timestamp (when the migration ran) everywhere.

### PR DESCRIPTION
**Pull request by kingjia90**
## Changes in this pull request  
Resolves https://github.com/pimcore/pimcore/issues/18784

### CODE REVIEW

**Comment by kingjia90** [comment]
Draft: thinking that many logs may have the exact same timestamp, could convert in batches after selecting distinct, but need to be careful that may happens that DATE `A` to `a`, having a situation where DATE `B` matches `a` (by chance) is the same, may wrongly converting all `a` to `b` as well.

File: bundles/CoreBundle/src/Migrations/Version20230321133700.php [hunk 1]
```diff
@@ -17,55 +17,95 @@
...
+                $db->quoteIdentifier($timeStampColumn),
+                $db->quote($fromTimeZone),
+                $db->quote($toTimeZone)
+            ));
+
+            return;
+        }
+
+        // ⚙️ Fallback to PHP-based conversion
+        $rows = $db->fetchAllAssociative(sprintf(
```
Comment (jdreesen) [inline bundles/CoreBundle/src/Migrations/Version20230321133700.php]: We could iterate lazy using `yield` instead of fetching all rows into memory before iteration:

```suggestion
        $rows = $db->iterateAssociative(sprintf(
```

**Review by jdreesen — COMMENTED** [review]
Looks good so far :) 
Thanks for fixing it so quickly <3

**Comment by jdreesen** [comment]
> Draft: thinking that many logs may have the exact same timestamp, could convert in batches after selecting distinct, but need to be careful that may happens that DATE A to a, having a situation where DATE B matches a (by chance) is the same, may wrongly converting all a to b as well.

Yes, that sounds a bit risky. I'll try it with our ~800,000 lines and see how long it takes on my machine.

**Comment by jdreesen** [comment]
What about `application_logs.timestamp`? Should it be converted from `DATETIME` to `TIMESTAMP` as originally stated in the description?

**Comment by kingjia90** [comment]
> What about `application_logs.timestamp`? Should it be converted from `DATETIME` to `TIMESTAMP` as originally stated in the description?

Mhh good input, however feels more like it should be in a new migration, if that was missed somehow.

Might need to dig a little more, to see if the code is already considering data as UTC or whether there is or not a follow up that migrates it and it was just description mistake.

**Comment by jdreesen** [comment]
Okay, I just tried it with a copy of the `application_logs` table from our production system, which contains 713,337 rows.

### With `CONVERT_TZ`
> finished in 4065.1ms, used 80M memory, 1 migrations executed, 3 sql queries

### With `fetchAllAssociative`:
> finished in 57559.6ms, used 1.54G memory, 1 migrations executed, 0 sql queries

### With `iterateAssociative`:
> finished in 58571.7ms, used 1.28G memory, 1 migrations executed, 0 sql queries

---

So, as expected, the native version is by far the fastest and uses the least amount of memory. 

`iterateAssociative` is about a second slower than `fetchAllAssociative` but uses ~260 MB less memory.

**Comment by kingjia90** [comment]
Thank you for testing it with real life use case and data, it is really helpful and insightful!

As suspected, a` N+1` is really expensive and slow, by a huge degree.

I've tried to create a `hybrid` with https://github.com/pimcore/pimcore/pull/18788/commits/65cb43d86cf722ecc3628a82b80b67f35c150814 
So it goes through a DISTINCT of datetimes, convert them all while checking if they collide/conflict the before&after, if so, they are skipped from batch update and a separate WHERE IN loop gets the affected rows (and timestamps) by ID.

It would be still slow and maybe harder to read (and overkill? )but it's the only way i can think of in reducing some queries 🤔  or we could just remove this commit and live with the former hoping not ending up in timeout or OOM.

**Comment by jdreesen** [comment]
This makes it way faster! Almost as fast as the native query with `CONVERT_TZ` :)

> finished in 6770.9ms, used 58M memory, 1 migrations executed, 0 sql queries

However, I have not checked the data for correctness ;)

**Comment by kingjia90** [comment]
Ah wow, that would be awesome if it's converting all correctly.

A 1:1 check of the result after migration of the table matches in both N+1 and Hybrid (or even better 3 by considering the SQL) approaches should give us a hint on that.

While you are at it, it would be helpful if we could put some breakpoints on the queries results to see the total count of the distinct values (to check how much the entire table is basically divided for and justifies this performance boost) and how many collision, to just have a rough idea of how likely a collision might be happening.

Thank you in advance!

**Comment by jdreesen** [comment]
> While you are at it, it would be helpful if we could put some breakpoints on the queries results to see the total count of the distinct values (to check how much the entire table is basically divided for and justifies this performance boost) and how many collision, to just have a rough idea of how likely a collision might be happening.

Ah, yes, I actually did that, and then forgot to post it here :facepalm:

Total rows: 713,337
`$convertedMap`: 8,897
`$collisions`: 59
`$collidingResults`: 117

In fact, we have many identical timestamps because we import several thousand objects every morning, which are logged in the application logger. Many of them are processed and logged in the same second.

**Comment by jdreesen** [comment]
I exported the IDs and timestamps before and after the migration into CSV files, then used AI to generate a small script to compare the data. 
According to this script, everything is correct! 
Since the time change just happened last weekend, you can even see that this works too :)

<details>
<summary>Comparison script</summary>

```php
<?php

$file1 = __DIR__.'/pimcore_application_logs-post-migration.csv';
$file2 = __DIR__.'/pimcore_application_logs-pre-migration.csv';

$handle1 = fopen($file1, 'r');
$handle2 = fopen($file2, 'r');

if (!$handle1 || !$handle2) {
    die("Error opening files\n");
}

$lineNumber = 0;
$allMatch = true;
$twoHoursDiff = 2 * 3600; // 2 hours in seconds
$oneHourDiff = 1 * 3600;   // 1 hour in seconds
$transitionDate = strtotime('2025-10-26 00:00:00');

$stats = [
    'two_hours' => 0,
    'one_hour' => 0,
    'errors' => 0
];

while (($line1 = fgets($handle1)) !== false && ($line2 = fgets($handle2)) !== false) {
    $lineNumber++;

    // Parse lines
    $parts1 = explode(',', trim($line1));
    $parts2 = explode(',', trim($line2));

    if (count($parts1) < 2 || count($parts2) < 2) {
        continue;
    }

    $id1 = $parts1[0];
    $id2 = $parts2[0];
    $date1 = $parts1[1];
    $date2 = $parts2[1];

    // IDs must match
    if ($id1 !== $id2) {
        echo "Line $lineNumber: IDs differ ($id1 vs $id2)\n";
        $allMatch = false;
        break;
    }

    // Calculate time difference
    $timestamp1 = strtotime($date1);
    $timestamp2 = strtotime($date2);

    if ($timestamp1 === false || $timestamp2 === false) {
        echo "Line $lineNumber: Invalid date format\n";
        continue;
    }

    $diff = $timestamp2 - $timestamp1;

    // Check: 2 hours before Oct 26, 1 hour from Oct 26 onwards
    $expectedDiff = ($timestamp1 < $transitionDate) ? $twoHoursDiff : $oneHourDiff;

    if ($diff === $twoHoursDiff) {
        $stats['two_hours']++;
    } elseif ($diff === $oneHourDiff) {
        $stats['one_hour']++;
    } else {
        echo "Line $lineNumber: Difference is $diff seconds (expected: $expectedDiff)\n";
        echo "  File 1: $date1\n";
        echo "  File 2: $date2\n";
        $stats['errors']++;
        $allMatch = false;
    }

    // Progress every 100,000 lines
    if ($lineNumber % 100000 === 0) {
        echo "Processed: $lineNumber lines...\n";
    }
}

fclose($handle1);
fclose($handle2);

echo "\n--- Results ---\n";
echo "Total lines processed: $lineNumber\n";
echo "2 hours difference: {$stats['two_hours']}\n";
echo "1 hour difference: {$stats['one_hour']}\n";
echo "Errors: {$stats['errors']}\n\n";

if ($allMatch) {
    echo "✓ All lines have a valid difference (2h or 1h)!\n";
} else {
    echo "✗ Some lines have an invalid difference.\n";
}
```

</details>

> Processed: 100000 lines...
> Processed: 200000 lines...
> Processed: 300000 lines...
> Processed: 400000 lines...
> Processed: 500000 lines...
> Processed: 600000 lines...
> Processed: 700000 lines...
> 
> --- Results ---
> Total lines processed: 713337
> 2 hours difference: 643957
> 1 hour difference: 69380
> Errors: 0
> 
> ✓ All lines have a valid difference (2h or 1h)!

**Comment by kingjia90** [comment]
wow, that was really helpful ❤️ ! 
Then i am marking this PR as ready for review and open for the final tweaks.

It would really depend on each case/project indeed, but so far it's the best compromise, considering that optimistically most of the projects would likely never fallback to this PHP conversion part. Thank you again for all the help!

**Comment by jdreesen** [comment]
I'm glad to help. Thank you for fixing it so quickly :)

**Comment by kingjia90** [comment]
Let's merge it



Leaving some extra notes, the only things that popup in my mind to improve it even more (but not worth it yet) are:
- to change the `convertToTimeZone` function to work on multiple table columns at once, for example `notification` is performed on `creationDate` and then `modificationDate` , it would be doubling the total queries amount.
- a `WHERE NOT IN collidingIds` for the batch updates just for *extra* safety, but the `in_array/array_key_exists/!isset($collisions[])` should be already properly registering all the risky rows.
- handle and output the faulty datetime throwing exception from try-catch, but it's unlikely there are invalid datetime in the first place, and a little out of the scope of a mass conversion in a migration (would skip them anyways), should be somewhere else beforehand like an integrity check or so.
- make this all somehow reusable, for future eventual migrations
