### PR TITLE
[Bug]: Calling absolute document URL of Sites should not be possible

### LINKED ISSUE #14315: [Bug]: Calling absolute document URL of Sites should not be possible
### Expected behavior

It should not be possible to call absolute document URL, only calling site URLs

e.g https://demo.pimcore.com/Classic%20Cars%20Portal should redirect to 404 page or site home page. Calling document directly via absolute URL can cause problems as these requests are not in the site scope. 

### Actual behavior

It is possible to call absolute document URL e.g https://demo.pimcore.com/Classic%20Cars%20Portal which in this case leads to an error and can cause problems for other Sites as well. 

### Steps to reproduce

Call https://demo.pimcore.com/Classic%20Cars%20Portal

### PR DESCRIPTION
**Pull request by martineiber**
## Changes in this pull request  
Resolves #14315

### CODE REVIEW

File: lib/Routing/Dynamic/DocumentRouteHandler.php [hunk 1]
```diff
@@ -103,11 +105,21 @@ public function getRouteByName(string $name): ?DocumentRoute
     public function matchRequest(RouteCollection $collection, DynamicRequestContext $context): void
     {
         $document = Document::getByPath($context->getPath());
+        $site = $this->siteResolver->getSite($context->getRequest());
+
+        // If the request is not from a site and the document is part of a site
+        // or the ID of the requested site does not match the site where the document is located.
+        // Then we have to throw a NotFoundHttpException
+        if($document && !$context->getRequest()->get('pimcore_editmode')) {
```
Comment (brusch) [inline lib/Routing/Dynamic/DocumentRouteHandler.php]:
```suggestion
        if(!$site && $document && !$context->getRequest()->get('pimcore_editmode')) {
```

File: lib/Routing/Dynamic/DocumentRouteHandler.php [hunk 2]
```diff
@@ -103,11 +105,21 @@ public function getRouteByName(string $name): ?DocumentRoute
...
+            $siteIdOfDocument = Frontend::getSiteIdForDocument($document);
+            if(!$site && $siteIdOfDocument || ($site && ($site->getId() != $siteIdOfDocument))) {
```
Comment (brusch) [inline lib/Routing/Dynamic/DocumentRouteHandler.php]:
```suggestion
            if($siteIdOfDocument) {
```

File: lib/Tool/Frontend.php [hunk 3]
```diff
@@ -51,25 +53,69 @@ public static function isDocumentInCurrentSite(Document $document): bool
...
+
+    /**
+     * @return Site\Listing[]
+     */
+    private static function getFullSiteListing() : array
+    {
+        if (RuntimeCache::isRegistered(SELF::SITE_CACHE_KEY)) {
+            $sites = RuntimeCache::get(SELF::SITE_CACHE_KEY);
+        } else {
+            $sites = new Site\Listing();
```
Comment (brusch) [inline lib/Tool/Frontend.php:90]: I'd create and cache the following array here: 
```php
[
            '/root/path/of/site-one' => 123,
            '/path/to/second/site' => 123,
        ]
```

We can then iterate over this array in `getSiteIdForDocument()` and check with `str_starts_with()` if the document is within a site. That should be quite quick and generic. 

Using the `RuntimeCache` shouldn't be necessary anymore then.

**Review by brusch — CHANGES_REQUESTED** [review]

File: lib/Tool/Frontend.php (hunk 3 above)
Comment (martineiber) [reply lib/Tool/Frontend.php:90]: Done.
 
Now we need to make a database call in `getSiteForDocument()` to get the site object, since we only have the `id` in the cache. Would it make sense to cache the site object as well? 

Or is it an overhead since the cache should be flushed every time the object is updated.

Comment (brusch) [reply lib/Tool/Frontend.php:90]: @martineiber using `Site::getById()` is fine, it has a 2-level cache (runtime + core) build in 😉

File: lib/Tool/Frontend.php [hunk 4]
```diff
@@ -51,25 +52,49 @@ public static function isDocumentInCurrentSite(Document $document): bool
...
+        foreach ($siteMapping as $sitePath => $id) {
+            if (str_starts_with($document->getRealFullPath(), $sitePath)) {
+                return $id;
             }
         }
 
         return null;
     }
 
+    private static function getSiteMapping() : array
```
Comment (brusch) [inline lib/Tool/Frontend.php:78]: @martineiber can you please check how often this method get's called on a normal document request? If it's called more than once, we should implement `RuntimeCache` in addition to the normal cache as well.

Comment (martineiber) [reply lib/Tool/Frontend.php:78]: @brusch If a document with in a site is called, then the method will be called more than once. 
I've added the `RuntimeCache` as well.

File: lib/Routing/Dynamic/DocumentRouteHandler.php [hunk 5]
```diff
@@ -103,11 +105,21 @@ public function getRouteByName(string $name): ?DocumentRoute
     public function matchRequest(RouteCollection $collection, DynamicRequestContext $context): void
     {
         $document = Document::getByPath($context->getPath());
+        $site = $this->siteResolver->getSite($context->getRequest());
+
+        // If the request is not from a site and the document is part of a site
+        // or the ID of the requested site does not match the site where the document is located.
+        // Then we have to throw a NotFoundHttpException
+        if(!$site && $document && !$context->getRequest()->get('pimcore_editmode')) {
```
Comment (dvesh3) [inline lib/Routing/Dynamic/DocumentRouteHandler.php]: Maybe call `Tool::isFrontendRequestByAdmin()` instead of just checking for editmode. otherwise it broken for other features in admin 
image

**Review by dvesh3 — COMMENTED** [review]
Please add upgrade notes for the changed behavior.

File: doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md [hunk 6]
```diff
@@ -271,6 +271,7 @@ pimcore:
 - Moved implementation of `PimcoreBundleAdminSupportInterface` from `AbstractPimcoreBundle` to bundle classes.
     Moved `getJsPaths`, `getCssPaths`, `getEditmodeJsPaths` and `getEditmodeCssPaths` from `AbstractPimcoreBundle` to `BundleAdminSupportTrait`.
 - [Cache] Responses containing a header `Cache-Control: no-cache`, `Cache-Control: private` or `Cache-Control: no-store` will no longer be cached by the full page cache.
+- [Sites] Calling absolut path from a site is not possible anymore. If the absolut path is called, a 404 error will be returned instead.
```
Comment (dvesh3) [inline doc/23_Installation_and_Upgrade/09_Upgrade_Notes/README.md]:
```suggestion
- [Sites] Calling absolute path from a site is not possible anymore. If the absolute path is called, a 404 error will be returned instead.
```
🍹
