### PR TITLE
FIX vimeo and dailymotion video editables

### LINKED ISSUE #10152: [Bug]: Video Vimeo and Dailymotion not work
### Expected behavior

At Video-Output from Object Youtube works, but vimeo and dailymotion-ids produce an error

On the demopage at
 https://demo.pimcore.com/admin/login/deeplink?object_1121_object
i insert vimeolink, but the whole eventpages didn't work at:
https://demo.pimcore.com/en/Events

Also the documentation:
https://pimcore.com/docs/pimcore/current/Development_Documentation/Objects/Object_Classes/Data_Types/Video_Type.html

```
with this lines are not correct:
$video->type = $v->getType();
    $video->id = ($videoData instanceof Asset) ? $videoData->getId() : $videoData;
    $video->title = $v->getTitle();
    $video->description = $v->getDescription();
    if($v->getPoster()) {
        $video->poster = $v->getPoster()->getId();
}

```
Solution for this is like this:

```
//$videoData
$data['type'] = $v->getType();
$data['id'] = ($videoData instanceof Asset) ? $videoData->getId() : $videoData;
$data['title'] = $v->getTitle();
$data['description'] = $v->getDescription();
if($v->getPoster()) {
  $data['poster'] = $v->getPoster()->getId();
} else {
  $data['poster'] = '';
}
$video->setDataFromEditmode($data);
```

For working vimeo and dailymotion it is necessary to change code in:
/pimcore/models/Document/Editable/Video.php
in methodes getDailymotionCode() and getVimeoCode() you have to add a little but code:

```
isset($config['config']['clip']) && 
```
to this:
```
if (isset($config['config']['clip']) && is_array($config['config']['clip'])) {
                $clipConfig = $config['config']['clip'];
}
            $configurations = $clipConfig;
            if (array_key_exists('vimeo', $config) && is_array($config['vimeo'])) {
                $configurations = array_merge($clipConfig, $config['vimeo']);
            }
```
like in getYoutubeCode()

But in getHtml5Code() there is a problem too. There is no Error-Message but didn't work.
With one mpg-Video there is a problem on this line:
```
$duration = ceil($video->getDuration());
```
... because there is no duration in $video. With other Videofile there is no message, but video didn't start.

### Actual behavior

No error-message but only preview-image is visible, no working video

### Steps to reproduce

Perhaps on this page:
https://demo.pimcore.com/en/Events

on "Auto Fair Salzburg '19" I added an vimeo-video, but all links on this page didn't work

### LINKED ISSUE #10368: [Bug]: Video-Types throw error in debugmode but work in prod
### Expected behavior

Videos get rendered and displayed OR don't produce an error which freezes the document.

### Actual behavior

BE document stuck in "Please Wait"

### Steps to reproduce

1. Insert random Video Content Area 
2. Change Type to 'dailymotion' 
3. insert random Video ID (eg.: x84cbm1)
4. When in debugmode you get an error
When in prod-mode, the video gets displayed

I tested in Pimcore Demo where i manually changed to debugmode 

Also reproducible with normal Assets:
1. insert random Video Content Area
2. Type->Asset
3. Path->some nonsense
4. When in debugmode you get an error which freezes the document
When in prod-mode the video gets not displayed

Could you please answer why a video can be loaded and rendered in prod but will throw an error in dev?
This makes debugging super hard. 

To reproduce in pimcore demo, it was pretty difficult to change it to debugmode. But this was the only way i could make sure it's not due to my code.

### PR DESCRIPTION
**Pull request by BabovicT**
## Changes in this pull request  
Resolves #10368
Resolves #10152

### CODE REVIEW

File: models/Document/Editable/Video.php [hunk 1]
```diff
@@ -707,11 +707,11 @@ private function getDailymotionCode()
 
             $additional_params = '';
 
-            $clipConfig = is_array($config['config']['clip']) ? $config['config']['clip'] : [];
+            $clipConfig = isset($config['config']['clip']) && is_array($config['config']['clip']) ? $config['config']['clip'] : [];
```
Comment (dvesh3) [inline models/Document/Editable/Video.php:710]: @BabovicT could you please fix Vimeo as well in `getVimeoCode()` then we can close the PR https://github.com/pimcore/pimcore/pull/10182/files in favor of this...thanks!

**Comment by BabovicT** [comment]
@dvesh3 is this it or is there something more to be done?

**Comment by dvesh3** [comment]
> @dvesh3 is this it or is there something more to be done?

looks good to me. thanks!
