### PR TITLE
calculate delta for relations in every relational field-type to prevent deadlock

### LINKED ISSUE #13678: [Bug]: Deadlock on relations Table (again)
### Expected behavior

When running multiple workers to process async imports, the relations table should not lock. Reason for the lock is the `key`: `forward_lookup`.

### Actual behavior

it does lock.

### Steps to reproduce

Run multiple workers with imports. (create or update object)

```
*** (1) TRANSACTION:
TRANSACTION 572017002, ACTIVE 0 sec inserting
mysql tables in use 1, locked 1
LOCK WAIT 19 lock struct(s), heap size 1128, 8 row lock(s), undo log entries 10
MySQL thread id 3738690, OS thread handle 508, query id 894258846 20.71.67.44 pimcore_dev Update
INSERT INTO object_relations_as_standard (`dest_id`, `type`, `fieldname`, `index`, `src_id`, `ownertype`) VALUES ('530970', 'object', 'attributes', '1', '769190', 'object')
*** (1) WAITING FOR THIS LOCK TO BE GRANTED:
RECORD LOCKS space id 4090 page no 4679 n bits 656 index forward_lookup of table `pimcore_dev`.`object_relations_as_standard` trx id 572017002 lock_mode X insert intention waiting
Record lock, heap no 1 PHYSICAL RECORD: n_fields 1; compact format; info bits 0
 0: len 8; hex 73757072656d756d; asc supremum;;

*** (2) TRANSACTION:
TRANSACTION 572017005, ACTIVE 0 sec inserting
mysql tables in use 1, locked 1
20 lock struct(s), heap size 1128, 9 row lock(s), undo log entries 10
MySQL thread id 3738691, OS thread handle 4428, query id 894258867 20.71.67.44 pimcore_dev Update
INSERT INTO object_relations_as_standard (`dest_id`, `type`, `fieldname`, `index`, `src_id`, `ownertype`) VALUES ('530970', 'object', 'attributes', '1', '769191', 'object')
*** (2) HOLDS THE LOCK(S):
RECORD LOCKS space id 4090 page no 4679 n bits 656 index forward_lookup of table `pimcore_dev`.`object_relations_as_standard` trx id 572017005 lock_mode X
Record lock, heap no 1 PHYSICAL RECORD: n_fields 1; compact format; info bits 0
 0: len 8; hex 73757072656d756d; asc supremum;;

*** (2) WAITING FOR THIS LOCK TO BE GRANTED:
RECORD LOCKS space id 4090 page no 4679 n bits 656 index forward_lookup of table `pimcore_dev`.`object_relations_as_standard` trx id 572017005 lock_mode X insert intention waiting
Record lock, heap no 1 PHYSICAL RECORD: n_fields 1; compact format; info bits 0
 0: len 8; hex 73757072656d756d; asc supremum;;

```

### PR DESCRIPTION
**Pull request by dpfaffenbauer**
fixes #13678

This attempts to solve the deadlock issues on the relations_* table by calculating the delta per relational field-type and only execute what actually changed against the database.

### CODE REVIEW

**Comment by dpfaffenbauer** [comment]
@brusch @fashxp what do you think of this? this might solve the deadlock issue with relations and only does delta-updates of changed relations.

File: models/DataObject/ClassDefinition/Data/Relations/AbstractRelations.php [hunk 1]
```diff
@@ -121,30 +121,107 @@ public function save(Localizedfield|AbstractData|\Pimcore\Model\DataObject\Objec
...
+            $classId = $object->getClassId();
+        } elseif ($object instanceof AbstractData) {
+            $classId = $object->getObject()->getClassId();
+        } elseif ($object instanceof Localizedfield) {
+            $classId = $object->getObject()->getClassId();
+        } elseif ($object instanceof \Pimcore\Model\DataObject\Objectbrick\Data\AbstractData) {
+            $classId = $object->getObject()->getClassId();
+        } else {
+            throw new \Exception('Invalid object type');
+        }
```
Comment (jdreesen) [inline models/DataObject/ClassDefinition/Data/Relations/AbstractRelations.php]: What do you think about writing it like this?

```suggestion
        $classId = match (true) {
        	$object instanceof Concrete => $object->getClassId(),
        	$object instanceof AbstractData => $object->getObject()->getClassId(),
        	$object instanceof Localizedfield => $object->getObject()->getClassId(),
        	$object instanceof \Pimcore\Model\DataObject\Objectbrick\Data\AbstractData => $object->getObject()->getClassId(),
        	default => throw new \Exception('Invalid object type'),
        };
```

Comment (dpfaffenbauer) [reply models/DataObject/ClassDefinition/Data/Relations/AbstractRelations.php]: nice

**Comment by brusch** [comment]
@dpfaffenbauer not entirely through yet, but like the general idea 😍

**Comment by dpfaffenbauer** [comment]
@brusch what do you mean with not entirely through yet?

**Comment by brusch** [comment]
@dpfaffenbauer through the code changes  😉just had a quick look yet, not in detail.

**Comment by dpfaffenbauer** [comment]
@brusch gotcha, give it a good look and test and let me know if you have any questions or changes ;)

**Comment by dpfaffenbauer** [comment]
any update on this @brusch? Its been some time now

**Comment by brusch** [comment]
@dpfaffenbauer unfortunately not yet 😬 was debugging some other tricky bugs 😉

**Comment by dpfaffenbauer** [comment]
ping @brusch Its been a month now...

File: models/DataObject/Traits/ContextPersistenceTrait.php [hunk 2]
```diff
@@ -25,6 +25,65 @@
  */
 trait ContextPersistenceTrait
 {
+    protected function prepareMyCurrentRelations(
+        Localizedfield|AbstractData|\Pimcore\Model\DataObject\Objectbrick\Data\AbstractData|Concrete $object,
```
Comment (brusch) [inline models/DataObject/Traits/ContextPersistenceTrait.php]: Maybe we could consistently use `Objectbrick\Data\AbstractData` and `Fieldcollection\Data\AbstractData` in this file for better readability 😊

File: models/DataObject/Concrete.php [hunk 3]
```diff
@@ -664,6 +664,9 @@ public function save(array $parameters = []): static
 
         try {
             parent::save($parameters);
+            //Reset Relational data to force a reload
+            $this->__rawRelationData = null;
```
Comment (brusch) [inline models/DataObject/Concrete.php:670]: This line I'd even consider as a bug 🤔 
It seems that `__rawRelationData` is never cleared and it's also not excluded from caching. 
In practice it shouldn't matter, because cache is getting cleared on save, but still, no point including that into serialized data (cache, versioning, ...). 

I'll create a PR for that 😊

**Review by brusch — CHANGES_REQUESTED** [review]
General approach LGTM 😊, just a few more things: 
- Object bricks are missing, loosing data now, see here: 
https://github.com/pimcore/pimcore/blob/130fd27c8a15d3cceae18fb71abf02c33db7a1b7/models/DataObject/Objectbrick/Data/Dao.php#L85
- since this is a very critical component we need to cover this by unit tests, we have existing ones for field collections: 
https://github.com/pimcore/pimcore/blob/35c2b6ced02ac2814a0003a442c3e7eae093e1c1/tests/Model/Relations/FieldcollectionTest.php#L55 , but others a missing

File: models/DataObject/Concrete.php (hunk 3 above)
Comment (brusch) [reply models/DataObject/Concrete.php:670]: just for the records #16596 is the PR 😉

**Comment by dpfaffenbauer** [comment]
@brusch alright, I'll look at the bricks and add a test

**Comment by brusch** [comment]
@dpfaffenbauer Maybe this #16545 also needs to be considered - Thanks again! 😊

**Comment by dpfaffenbauer** [comment]
@brusch Objectbricks are now considered as well

**Comment by brusch** [comment]
@dpfaffenbauer cool, thanks a lot! 
One more thing, you've added unit tests for object bricks but not for relations in general and in the context of localized fields. Would be nice if you could add them as well. Thanks again!

**Comment by dpfaffenbauer** [comment]
@brusch I don't have any capacity to add this in the next weeks. So you either take this as is or we close it. It is not my responsability to add tests for the most important core feature of pimcore.

**Comment by dpfaffenbauer** [comment]
@brusch will this get merged anytime soon?

**Comment by brusch** [comment]
@dpfaffenbauer Unfortunately we have currently some other priorities, that's why we haven't found the time yet to add tests and we won't merge this PR without tests as it's quite critical (see earlier comments).

**Comment by dpfaffenbauer** [comment]
@brusch this is open since january 17....

File: models/DataObject/Concrete.php (hunk 3 above)
Comment (kingjia90) [inline models/DataObject/Concrete.php:670]:
```suggestion
```
could be removed, if it's fixed by #16596

File: models/DataObject/Concrete/Dao.php [hunk 4]
```diff
@@ -215,12 +215,6 @@ public function update(bool $isUpdate = null): void
             $condition = '(' . $condition . ' AND ownerType != "localizedfield" AND ownerType != "fieldcollection")';
         }
```
Comment (kingjia90) [inline models/DataObject/Concrete/Dao.php]: https://github.com/dpfaffenbauer/pimcore/blob/45c4d2a36927da5efaf49b0d4e6ccf132132da94/models/DataObject/Concrete/Dao.php#L206-L216

this part ($condition would be unused) seems not neccessary anymore

File: models/DataObject/Fieldcollection/Dao.php [hunk 5]
```diff
@@ -248,12 +248,20 @@ public function delete(DataObject\Concrete $object, bool $saveMode = false): arr
             }
         }
 
-        $where = "(ownertype = 'fieldcollection' AND " . Helper::quoteInto($this->db, 'ownername = ?', $this->model->getFieldname())
-            . ' AND ' . Helper::quoteInto($this->db, 'src_id = ?', $object->getId()) . ')';
-
-        // empty relation table
-        $this->db->executeStatement('DELETE FROM object_relations_' . $object->getClassId() . ' WHERE ' . $where);
-        $this->db->executeStatement('DELETE FROM object_relations_' . $object->getClassId() . ' WHERE ' . $whereLocalizedFields);
+        if (!$saveMode) {
```
Comment (kingjia90) [inline models/DataObject/Fieldcollection/Dao.php]:
```suggestion
```
this seems wrong, the relations would be not deleted when deleting the field collection group

File: models/DataObject/Fieldcollection/Dao.php [hunk 6]
```diff
@@ -248,12 +248,20 @@ public function delete(DataObject\Concrete $object, bool $saveMode = false): arr
...
+                    'ownername = ?',
+                    $this->model->getFieldname()
+                )
+                .' AND '.Helper::quoteInto($this->db, 'src_id = ?', $object->getId()).')';
+
+            // empty relation table
+            $this->db->executeStatement('DELETE FROM object_relations_'.$object->getClassId().' WHERE '.$where);
+            $this->db->executeStatement(
+                'DELETE FROM object_relations_'.$object->getClassId().' WHERE '.$whereLocalizedFields
+            );
```
Comment (kingjia90) [inline models/DataObject/Fieldcollection/Dao.php]:
```suggestion
            if ($hasLocalizedFields){
                  $this->db->executeStatement(
                      'DELETE FROM object_relations_'.$object->getClassId().' WHERE '.$whereLocalizedFields
                  );
            }
```
but i am not sure if is correct and why the former code looked like that (with some repetition), It probably needs to be refactored along 
https://github.com/pimcore/pimcore/pull/16482/files#diff-7011a9d08159e8735c4312cbc3c25f66574317e745300d8c913181bc55eb280cR245

File: models/DataObject/ClassDefinition/Data/Relations/AbstractRelations.php [hunk 7]
```diff
@@ -121,30 +121,104 @@ public function save(Localizedfield|AbstractData|\Pimcore\Model\DataObject\Objec
...
-                    // relation needs to be an array with src_id, dest_id, type, fieldname
-                    try {
-                        $db->insert('object_relations_' . $classId, Db\Helper::quoteDataIdentifiers($db, $relation));
-                    } catch (\Exception $e) {
-                        Logger::error('It seems that the relation ' . $relation['src_id'] . ' => ' . $relation['dest_id']
-                            . ' (fieldname: ' . $this->getName() . ') already exist -> please check immediately!');
-                        Logger::error((string)$e);
+                    if ($object instanceof Concrete) {
+                        $relation['ownername'] = '';  //default in db
+                        $relation['position'] = '0'; //default in db
```
Comment (kingjia90) [inline models/DataObject/ClassDefinition/Data/Relations/AbstractRelations.php:177]: The problematic code is not exactly here, but It seem it is not working when the relational field-type is under a Field Collection
sdvsdf

It would create all and remove all a the same time (`$newRelations` and `$removedRelations` with same row count).

See also the review comment below about ContextPersistenceTrait

File: models/DataObject/Traits/ContextPersistenceTrait.php [hunk 8]
```diff
@@ -25,6 +25,65 @@
...
+    ): array {
+        if ($object instanceof Concrete) {
+            $relations = $object->retrieveRelationData(['fieldname' => $this->getName(), 'ownertype' => 'object']);
+        } elseif ($object instanceof AbstractData) {
+            $relations = $object->getObject()->retrieveRelationData(
+                [
+                    'fieldname' => $this->getName(),
+                    'ownertype' => 'fieldcollection',
+                    'ownername' => $object->getFieldname(),
+                    'position' => $object->getIndex(),
```
Comment (kingjia90) [inline models/DataObject/Traits/ContextPersistenceTrait.php]: https://github.com/pimcore/pimcore/blob/291f133bc562a3985b216876197c2f4bb6601c91/models/DataObject/Fieldcollection/Data/AbstractData.php#L44-L47 wouldn't match and be flagged as existing entry because `position` is checked by `===` to strings

**Review by kingjia90 — CHANGES_REQUESTED** [review]
Thank you for your PR and your patience!

I've had a look and after an initial scan, looks good for basic/common usages, but i need some more time to cover all the more complex combinations, in the meanwhile, i already have some feedback/inputs.

File: models/DataObject/Concrete.php (hunk 3 above)
Comment (dpfaffenbauer) [reply models/DataObject/Concrete.php:670]: not yet merged, so I'll wait

File: models/DataObject/Concrete/Dao.php (hunk 4 above)
Comment (dpfaffenbauer) [reply models/DataObject/Concrete/Dao.php]: done

File: models/DataObject/Fieldcollection/Dao.php (hunk 5 above)
Comment (dpfaffenbauer) [reply models/DataObject/Fieldcollection/Dao.php]: right. This will never work for Fieldcollection in general. I reverted it and handle fieldcollection the way as it currently is.

File: models/DataObject/ClassDefinition/Data/Relations/AbstractRelations.php (hunk 7 above)
Comment (dpfaffenbauer) [reply models/DataObject/ClassDefinition/Data/Relations/AbstractRelations.php:177]: fixed by casting it to string

**Comment by dpfaffenbauer** [comment]
@kingjia90 I changed the PR according to your comments

File: models/DataObject/Fieldcollection/Dao.php [hunk 9]
```diff
@@ -143,9 +143,6 @@ public function load(DataObject\Concrete $object): array
      */
     public function delete(DataObject\Concrete $object, bool $saveMode = false): array
     {
-        // empty or create all relevant tables
-
-        /** @var DataObject\ClassDefinition\Data\Fieldcollections $fieldDef */
         $fieldDef = $object->getClass()->getFieldDefinition($this->model->getFieldname(), ['suppressEnrichment' => true]);
```
Comment (kingjia90) [inline models/DataObject/Fieldcollection/Dao.php:147]: to fix phpstan error, we might need to restore this line

```suggestion
        /** @var DataObject\ClassDefinition\Data\Fieldcollections $fieldDef */
        $fieldDef = $object->getClass()->getFieldDefinition($this->model->getFieldname(), ['suppressEnrichment' => true]);
```

Comment (dpfaffenbauer) [reply models/DataObject/Fieldcollection/Dao.php:147]: thanks @kingjia90. I was about to commit that later today ;)

File: models/DataObject/ClassDefinition/Data/Relations/AbstractRelations.php [hunk 10]
```diff
@@ -144,7 +164,89 @@ public function save(Localizedfield|AbstractData|\Pimcore\Model\DataObject\Objec
...
+
+                    //Index does not exist for OneToMany relations
+                    if (array_key_exists('index', $relation) && $relation['index'] !== $existingRelation['index']) {
+                        $updatedRelation = $relation;
+                        $updatedRelation['id'] = $existingRelation['id'];
+
+                        $updatedRelations[] = $updatedRelation;
+                    } else {
+                        $existingRelations[] = $relation;
+                    }
```
Comment (kingjia90) [inline models/DataObject/ClassDefinition/Data/Relations/AbstractRelations.php:208]:
```suggestion
        $removedRelations = [];
        //Updates can happen to the index
        $updatedRelations = [];

        foreach ($myNewRawRelations as $relation) {
            foreach ($myCurrentRawRelations as $existingRelation) {
                if ($relation['dest_id'] === $existingRelation['dest_id'] &&
                    $relation['type'] === $existingRelation['type'] &&
                    $relation['fieldname'] === $existingRelation['fieldname'] &&
                    $relation['ownertype'] === $existingRelation['ownertype'] &&
                    $relation['ownername'] === $existingRelation['ownername'] &&
                    $relation['position'] === $existingRelation['position']) {

                    //Index does not exist for OneToMany relations
                    if (array_key_exists('index', $relation) && $relation['index'] !== $existingRelation['index']) {
                        $updatedRelation = $relation;
                        $updatedRelation['id'] = $existingRelation['id'];

                        $updatedRelations[] = $updatedRelation;
                    }
```
`$existingRelations` has no any use, other than helping in debugging, maybe we should keep it but commented out? 😃

File: models/DataObject/ClassDefinition/Data/Relations/AbstractRelations.php [hunk 11]
```diff
@@ -144,7 +164,89 @@ public function save(Localizedfield|AbstractData|\Pimcore\Model\DataObject\Objec
...
+                    continue 2;
+                }
             }
+
+            $newRelations[] = $relation;
+        }
+
+        foreach ($myCurrentRawRelations as $existingRelation) {
+            foreach ($myNewRawRelations as $relation) {
```
Comment (kingjia90) [inline models/DataObject/ClassDefinition/Data/Relations/AbstractRelations.php:217]: what about if we after `$updatedRelations[] = $updatedRelation;` and `$existingRelations` we unset the found relation from these 2 arrays? so it would reduce the array length for these loops when performed here

File: models/DataObject/ClassDefinition/Data/Relations/AbstractRelations.php [hunk 12]
```diff
@@ -121,21 +121,41 @@ public function save(Localizedfield|AbstractData|\Pimcore\Model\DataObject\Objec
...
         if ($data !== null) {
             $relations = $this->prepareDataForPersistence($data, $object, $params);
 
-            if (is_array($relations) && !empty($relations)) {
-                $db = Db::get();
-
+            /**
+             * FieldCollection don't support delta Updates of relations
+             * A FieldCollection Entry does not have a unique ID,
+             * so we need to delete all relations and insert them again
```
Comment (kingjia90) [inline models/DataObject/ClassDefinition/Data/Relations/AbstractRelations.php:145]: That's unfortunate, i feel that the FC current approach(before PR) itself could be a dead-lock factor 😿 

Leaving some notes, maybe somebody has some ideas.

In short, when swapping or removing collections/groups, the delta calculator get confused:
Screenshot from 2024-05-08 18-48-56
since we check by collection per collection, if we move the collection with 1 item down (swap order 🔽 crossed in red ), it would calculate and determine that 4 rows with `position=0` are added and 1 is removed, and for the second collection that 1 item  is added and 4 removed, resulting in 10 queries (minus any same item in both collections), instead of total of 5 updates ( `position` 0 to 1 and viceversa).

So far, it always removed everything and re-saved, in this resulting in [2 "big" and deadlockish remove queries](https://github.com/pimcore/pimcore/blob/196d996ac40726fff3e6067fe9d66b4f816e5729/models/DataObject/Fieldcollection/Dao.php#L260-L261) plus 5 inserts, even when there are no relevant changes at all (as soon as it is minimally "dirty").

The thing is, the former attempt in this PR was working "almost fine" for removing,adding elements and moving the order(`index`) within the same collection(aka `position` column). 

An idea would be for FCs to create the same delta calculator but *reversed* and without strictly limit to position: 
1. loop in loop and unsets all the rows that are the same before and after save (unchanged rows).
2. A second loop in loop that check the existing ones without considering the position and set a part for potential update (NB: the ones with the same position are already out from the first check) and unset these for next loop.
3. A third loop, here the remaining are either small updates (eg.index change within the same position/group), addition or deletion.

Could it work or would it be a loop hell?

**Review by kingjia90 — CHANGES_REQUESTED** [review]

File: models/DataObject/ClassDefinition/Data/Relations/AbstractRelations.php (hunk 12 above)
Comment (kingjia90) [reply models/DataObject/ClassDefinition/Data/Relations/AbstractRelations.php:145]: - in the case of the example above, it would basically stop at second loop in loop.  (4 updates)
- in the case we swap the index within the same collection, first loop in loop strips all beside the 2 affected rows. (2 updates)
- In the case we add the same row (Le Mans) in the second group and swap, the Le Mans row would be stripped out on the first loop in loop (leave unchanged, exists in both), the second loop would update the remaining 4 to change to position 0,  and third loop in loop, would add 1 Le Mans to collection in position 1.   (4 updates, 1 addition, 0 removal)
- In the case we delete 3 rows from collection 2 (pos:1) and add 2 to collection 1, the first and second loop in loop would do nothing and it would perform as expected (3 removals and 2 additions)
- In the case we delete 3 rows from collection 2 (pos:1) and add 2 to collection 1, with 1 same row in this operation, the first loop would do nothing, the second one would update by moving the "same row" to the right position to where it's supposedly added, instead of delete + add  (2 removals and 1 update and 1 addition)

File: models/DataObject/ClassDefinition/Data/Relations/AbstractRelations.php [hunk 13]
```diff
@@ -144,7 +164,89 @@ public function save(Localizedfield|AbstractData|\Pimcore\Model\DataObject\Objec
...
+                    $relation['position'] === $existingRelation['position']) {
+                    continue 2;
+                }
+            }
+
+            $removedRelations[] = $existingRelation;
+        }
+
+        //Nothing changed, no need to update
+        if (empty($updatedRelations) && empty($newRelations) && empty($removedRelations)) {
```
Comment (kingjia90) [inline models/DataObject/ClassDefinition/Data/Relations/AbstractRelations.php:232]: I'd suggest to refactor and move the part above this in a separate method (eg. `computeChanges`, `calculateDelta`, `commit`?) that returns a multidimensional array, it would useful especially for automated testing purposes, we could then check if the behavior is followed and assert how many rows are planned to be inserted,updated,removed, kept at this step

File: models/DataObject/Concrete.php (hunk 3 above)
Comment (kingjia90) [reply models/DataObject/Concrete.php:670]: I have just merged that mentioned PR in `11.2` and is upmerged into `11.x`, please pull the latest `11.x` in this branch

File: models/DataObject/ClassDefinition/Data/Relations/AbstractRelations.php (hunk 12 above)
Comment (kingjia90) [reply models/DataObject/ClassDefinition/Data/Relations/AbstractRelations.php:145]: @dpfaffenbauer Beside this point, could you check the other unresolved inputs? Then it would LGTM and ready to be merged while i would try the approach proposed above to see if it works in a new branch/PR focusing the field collections
Thank you in advance!

**Comment by markus-moser** [comment]
@dpfaffenbauer Could you please resolve the conflict?

@kingjia90 Please let's merge the PR after the conflict is resolved and please add as discussed your improvement ideas to a separate PR afterwards, thanks!

**Review by kingjia90 — APPROVED** [review]

**Comment by dpfaffenbauer** [comment]
@markus-moser conflict is resolved

File: models/DataObject/Concrete.php (hunk 3 above)
Comment (kingjia90) [reply models/DataObject/Concrete.php:670]: Mhhh, i've tried to apply the removal in https://github.com/pimcore/pimcore/pull/17097 but tests started failing and went back to [green](https://github.com/pimcore/pimcore/pull/17097/commits/5d78720aabab64bab6a670afe0a0da6d5c44c03a) by reverting these 2 lines
@brusch https://github.com/pimcore/pimcore/pull/16596 seems didn't directly resolve this or is there anything more to consider in the tests that i may be missing?

File: models/DataObject/ClassDefinition/Data/Relations/AbstractRelations.php (hunk 11 above)
Comment (kingjia90) [reply models/DataObject/ClassDefinition/Data/Relations/AbstractRelations.php:217]: Resolved: https://github.com/pimcore/pimcore/pull/17097/files#diff-70ce41661e87c5fc6a8563bfd4137c6e12c5400c06bee0752b0fcdd416b910f6R194-R223 may work just fine, so reduced from 4 loops to 2 loops
