### PR TITLE
[Bug]: PHP API does not validate the objectbrick definition key (or not as in the javascript)

### LINKED ISSUE #14550: [Bug]: PHP API does not validate the objectbrick definition key (or not as in the javascript)
### Expected behavior

Not being able to create object brick class definition trough PHP API with name catalog_product.

### Actual behavior

Being able to create object brick class definition named catalog_product.

### Steps to reproduce

Use custom PHP code to create object brick definition and use the `setKey` method with value `catalog_product`.
EG:
```
$brickDef = new \Pimcore\Model\DataObject\Objectbrick\Definition();
$brickDef->setKey($key);
// ... set whatever else is required for a definition to get saved, and then save:
$brickDef->save();
```

PS: _pimcore.object.objectbrick.addFieldComplete_ here we have the following regex validation:
```
var isValidName = /^[a-zA-Z][a-zA-Z0-9]*$/;
```
which seems is not available in the PHP API.

This can result in bad development experience.
In my case I understood there is a problem by running the maintenance command manually with `-vv` to verify all tasks are fine, then I noticed these problems:

```
17:55:02 INFO      [app] Starting job with ID cleanupBrickTables ["id" => "cleanupBrickTables"]
17:55:02 ERROR     [app] Brick 'catalog' not found. Please check table object_brick_store_catalog_category_name_1
17:55:02 ERROR     [app] Brick 'catalog' not found. Please check table object_brick_store_catalog_category_url_1
17:55:02 ERROR     [app] Brick 'catalog' not found. Please check table object_brick_store_catalog_product_aero_product_type_1
17:55:02 ERROR     [app] Brick 'catalog' not found. Please check table object_brick_store_catalog_product_attribute_set_1
... a lot more of that type
```
this lead me to believe that it is very likely I have created bricks with unsupported key/name, which turned to be true.

### PR DESCRIPTION
**Pull request by mcop1**
Resolves #14550

### CODE REVIEW

File: models/DataObject/Fieldcollection/Definition.php [hunk 1]
```diff
@@ -288,4 +296,12 @@ protected function getInfoDocBlock(): string
 
         return $cd;
     }
+
+    /**
+     * @return bool
+     */
+    public function isForbiddenName()
```
Comment (mcop1) [inline models/DataObject/Fieldcollection/Definition.php]:
```suggestion

    public function isForbiddenName(): bool
```
