### PR TITLE
[Bug]: env variable PIMCORE_CLASS_DEFINITION_DIRECTORY causes double loading

### LINKED ISSUE #17938: [Bug]: env variable PIMCORE_CLASS_DEFINITION_DIRECTORY causes double loading
### Pimcore version

11.5

### Steps to reproduce

When using the `PIMCORE_CLASS_DEFINITION_DIRECTORY` and set to the `config/pimcore/classes` it seems that pimcore loads some stuff twice which leads to

 Compile Error: Cannot redeclare 

We should look into it.

### Actual Behavior

When using the `PIMCORE_CLASS_DEFINITION_DIRECTORY` and set to the `config/pimcore/classes` it seems that pimcore loads some stuff twice which leads to

### Expected Behavior

When using the `PIMCORE_CLASS_DEFINITION_DIRECTORY` and set to the `config/pimcore/classes` it pimcore should not load it twice

### PR DESCRIPTION
**Pull request by robertSt7**
resolves #17938

### CODE REVIEW

**Comment by robertSt7** [comment]
@fashxp @kingjia90 @bluvulture Could this be a possible fix for https://github.com/pimcore/pimcore/issues/17938 ?

File: models/DataObject/Objectbrick/Definition/Listing.php [hunk 1]
```diff
@@ -55,14 +55,23 @@ public function loadNames(): array
...
 
         foreach ($objectBricksFolders as $objectBricksFolder) {
             $files = glob($objectBricksFolder . '/*.php');
             foreach ($files as $file) {
-                $filenames[] = $file;
+                $realFile = realpath($file);
+                if (!isset($loadedFiles[$realFile])) {
+                    $loadedFiles[$realFile] = true;
+                    $filenames[] = $file;
+                }
```
Comment (kingjia90) [inline models/DataObject/Objectbrick/Definition/Listing.php:71]: Not entirely sure if it resolves the problem, as i couldn't reproduce, but just wanted to refactor to something like

```
foreach ($objectBricksFolders as $objectBricksFolder) {
    $files = glob($objectBricksFolder . '/*.php');
    foreach ($files as $file) {
        $realFile = realpath($file);
        if ($realFile) {
            $filenames[] = $realFile;
        }
    }
}

return array_unique($filenames);
```

this way we don't need the `$loadedFiles` array  and also the returned array has all real paths, which should be avoiding us to do any realpath check later on, wdyt?

**Review by kingjia90 — CHANGES_REQUESTED** [review]
LGTM, just a micro-optimization

File: models/DataObject/Objectbrick/Definition/Listing.php (hunk 1 above)
Comment (robertSt7) [reply models/DataObject/Objectbrick/Definition/Listing.php:71]: @kingjia90 done

File: bundles/CoreBundle/src/Command/ClassesDefinitionsBuildCommand.php [hunk 2]
```diff
@@ -52,12 +52,25 @@ protected function execute(InputInterface $input, OutputInterface $output): int
...
             $files = glob($objectClassesFolder.'/*.php');
 
             foreach ($files as $file) {
+                $realFile = realpath($file);
+
+                if (isset($includedFiles[$realFile])) {
+                    continue;
+                }
+
+                $includedFiles[$realFile] = true;
```
Comment (kingjia90) [inline bundles/CoreBundle/src/Command/ClassesDefinitionsBuildCommand.php:73]: there's a potential edge case that `include` temporarily fails (race conditions or filesystem issues), and returns `false`, i'd like to suggest to make it something like
```
$class = include $realFile;
if ($class){
    $includedFiles[$realFile] = true;
    $this->classDumper->dumpPHPClasses($class);
}
```
by doing this way, it may retry and still not double loading, but that has to be multiple duplicate entry in the `$files` which is already an edge case itself or unwanted scenario.

Additionally, `$includedFiles` would be more precise on what is actually included

Comment (kingjia90) [reply bundles/CoreBundle/src/Command/ClassesDefinitionsBuildCommand.php:73]: oh wait, it would need to be suppressed error like @include otherwise it fatally crashes , nevermind, i guess we don't expect (yet?) )that scenario at all to be implicitly handled
