### PR TITLE
[Pimcore X][ClassDefinition] quantityValue unit selection broken

### LINKED ISSUE #8974: [Pimcore X][ClassDefinition] quantityValue unit selection broken
### Expected behavior
'Default unit' dropdown field and 'Valid units'-Field are populated with existing units.
### Actual behavior
Both fields are empty.

### Steps to reproduce
Create Class with quantityValue and try to select default unit and valid units.

### PR DESCRIPTION
**Pull request by weisswurstkanone**
resolves #8974

### CODE REVIEW

File: bundles/AdminBundle/Controller/Admin/DataObject/QuantityValueController.php [hunk 1]
```diff
@@ -184,8 +184,9 @@ public function unitListAction(Request $request)
             $list->setCondition('id IN (' . $string . ')');
         }
 
+        $result = [];
         $units = $list->getUnits();
-        foreach ($units as $unit) {
+        foreach ($units as &$unit) {
```
Comment (jdreesen) [inline bundles/AdminBundle/Controller/Admin/DataObject/QuantityValueController.php:189]: Why the reference?
