### PR TITLE
[DataObject Tree] Allow expand and collapse on expandable property 

### LINKED ISSUE #12089: Do not show expand/collapse children on leaf element
### Expected behavior

This button is not supposed to appear on elements that have no children (leaf)
image
image

### Actual behavior

The button appears

### Steps to reproduce

1. Right click on leaf (no children) tree item.
2. Go to Advanced -> Collapse Children

Related to https://github.com/pimcore/pimcore/pull/11908

### PR DESCRIPTION
**Pull request by dvesh3**
## Changes in this pull request  
Resolves #12089

### CODE REVIEW

File: bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php [hunk 1]
```diff
@@ -303,8 +303,8 @@ protected function getTreeNodeConfig($element): array
 
         if ($tmpObject['leaf']) {
             $tmpObject['expandable'] = false;
+            $tmpObject['leaf'] = false; //this is required to allow drag&drop
```
Comment (dvesh3) [inline bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php:306]: we have to use this due to ExtJS limitation, which doesn't allow drag&drop on leaf nodes.
