### PR TITLE
[Bug]: Can't save Objects of Advanced Many To Many Object Relation

### LINKED ISSUE #14129: [Bug]: Can't save Objects of Advanced Many To Many Object Relation
### Expected behavior

Objects will be saved

### Actual behavior

Objects are gone after refresh

### Steps to reproduce

- Create an Object with an Advanced Many To Many Object Relation
- Try to select and save some Objects
- Refresh the Object

### PR DESCRIPTION
**Pull request by lukmzig**
## Changes in this pull request  
Resolves #14129

### CODE REVIEW

File: bundles/AdminBundle/Resources/public/js/pimcore/object/classes/class.js [hunk 1]
```diff
@@ -1391,6 +1388,15 @@ pimcore.object.classes.klass = Class.create({
                     fieldValidation = node.data.editor.isValid();
                 }
 
+                if (fieldValidation && data.fieldtype === 'advancedManyToManyObjectRelation') {
```
Comment (fashxp) [inline bundles/AdminBundle/Resources/public/js/pimcore/object/classes/class.js]: can we find a more generic implementation here so that  `data.fieldtype === 'advancedManyToManyObjectRelation'` is not necessary and `class.js`  does not need to know anything about the available types?

**Review by fashxp — CHANGES_REQUESTED** [review]
