### PR TITLE
Don't roll back transaction if there is an error with moving thumbnails.

### LINKED ISSUE #18179: Don't Rollback Asset Move Transaction if Thumbnail Move Fails
> @brusch Looking #17850 A few issue I am seeing:
> 1. [If the the relocating of the thumbnails errors, the transaction gets rolled back but the main files have still been moved](https://github.com/pimcore/pimcore/blob/6c507959db15a9fc26f7a746cd286dbf0f7dc4ec/models/Asset.php#L537). I am not sure we want to fail if thumbnails can't be moved
>  

 _Originally posted by @cancan101 in [#17534](https://github.com/pimcore/pimcore/issues/17534#issuecomment-2707267851)_

### PR DESCRIPTION
**Pull request by cancan101**
## Changes in this pull request  
Resolves #18179

## Additional info
@brusch

### CODE REVIEW

File: models/Asset.php [hunk 1]
```diff
@@ -1689,6 +1695,9 @@ private function updateChildPaths(FilesystemOperator $storage, string $oldPath,
 
             $storage->deleteDirectory($oldPath);
         } catch (UnableToMoveFile $e) {
+            if ($skipError) {
```
Comment (cancan101) [inline models/Asset.php:1698]: alternatively we could just catch the `UnableToMoveFile` when trying to move the initial file and just continue trying to move files in the case of thumbnails:
```php
    private function updateChildPaths(
        FilesystemOperator $storage,
        string $oldPath,
        ?string $newPath = null,
        bool $skipError = false
    ): void {
        if ($newPath === null) {
            $newPath = $this->getRealFullPath();
        }

        try {
            $movedFiles = [];
            $children = $storage->listContents($oldPath, true);
            foreach ($children as $child) {
                if ($child['type'] === 'file') {
                    $src  = $child['path'];
                    $dest = str_replace($oldPath, $newPath, '/' . $src);
                    try {
                        $storage->move($src, $dest);
                    } catch (UnableToMoveFile $e) {
                        if ($skipError) { continue; }
                        throw $e;
                    }
                    $movedFiles[$dest] = $src;
                }
            }

            $storage->deleteDirectory($oldPath);
        } catch (UnableToMoveFile $e) {
            // rollback moved files
            foreach ($movedFiles as $src => $dest) {
                $storage->move($src, $dest);
            }

            // trigger database rollback
            throw $e;
        }
    }
```
