### PR TITLE
[Classification Store] Inheritance not working for PHP API

### LINKED ISSUE #14367: [Classification Store] Inheritance not working for PHP API
### Expected behavior

`getGroups()`, `getItems()` and other methods of `Pimcore\Model\DataObject\ClassificationStore` should support inheritance.

### Actual behavior

Only if a data field is filled a record in `object_classificationstore_groups_<class id>` gets added. If the classification store is completely inherited it gets shown correctly in the backend. But when using PHP API function `getGroups()` returns an emtpy array.

### Steps to reproduce

1. Create classification store with some groups and fields
2. Create class `Abc`, enable inheritance, add classification store field `classificationStore`.
3. Create object `/parent`, add classification store group and set some field values
4. Create object `/parent/child`

In backend you see the inherited fields.

With PHP script:
```php
$object = \Pimcore\Model\DataObject\Abc::getByPath('/parent/child');
var_dump($object->getClassificationStore()->getGroups()); // returns []
```

Similar issue like #6447 - there it was referenced to use `getLocalizedKeyValue()` which supports inheritance. This is correct but how to get all assigned groups of an object including the inherited ones?

### PR DESCRIPTION
**Pull request by robertSt7**
resolves #14367

### CODE REVIEW

File: models/DataObject/Classificationstore.php [hunk 1]
```diff
@@ -496,19 +510,38 @@ public function setGroupCollectionMapping($groupId = null, $collectionId = null)
...
+                if ($fd instanceof Model\DataObject\ClassDefinition\Data\Classificationstore) {
+                    $getter = 'get' . ucfirst($key);
+                    $groups = array_merge(Classificationstore::getActiveGroupsWithConfig($parent->$getter()), $groups);
+                }
+            }
+            $object = $parent;
+        }
+
+        return $groups;
+    }
```
Comment (lukmzig) [inline models/DataObject/Classificationstore.php]: Hi @robertSt7, 
I would suggest that this would be more readable
 
    ($parent = Service::hasInheritableParentObject($object)) !== null)
 
Also, as most of this code is same as in lines 470 - 484 what do you think about creating a private method and deciding with param for example how to build the final array to minimize redundancy? Something like

    private function getInheritedData(array $groups, bool $merge = false)
    {
        $object = $this->getObject();
        while (($parent = Service::hasInheritableParentObject($object)) !== null) {
            $fieldDefintions = $parent->getClass()->getFieldDefinitions();
            foreach ($fieldDefintions as $key => $fd) {
                if($fd instanceof Model\DataObject\ClassDefinition\Data\Classificationstore){
                    $getter = 'get' . ucfirst($key);
                    if ($merge) {
                        $groups = array_merge(Classificationstore::getActiveGroupsWithConfig($parent->$getter()), $groups);
                    } else {
                        $groups = $groups + $parent->$getter()->groupCollectionMapping;
                    }

                }
            }

            $object = $parent;
        }

        return $groups;
    }

Comment (robertSt7) [reply models/DataObject/Classificationstore.php]: @lukmzig Done

**Comment by lukmzig** [comment]
Hi @robertSt7 ,
`getGroups()` method looks good now and is returning inherited values. 
However, method `getItems` which was also mentioned in the issue is still returning only empty array (is not returning inherited values). Should this be fixed as well? Can you have a look?

**Comment by flamadrid-jsmdg** [comment]
@lukmzig @robertSt7 , I think this PR is breaking something else related to inherited flag on the metadata that is created within
_\Pimcore\Model\DataObject\ClassDefinition\Data\Classificationstore::doGetDataForEditMode_
(Or perhaps the PR is incomplete)
In that function the first call to $data->getItems() will bring the values from the parent, but leaving the inheritance flag set to false because we are still in level 1
`$metaData[$language][$groupId][$keyId] = ['inherited' => $level > 1, 'objectid' => $object->getId()];`
In turn, in the UI the form looks like the fields are not inherited when they really are.

**Comment by NiklasBr** [comment]
@flamadrid-jsmdg did you figure out what the issue is?

**Comment by flamadrid-jsmdg** [comment]
@NiklasBr I'm don't know much the logic about classification store and its moving parts but after debugging it seems that the method doGetDataForEditMode (with the changes in this PR) get the values in the first go, so it does not look to the parent. That is because getItems fetches already the value from the parent with this new logic, that causes the metadata in that function to have the key "inherited" set to false. That causes the UI show this values as would be set on the child rather than coming from the parent. That is the problem I see, not sure if this affects other parts.
When the dataobject is in draft, so is not published, the values appears correctly displayed (greyed-out), however as soon as the object is publish appear as below:

This is how the child look (those values are inherited not specific for the child)
image

**Comment by lukmzig** [comment]
@flamadrid-jsmdg thank you very much for reporting about these problems. I created a new issue https://github.com/pimcore/pimcore/issues/14874 based on the information which you provided and we will look into this.

**Comment by flamadrid-jsmdg** [comment]
@lukmzig thanks a lot!
