### PR TITLE
[Thumbnails] Add width, height and filesize to the cache

### LINKED ISSUE #12055: [Bug]: Pimcore serving deferred thumbnail URL even though the thumbnail exists (Azure Storage used)
### Expected behavior

I have assets set up like this:

```yaml
flysystem:
    storages:
        pimcore.thumbnail.storage:
            adapter: 'flysystem.adapter.azure.thumbnail'
            visibility: public

pimcore:
    assets:
        frontend_prefixes:
            source: 'https://storage.example.com/asset'
            thumbnail: 'https://storage.example.com/thumbnail'
```

And it works, the files get created in the correct, expected place, etc.

The issue is, the `\Pimcore\Model\Asset\Image\Thumbnail::getPath` seems to return a deferred URL instead of the storage (static file, with the frontend prefix) quite often, even though the image exists on the remote storage (using Azure Blob Storage).

What's more, it seems the request then sometimes actually crops and writes over the existing file in the storage, meaning it can take quite a long time, all of which unnecessary.

### Actual behavior

Even though the thumbnail exists in storage, the deferred (crop on demand) URL version is generated.

### Steps to reproduce

The static URL version gets generated if the thumbnail exists.

### LINKED ISSUE #12057: [Bug]: \Pimcore\Model\Asset\Thumbnail\ImageThumbnailTrait::getDimensions is reading dimensions from file every time
### Expected behavior

With a remote storage, reading remote files just to find out the thumbnail width / height is suboptimal. The asset cache could cache these values.

### Actual behavior

The values are read from the file which is pulled from remote storage.

### Steps to reproduce

1. have a remote storage for thumbnails set up
2. call `\Pimcore\Twig\Extension\ImageThumbnailExtension::getImageThumbnailHtml`
3. `\Pimcore\Model\Asset\Thumbnail\ImageThumbnailTrait::readDimensionsFromFile` is triggered, which pulls the remote file and reads width / height directly from it

This also applies to filesize, maybe MIME type?

### PR DESCRIPTION
**Pull request by brusch**
follow up to #12414 from @dkarlovi (🍒-picked & squashed commits from there, keeping the author) 

resolves #12057 
resolves #12055

### CODE REVIEW

File: bundles/CoreBundle/Command/ThumbnailsImageCommand.php [hunk 1]
```diff
@@ -182,17 +182,12 @@ protected function runSingleCommand(string $item, InputInterface $input, OutputI
             $thumbnail = $image->getThumbnail($thumbnailConfig);
             $path = $thumbnail->getPath(false);
 
-            // triggers fetching the thumbnail info and updating the asset cache table
-            $dimensions = $thumbnail->getDimensions();
```
Comment (dkarlovi) [inline bundles/CoreBundle/Command/ThumbnailsImageCommand.php]: Note: this updates the thumbnail cache when running the thumbnail generator, I'm not sure it's dead code. Updating the cache is required to fix #12055.

Comment (dkarlovi) [reply bundles/CoreBundle/Command/ThumbnailsImageCommand.php]: See https://github.com/pimcore/pimcore/pull/12056#issuecomment-1120870522

Comment (brusch) [reply bundles/CoreBundle/Command/ThumbnailsImageCommand.php]: Yeah, that could be useful in case you have inconsistent data in the cache (missing width, height, filesize)  ... it doesn't hurt, so yes, we can keep that.

Comment (dkarlovi) [reply bundles/CoreBundle/Command/ThumbnailsImageCommand.php]: The issue with #12055 is that otherwise you can't fix it without clearing the cache table IIRC.

**Review by aashan10 — APPROVED** [review]

**Comment by dkarlovi** [comment]
Yay! \o/ Thanks for your help with this @brusch.

**Comment by BlackbitDevs** [comment]
@brusch The migration class / file name is wrong, it is for the year 2202. But we cannot simply rename it because this may have been already executed in some systems and then would lead to a doctrine notice. Perhaps keep the wrongly named migration but make it do nothing - and then create a renamed one which contains the actual logic. Otherwise, when we keep it as is, it will lead to wrong migration execution order as soon as there will be a migration which relies on the changes of this migration.

**Comment by brusch** [comment]
@BlackbitNeueMedien Is there an actual problem if we just keep the wrong filename?

**Comment by BlackbitDevs** [comment]
Not now but when a new migration will get created and for example be named `Version20220907000000`, this will be executed before the `Version22020614115124` if none of the migrations has been executed on the given Pimcore system before (because Doctrine executes them in ascending order). But it the `Version22020614115124` has already been executed, the new migration will be executed afterwards (because already executed migrations will not get executed again).
So the order of execution differs if you have installed Pimcore 10.5 before (which includes `Version22020614115124`) or not - and if the new migration relies on changes made in `Version22020614115124`, there will be errors.
