### PR TITLE
[Bug]: TestDataHelper doesn´t respect localizedFields in assertIsEqua…

### LINKED ISSUE #13868: [Bug]: `TestDataHelper` doesn´t respect `localizedFields` in `assertIsEqual` method
### Expected behavior

Should respect localizedFields

### Actual behavior

Returns `null`

### Steps to reproduce

Execute testcase `testLocalizedInput`

Needed for testcases in #13853

### PR DESCRIPTION
**Pull request by mcop1**
Resolves #13868

### CODE REVIEW

File: tests/_support/Helper/DataType/TestDataHelper.php [hunk 1]
```diff
@@ -105,6 +106,23 @@ public function assertCountry(Concrete $object, $field, $seed = 1)
         $this->assertEquals($expected, $value);
     }
 
+    /**
+     * @param Concrete $object
+     * @param string $field
+     * @return Data|null
+     */
+    public function getFieldDefinition(Concrete $object, string $field): ?Data {
```
Comment (blankse) [inline tests/_support/Helper/DataType/TestDataHelper.php]:
```suggestion
    public function getFieldDefinition(Concrete $object, string $field): ?Data
    {
```

File: tests/_support/Helper/DataType/TestDataHelper.php [hunk 2]
```diff
@@ -114,12 +132,28 @@ public function assertCountry(Concrete $object, $field, $seed = 1)
...
+
+    /**
+     * @param Concrete $object
+     * @param string $field
+     * @param mixed $expected
+     * @param mixed $value
+     * @return void
+     */
+    public function assertIsNotEqual(Concrete $object, string $field, mixed $expected, mixed $value): void
+    {
```
Comment (blankse) [inline tests/_support/Helper/DataType/TestDataHelper.php]:
```suggestion
    public function assertIsNotEqual(Concrete $object, string $field, mixed $expected, mixed $value): void
    {
```

**Review by blankse — CHANGES_REQUESTED** [review]
No redundant php docs

**Review by fashxp — APPROVED** [review]
