### PR TITLE
[SentMails] Fix document reference in sent email logs

### LINKED ISSUE #10354: [Bug][SentMails] Do not appear in sent mails of mail document
### Expected behavior

do appear in sent mails list of mail document

image

### Actual behavior

only appear in global list

### Steps to reproduce

send document mail... e.g. for demo
```
        $params = [
            'customerId' => 1018,
            'tokenLink' => 'fooo'
        ];

        $mail = new \Pimcore\Mail(['document' => '/en/mails/password-recovery', 'params' => $params]);
        $mail->addTo('YOUR_MAIL_ADDRESS');
        $mail->send();
```

### PR DESCRIPTION
**Pull request by dvesh3**
## Changes in this pull request  
Resolves #10354

### CODE REVIEW

File: lib/Mail.php [hunk 1]
```diff
@@ -50,6 +50,13 @@ class Mail extends Email
      */
     private $document;
 
+    /**
+     * Contains the email document Id
+     *
+     * @var int|null
+     */
+    private $documentId;
```
Comment (brusch) [inline lib/Mail.php]:
```suggestion
    private ?int $documentId = null;
```

**Review by brusch — CHANGES_REQUESTED** [review]
