### PR TITLE
Fix: Converting Page to Email or Snippet

### LINKED ISSUE #259: [Bug]: Converting Page to Email or Snippet
follow up https://github.com/pimcore/admin-ui-classic-bundle/pull/255

### PR DESCRIPTION
**Pull request by blankse**
## Changes in this pull request  
Resolves https://github.com/pimcore/admin-ui-classic-bundle/issues/259

`Pimcore\Model\Document\PageSnippet::setVersions(): Argument #1 ($versions) must be of type array, null given, called in /var/www/html/vendor/pimcore/pimcore/lib/Model/AbstractModel.php on line 188`

### <samp>🤖 Generated by Copilot at 51a13c6</samp>

This pull request improves the PHPDoc comments of the `PageSnippet` class to reflect fluent interface and nullable types. This enhances the code readability and fixes a null version bug.

### <samp>🤖 Generated by Copilot at 51a13c6</samp>

> _`PageSnippet` of doom, reveal your secrets_
> _Fluent interface, chain of darkness_
> _Nullable types, the void awaits_
> _PHPDoc comments, the only salvation_

### <samp>🤖 Generated by Copilot at 51a13c6</samp>

*  Add PHPDoc comments to several methods of the `PageSnippet` class to indicate fluent interface ([link](https://github.com/pimcore/pimcore/pull/15910/files?diff=unified&w=0#diff-af590f2e28178b47df6034df5b2fa8d9a2fdd93e2bd1ada546bdfc6598323269R305-R307), [link](https://github.com/pimcore/pimcore/pull/15910/files?diff=unified&w=0#diff-af590f2e28178b47df6034df5b2fa8d9a2fdd93e2bd1ada546bdfc6598323269R315-R317), [link](https://github.com/pimcore/pimcore/pull/15910/files?diff=unified&w=0#diff-af590f2e28178b47df6034df5b2fa8d9a2fdd93e2bd1ada546bdfc6598323269R372-R374), [link](https://github.com/pimcore/pimcore/pull/15910/files?diff=unified&w=0#diff-af590f2e28178b47df6034df5b2fa8d9a2fdd93e2bd1ada546bdfc6598323269R475-R477), [link](https://github.com/pimcore/pimcore/pull/15910/files?diff=unified&w=0#diff-af590f2e28178b47df6034df5b2fa8d9a2fdd93e2bd1ada546bdfc6598323269R514-R516), [link](https://github.com/pimcore/pimcore/pull/15910/files?diff=unified&w=0#diff-af590f2e28178b47df6034df5b2fa8d9a2fdd93e2bd1ada546bdfc6598323269R626-R628))
*  Add nullable type hint to the `$versions` parameter of the `setVersions` method of the `PageSnippet` class to fix a bug with null versions ([link](https://github.com/pimcore/pimcore/pull/15910/files?diff=unified&w=0#diff-af590f2e28178b47df6034df5b2fa8d9a2fdd93e2bd1ada546bdfc6598323269L521-R539))

### CODE REVIEW

**Comment by jdreesen** [comment]
How does the PhpDoc resolve the mentioned error?

File: models/Document/PageSnippet.php [hunk 1]
```diff
@@ -518,7 +533,10 @@ public function getVersions(): array
         return $this->versions;
     }
 
-    public function setVersions(array $versions): static
+    /**
+     * @return $this
+     */
+    public function setVersions(?array $versions): static
```
Comment (blankse) [inline models/Document/PageSnippet.php:539]: @jdreesen See this line

Comment (jdreesen) [reply models/Document/PageSnippet.php:539]: Ooh, I had overlooked that, thx!

**Comment by robertSt7** [comment]
@blankse The converting works fine.  Now I am getting an error when opening the email. 
`An exception has been thrown during the rendering of a template ("Call to undefined method getTitle in class Pimcore\Model\Document\Email").`

**Comment by blankse** [comment]
@robertSt7 This is because the controller/template is still for the page. You have to change it in the "Settings" tab.

**Comment by robertSt7** [comment]
> @robertSt7 This is because the controller/template is still for the page. You have to change it in the "Settings" tab.

@blankse What do you think about changing this in the converting process?

**Comment by blankse** [comment]
@robertSt7 I think this should do the user. How do we know which controller the user wishes?

**Comment by robertSt7** [comment]
> @robertSt7 I think this should do the user. How do we know which controller the user wishes?

@blankse That's right. I am thinking about clearing it

**Comment by blankse** [comment]
@robertSt7 When we clear it, it will be used the default controller (which is also for Pages). We haven't a default controller for emails, right?

**Comment by robertSt7** [comment]
@blankse True, but we don't get an error when we use that one

**Comment by blankse** [comment]
@robertSt7 Only in case of the demo. Because there the default template doesn't use the getTitle method :) Is dependent of the controller/templates of the project. I can create a PR to clear controller/template if you wish. This will be part of the admin-classic-ui-bundle

**Comment by blankse** [comment]
@robertSt7 See https://github.com/pimcore/admin-ui-classic-bundle/pull/263

**Comment by robertSt7** [comment]
@blanks Thanks a lot :)
