### PR TITLE
Drop foreign key constraint with o_ prefix if it exists and re-create it

### LINKED ISSUE #16620: [Bug]: Core migration Version20230616085142 does not run properly when upgrading from 10.6 to 11.5
### Pimcore version

11.1.5

### Steps to reproduce

- Run migrations after updating to Pimcore 11.1.5 from 10.6.7
- Foreign key constraint on `object_metadata_%` tables is not re-created

### Actual Behavior

- Foreign key constraint on `object_metadata_%` tables are not dropped and recreated because the migration looks for the foreign key with the wrong name.
- Foreign key name is `fk_object_metadata_%__o_id` but the migration is looking for `fk_object_metadata_%__id`
- This leads to an exception when trying to delete any kind of object (regardless if it is related to the metadata tables)

> Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails

### Expected Behavior

The migration drops & re-creates the foreign keys on `object_metadata_%`.

I assume the migration script could have checked for both names to support upgrades from 10.6.x ( `fk_object_metadata_%__o_id` and  `fk_object_metadata_%__id`)

### PR DESCRIPTION
**Pull request by muratbinerbay**
Ensures that the foreign key constraint on `object_metadata_%` tables are also renamed and updated properly when upgrading from Pimcore 10.6 to 11.1.5

  
  

## Changes in this pull request  
Resolves #16620

### CODE REVIEW

File: bundles/CoreBundle/src/Migrations/Version20230616085142.php [hunk 1]
```diff
@@ -51,10 +52,13 @@ public function up(Schema $schema): void
             $tableName = current($table);
             $metaDataTable = $schema->getTable($tableName);
             $foreignKeyName = AbstractDao::getForeignKeyName($tableName, self::ID_COLUMN);
+            $foreignKeyNameWithOPrefix = AbstractDao::getForeignKeyName($tableName, self::O_PREFIX . self::ID_COLUMN);
 
             if (!$metaDataTable->hasColumn(self::AUTO_ID)) {
                 if ($recreateForeignKey = $metaDataTable->hasForeignKey($foreignKeyName)) {
                     $this->addSql('ALTER TABLE `' . $tableName . '` DROP FOREIGN KEY `' . $foreignKeyName . '`');
+                } elseif ($recreateForeignKey = $metaDataTable->hasForeignKey($foreignKeyNameWithOPrefix)) {
```
Comment (kingjia90) [inline bundles/CoreBundle/src/Migrations/Version20230616085142.php:60]: Fine for more idempotency, but this suggests/hints that this migration (with a more "in-the-past" timestamp) didn't run properly?

https://github.com/pimcore/pimcore/blob/40890a3c30481fec0d15dbd0b550b1865a55d8fc/bundles/CoreBundle/src/Migrations/Version20221003115124.php#L90-L98

In other words, if that Version20221003115124 ran successfully, Version20230616085142 should be fine already to stop considering the `o_` fallback, or am i missing something?

Comment (kingjia90) [reply bundles/CoreBundle/src/Migrations/Version20230616085142.php:60]: Ah, maybe i got it, it's the "static" name of the foreign key still containing `o_id`, even though the column reference is to `id`

image

Comment (muratbinerbay) [reply bundles/CoreBundle/src/Migrations/Version20230616085142.php:60]: Exactly, the name of the foreign key does not get updated. 

Although minor, this also adds the `ON UPDATE NO ACTION` to the foreign key constraint.

**Comment by jdreesen** [comment]
Should be added to the `11.1.6` milestone, right? (same for the issue: #16620)
