### PR TITLE
[Bug]: Config paths change after upgrade

### LINKED ISSUE #15264: [Bug]:  Config paths change after upgrade
### Pimcore version

10.6

### Steps to reproduce

Use a pimcore version prior to 10.6 and add some document types or predefined properties. The yaml-files will be saved e.g. in `var/config/document-types` or  `var/config/predefined-properties`.

After the upgrade the paths change the following way:

* `var/config/custom-views` -> `var/config/custom_views`
* `var/config/document-types` -> `var/config/document_types`
* `var/config/predefined-asset-metadata` -> `var/config/predefined_asset_metadata`
* `var/config/predefined-properties` -> `var/config/predefined_properties`

The only path where no change happens is `var/config/image-thumbnails`.

### Expected / actual behavior

The paths should stay the same, or the should be a mention of this in the upgrade notes.

### PR DESCRIPTION
**Pull request by robertSt7**
resolves #15264

### CODE REVIEW

File: lib/Kernel.php [hunk 1]
```diff
@@ -242,13 +242,12 @@ public function registerContainerConfiguration(LoaderInterface $loader)
...
 
             foreach ($configArray as $config) {
-                $configKey = str_replace('-', '_', $config['defaultStorageDirectoryName']);
+                $configKey = $config['defaultStorageDirectoryName'];
                 if (!isset($containerConfig[self::CONFIG_LOCATION][$configKey])) {
                     continue;
                 }
-                $options = $containerConfig[self::CONFIG_LOCATION][$configKey]['write_target']['options'];
 
-                $configDir = rtrim($options['directory'] ?? self::getStorageDirectoryFromSymfonyConfig($containerConfig, $config['defaultStorageDirectoryName'], $config['storageDirectoryEnvVariableName']), '/\\');
```
Comment (lukmzig) [inline lib/Kernel.php:251]: HI @robertSt7, does this mean that it is not possible to have a custom location anymore?

Comment (robertSt7) [reply lib/Kernel.php:251]: Hi @lukmzig, no it was a duplicate, because we get the directory from the symfony config also here https://github.com/pimcore/pimcore/pull/15291/files/c82012a07910cd02bc631d6d08fa902ae5b6a67c#diff-332ac2e54ccef891942249e9f2d654a5e8dc16de6f5243f11802991919d5396eL270

Comment (lukmzig) [reply lib/Kernel.php:251]: Oh, I see now, thank you for the clarification!
