### PR TITLE
FIX(10708): fix for image assets that don't have set dimensions.

### LINKED ISSUE #10708: [Bug]: Can't open DWG file
### Expected behavior

- Open an asset with dwg extension. (DEBUG MODE)

### Actual behavior

- Can't open an asset with dwg extension without any error. ( Error appears only in debug mode)

### Steps to reproduce

- Set Debug mode on.
- Load an asset with dwg extension.
- Open an asset with dwg extension.
STEP_1
STEP_2
STEP_3
)
STEP_4

### PR DESCRIPTION
**Pull request by BabovicT**
Resolves #10708
Admin is no longer giving error, but as far as i can see .dwg is not supported by pimcore.

### CODE REVIEW

File: models/Asset/Image.php [hunk 1]
```diff
@@ -403,7 +403,11 @@ public function getWidth()
     {
         $dimensions = $this->getDimensions();
 
-        return $dimensions['width'];
+        if (isset($dimensions)) {
```
Comment (brusch) [inline models/Asset/Image.php]:
```suggestion
        if ($dimensions) {
```
As `null` is returned in case the dimensions cannot be read, a simple `if` should be sufficient.

File: models/Asset/Image.php [hunk 2]
```diff
@@ -413,7 +417,11 @@ public function getHeight()
     {
         $dimensions = $this->getDimensions();
 
-        return $dimensions['height'];
+        if (isset($dimensions)) {
```
Comment (brusch) [inline models/Asset/Image.php]:
```suggestion
        if ($dimensions) {
```

**Review by brusch — CHANGES_REQUESTED** [review]
