### PR TITLE
[DataObjects] Fix Encrypted fields with Ownerawareinterface leads to recursion on save

### LINKED ISSUE #8501: [DataObjects] Encrypted fields with ownerawareinterface leads to recursion on save
# Bug Report
when saving an object with encrypted field having "_owner" property, it leads to recursion. see https://github.com/pimcore/pimcore/blob/fb48e8b95b53fa0cd8efa33de36bea01705210c5/models/DataObject/Data/EncryptedField.php#L104

### PR DESCRIPTION
**Pull request by dvesh3**
## Changes in this pull request  
Resolves #8501

### CODE REVIEW

File: models/DataObject/Data/EncryptedField.php [hunk 1]
```diff
@@ -129,6 +134,11 @@ public function __wakeup()
                 $data = Crypto::decrypt($this->encrypted, $key, true);
 
                 $data = Serialize::unserialize($data);
+
+                if ($data instanceof OwnerAwareFieldInterface) {
+                    $data->setOwner($this, '_owner');
```
Comment (dvesh3) [inline models/DataObject/Data/EncryptedField.php:139]: this seems wrong as owner should be object not encryptedField..

Comment (dvesh3) [reply models/DataObject/Data/EncryptedField.php]: used `$this->_owner` as encrypted field is just for delegation.

**Review by weisswurstkanone — APPROVED** [review]
