### PR TITLE
[Sitemap] Ignore hardlinks

### LINKED ISSUE #6053: [Sitemap]  DocumentTypeFilter ignores Hardlinks
# Bug Report

### Expected behavior
DocumentTypeFilter should check if element is of type page/link/hardlink

### Actual behavior
DocumentTypeFilter ignores hardlinks because it is of the type 'Pimcore\Model\Document\Hardlink\Wrapper\Page' and returns 'page' instead of 'hardlink' on the function $element->getType()

[https://github.com/pimcore/pimcore/blob/master/lib/Sitemap/Document/Filter/DocumentTypeFilter.php](url)

### PR DESCRIPTION
**Pull request by dvesh3**
## Changes in this pull request  
Resolves #6053

## Additional info  
please see https://github.com/pimcore/pimcore/issues/6053#issuecomment-603162070

### CODE REVIEW

File: lib/Sitemap/Document/Filter/DocumentTypeFilter.php [hunk 1]
```diff
@@ -56,7 +56,7 @@ public function __construct(array $documentTypes = null, array $containerTypes =
 
     public function canBeAdded(AbstractElement $element, GeneratorContextInterface $context): bool
     {
-        if (!$element instanceof Document) {
+        if (!$element instanceof Document || $element instanceof Document\Hardlink\Wrapper\Page) {
```
Comment (brusch) [inline lib/Sitemap/Document/Filter/DocumentTypeFilter.php:59]: Should we better use `\Pimcore\Model\Document\Hardlink\Wrapper\WrapperInterface` here instead? That would cover all hardlinks, no matter which type, or is there a special reason for `Page` ?

Comment (dvesh3) [reply lib/Sitemap/Document/Filter/DocumentTypeFilter.php]: you are right, it should cover all hardlinks...changed it.
