### PR TITLE
fix AreabrickPass to work on Windows

### LINKED ISSUE #12938: [Bug]: Pimcore Bricks are not working
### Expected behavior

Default Pimcore Bricks are working with demo tutorial.

### Actual behavior

Pimcore Bricks can not be found and used in Backend and Frontend since some of the latest updates. 

### Use demo tutorial from Pimcore Academy. 
Using **xampp** with php >= 8

- Tools -> Bundles and Bricks  are not visible in list.  
- Documents -> edit -> shows an error:
  Areabrick wysiwyg-with-images is not registered File: C:\xampp\htdocs\my- 
  project\vendor\pimcore\pimcore\lib\Extension\Document\Areabrick\AreabrickManager.php Line: 129
- Frontend shows the same error: 
  Areabrick hero-teaser is not registered File: C:\xampp\htdocs\my- 
  project\vendor\pimcore\pimcore\lib\Extension\Document\Areabrick\AreabrickManager.php Line: 129

### I tried to fix it with: 
pimcore:build:classes 
pimcore:cache:clear

### I checked the system requirements:
 bin/console pimcore:system:requirements:check
 ------------------------------ ---------
  PHP
 ------------------------------ ---------
  memory_limit (in php.ini)      ok
  PDO MySQL                      ok
  Mysqli                         ok
  iconv                          ok
  Document Object Model (DOM)    ok
  SimpleXML                      ok
  GD                             ok
  EXIF                           ok
  Multibyte String (mbstring)    ok
  File Information (file_info)   ok
  zip                            ok
  zlib / gzip                    ok
  Intl                           ok
  locales-all                    ok
  Imagick                        warning
  APCu                           warning
  OPcache                        ok
  Redis                          warning
  curl                           ok
  WebP (via GD)                  ok
  AVIF (via GD)                  warning
 ------------------------------ ---------

 -------------------------------- ----
  MySQL
 -------------------------------- ----
  InnoDB Support                   ok
  ARCHIVE or MyISAM Support        ok
  Database Charset utf8mb4         ok
  innodb_large_prefix = ON         ok
  innodb_file_format = Barracuda   ok
  innodb_file_per_table = ON       ok
  CREATE TABLE                     ok
  ALTER TABLE                      ok
  Manage Indexes                   ok
  Fulltext Indexes                 ok
  INSERT                           ok
  UPDATE                           ok
  SELECT                           ok
  CREATE VIEW                      ok
  SELECT (from view)               ok
  DELETE                           ok
  SHOW CREATE VIEW                 ok
  SHOW CREATE TABLE                ok
  DROP VIEW                        ok
  DROP TABLE                       ok
  WITH RECURSIVE                   ok
 -------------------------------- ----

 ------------------------------------- ---------
  Filesystem
 ------------------------------------- ---------
  /var (not checked - too many files)   warning
 ------------------------------------- ---------

 ------------------------------------- ---------
  CLI Tools & Applications
 ------------------------------------- ---------
  PHP                                   ok
  Composer                              ok
  FFMPEG                                warning
  Chromium                              warning
  Ghostscript                           warning
  LibreOffice                           warning
  jpegoptim                             warning
  pngquant                              warning
  optipng                               warning
  exiftool                              warning
  timeout - (GNU coreutils)             ok
  pdftotext - (part of poppler-utils)   ok
  facedetect                            warning
  Graphviz                              warning
 ------------------------------------- ---------

### PR DESCRIPTION
**Pull request by mhujer**
## Changes in this pull request  
Resolves #12938 

## Additional info

Areabricks were not automatically registered on Windows because hardcoded forward-slash was used here but bellow in `str_replace` calls `DIRECTORY_SEPARATOR` was used which caused mismatch on Windows.

Was already reported previously as #12938 (was closed without fix).

### <samp>🤖 Generated by Copilot at c5d1565</samp>

This change improves the portability of the `AreabrickPass` class by using the `DIRECTORY_SEPARATOR` constant instead of hard-coded slashes. This is part of a pull request to enhance the Windows compatibility of Pimcore.

### <samp>🤖 Generated by Copilot at c5d1565</samp>

> _`DIRECTORY_SEPARATOR`_
> _No more hard-coded slashes_
> _Code adapts to winter_

### <samp>🤖 Generated by Copilot at c5d1565</samp>

* Use `DIRECTORY_SEPARATOR` constant instead of hard-coded slashes for path manipulation ([link](https://github.com/pimcore/pimcore/pull/15021/files?diff=unified&w=0#diff-2b2fdd9d344066a0eee77195d487f20860edb5471ff0db54aae8bffbdd555e05L207-R207))

### CODE REVIEW

File: bundles/CoreBundle/DependencyInjection/Compiler/AreabrickPass.php [hunk 1]
```diff
@@ -204,7 +204,7 @@ protected function handleContainerAwareDefinition(ContainerBuilder $container, D
     protected function findBundleBricks(ContainerBuilder $container, string $name, array $metadata, array $excludedClasses = []): array
     {
         $sourcePath = is_dir($metadata['path'].'/src') ? $metadata['path'].'/src' : $metadata['path'];
-        $directory = $sourcePath.'/Document/Areabrick';
+        $directory = $sourcePath.DIRECTORY_SEPARATOR.'Document'.DIRECTORY_SEPARATOR.'Areabrick';
```
Comment (dvesh3) [inline bundles/CoreBundle/DependencyInjection/Compiler/AreabrickPass.php:207]: should we consider it in the source path as well?

Comment (mhujer) [reply bundles/CoreBundle/DependencyInjection/Compiler/AreabrickPass.php:207]: @dvesh3 `$sourcePath` is removed with str_replace bellow on line 230 so I don't think it is necessary

**Comment by dvesh3** [comment]
@mhujer thanks!
