### PR TITLE
Fixed object reference setting for objectbricks and fieldcollections …

### LINKED ISSUE #12290: [Bug]: Broken pimcore cache for relations inside objectbricks
### Expected behavior

Relation in Objectbricks should work without any problems.

### Actual behavior

If the field is a mandatory field, an validation exception is thrown. If it' not a mandatory field, the relation will be removed.

It can be reproduced in the official demo:
image
image

### Steps to reproduce

1. Create a mandatory relation field inside a ojectbrick
2. Create a data object and assigne any object to relation to the new field
3. Reload the object (or open an existing object with a relation) and save it without change the relation

<hr>

## More information

The bug occurs when the cache is fetched from the cache_items table while saving the object. By opening the object and clearing the Pimcore cache before saving, everything works.

### PR DESCRIPTION
**Pull request by fashxp**
…when loading data from cache

fixes #12290

### CODE REVIEW

**Comment by fashxp** [comment]
@skochTC  can you please check if that solves your issue (don't forget to clear the pimcore data cache)

**Comment by skoch-twocream** [comment]
> @skochTC can you please check if that solves your issue (don't forget to clear the pimcore data cache)

I checked it several times now and compared it with the previous bug behavior. With your change it works fine!

Thanks a lot!

File: models/DataObject/Concrete.php [hunk 1]
```diff
@@ -788,6 +797,14 @@ public function __wakeup()
         if (property_exists($this, 'localizedfields') && $this->localizedfields instanceof Localizedfield) {
             $this->localizedfields->setObject($this, false);
         }
+
+        // renew object reference to other object aware fields
+        foreach($this->__objectAwareFields as $objectAwareField => $exists) {
+            $brickContainer = $this->$objectAwareField;
+            if($brickContainer instanceof ObjectAwareFieldInterface) {
+                $brickContainer->setObject($this);
+            }
```
Comment (brusch) [inline models/DataObject/Concrete.php]:
```suggestion
            if(isset($this->$objectAwareField) && $this->$objectAwareField instanceof ObjectAwareFieldInterface) {
                $this->$objectAwareField->setObject($this);
            }
```
I'd add `isset($this->$objectAwareField)` here, just in case the class definition changed in the meantime and a field definition was removed.

**Review by brusch — CHANGES_REQUESTED** [review]

File: models/DataObject/Concrete.php (hunk 1 above)
Comment (fashxp) [reply models/DataObject/Concrete.php]: but `$brickContainer instanceof ObjectAwareFieldInterface` doesn't evaluate to true, if `$this->$objectAwareField` is not set, right?

Comment (brusch) [reply models/DataObject/Concrete.php]: But it would throw an `Warning: Undefined property: ....` error.

Comment (brusch) [reply models/DataObject/Concrete.php]: Just verified that: 
```php
        $image = Asset\Image::getById(360);

        // works
        if(isset($image->sdfdsgdfgfghfgh) && $image->sdfdsgdfgfghfgh instanceof Asset) {
            $foo = 'bar';
        }

        // throws Warning: Undefined property: Pimcore\Model\Asset\Image::$sdfdsgdfgfghfgh
        if($image->sdfdsgdfgfghfgh instanceof Asset) {
            $foo = 'bar';
        }
```
