### PR TITLE
Language selector in Grid options don't change language in view

### LINKED ISSUE #6173: Language selector in Grid options don't change language in view
### Expected behavior
When change language in Grid options, it should change data language in Grid.
### Actual behavior
Default language:
image
Change language to French:
image
In Grid options window all right, but when we push "Apply" language in grid is still Default:
image

### Steps to reproduce
* add localizedfield in grid
* try to change language in Grid options and push Apply

It's related to https://demo.pimcore.fun/ and version v6.6.0 (Git Hash: e1328ffdb6cdc5416279c72353f2de9817ce9d1f).

### PR DESCRIPTION
**Pull request by weisswurstkanone**
resolves #6173

### CODE REVIEW

File: bundles/AdminBundle/Resources/public/js/pimcore/object/folder/search.js [hunk 1]
```diff
@@ -202,15 +202,21 @@ pimcore.object.search = Class.create(pimcore.object.helpers.gridTabAbstract, {
         // get current class
         var classStore = pimcore.globalmanager.get("object_types_store");
         var klass = classStore.getById(this.classId);
-        var baseParams = {
-            language: this.gridLanguage,
-        };
+
+        var baseParams;
```
Comment (dvesh3) [inline bundles/AdminBundle/Resources/public/js/pimcore/object/folder/search.js:206]: It should be changed for variants tab as well. https://github.com/pimcore/pimcore/blob/f9fc337d234a92d1f30dbad53739b66bb71020f5/bundles/AdminBundle/Resources/public/js/pimcore/object/variantsTab.js#L91
