### PR TITLE
[Bug] Fix cache clear memory issue

### LINKED ISSUE #16068: [Bug]: Memory issue with cache:clear
### Pimcore version

11.0 - 11.x

### Steps to reproduce

1. Checkout demo-enterprise version
2. Install pimcore
3. Add/install as many bundles as possible / also maybe new ones that are not published yet
4. Try to clear cache bin/console cache:clear

Memory limit is set to 256MB

### Actual Behavior

A memory error is thrown while cache clear

image

### Expected Behavior

No errors should appear and the cache should be cleared.

### PR DESCRIPTION
**Pull request by mattamon**
## Changes in this pull request  
Resolves #16068 

## Additional info
In PimcoreCoreCacheWarmer every class is loaded via class_exists check even though we only need the FQN here. 
This causes memory issues while cache:clear.

The preloader actually already takes care of it: https://github.com/symfony/symfony/blob/6.4/src/Symfony/Component/DependencyInjection/Dumper/Preloader.php#L80

Including now interfaces and traits.

### <samp>🤖 Generated by Copilot at 4d18c0b</samp>

Filter out non-class files in core cache warmer. This prevents errors or warnings when loading files that are not classes, interfaces or traits, such as `helper-functions.php`, from directories scanned by `getClassesFromDirectory`.

### <samp>🤖 Generated by Copilot at 4d18c0b</samp>

> _`getClassesFromDirectory`_
> _Filters out non-class files_
> _Autumn leaves no trace_

### <samp>🤖 Generated by Copilot at 4d18c0b</samp>

*  Filter out invalid files from class scanning ([link](https://github.com/pimcore/pimcore/pull/16069/files?diff=unified&w=0#diff-ca023d4b8c811a986f30c80457319d74e2af1630e460d7d04577d4f3197f4dc7L82-R84))

### CODE REVIEW

File: lib/HttpKernel/CacheWarmer/PimcoreCoreCacheWarmer.php [hunk 1]
```diff
@@ -79,7 +79,8 @@ private function getClassesFromDirectory(string $dir, string $excludePattern, st
                 $className = preg_replace('@\.php$@', '', $className);
                 $className = str_replace(DIRECTORY_SEPARATOR, '\\', $className);
 
-                if (class_exists($className)) {
+                // do not load all classes here / causes memory issues
+                if (class_exists($className, false)) {
```
Comment (brusch) [inline lib/HttpKernel/CacheWarmer/PimcoreCoreCacheWarmer.php]: At this time, no of the classes will be loaded already, so this change makes the whole cache-warmer obsolete.

**Review by brusch — CHANGES_REQUESTED** [review]

File: lib/HttpKernel/CacheWarmer/PimcoreCoreCacheWarmer.php (hunk 1 above)
Comment (mattamon) [reply lib/HttpKernel/CacheWarmer/PimcoreCoreCacheWarmer.php]: The cache warmer is only returning an array of classes, why would this change make the cache warmer obsolete?

The real problem is, that the memory consumption is causing cache:clear to fail because we are loading the whole lib, models and classes. 
This would also cause problems in instances with many classes.

Comment (jdreesen) [reply lib/HttpKernel/CacheWarmer/PimcoreCoreCacheWarmer.php]: @mattamon is right, these are classes that should be *preloaded* by PHP:

https://symfony.com/doc/current/reference/dic_tags.html#kernel-cache-warmer

Comment (mattamon) [reply lib/HttpKernel/CacheWarmer/PimcoreCoreCacheWarmer.php]: https://symfony.com/doc/current/reference/dic_tags.html#kernel-cache-warmer
Also according to symfony, you do not need to load the classes inside here, just return the array, what should be considered.

Comment (brusch) [reply lib/HttpKernel/CacheWarmer/PimcoreCoreCacheWarmer.php]: That's true, but with your change, no class is returned anymore, because `class_exists($className, false)` is always `false` because it disables autoloading (and non of the classes is loaded at this time), therefore no classes will get added to the return value, ergo -> obsolete.

Comment (mattamon) [reply lib/HttpKernel/CacheWarmer/PimcoreCoreCacheWarmer.php:83]:
```php
    if (class_exists($className, false)) {
           p_r("In here");
           $classes[] = $className;
}
```
I just tested it with autoload false and the debug statement.
image

At least for my system it still works

Comment (mattamon) [reply lib/HttpKernel/CacheWarmer/PimcoreCoreCacheWarmer.php]: @brusch, @cipribucur and I tested it more extensively and discovered some more problems with `class_exists`. 
`class_exists`  excludes traits and interfaces. We changed now to a different approach and do not use the `class_exists` altogether since it is covered in the preloader anyways. https://github.com/symfony/symfony/blob/6.4/src/Symfony/Component/DependencyInjection/Dumper/Preloader.php#L80

File: lib/HttpKernel/CacheWarmer/PimcoreCoreCacheWarmer.php [hunk 2]
```diff
@@ -79,7 +79,9 @@ private function getClassesFromDirectory(string $dir, string $excludePattern, st
                 $className = preg_replace('@\.php$@', '', $className);
                 $className = str_replace(DIRECTORY_SEPARATOR, '\\', $className);
 
-                if (class_exists($className)) {
+                // include classes, interfaces and traits
+                // exclude invalid files like helper-functions
+                if (!preg_match('/[_.-]/', $className)) {
```
Comment (brusch) [inline lib/HttpKernel/CacheWarmer/PimcoreCoreCacheWarmer.php:84]: @mattamon should we maybe check for a valid class name here, as described here: 
https://www.php.net/manual/en/language.oop5.basic.php#:~:text=The%20class%20name%20can%20be,_%5Cx80-%5Cxff%5D*%24%20. (plus `\` - I think that's missing in the regexp)

**Review by brusch — CHANGES_REQUESTED** [review]

File: lib/HttpKernel/CacheWarmer/PimcoreCoreCacheWarmer.php (hunk 2 above)
Comment (jdreesen) [reply lib/HttpKernel/CacheWarmer/PimcoreCoreCacheWarmer.php:84]: Class names cannot contain `\`, because it's the namespace separator.

Comment (brusch) [reply lib/HttpKernel/CacheWarmer/PimcoreCoreCacheWarmer.php:84]: But it's part of the string we check, right? Because it's the FQCN, not?

Comment (mattamon) [reply lib/HttpKernel/CacheWarmer/PimcoreCoreCacheWarmer.php:84]: Yes the `$className` is actually the FQCN. But we do generate it out of the filename right?
That would mean, if we have a bad file name, we would have a bad class. We can add the check but I am not sure if it is necessary, since we are adding our own classes, which should make sure anyways that the filename and the classname is the same right?

Comment (jdreesen) [reply lib/HttpKernel/CacheWarmer/PimcoreCoreCacheWarmer.php:84]: If you want to check the FQCN, I recently stumbled across this crazy regex [in the Symfony code base](https://github.com/symfony/symfony/blob/f3a09b9a9957546118bf06d3d0570598afb76cb0/src/Symfony/Component/DependencyInjection/Attribute/AutowireIterator.php#L59C52-L59C204): 
`/(?(DEFINE)(?<cn>[a-zA-Z_\x7f-\xff][a-zA-Z0-9_\x7f-\xff]*+))(?(DEFINE)(?<fqcn>(?&cn)(?:\\\\(?&cn))*+))^\??(?&fqcn)(?:(?:\|(?&fqcn))*+|(?:&(?&fqcn))*+)$/`

Comment (mattamon) [reply lib/HttpKernel/CacheWarmer/PimcoreCoreCacheWarmer.php:84]: @jdreesen wooooow, I would not even pretend to understand this regex :D 
But thank you very much! @brusch wdyt? 
Does it make sense to check if or are we sure, that our internal classes meet the expectations anyway?

Comment (jdreesen) [reply lib/HttpKernel/CacheWarmer/PimcoreCoreCacheWarmer.php:84]: Me neither, so I tried to understand what it does with the help of the explanation box of https://regex101.com/ :grin:

Comment (brusch) [reply lib/HttpKernel/CacheWarmer/PimcoreCoreCacheWarmer.php:84]: @mattamon I'd go for the simple solution for now (keep it as it is), if we see issues we can refine it anyway 😎
