### PR TITLE
Fix custom reports export

### LINKED ISSUE #7651: [Custom Reports] Cannot export to CSV when filters are enabled
# Bug Report

### Expected behavior

CSV file is exported from filtered custom report

### Actual behavior

Console throws an error and progress bar is stuck at 0%

### Steps to reproduce

Reproducable at [https://demo.pimcore.fun/](https://demo.pimcore.fun/)

1. Select default perspective and go to Marketing > Custom reports
2. Ensure you have a custom report with filterable fields, for example open `Workflow_TODO` and set filter type of field `name` to `Text`. Save & reload. 
Screenshot from 2020-12-02 14-24-50
3. Go to Marketing > Reports and open `Workflow`/`TODOs`. 

4. Add filter to column `Name`.
5. Click CSV Export button.

### Console error
```
report.js?_dc=4256328a6362ffcdcc83b9c95bee17804bd0cc71:548 Uncaught ReferenceError: proxy is not defined
    at klass.createCsv (report.js?_dc=4256328a6362ffcdcc83b9c95bee17804bd0cc71:548)
    at klass.exportBtnHandler (report.js?_dc=4256328a6362ffcdcc83b9c95bee17804bd0cc71:208)
    at Object.callback (ext-all-debug.js?_dc=4256328a6362ffcdcc83b9c95bee17804bd0cc71:8174)
    at constructor.fireHandler (ext-all-debug.js?_dc=4256328a6362ffcdcc83b9c95bee17804bd0cc71:128461)
    at constructor.onClick (ext-all-debug.js?_dc=4256328a6362ffcdcc83b9c95bee17804bd0cc71:128938)
    at constructor.fire (ext-all-debug.js?_dc=4256328a6362ffcdcc83b9c95bee17804bd0cc71:19779)
    at constructor.fire (ext-all-debug.js?_dc=4256328a6362ffcdcc83b9c95bee17804bd0cc71:31904)
    at constructor.publish (ext-all-debug.js?_dc=4256328a6362ffcdcc83b9c95bee17804bd0cc71:31880)
    at constructor.doDelegatedEvent (ext-all-debug.js?_dc=4256328a6362ffcdcc83b9c95bee17804bd0cc71:31930)
    at constructor.onDelegatedEvent (ext-all-debug.js?_dc=4256328a6362ffcdcc83b9c95bee17804bd0cc71:31917)
```

### PR DESCRIPTION
**Pull request by t-zilla**
## Changes in this pull request  
Resolves #7651

Fixed CSV export of filtered custom reports

### CODE REVIEW

File: bundles/AdminBundle/Controller/Reports/CustomReportController.php [hunk 1]
```diff
@@ -384,7 +384,13 @@ public function createCsvAction(Request $request)
 
         $sort = $request->get('sort');
         $dir = $request->get('dir');
-        $filters = ($request->get('filter') ? json_decode($request->get('filter'), true) : null);
+
+        if ($request->get('filter')) {
+            $filters = json_decode(urldecode($request->get('filter')), true);
+        } else {
+            $filters = null;
+        }
```
Comment (jdreesen) [inline bundles/AdminBundle/Controller/Reports/CustomReportController.php:392]: I think it should stay ternary.

```suggestion
        $filters = $request->get('filter') ? json_decode(urldecode($request->get('filter')), true) : null;
```

File: bundles/AdminBundle/Controller/Reports/CustomReportController.php [hunk 2]
```diff
@@ -384,7 +384,13 @@ public function createCsvAction(Request $request)
...
+
```
Comment (jdreesen) [inline bundles/AdminBundle/Controller/Reports/CustomReportController.php:393]: I think it should stay ternary.

```suggestion
        $filters = $request->get('filter') ? json_decode(urldecode($request->get('filter')), true) : null;
```

**Comment by brusch** [comment]
Thank you! 😊
