### PR TITLE
[Bug]: Fix unique constraint issue when updating advanced many-to-many 

### LINKED ISSUE #16265: [Bug]: updating advanced many-to-many relationship fails when changing metadata
### Pimcore version

11.0.9

### Steps to reproduce

See https://github.com/pimcore/data-hub/issues/819

### Actual Behavior

See https://github.com/pimcore/data-hub/issues/819

### Expected Behavior

See https://github.com/pimcore/data-hub/issues/819

I can confirm charging 

https://github.com/pimcore/pimcore/blob/74c15378aa58f6ee4b7e667f94cbe992b24ccfa7/models/DataObject/Data/ElementMetadata/Dao.php#L46

to 
```php
            Helper::upsert($this->db, $table, $data, ['id', 'dest_id', 'type', 'fieldname', 'column', 'ownertype', 'ownername', 'position', 'index']);
```

seems to fix it.

### PR DESCRIPTION
**Pull request by kingjia90**
## Changes in this pull request  
Potentially resolves https://github.com/pimcore/pimcore/issues/16265

## Additional info
It seems that https://github.com/pimcore/pimcore/pull/15746 applied only to `ObjectMetadata`'s CREATE TABLE while the migration ran for both `ObjectMetadata` and `ElementMetadata` (as it should, supposing the ObjectMetadata anti-deadlock changes are fine).

So existing data at the time migration ran are fine, anything new afterwards is likely not working fine and won't work with the fixes because `metadata_un` doesn't exists.

A little bit tricky because we basically need to re-run `Pimcore\Bundle\CoreBundle\Migrations\Version20230616085142` somehow but shouldn't be in a bugfix release.

### CODE REVIEW

File: models/DataObject/Data/ElementMetadata/Dao.php [hunk 1]
```diff
@@ -43,7 +43,7 @@ public function save(DataObject\Concrete $object, string $ownertype, string $own
             $data = $dataTemplate;
             $data['column'] = $column;
             $data['data'] = $this->model->$getter();
-            Helper::upsert($this->db, $table, $data, $this->getPrimaryKey($table));
+            Helper::upsert($this->db, $table, $data, [parent::UNIQUE_KEY_NAME]);
```
Comment (kingjia90) [inline models/DataObject/Data/ElementMetadata/Dao.php:46]: to avoid bc breaks and if we cannot re-run the migration, it should be something like
```suggestion
            $key = check if parent::UNIQUE_KEY_NAME exists ?? $this->getPrimaryKey($table)
            Helper::upsert($this->db, $table, $data, $key);
```

**Comment by kingjia90** [comment]
but wait, i cannot reproduce the error described in https://github.com/pimcore/data-hub/issues/819 anymore, @dkarlovi would you be able to check if it is still throwing errors?

**Comment by mcop1** [comment]
@kingjia90 Just tried to reproduce the issue described in the data-hub. Stumbled upon it while working on other things and was interested. Couldn´t reproduce it as well, updating the quantity in the relation's metadata worked fine. 

@dkarlovi Is the problem still there for you? Could you please try to reproduce it once again? Would be appreciated.

File: models/DataObject/Data/ElementMetadata/Dao.php (hunk 1 above)
Comment (kingjia90) [reply models/DataObject/Data/ElementMetadata/Dao.php:46]: It seems it would be better to just merge in next minor and have to rerun the migration
