### PR TITLE
[Data Objects] Password data type: fixed hash detection for password_hash algorithm

### LINKED ISSUE #16236: [Bug]: Passwords that appear to be a hashed String cannot be used as password with recommended 'password_hash' algorithm
### Pimcore version

All versions

### Steps to reproduce

Create a Data Object class with a "Password" field and select 'password_hash' as algorithm. Create a new data object and enter 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa1a' or 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA1A' as password. Both passwords are "MD5-like" strings.

Now when Pimcore authenticates against a Data Object of such a class by using 'ObjectUserProvider', it will fail.

If you set the password to 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaz', it will work because "z" is not allowed in a hexadecimal MD5 string.

You can also easily try it with the Pimcore Demo 10.3 or higher: 
Open the Data Object with path "/Customer Management/customers/AT/1020/Fred-Flintstone".
Click tab 'Authentication' and set password to 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa1a'.
Now go to Frontend and login with email 'fred.flintstone@stone.age' and password 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa1a'. Login will fail.

If you set 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaz' as password, it will work.

If you have a look into the database, you will see 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa1a' as plain text. In contrast when using 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaz', you will see its hashed value.

### Actual Behavior

"Hash-like" strings are not hashed again. This is documented ( https://pimcore.com/docs/platform/Pimcore/Objects/Object_Classes/Data_Types/Text_Types#password ) but in my opinion, it makes absolutely no sense.
When offering a password field with "encryption magic", why should "pre-hashed" strings be excluded from being stored here? Either all strings should be encoded automatically or none (in that case, the developer has to make sure strings are pre-encoded)

Problem: If you have a self registration process and a user would enter something like 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa1a' as password, he will not be shown a failure message (except if you implement yourself a check with "password_get_info()") but when the user tries to login, it will fail.

A colleague told me, this may be a backward-compatibility issue. If this is the case, please update the documentation and tell the reader that some passwords like 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa1a' cannot be used due to backward-compatibility.

### Expected Behavior

"Hash-like" passwords should work with recommended 'password_hash' algorithm.
If this is not possible due to backward-compatibility issues, please clarify it in the documentation.

### PR DESCRIPTION
**Pull request by brusch**
partly fixes #16236 

The idea is that we don't need to check for other algorithms when we're using `password_hash`, where we can clearly identify a string as a hash. 
So this would fix the issue described in #16236 for `password_hash` but not for all the other algos. 

I agree with @NiklasBr that we should remove the support for other algos in the future. 

@NiklasBr @schmidt-travixmedia @kingjia90 @dvesh3 WDYT?

### CODE REVIEW

**Comment by NiklasBr** [comment]
LGTM 👍

File: models/DataObject/ClassDefinition/Data/Password.php [hunk 1]
```diff
@@ -105,27 +105,29 @@ public function getDataForResource(mixed $data, DataObject\Concrete $object = nu
...
+        if($this->getAlgorithm() === self::HASH_FUNCTION_PASSWORD_HASH) {
+            $info = password_get_info($data);
+            if ($info['algo'] !== null && $info['algo'] !== 0) {
+                return $data;
+            }
+        } else {
+            // password_get_info() will not detect older, less secure, hashing algos.
+            // It might not detect some less common ones as well.
+            $maybeHash = preg_match('/^[a-f0-9]{32,}$/i', $data);
+            $hashLenghts = [
```
Comment (kingjia90) [inline models/DataObject/ClassDefinition/Data/Password.php:117]: LGTM as it reduces the false positive but i have casually found another problem when reviewing this area:

we are actually not supporting all the [hash_algos()](https://github.com/pimcore/admin-ui-classic-bundle/blob/d9aff7c5f8378b6bf9f30f1a4b672d48f4198e47/src/Controller/Admin/SettingsController.php#L1404) we allow to be selected and used

If i pick one of the following algos that is marked as `not supported` in the screenshot below (eg, `xxh32` which has 8 characters), the character length of the hashed string is below 32, and when is not matched, it leads to  `$data` to be hashed again
image

(here the quick snippet i just made to check)
```
<?php

        $hashLenghts = [
            32,  // D2, MD4, MD5, RIPEMD-128, Snefru 128, Tiger/128, HAVAL128
            40,  // SHA-1, HAS-160, RIPEMD-160, Tiger/160, HAVAL160
            48,  // Tiger/192, HAVAL192
            56,  // SHA-224, HAVAL224
            64,  // SHA-256, BLAKE-256, GOST, GOST CryptoPro, HAVAL256, RIPEMD-256, Snefru 256
            96,  // SHA-384
            128, // SHA-512, BLAKE-512, SWIFFT
        ];

$algos = hash_algos();

foreach ($algos as $algo){
	echo $algo.' ----- ';
	$hashed = hash($algo, 'test');
	$len = strlen($hashed);
	
	echo $len . ' ---- ';
	if (!in_array($len, $hashLenghts)){
		echo '<b>not supported</b>';	
	}
				  
	echo '<br>';
}
```

Comment (kingjia90) [reply models/DataObject/ClassDefinition/Data/Password.php:117]: probably it's more a task for admin ui bundle to remove the unsupported ones by unsetting the options.
By looking at this comment `// password_get_info() will not detect older, less secure, hashing algos.` only `ripemd320`(80 characters) is likely not working

Comment (kingjia90) [reply models/DataObject/ClassDefinition/Data/Password.php:117]: What if i have some users saving password on `hash()` but i later change to use `password_hash()`? i think the fallback was meant to cover this case as well?

**Comment by schmidt-travixmedia** [comment]
> partly fixes #16236
> 
> The idea is that we don't need to check for other algorithms when we're using `password_hash`, where we can clearly identify a string as a hash. So this would fix the issue described in #16236 for `password_hash` but not for all the other algos.
> 
> I agree with @NiklasBr that we should remove the support for other algos in the future.
> 
> @NiklasBr @schmidt-travixmedia @kingjia90 @dvesh3 WDYT?

Yes, the fix reduces false positive. For the example I reported in [16236](https://github.com/pimcore/pimcore/issues/16236) it helps, but I don't know if this works for all hash-like strings/other algos. I think a  clean solution would be to store the used algo as additional info.

File: models/DataObject/ClassDefinition/Data/Password.php (hunk 1 above)
Comment (brusch) [reply models/DataObject/ClassDefinition/Data/Password.php:117]: @kingjia90 No, not that I can remember - it was never designed to change the hash algo. 
@schmidt-travixmedia Yes, saving the algo along with the hash itself would solve the issue - the problem is that this doesn't cover existing data. 

So in the end, I'd leave the rest now as it is, and remove support for all other algos in v12.

Comment (schmidt-travixmedia) [reply models/DataObject/ClassDefinition/Data/Password.php:117]: > @kingjia90 No, not that I can remember - it was never designed to change the hash algo. @schmidt-travixmedia Yes, saving the algo along with the hash itself would solve the issue - the problem is that this doesn't cover existing data.
> 
> So in the end, I'd leave the rest now as it is, and remove support for all other algos in v12.

A migration script could be provided that detects the used algorithm of a password using PHP's password_get_info() and set the algorithm name in a new property.  Of course, this would have to be done for all Data Objects that contain password fields in a project.

Comment (kingjia90) [reply models/DataObject/ClassDefinition/Data/Password.php:117]: @schmidt-travixmedia the problem with the migration would be that `password_get_info` would only get `PASSWORD_BCRYPT` or `PASSWORD_ARGON_*` and still wouldn't retroactively detect the `hash()` algos

What about having 2 separate text fields, one for stored hash as is (for select all, copy/paste/edit stuff on hashed string), one "empty" for inserting a string that will be hashed (which activates once is a dirty field), in both the UI and APIs (getter/setter), and replaces the stored hash.
 
In this way, you always hash it once before persisting, the unhashed string should be never saved anywhere.

**Comment by brusch** [comment]
Imho the support for `hash()` should be just removed in next major version. 
It's anyway not best-practice and shouldn't be offered as an option anymore. 

See also: https://github.com/pimcore/pimcore/issues/16292 (already scheduled for next major).
