### PR TITLE
Fix: OwnerAwareField shouldn't save Owner

### LINKED ISSUE #3543: Link null after update to 5.5.3
# Bug Report
 
 
### Expected behavior 
  
Working links in objects after update from 5.2.1 (219) to 5.5.3

### Actual behavior  
Links in objects are NULL after an update from 5.2.1 to 5.5.3

Working link in 5.2.1 looks like this:

`O:34:"Pimcore\Model\DataObject\Data\Link":14:{s:4:"text";s:8:"LocalFoo";s:12:"internalType";s:8:"document";s:8:"internal";i:1;s:6:"direct";N;s:8:"linktype";s:8:"internal";s:6:"target";s:6:"_blank";s:10:"parameters";s:0:"";s:6:"anchor";s:0:"";s:5:"title";s:8:"LocalFoo";s:9:"accesskey";s:0:"";s:3:"rel";s:0:"";s:8:"tabindex";s:0:"";s:5:"class";s:0:"";s:10:"attributes";s:0:"";}
  `

in 5.5.3

`O:34:"Pimcore\Model\DataObject\Data\Link":17:{s:7:"�*�text";s:8:"LocalFoo";s:15:"�*�internalType";s:8:"document";s:11:"�*�internal";i:1;s:9:"�*�direct";N;s:11:"�*�linktype";s:8:"internal";s:9:"�*�target";s:6:"_blank";s:13:"�*�parameters";s:0:"";s:9:"�*�anchor";s:0:"";s:8:"�*�title";s:8:"LocalFoo";s:12:"�*�accesskey";s:0:"";s:6:"�*�rel";s:0:"";s:11:"�*�tabindex";s:0:"";s:8:"�*�class";s:0:"";s:13:"�*�attributes";s:0:"";s:9:"�*�_owner";N;s:13:"�*�_fieldname";N;s:12:"�*�_language";N;}`

### LINKED ISSUE #3698: OwnerAwareField shouldn't save Owner
# Bug Report

I have a Link Localizedfield in a class with many languages.

The Dao couldn't load the data, because the serialized string is cut off in the database.

Here is the owner set:
https://github.com/pimcore/pimcore/blob/master/models/DataObject/Localizedfield/Dao.php#L537

I think it should be removed before saving.

### Steps to reproduce 

1. Create class with panel, localizedfield, input and link
test
2. Create data object with filled input and link
3. Save and Publish
3. Reload the tab (Required!)
4. Change the input
5. Save and Publish
6. The owner is filled in the db table
test2

### PR DESCRIPTION
**Pull request by blankse**
## Changes in this pull request  
Resolves #3698
Resolves #3543

### CODE REVIEW

**Comment by brusch** [comment]
@blankse  please let us know when you're done with testing.
Thanks!

File: models/DataObject/ClassDefinition/Data/Block.php [hunk 1]
```diff
@@ -166,14 +166,14 @@ public function getDataForResource($data, $object = null, $params = [])
      * @param null|Model\DataObject\AbstractObject $object
      * @param mixed $params
      *
-     * @return string
+     * @return array|null
```
Comment (dpfaffenbauer) [inline models/DataObject/ClassDefinition/Data/Block.php]: not true, should be mixed since it could be anything

File: models/DataObject/ClassDefinition/Data/Block.php [hunk 2]
```diff
@@ -115,7 +115,7 @@ class Block extends Model\DataObject\ClassDefinition\Data
     /**
      * @see DataObject\ClassDefinition\Data::getDataForResource
      *
-     * @param string $data
+     * @param array $data
```
Comment (dpfaffenbauer) [inline models/DataObject/ClassDefinition/Data/Block.php]: not true, should be mixed since it could be anything

File: models/DataObject/ClassDefinition/Data.php [hunk 3]
```diff
@@ -133,31 +133,34 @@
...
      *
      * @param mixed $data
+     * @param null|\Pimcore\Model\DataObject\AbstractObject $object
+     * @param mixed
      *
      * @return mixed
-     *
-     * abstract public function getDataForResource($data);
      */
+    abstract public function getDataForResource($data, $object = null, $params = []);
```
Comment (dpfaffenbauer) [inline models/DataObject/ClassDefinition/Data.php]: I agree with you about that, but this shouldn't be in this PR since it doesn't belong to what to are trying to do

**Comment by brusch** [comment]
@blankse I agree with @dpfaffenbauer : please separate out the things out of scope into a new PR. Thanks again!

**Comment by dpfaffenbauer** [comment]
@blankse same here, but thats legacy stuff Pimcore still carries with it and it obviously needs fixing, but in a coordinated way ;)

File: models/DataObject/ClassDefinition/Data/Block.php (hunk 1 above)
Comment (blankse) [reply models/DataObject/ClassDefinition/Data/Block.php]: PR: #3710

**Comment by blankse** [comment]
@brusch @dpfaffenbauer 

I split off thinks #3709 #3710 
I tested it tomorrow and let you know, when it is ready.

**Comment by brusch** [comment]
@blankse Thanks, that looks very good and complete to me!
Nevertheless ... I'm waiting for your final go. 
@weisswurstkanone could you please also have a look at this? Just to be sure ;) Thanks!

**Comment by dpfaffenbauer** [comment]
I am not sure, but why should this fix the odd characters?

**Comment by blankse** [comment]
@brusch I tested it and works for me.

@dpfaffenbauer The odd characters are only in adminer. In phpmyadmin it looks ok.
The problem here is the owner field. It can be long if the object has many fields and/or many languages. The serialize string can be cut off in the table field and so the unserialize function returns false.

**Comment by brusch** [comment]
@blankse alright, thanks again!
