### PR TITLE
[Assets] Fix metadata grid issues

### LINKED ISSUE #5260: [Assets] Updating asset meta data in grid view fails
### Expected behavior
Open folder in grid view for assets and updating some meta data for them.

### Actual behavior
Newly added colums where predefined asset metadata (e.g. myMetaData) have a defined target type (e.g. document) have the target type as addition. 
image
image

This results in update failure when updating these meta data.

image

### Steps to reproduce
1. Add new asset metadata "myMetaData" with defined target type "document"
2. Open folder with documents in grid mode and add column "myMetaData"
3. Try to update meta data for asset

### PR DESCRIPTION
**Pull request by dvesh3**
## Changes in this pull request  
Resolves #5260

### CODE REVIEW

File: bundles/AdminBundle/Helper/GridHelperService.php [hunk 1]
```diff
@@ -630,15 +630,19 @@ public function prepareAssetListingForGrid($allParams, $adminUser)
...
                     $operator = '=';
                     $filter['value'] = (int) $filter['value'];
                 }
                 // system field
                 $value = $filter['value'];
                 if ($operator == 'LIKE') {
-                    $value = '%' . $value . '%';
+                    $value = $db->quote('%' . $value . '%');
+                } elseif ($operator == 'IN') {
+                    $value = '(' . implode(',',$value) . ')';
```
Comment (brusch) [inline bundles/AdminBundle/Helper/GridHelperService.php]: Quoting is missing here.

Comment (brusch) [reply bundles/AdminBundle/Helper/GridHelperService.php]: Done
