### PR TITLE
[Bug]: empty values in $context in CalculatorClassInterface

### LINKED ISSUE #13098: [Bug]: empty values in $context in CalculatorClassInterface
### Expected behavior

`$context` should have set according data in instances of CalculatorClassInterface 

### Actual behavior

$context has empty values for index, position and groupId in CalculatorClassInterface within object bricks

maybe related to #13028 ?

image

### Steps to reproduce

Create a calculated value field within an object brick and check the values of `$context`

`public function compute(Concrete $object, CalculatedValue $context): string`

### PR DESCRIPTION
**Pull request by mcop1**
Resolves #13098

### CODE REVIEW

File: models/DataObject/Data/CalculatedValue.php [hunk 1]
```diff
@@ -64,7 +64,7 @@ public function __construct($fieldname)
      *
      * @param string $ownerType
      * @param string|null $ownerName
-     * @param int|null $index
+     * @param int|string|null $index
```
Comment (blankse) [inline models/DataObject/Data/CalculatedValue.php:67]: Should be also changed for the attribute and the getter return

Comment (mcop1) [reply models/DataObject/Data/CalculatedValue.php:67]: You are way too fast 💯 
And I am really looking forward to having everything typed.
