### PR TITLE
Url slug route fix, Resolves #10005

### LINKED ISSUE #10005: [Bug]: URL Slugs that partially matches a Document path gives 404
### Expected behavior

Any published Data Object with a URL Slug should be reachable

### Actual behavior

Any time a part of the URL Slug matches a full path of an unpublished Document page, the URL Slug will return a 404.

### Steps to reproduce

1. Create a URL Slug on a data object, .e.g. `/a/b/c/123`
2. Create a Document page structure like with a Pretty URL like `/a/b/c`
3. Save, and unpublish the page `c`
4. Visit  `/a/b/c/123` on the front end.

Result: 404

### PR DESCRIPTION
**Pull request by dturopoli**
Resolves #10005, but with option to switch behavior off and on via config

### CODE REVIEW

**Comment by brusch** [comment]
@EqualString @dturopoli Unfortunately adding an annotation is not enough. We also need to call `trigger_deprecation()` in case you're accessing an object slug but it's getting blocked by the underlying document. So that needs to be done somewhere in `\Pimcore\Bundle\CoreBundle\EventListener\Frontend\ElementListener` i guess. 
Thanks again!

File: lib/Routing/Dynamic/DataObjectRouteHandler.php [hunk 1]
```diff
@@ -114,6 +123,17 @@ private function buildRouteForFromSlug(DataObject\Data\UrlSlug $slug, DataObject
         $route->setDefault('object', $object);
         $route->setDefault('urlSlug', $slug);
 
+        trigger_deprecation(
```
Comment (jdreesen) [inline lib/Routing/Dynamic/DataObjectRouteHandler.php]: I'd say the deprecation should not be triggered if the value is the one that is not deprecated. I.e. it should only be triggered if the value is `false`. Otherwise, you can't fix the deprecation in your code prior to updating to the version where the behavior changes.

Comment (brusch) [reply lib/Routing/Dynamic/DataObjectRouteHandler.php]: This is the wrong place anyway, that needs to be done in ElementListener as mentioned before. 
Here should be the right place: 
https://github.com/pimcore/pimcore/blob/e37d843d43299593391baa3d24e46cd442cf82ec/bundles/CoreBundle/EventListener/Frontend/ElementListener.php#L96-L95

Something like the following: 
```php
                if($request->get('object') && $request->get('urlSlug')) {
                    trigger_deprecation(...);
                }
```

**Review by brusch — CHANGES_REQUESTED** [review]
Additionally I think we'd need to do that for Static Routes as well.

File: bundles/CoreBundle/DependencyInjection/Configuration.php [hunk 2]
```diff
@@ -687,6 +687,20 @@ private function addObjectsNode(ArrayNodeDefinition $rootNode)
                                 ->end()
                             ->end()
                         ->end()
+                        ->booleanNode('allow_processing_unpublished_elements_for_url_slug')
```
Comment (brusch) [inline bundles/CoreBundle/DependencyInjection/Configuration.php]: This is now the wrong location for the config, since it also covers static routes. 
I'd propose the following location/naming: `pimcore.routing.allow_processing_unpublished_fallback_document`

File: bundles/CoreBundle/EventListener/Frontend/ElementListener.php [hunk 3]
```diff
@@ -94,6 +96,20 @@ public function onKernelController(ControllerEvent $event)
...
+                    (
+                        ($request->get('object') && $request->get('urlSlug')) ||
+                        $request->get('pimcore_request_source') == 'staticroute'
+                    ) &&
+                    !$this->config['objects']['allow_processing_unpublished_elements_for_url_slug']
+                ) {
+                    trigger_deprecation(
+                        'pimcore/pimcore',
+                        '10.2',
+                        '`allow_processing_unpublished_elements_for_url_slug` is deprecated, in Pimcore 11 it will always be `true`'
```
Comment (brusch) [inline bundles/CoreBundle/EventListener/Frontend/ElementListener.php]:
```suggestion
                        'Blocking routes where the underlying fallback document is unpublished is deprecated and will be removed in Pimcore 11. If you rely on this behavior please change your controllers accordingly and set the config option `pimcore.routing.allow_processing_unpublished_fallback_document=true`'
```

**Review by brusch — CHANGES_REQUESTED** [review]
We are almost there, just two more small changes 😉

**Comment by brusch** [comment]
Thanks a lot! 👍
