### PR TITLE
[Bug]: Objectbrick definition update fails when changing field of type text to type textarea

### LINKED ISSUE #13436: [Bug]: Objectbrick definition update fails when changing field of type text to type textarea
### Expected behavior

Save of objectbrick field definition to succeed.

### Actual behavior

Save fails with MySQL error resulting in the following exception:
`An exception occurred while executing 'ALTER TABLE `object_brick_query_catalog_product_description_1` CHANGE COLUMN `fieldValue` `fieldValue` longtext NULL;':
SQLSTATE[42000]: Syntax error or access violation: 1170 BLOB/TEXT column 'fieldValue' used in key specification without a key length.`
image

### Steps to reproduce

From admin panel:
- Create Class definition with objectbrick field.
- Create object brick definition with 1 text field linked to the class and save it.
- Change the type of the objectbrick field from text to textarea and save.
The exception occurs.
This same fieldtype change scenario works as expected when done in class definition but fails when done to objectbrick definition.
If we create the objectbrick field with type textarea the first time than the save works as expected as there is no such index. It seems that the index created for the text type field is not being dropped before changing the column type in MySQL.

### PR DESCRIPTION
**Pull request by mcop1**
Resolves #13436

### CODE REVIEW

File: models/DataObject/Objectbrick/Definition/Dao.php [hunk 1]
```diff
@@ -173,4 +177,22 @@ public function classSaved(DataObject\ClassDefinition $classDefinition)
...
+     * @param string $table
+     * @param array $columnsToRemove
+     * @param array $protectedColumns
+     */
+    protected function removeIndices($table, $columnsToRemove, $protectedColumns)
+    {
+        if (is_array($columnsToRemove) && count($columnsToRemove) > 0) {
+            $indexPrefix = str_starts_with($table, 'object_brick_query_') ? 'p_index_' : 'u_index_';
+            foreach ($columnsToRemove as $value) {
+                if (!in_array(strtolower($value), array_map('strtolower', $protectedColumns))) {
```
Comment (jdreesen) [inline models/DataObject/Objectbrick/Definition/Dao.php]: I don't think you should call this `array_map('strtolower', $protectedColumns)` over and over again in the loop.

Comment (mcop1) [reply models/DataObject/Objectbrick/Definition/Dao.php]: Good point, I copied this part of the method. I think we should do it for both then.

**Review by dvesh3 — APPROVED** [review]
