### PR TITLE
Fixed Voucher paginator issue

### LINKED ISSUE #14162: [Bug]: Ecommerce Voucher Detail paginator when switching entries per page
### Expected behavior

When switching entries per page button, it should do some check:

41 tokens /  25 tokens per page  = 1,64 and current page is between 1 and 2 (round up of 1,64), then it's ok, anything above it , then force current page to the maximum, which is 2.
41 tokens / 75 tokens per page = 0,54 , if current page is above 1, force it to 1

### Actual behavior

image
It's empty because it is still on page 2, so technically trying to show entries in the range of 75-150 but there are only 41 entries.

https://github.com/pimcore/pimcore/blob/b5b83ca5ef5a6e2a151c2fa5a683bcfc65fd5595/bundles/EcommerceFrameworkBundle/VoucherService/TokenManager/Single.php#L86-L92

image

### Steps to reproduce

Go on any voucher, generate at least to have 25+ entries but fewer than 75.
Press page `2` to display entries in the range 25-50, then switch the `Tokens per page` to 75. 
It stays on page 2 but it's hidden, so unless one switch back to `25 entries per page`, the following buttons do not appear (like in the other screenshot)
image

### PR DESCRIPTION
**Pull request by aashan10**
## Changes in this pull request  
Resolves #14162

### CODE REVIEW

File: bundles/EcommerceFrameworkBundle/VoucherService/TokenManager/Pattern.php [hunk 1]
```diff
@@ -541,10 +541,26 @@ public function prepareConfigurationView(&$viewParamsBag, $params)
...
+
+        $availablePages = ceil($total / $perPage);
+
+        if ($page > $availablePages) {
+            $page = $availablePages;
+        }
+
+        if ((int) $availablePages === 0) {
+            $page = 1;
+        }
```
Comment (kingjia90) [inline bundles/EcommerceFrameworkBundle/VoucherService/TokenManager/Pattern.php]:
```suggestion
        $page = isset($params['page']) ? (int)$params['page'] : 1;
        $perPage = isset($params['tokensPerPage']) ? (int)$params['tokensPerPage'] : 25;

        $total = count($tokens);

        $availablePages = (int) ceil($total / $perPage);

        if ($page > $availablePages) {
            $page = $availablePages;
        }

       $page = $page ?: 1;
```

- added isset and cast to `params['page']`, otherwise would appear as a string 
- convert the ceil result of `availablePages` to int, to remove the cast below (for `===0` check) and because `$page` should be `int` (otherwise would be `float` after `$page = $availablePages`).
- added elvis check for `$page`, as it should be never 0 but starting from 1, therefore not limiting this check to only when availablePages is 0, to be moved under, eg. `$paginator->paginate($token, $page ?: 1)`

See also https://github.com/KnpLabs/knp-components/blob/6b6efa81ee894e325744bf785d50dc962937b1f2/src/Knp/Component/Pager/PaginatorInterface.php#L39-L40

**Review by kingjia90 — DISMISSED** [review]

File: bundles/EcommerceFrameworkBundle/VoucherService/TokenManager/Pattern.php [hunk 2]
```diff
@@ -541,14 +541,25 @@ public function prepareConfigurationView(&$viewParamsBag, $params)
 
         /** @var PaginatorInterface $paginator */
         $paginator = \Pimcore::getContainer()->get(\Knp\Component\Pager\PaginatorInterface::class);
+
+        $page = isset($params['page']) ? (int)$params['page'] : 1;
+        $perPage = isset($params['tokensPerPage']) ? (int)$params['tokensPerPage'] : 25;
```
Comment (dvesh3) [inline bundles/EcommerceFrameworkBundle/VoucherService/TokenManager/Pattern.php]:
```suggestion
        $page = (int)($params['page'] ?? 1);
        $perPage = (int)($params['tokensPerPage'] ?? 25);
```

File: bundles/EcommerceFrameworkBundle/VoucherService/TokenManager/Single.php [hunk 3]
```diff
@@ -83,13 +83,24 @@ public function prepareConfigurationView(&$viewParamsBag, $params)
         if ($codes) {
             /** @var PaginatorInterface $paginator */
             $paginator = \Pimcore::getContainer()->get(\Knp\Component\Pager\PaginatorInterface::class);
+
+            $page = isset($params['page']) ? (int)$params['page'] : 1;
+            $perPage = isset($params['tokensPerPage']) ? (int)$params['tokensPerPage'] : 25;
```
Comment (dvesh3) [inline bundles/EcommerceFrameworkBundle/VoucherService/TokenManager/Single.php]:
```suggestion
            $page = (int)($params['page'] ?? 1);
            $perPage = (int)($params['tokensPerPage'] ?? 25);
```

File: bundles/EcommerceFrameworkBundle/VoucherService/TokenManager/Pattern.php [hunk 4]
```diff
@@ -541,14 +541,25 @@ public function prepareConfigurationView(&$viewParamsBag, $params)
...
+
+        $page = (int)($params['page'] ?? 1);
+        $perPage = (int)($params['tokensPerPage'] ?? 25);
+        
+        $total = count($tokens);
+        
+        $availablePages = (int) ceil($total / $perPage);
+        if ($page > $availablePages) {
+            $page = $availablePages;
+        }
```
Comment (dvesh3) [inline bundles/EcommerceFrameworkBundle/VoucherService/TokenManager/Pattern.php]:
```suggestion
        $page = min($page, (int) ceil($total / $perPage));
```
should also work? since we are looking for available page with min value

Comment (kingjia90) [reply bundles/EcommerceFrameworkBundle/VoucherService/TokenManager/Pattern.php]: yes, lgtm even though i feel that with `$availablePages` is a little more clear to understand what's going on
maybe like this?
```suggestion
        $availablePages = (int) ceil($total / $perPage);
        $page = min($page, availablePages);
```

File: bundles/EcommerceFrameworkBundle/VoucherService/TokenManager/Pattern.php [hunk 5]
```diff
@@ -541,14 +541,23 @@ public function prepareConfigurationView(&$viewParamsBag, $params)
...
         /** @var PaginatorInterface $paginator */
         $paginator = \Pimcore::getContainer()->get(\Knp\Component\Pager\PaginatorInterface::class);
+
+        $page = (int)($params['page'] ?? 1);
+        $perPage = (int)($params['tokensPerPage'] ?? 25);
+        
+        $total = count($tokens);
+        
+        $availablePages = (int) ceil($total / $perPage);
+        $page = min($page, availablePages);
```
Comment (dvesh3) [inline bundles/EcommerceFrameworkBundle/VoucherService/TokenManager/Pattern.php]:
```suggestion
        $page = min($page, $availablePages);
```

File: bundles/EcommerceFrameworkBundle/VoucherService/TokenManager/Single.php [hunk 6]
```diff
@@ -83,13 +83,24 @@ public function prepareConfigurationView(&$viewParamsBag, $params)
...
+
+            $page = (int)($params['page'] ?? 1);
+            $perPage = (int)($params['tokensPerPage'] ?? 25);
+
+            $total = count($codes);
+
+            $availablePages = (int) ceil($total / $perPage);
+            if ($page > $availablePages) {
+                $page = $availablePages;
+            }
```
Comment (dvesh3) [inline bundles/EcommerceFrameworkBundle/VoucherService/TokenManager/Single.php]:
```suggestion
            $availablePages = (int) ceil($total / $perPage);
            $page = min($page, $availablePages);
```
