### PR TITLE
[Bug]: Data Components in Custom Layout without Layout Component

### LINKED ISSUE #12309: [Bug]: Data Components in Custom Layout without Layout Component
### Expected behavior

Every Data Component have to be in a Layout Component in a Custom Layout

### Actual behavior

There can be Data Components outside of Layout Components
image

### Steps to reproduce

- Create a Custom Layout
- Drag and drop some Data Components to the "Base"

### PR DESCRIPTION
**Pull request by lukmzig**
## Changes in this pull request  
Resolves #12309

### CODE REVIEW

File: bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/customLayoutEditor.js [hunk 1]
```diff
@@ -343,6 +344,10 @@ pimcore.object.helpers.customLayoutEditor = Class.create({
 
                     if (target != source) {
                         var record = data.records[0];
+                        console.log(overModel);
```
Comment (robertSt7) [inline bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/customLayoutEditor.js]:
```suggestion
```

Comment (lukmzig) [reply bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/customLayoutEditor.js]: thanks 👍
