### PR TITLE
[Bug]: Fix multisite internal link when using document preview

### LINKED ISSUE #15336: [Bug]: Wrong internal links in documents preview when using site(s)
### Pimcore version

10.5.23

### Steps to reproduce

When opening a document within a site in preview mode wrong (internal) links are parsed. The link starts with the path/key of the site. When clicking the link, a 404 error appears because the route does not exist.

Same behavior for links in a WYSIWYG editable or in a link editable.

Example:
```
Home
|
└───Website (defined as site with given domain)
    |
    └───Page 1
    │   │   Page 1.1
    │   │   Page 1.2
    │   │   ...
    │
    └───Page 2
        │   Page 2.1
        │   Page 2.2
        │   ...
```

A link to Page 1.2 is parsed in preview (both embedded or new window) as `/Website/Page 1/Page 1.2`.

When opening the page **not** in preview mode the link is parsed correctly as `/Page 1/Page 1.2`.

### Expected / actual behavior

When opening the page in preview, the link should also be parsed as `/Page 1/Page 1.2`, so that the link can also be clicked in preview mode without getting an error.

### PR DESCRIPTION
**Pull request by kingjia90**
## Changes in this pull request  
Resolves https://github.com/pimcore/pimcore/issues/15336

## Additional info
Since it's already working for the frontend without any issues, refining/loosing up the IF block conditions 
https://github.com/pimcore/pimcore/compare/10.6...fix-multisite-link?expand=1#diff-48235de7b392a4ff9ed273062d750e2732a5b1f8355cd76109abf4c5538a6c45L868  
does the trick.
`isDocumentInCurrentSite` defaults to `true` when not a siteRequest, which is the case when in main site backend 
https://github.com/pimcore/pimcore/blob/727ab1a73020f540ac1d2c12386292909e6b3125/lib/Tool/Frontend.php#L49

The rest is just indentation and some minor refactor
Added some documentation notes, since it may trigger unwanted CSP (Pimcore 11+) and CORS errors in console.

### <samp>🤖 Generated by Copilot at ab221b7</samp>

This pull request fixes a bug in the `getFullPath` function of the `Document` class that affected document links for different sites, and updates the documentation to warn users about the preview navigation issues when using sites with links. The changes improve the code quality and the user experience of the admin interface.

### <samp>🤖 Generated by Copilot at ab221b7</samp>

> _If you work with documents from sites_
> _You may face some previewing plights_
> _The docs warn of frames_
> _And CORS policy names_
> _That may block or distort your sights_

### <samp>🤖 Generated by Copilot at ab221b7</samp>

*  Fix a bug that caused incorrect links to be generated for documents that are not part of the current site when previewing them from the admin interface ([link](https://github.com/pimcore/pimcore/pull/15724/files?diff=unified&w=0#diff-48235de7b392a4ff9ed273062d750e2732a5b1f8355cd76109abf4c5538a6c45L868-R918))
* Simplify and unify the code style by removing unnecessary namespace prefixes from the `Tool`, `Site`, and `Model` classes ([link](https://github.com/pimcore/pimcore/pull/15724/files?diff=unified&w=0#diff-48235de7b392a4ff9ed273062d750e2732a5b1f8355cd76109abf4c5538a6c45L844-R844), [link](https://github.com/pimcore/pimcore/pull/15724/files?diff=unified&w=0#diff-48235de7b392a4ff9ed273062d750e2732a5b1f8355cd76109abf4c5538a6c45L938-R946), [link](https://github.com/pimcore/pimcore/pull/15724/files?diff=unified&w=0#diff-48235de7b392a4ff9ed273062d750e2732a5b1f8355cd76109abf4c5538a6c45L966-R974))
* Assign the current request object to a variable `$request` for readability and consistency in the `getFullPath` function of `models/Document.php` ([link](https://github.com/pimcore/pimcore/pull/15724/files?diff=unified&w=0#diff-48235de7b392a4ff9ed273062d750e2732a5b1f8355cd76109abf4c5538a6c45R858))
* Add a new subsection to the documentation about working with sites, warning the users about the possible issues with document preview navigation when using different sites with links ([link](https://github.com/pimcore/pimcore/pull/15724/files?diff=unified&w=0#diff-cac7fbec00e9439520d8d17395810dfb9a5ddfc744ca386b50892c281b23f7c3R93-R95))

### CODE REVIEW

File: models/Document.php [hunk 1]
```diff
@@ -865,49 +866,56 @@ public function getFullPath(bool $force = false)
...
-
-                        $link = preg_replace('@^' . preg_quote($hardlinkTarget->getRealFullPath(), '@') . '@',
-                            $hardlinkPath, $this->getRealFullPath());
-                    }
+        if (!$link && Tool::isFrontend()) {
+            $differentDomain = false;
+            $site = FrontendTool::getSiteForDocument($this);
+            if ($site instanceof Site){
+                $differentDomain = $site->getMainDomain() != $request->getHost();
+            }
```
Comment (dvesh3) [inline models/Document.php]: I think we should only perform this calculation in `Tool::isFrontendRequestByAdmin()` check. wdyt?

File: models/Document.php [hunk 2]
```diff
@@ -865,49 +866,56 @@ public function getFullPath(bool $force = false)
...
+
+            if ((Site::isSiteRequest() && !FrontendTool::isDocumentInCurrentSite($this))
+                || (Tool::isFrontendRequestByAdmin() && $differentDomain)){
```
Comment (kingjia90) [inline models/Document.php]: @dvesh3 do you mean like this? 

```suggestion
            if (Tool::isFrontendRequestByAdmin() && $site instanceof Site){
                $differentDomain = $site->getMainDomain() != $request->getHost();
            }

            if ((Site::isSiteRequest() && !FrontendTool::isDocumentInCurrentSite($this))
                || $differentDomain){
```

**Review by dvesh3 — APPROVED** [review]
