### PR TITLE
[Bug]: Omit Mandatory Check on field with Default Value when creating a new DataObject

### LINKED ISSUE #15311: [Bug]: the default value is not used for mandatory fields
### Expected behavior

The default value is set on the (newly created) DataObject

### Actual behavior

Pimcore\Model\Element\ValidationException: Empty mandatory field [ fieldName ]

### Steps to reproduce

With (currently latest versions) Pimcore v10.5.20, DataHub v1.5.6 and DataImporter v1.7.5

1. Create a class definition, with
  a. Mark one field as mandatory field and also give it a default value (e.g. a status dropdown with default value "New")
2. Create a data importer definition, with
  a. Resolver configuration with a valid "Element Creation" config
  b. Resolver configuration publish strategy set to "Always publish" or "Publish new"
  c. Valid mapping configuration so that it can create new DataObjects (mainly, the system key should be set)
  d. Important: don't map the field created in step 1a.
3. Run an import

### PR DESCRIPTION
**Pull request by kingjia90**
## Changes in this pull request  
Resolves https://github.com/pimcore/pimcore/issues/15311

### <samp>🤖 Generated by Copilot at 5c02d95</samp>

Fix mandatory check for fields with default values in `DataObject/Concrete.php`. This allows saving new objects with empty mandatory fields that have a default value set in the class definition.

### <samp>🤖 Generated by Copilot at 5c02d95</samp>

> _`default` values_
> _skip the mandatory check_
> _autumn leaves falling_

### <samp>🤖 Generated by Copilot at 5c02d95</samp>

*  Skip mandatory check on fields with default value when adding new object ([link](https://github.com/pimcore/pimcore/pull/15812/files?diff=unified&w=0#diff-8ff96247c8a26d5a3ecbf9b79e38c31b8fc8a638bd145a46b9cdb7ee27d4869bL143-R150))

### CODE REVIEW

**Comment by kingjia90** [comment]
Notes about Codeception Tests: in https://github.com/pimcore/pimcore/actions/runs/5962567143/job/16173995193#step:11:3166 (commit https://github.com/pimcore/pimcore/pull/15812/commits/e9c22533abbc7c12c52afa3ad31dd6a8f537fb87) the error there is after the exception get caught and string contain asserted true and that's positive as it was intentionally to check if save was unsuccessfull and the wanted exception got caught, https://github.com/pimcore/pimcore/pull/15812/commits/3e954039a222b7cf63d46d68a57426e2986e5e55 (ndr it's passed, only sonar cloud crashed causing false negative) meaning `save()` in try block was successfull and reached the assertEquals of the default value. 
Then cleaned up as these were "inverted tests"(expecting to fail but with assert in the catch block), but this PR fixes the initial problem and can't intentionally make it crash, however it would crash in future if the problem resurfaces/regresses, eg. by commenting the fix it returns
image

File: models/DataObject/Concrete.php [hunk 1]
```diff
@@ -140,7 +140,14 @@ protected function update(bool $isUpdate = null, array $params = []): void
 
                 if (method_exists($this, $getter)) {
                     $value = $this->$getter();
+
                     $omitMandatoryCheck = $this->getOmitMandatoryCheck();
+                    // when adding a new object, skip check on mandatory fields with default value
+                    if (empty($value) && !$isUpdate && $fd->getMandatory()
```
Comment (dvesh3) [inline models/DataObject/Concrete.php]: Is it necessary to check `$fd->getMandatory()` here? I mean if default value exists then `$omitMandatoryCheck` is true anyways.

Comment (kingjia90) [reply models/DataObject/Concrete.php]: Thank you, sounds right, it is not necessary
