### PR TITLE
[Bug]: Can't filter classification store booleanSelect type in grid

### LINKED ISSUE #13096: [Bug]: Can't filter classification store booleanSelect type in grid
### Expected behavior

Be able to filter grid list on classification store field of type booleanSelect.

### Actual behavior

Filter grid list on classification store field of type booleanSelect gives error.

### Steps to reproduce

- add CS key for booleanSelect
image

- add CS store field in Product class
- add CS key in Grid
- try to filter
image

- error
image

### PR DESCRIPTION
**Pull request by robertSt7**
resolve #13096

### CODE REVIEW

File: models/DataObject/ClassDefinition/Data.php [hunk 1]
```diff
@@ -579,7 +580,19 @@ public function getFilterConditionExt($value, $operator, $params = [])
         }
 
         if (in_array($operator, DataObject\ClassDefinition\Data::$validFilterOperators)) {
-            return $key . ' ' . $operator . ' ' . $value . ' ';
+            $trailer = '';
+            if($value === '\'0\'' || is_array($value) && in_array(0, $value)) {
```
Comment (brusch) [inline models/DataObject/ClassDefinition/Data.php:590]: I think we should explain the following lines a bit :)

**Review by mcop1 — COMMENTED** [review]
The filter itself works now, but there is still an exception. 
1.) Make sure the checkboxes for "yes", "no" and "empty" aren´t checked
2.) Klick on the checkbox next to the filter button
grafik

results in

grafik
