### PR TITLE
[DataObjects] When renaming fieldname of object brick, brick tables a…

### LINKED ISSUE #5656: [DataObjects] When renaming fieldname of object brick, brick tables are not cleaned up
rename field name of object brick 
image

old values remain in store and query table
image

new values are added in addition. 

This results in potentially unexpected filter results. 

also cause for https://github.com/pimcore/demo/issues/169

### PR DESCRIPTION
**Pull request by weisswurstkanone**
resolves #5656

### CODE REVIEW

File: lib/Maintenance/Tasks/CleanupBrickTablesTask.php [hunk 1]
```diff
@@ -0,0 +1,90 @@
...
+    {
+        $this->logger = $logger;
+    }
+
+    /**
+     * {@inheritdoc}
+     */
+    public function execute()
+    {
+        $db = Db::get();
```
Comment (dpfaffenbauer) [inline lib/Maintenance/Tasks/CleanupBrickTablesTask.php]: inject via DI

Comment (brusch) [reply lib/Maintenance/Tasks/CleanupBrickTablesTask.php]: @weisswurstkanone no, please not, it will break the installer ;) Thanks!

**Comment by dvesh3** [comment]
same issue with field collections :)
