### PR TITLE
Fix duplicate relations on event listeners save

### LINKED ISSUE #17367: [Bug]: DataObjects onPostAdd Event Listener makes duplicate Object Relation
### Pimcore version

11.3.0

### Steps to reproduce

- create `order` & `orderItem` classes
- add input field (e.g. "filepath")
- add Many-To-One Relation in orderItem linking to the `order` class
- create Event Listener - pimcore.dataobject.onPostAdd

```
public function onPostAdd(DataObjectEvent $event)
{
...
            $object = $event->getObject();

            if ($object instanceof OrderItem) {
                $orderItem = $object;
                $filePath = $orderItem->getFilepath();

                // generate new filepath on orderitem
                $newFilePath = $this->modifyFilePath($filePath);
                $orderItem->setFilepath($newFilePath)
                    ->save();
            }
...
}
```

- create a new order object (order `#1`)
- create a new orderItem object, set Order = order `#1` 

### Actual Behavior

A new order created with one orderItem.

### Expected Behavior

A new order created with duplicate orderItem in the order grid and in the twig template. 
In `objects`, `object_query_OrderItem`, `object_OrderItem` & `object_store_OrderItem` table, it's only recorded 1 order item. But, in the `object_relations_OrderItem`, there is duplicated data for relation data with "order".

### PR DESCRIPTION
**Pull request by cuca24**
## Changes in this pull request  
Resolves #
Duplicate relations on event listeners save
 
## Additional info

Prerequisite
1. Object with at least one data type relation
2. Event Listener that listens to event pimcore.dataobject.postAdd
3. Inside event listener additional save call on target element in event

What happens is that if we have event listener pimcore.dataobject.postAdd or pimcore.dataobject.postUpdate and inside that function we have to call additional save in that case all relations inside of that object would get duplicate. 

This happens because of the calculation of the delta determines that there is no records for relation id db, introduced here: https://github.com/pimcore/pimcore/commit/5a91072f027b4b7d61859d830a167ab8406b177f

Although there is noting wrong with the delta calculation itself, the problem is that state of relations has been temporary cached inside __rawRelationData. Now Concrete class itself has `$this->__rawRelationData = null` but it happens too late, as event for post add/post update is dispatched earlier and therefore any additional calls to save inside listeners will duplicate relations. 

To correct this late call i moved `$this->__rawRelationData = null`  into parent class AbstractObject as well as full variable there. With this change there is no duplication of relations data.

### CODE REVIEW

**Comment by fashxp** [comment]
@dpfaffenbauer any thoughts on this?

**Comment by kingjia90** [comment]
looks like a follow up of https://github.com/pimcore/pimcore/pull/16596 , just linking it for code documentation purposes

**Comment by mcop1** [comment]
Hello @cuca24 , there is also a getter for the property you moved. What do you think about moving it to the abstract class too?

**Comment by cuca24** [comment]
Agree, I moved it to abstract class.

**Comment by mcop1** [comment]
@cuca24 Thank you! One last thing, could you please take a look at the merge conflict and tag me after it was resolved? Will merge it then.

**Comment by cuca24** [comment]
Thanks @mcop1 done.

**Comment by mattamon** [comment]
> Thanks @mcop1 done.

Hey @cuca24 can you recheck again for the failing tests? Seems like the `getClassId` is not available everywhere.

**Comment by cuca24** [comment]
Hey @mattamon Thanks

So yes  $this->getClassId() doesn't exist in AbstractObject it will be populated later in child Concrete class.

@mattamon or anybody else i need your advice how to pull out classId. I could just make a protected variable classId in AbstractObject and use it, other methods as i can see is to store variable in Dao object and read it from there. What would be preferred pimcore's way of doing it.

**Comment by oriiyx** [comment]
Is there any known workaround for now? 🤔

**Comment by mattamon** [comment]
> Hey @mattamon Thanks
> 
> So yes $this->getClassId() doesn't exist in AbstractObject it will be populated later in child Concrete class.
> 
> @mattamon or anybody else i need your advice how to pull out classId. I could just make a protected variable classId in AbstractObject and use it, other methods as i can see is to store variable in Dao object and read it from there. What would be preferred pimcore's way of doing it.

Hey @cuca24 sorry I was on vacation.

For the static error to go away, we need to define the class in the abstract. 
The preferred way would be to define the classId method as an abstract method. Guess there is no need to define a property classid.

WDYT?

**Comment by cuca24** [comment]
Hey @mattamon 

> For the static error to go away, we need to define the class in the abstract.
> The preferred way would be to define the classId method as an abstract method. Guess there is no need to define a property classid.

You mean to add `abstract function getClassId(): ?string;` into AbstractObject? 
If so than DataObject class must also be declared as abstract, but this cannot happen as DataObject is instantiated 
For example in Pimcore\Model\Element\Service  `DataObject::getByPath($path) ` and in other occasions too.

**Comment by mattamon** [comment]
> Hey @mattamon
> 
> > For the static error to go away, we need to define the class in the abstract.
> > The preferred way would be to define the classId method as an abstract method. Guess there is no need to define a property classid.
> 
> You mean to add `abstract function getClassId(): ?string;` into AbstractObject? If so than DataObject class must also be declared as abstract, but this cannot happen as DataObject is instantiated For example in Pimcore\Model\Element\Service `DataObject::getByPath($path) ` and in other occasions too.

I just checked and yes you are right sorry. This is a conundrum that the DataObject is another layer inbetween the concret and the abstract.

Either we would need to make it abstract or implement the getClassId in the DataObject. The first option is not possible and the second is not ideal. 

Let's go for the protected variable then and implement the function in the abstract please.

**Comment by dpfaffenbauer** [comment]
@fashxp sorry, I did not see that you pinged me here. What confuses me, that the issue itself also happens on Pimcore 10, so pre delta calculations for relations.

File: models/DataObject/AbstractObject.php [hunk 1]
```diff
@@ -966,6 +983,39 @@ public function getChildrenSortOrder(): string
...
+    public function setClassId(string $classId): static
+    {
+        $this->classId = $classId;
+
+        return $this;
+    }
+
+    public function getClassId(): ?string
+    {
+        if (isset($this->classId)) {
```
Comment (mattamon) [inline models/DataObject/AbstractObject.php]: @cuca24 thank you for moving the method and the property. I am thinking about also improving the method itself.
Since the setClassId has now a string parameter, we could remove the string cast from the getter. Also we do not need the `isset` anymore right? Since classId always exists and it returns null anyways if the setter is not called.
WDYT?

Comment (cuca24) [reply models/DataObject/AbstractObject.php]: @mattamon You are totally right. PR updated :)

**Review by mattamon — APPROVED** [review]
Looks good to me now! 
Thanks for your effort!

File: models/DataObject/AbstractObject.php [hunk 2]
```diff
@@ -115,6 +116,19 @@ abstract class AbstractObject extends Model\Element\AbstractElement
      */
     protected ?string $childrenSortOrder = null;
 
+    /**
+     * @internal
+     *
+     * @var string|null
+     */
+    protected $classId = null;
```
Comment (blankse) [inline models/DataObject/AbstractObject.php:124]: Use native types instead of php doc.

```suggestion
    /**
     * @internal
     */
    protected ?string $classId = null;
```

File: models/DataObject/AbstractObject.php [hunk 3]
```diff
@@ -115,6 +116,17 @@ abstract class AbstractObject extends Model\Element\AbstractElement
      */
     protected ?string $childrenSortOrder = null;
 
+    /**
+     * @internal
+     */
+    protected ?string $classId = null;
```
Comment (blankse) [inline models/DataObject/AbstractObject.php]: I'm sorry, but we have to revert the last commit. In the concrete classes it is also declared without native types and a syntax error occurs.

```suggestion
    /**
     * @internal
     *
     * @var string|null
     */
    protected $classId = null;
```
