### PR TITLE
Fix Version20210324152822 migration checks

### LINKED ISSUE #14065: Version20210324152822 migration breaks with translations-provider-interfaces
### Expected behavior

Migration should be executed without any issues.

### Actual behavior

[Migration](https://github.com/pimcore/pimcore/blob/83142b53cfd5a791e3c6167470a66336fd03da22/bundles/CoreBundle/src/Migrations/Version20210324152822.php#L33) breaks as it tries to update bundle table `translations_interface_bundle__jobs` along with translation tables.

```console
[error] Migration Pimcore\Bundle\CoreBundle\Migrations\Version20210324152822 failed during Execution. Error: "An exception occurred while executing 'ALTER TABLE `translations_interface_bundle__jobs` ADD COLUMN `type` varchar(10) DEFAULT NULL AFTER `key`':
 
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'key' in 'translations_interface_bundle__jobs'"

```

### Steps to reproduce

- Install `translations-provider-interfaces` bundle
- Execute migration `Pimcore\Bundle\CoreBundle\Migrations\Version20210324152822`

### PR DESCRIPTION
**Pull request by dvesh3**
## Changes in this pull request  
Resolves #14065

### CODE REVIEW

File: models/Translation.php [hunk 1]
```diff
@@ -262,6 +262,17 @@ public static function getValidLanguages(string $domain = self::DOMAIN_DEFAULT):
         return Tool::getValidLanguages();
     }
 
+    /**
+     *
+     * @return array
```
Comment (blankse) [inline models/Translation.php]:
```suggestion
     * @return string[]
```
