### PR TITLE
[Bug]: Fix multisite link 

### LINKED ISSUE #17473: [Bug]: Multisite Link
### Pimcore version

11.x

### Steps to reproduce

Add 2 sites
- Site 1
- Site 2

Create in a wysiwyg on Site 1 a link to Site 2.

### Actual Behavior

The link is rendered as https://site2.comhttps//site2.com/link/to/path

### Expected Behavior

The link should be rendered as https://site2.com/link/to/path
or just /link/to/path (if it's on the same site).

I suspect it has something todo with #16892, because if I delete this change everything works as expected.
=> This PR was created because of #16595, but I can't reproduce this problem (it only shows the sitename in the wysiwyg link editor, what I think is correct).

### PR DESCRIPTION
**Pull request by kingjia90**
## Changes in this pull request  
Resolves https://github.com/pimcore/pimcore/issues/17473

## Additional info
If the url belonging to another site is hardcoded or already converted to the right domain (eg. absolute url instead of relative), then it was returning wrong urls by be re-appending the site Main domain, resulting in an url as `https://site2.comhttps//site2.com/link/to/path`

### CODE REVIEW

File: lib/Tool/Text.php [hunk 1]
```diff
@@ -82,7 +82,9 @@ public static function wysiwygText(?string $text, array $params = []): ?string
 
                             $site = Frontend::getSiteForDocument($element);
                             if ($site instanceof Site) {
-                                $path = Tool::getRequestScheme() . '://' . $site->getMainDomain() . preg_replace('~^' . preg_quote($site->getRootPath(), '~') . '~', '', $path);
+                                if (preg_match('~^' . preg_quote($site->getRootPath(), '~') . '~', $path)) {
```
Comment (kingjia90) [inline lib/Tool/Text.php:85]: maybe it would be better to check if `$site->getMainDomain()` is already there? 🤔
