### PR TITLE
[Authentication] Do not close session on authenticateSession

### LINKED ISSUE #11927: [Bug]: Authentication is closing session when its not supposed to
### Expected behavior

`Authentication::authenticateSession($request);` should find the current Admin User in the Session

### Actual behavior

`Authentication::authenticateSession($request);` finds the current user, but it uses `AdminSessionHandler::useSessionAttributeBag` which runs `writeClose` closing the current session and therefore hindering Symfony from sending the right newly, generated and migrated, session ID to the user since the session is actually closed.

### Steps to reproduce

Enabled Pimcore Targeting:

```
pimcore:
    targeting:
        enabled: false
```

And authenticate to a firewall. In my case it happens with CoreShop Tests: https://github.com/coreshop/CoreShop/pull/1970/files#diff-2f8cab0f04dcf2454dbe1699f7f35fd8d169952ad38ba6baee510b20bde8ef6cR5

### PR DESCRIPTION
**Pull request by dvesh3**
## Changes in this pull request  
Resolves #11927

### CODE REVIEW

**Comment by brusch** [comment]
Hmm, I think that has some unwanted side-effects as well, because actually we don't want to keep the session open here (it's about concurrency and session locks). So this fix would cause performance issues (especially in the admin UI) when using a session handler that uses locks (e.g. file handler).

**Comment by brusch** [comment]
Hmm, I think that has some unwanted side-effects as well, because actually we don't want to keep the session open here (it's about concurrency and session locks). So this fix would cause performance issues (especially in the admin UI) when using a session handler that uses locks (e.g. file handler).

**Comment by brusch** [comment]
Maybe a solution could be to change the behavior depending on the context, so if in admin context, we keep the current behavior, if outside, the AdminSessionHandler just does nothing in `writeClose()`?

**Comment by dvesh3** [comment]
> Maybe a solution could be to change the behavior depending on the context, so if in admin context, we keep the current behavior, if outside, the AdminSessionHandler just does nothing in `writeClose()`?

@brusch I changed it to this solution now. thanks!

File: bundles/AdminBundle/Session/Handler/AdminSessionHandler.php [hunk 1]
```diff
@@ -98,7 +108,12 @@ public function useSessionAttributeBag(callable $callable, string $name = 'pimco
 
         $result = call_user_func_array($callable, [$attributeBag, $session]);
 
-        $this->writeClose();
+        // write & close session when in admin context
+        // https://github.com/pimcore/pimcore/pull/12022#issuecomment-1119451897
+        $request = $this->requestStack->getCurrentRequest();
+        if ($this->matchesPimcoreContext($request, PimcoreContextResolver::CONTEXT_ADMIN)) {
```
Comment (brusch) [inline bundles/AdminBundle/Session/Handler/AdminSessionHandler.php]: I think we also need to consider `$requestHelper->isFrontendRequestByAdmin($request)` here, so that the editmode is not blocking anything.

**Review by brusch — CHANGES_REQUESTED** [review]

File: bundles/AdminBundle/Session/Handler/AdminSessionHandler.php (hunk 1 above)
Comment (dvesh3) [reply bundles/AdminBundle/Session/Handler/AdminSessionHandler.php]: done 😉

File: bundles/AdminBundle/Session/Handler/AdminSessionHandler.php [hunk 2]
```diff
@@ -98,7 +108,15 @@ public function useSessionAttributeBag(callable $callable, string $name = 'pimco
 
         $result = call_user_func_array($callable, [$attributeBag, $session]);
 
-        $this->writeClose();
+        // write & close session when in admin context
+        // https://github.com/pimcore/pimcore/pull/12022#issuecomment-1119451897
+        $request = $this->requestHelper->getCurrentRequest();
+        if (
+            $this->matchesPimcoreContext($request, PimcoreContextResolver::CONTEXT_ADMIN) &&
```
Comment (brusch) [inline bundles/AdminBundle/Session/Handler/AdminSessionHandler.php]:
```suggestion
            $this->matchesPimcoreContext($request, PimcoreContextResolver::CONTEXT_ADMIN) ||
```
This should be an `or` as the context it not admin in case of `isFrontendRequestByAdmin() === true`
See e.g. https://github.com/pimcore/pimcore/blob/d124b16a837567ed9b7ff010fdeff6e82e9bfaf3/bundles/AdminBundle/EventListener/AdminSecurityListener.php#L70

I'm also just thinking whether we should do the check on the main request and cache the result for further use? wdyt?

**Review by brusch — CHANGES_REQUESTED** [review]

File: bundles/AdminBundle/Session/Handler/AdminSessionHandler.php (hunk 2 above)
Comment (dvesh3) [reply bundles/AdminBundle/Session/Handler/AdminSessionHandler.php]: Changed to `||` check and added `$canWriteAndClose` property for caching the result for subsequent requests.

File: bundles/AdminBundle/Session/Handler/AdminSessionHandler.php [hunk 3]
```diff
@@ -273,4 +272,23 @@ public function writeClose()
...
+            if (
+                $this->matchesPimcoreContext($request, PimcoreContextResolver::CONTEXT_ADMIN) ||
+                $this->requestHelper->isFrontendRequestByAdmin($request)
+            ) {
+                $this->canWriteAndClose = true;
+            }
+        }
+
+        return $this->canWriteAndClose;
+    }
```
Comment (jdreesen) [inline bundles/AdminBundle/Session/Handler/AdminSessionHandler.php]: What about writing it like this? 
For me this is more readable:

```suggestion
    private function shouldWriteAndClose(): bool
    {
        return $this->canWriteAndClose ??= $this->isAdminRequest($this->requestHelper->getMainRequest());
    }

    /**
     * @return bool
     */
    private function isAdminRequest(Request $request): bool
    {
        return $this->matchesPimcoreContext($request, PimcoreContextResolver::CONTEXT_ADMIN)
            || $this->requestHelper->isFrontendRequestByAdmin($request);
    }
```

Comment (dvesh3) [reply bundles/AdminBundle/Session/Handler/AdminSessionHandler.php]: and reusable as well 😉 thanks!

**Comment by brusch** [comment]
Great - thanks guys! 👍

**Review by brusch — APPROVED** [review]
