### PR TITLE
Model::getByName shouldn't catch any exceptions

### LINKED ISSUE #7322: Model::getById() ::getByPath() ::getByName() ...  shouldn't catch any Exceptions

### LINKED ISSUE #7591: Model::getByName shouldn't catch any exceptions
Follow-up of #7322

### PR DESCRIPTION
**Pull request by weisswurstkanone**
resolves #7591 
resolves #7322

### CODE REVIEW

File: models/DataObject/ClassDefinition/Dao.php [hunk 1]
```diff
@@ -74,6 +76,12 @@ public function getIdByName($name)
         } catch (\Exception $e) {
         }
 
+        if (empty($id)) {
+            throw new Model\Exception\NotFoundException(sprintf(
+                'Class with with name "%s" does not exist.',  $name
```
Comment (brusch) [inline models/DataObject/ClassDefinition/Dao.php:81]:
```suggestion
                'Data object class definition with with name "%s" does not exist.',  $name
```

File: models/DataObject/Classificationstore/CollectionConfig/Dao.php [hunk 2]
```diff
@@ -66,10 +66,10 @@ public function getByName($name = null)
 
         $data = $this->db->fetchRow('SELECT * FROM ' . self::TABLE_NAME_COLLECTIONS . ' WHERE name = ? and storeId = ?', [$name, $storeId]);
 
-        if ($data['id']) {
+        if (!empty($data['id'])) {
             $this->assignVariablesToModel($data);
         } else {
-            throw new \Exception('Config with name: ' . $this->model->getName() . ' does not exist');
+            throw new Model\Exception\NotFoundException(sprintf('Collection Config with name "%s" does not exist.', $name));
```
Comment (brusch) [inline models/DataObject/Classificationstore/CollectionConfig/Dao.php:72]:
```suggestion
            throw new Model\Exception\NotFoundException(sprintf('Classification store collection config with name "%s" does not exist.', $name));
```

File: models/DataObject/Classificationstore/GroupConfig/Dao.php [hunk 3]
```diff
@@ -68,10 +68,10 @@ public function getByName($name = null)
 
         $data = $this->db->fetchRow('SELECT * FROM ' . self::TABLE_NAME_GROUPS . ' WHERE name = ? and storeId = ?', [$name, $storeId]);
 
-        if ($data['id']) {
+        if (!empty($data['id'])) {
             $this->assignVariablesToModel($data);
         } else {
-            throw new \Exception('Config with name: ' . $this->model->getName() . ' does not exist');
+            throw new Model\Exception\NotFoundException(sprintf('Group Config with name "%s" does not exist.', $name));
```
Comment (brusch) [inline models/DataObject/Classificationstore/GroupConfig/Dao.php:74]:
```suggestion
            throw new Model\Exception\NotFoundException(sprintf('Classification store group config with name "%s" does not exist.', $name));
```

File: models/DataObject/Classificationstore/KeyConfig/Dao.php [hunk 4]
```diff
@@ -68,10 +68,10 @@ public function getByName($name = null)
 
         $data = $this->db->fetchRow($stmt);
 
-        if ($data['id']) {
+        if (!empty($data['id'])) {
             $this->assignVariablesToModel($data);
         } else {
-            throw new \Exception('KeyConfig with name: ' . $this->model->getName() . ' does not exist');
+            throw new Model\Exception\NotFoundException(sprintf('Key Config with name "%s" does not exist.', $name));
```
Comment (brusch) [inline models/DataObject/Classificationstore/KeyConfig/Dao.php:74]:
```suggestion
            throw new Model\Exception\NotFoundException(sprintf('Classification store key config with name "%s" does not exist.', $name));
```

File: models/DataObject/Classificationstore/StoreConfig/Dao.php [hunk 5]
```diff
@@ -65,10 +65,10 @@ public function getByName($name = null)
 
         $data = $this->db->fetchRow('SELECT * FROM ' . self::TABLE_NAME_STORES . ' WHERE name = ?', $name);
 
-        if ($data['id']) {
+        if (!empty($data['id'])) {
             $this->assignVariablesToModel($data);
         } else {
-            throw new \Exception('StoreConfig with name: ' . $this->model->getName() . ' does not exist');
+            throw new Model\Exception\NotFoundException(sprintf('Store Config with name "%s" does not exist.', $name));
```
Comment (brusch) [inline models/DataObject/Classificationstore/StoreConfig/Dao.php:71]:
```suggestion
            throw new Model\Exception\NotFoundException(sprintf('Classification store config with name "%s" does not exist.', $name));
```

File: models/User/AbstractUser/Dao.php [hunk 6]
```diff
@@ -61,7 +61,7 @@ public function getByName($name)
         if (!empty($data['id'])) {
             $this->assignVariablesToModel($data);
         } else {
-            throw new \Exception("user doesn't exist");
+            throw new Model\Exception\NotFoundException("user doesn't exist");
```
Comment (brusch) [inline models/User/AbstractUser/Dao.php:64]:
```suggestion
            throw new Model\Exception\NotFoundException(sprintf('User with name "%s" does not exist', $name));
```
