### PR TITLE
[Bug]: Fix nested block index

### LINKED ISSUE #17927: [Bug]: current value for nested pimcore blocks is wrong with new syntax
### Pimcore version

11.5.0

### Steps to reproduce

```
{% for i in pimcore_block('foo').iterator %}
  {% for j in pimcore_block('bar').iterator %}

  {% endfor %}

  {{ dump(pimcore_block('foo').current) }}
{% endfor %}
```

```
{% pimcoreblock 'foo' %}
  {% pimcoreblock 'bar' %}

  {% endpimcoreblock %}

  {{ dump(_block.current) }}
{% endpimcoreblock %}
```

Create two items for "foo" and three "bar" items for the first "foo".

### Actual Behavior

The first block dumps:

0
1

The second block dumps:

-1
-1

Without the inner block ("bar") `dump(_block.current)` has the correct values.

### Expected Behavior

The `_block` variable should be scoped to the block, so the inner block should not affect the `_block` variable of the outer block.

### PR DESCRIPTION
**Pull request by kingjia90**
## Changes in this pull request  
Resolves https://github.com/pimcore/pimcore/issues/17927

## Additional info
A little hacky&quick workaround... i am sure the real issue is somewhere inside this "dark area" http://github.com/pimcore/pimcore/blob/3322e055636b9e96a758bf858e02bafc82a3f75c/models/Document/Editable/Block.php#L111  😄

### CODE REVIEW

File: models/Document/Editable/Block.php [hunk 1]
```diff
@@ -329,6 +329,15 @@ public function getCurrent(): int
         return $this->current - 1;
     }
 
+    /**
+     * @internal
+     *
+     */
+    public function setCurrent(int $current): void
+    {
+        $this->current = $current + 1;
```
Comment (kingjia90) [inline models/Document/Editable/Block.php:338]: `+1` because the getCurrent() has a `-1`...

File: lib/Twig/Node/BlockNode.php [hunk 2]
```diff
@@ -56,8 +56,8 @@ private function getPhpCode(string $splitChars): string
         return <<<PHP
         \$editableExtension = \$this->env->getExtension('Pimcore\Twig\Extension\DocumentEditableExtension');
         \$block = \$editableExtension->renderEditable(\$context, 'block', '{$this->blockName}', $optionsString);
-
-        foreach(\$block->getIterator() as \$index) {
+        foreach(\$block->getIterator() as \$key=>\$index) {
```
Comment (jdreesen) [inline lib/Twig/Node/BlockNode.php]:
```suggestion
        foreach(\$block->getIterator() as \$key => \$index) {
```

**Comment by cadeyrn** [comment]
@kingjia90 Is the work on this PR blocked by something?

**Comment by kingjia90** [comment]
> @kingjia90 Is the work on this PR blocked by something?

Thank you for the reminder, i am waiting for a feedback from @brusch , my apologies for the long wait, this PR went under the radar as we were busy around the Inspire 2025, i am tagging him for a reminder as well

**Comment by cadeyrn** [comment]
No problem at all. I just wanted to make sure that it is not forgotten as long as Pimcore 11 is not yet EOL. 😀 Thanks for working on it!

**Review by brusch — APPROVED** [review]
LGTM and should be safe 👍
