### PR TITLE
[Bug]: ReverseObjectRelation data is inherited

### LINKED ISSUE #11818: [Bug]: ReverseObjectRelation data is inherited
### Expected behavior

ReverseObjectRelation data is inherited should not be inherited as it was discussed here:
https://github.com/pimcore/pimcore/issues/11529

### Actual behavior

Data is inherited. As a starting point see these lines of code
https://github.com/pimcore/pimcore/blob/f415841de9a3b09308a2be99580261a31e4fec40/bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php#L619-L626
...

### Steps to reproduce

As described in https://github.com/pimcore/data-hub/issues/498

### PR DESCRIPTION
**Pull request by mcop1**
Resolves #11818

### CODE REVIEW

**Comment by fashxp** [comment]
please rebase to 10.3

**Comment by mcop1** [comment]
> please rebase to 10.3

Needs to be implemented in 10.x (10.4), because the method is not available in 10.3, see
https://github.com/pimcore/pimcore/issues/11529#issuecomment-1056779990

File: bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php [hunk 1]
```diff
@@ -618,7 +618,7 @@ private function getDataForField($object, $key, $fielddefinition, $objectFromVer
 
             $relations = $object->getRelationData($refKey, !$fielddefinition instanceof ReverseObjectRelation, $refId);
 
-            if (empty($relations) && !empty($parent)) {
+            if (empty($relations) && !empty($parent) && $fielddefinition->supportsInheritance()) {
```
Comment (dvesh3) [inline bundles/AdminBundle/Controller/Admin/DataObject/DataObjectController.php]: I would check if field supports inheritance before checking relations & parent
```suggestion
            if ($fielddefinition->supportsInheritance() && empty($relations) && !empty($parent)) {
```

**Review by dvesh3 — APPROVED** [review]
