### PR TITLE
[Bug]: Error OpenStreetMap Cors Headers 

### LINKED ISSUE #15661: [Bug]: Error OpenStreetMap Cors Headers
### Pimcore version

ALL version

### Steps to reproduce

- Go to the https://demo.pimcore.fun/admin/ and login **admin / demo**
- Open a car object (ex : /Product Data/Cars/ac cars/Cobra 427)
- Set a location in the **Sale Information** tab
- An error occured each time you open the object

image
image

### Actual Behavior

Hello,

I would like to report you a cross headers error when you have a GeoCoordinate field.
Indeed the URL  : https://nominatim.openstreetmap.org/reverse?format=json&lat=47.040182144807&lon=2.8125&addressdetails=1 is blocking when Pimcore try to get the location from the Latitude and longitude.
If we analyzed the console we can see that : 
`Access to XMLHttpRequest at 'https://nominatim.openstreetmap.org/reverse?format=json&lat=47.040182144806664&lon=2.8125&addressdetails=1&_dc=1690875423920' from origin 'https://demo.pimcore.fun' has been blocked by CORS policy: Request header field x-pimcore-extjs-version-major is not allowed by Access-Control-Allow-Headers in preflight response.`

So it's maybe OpenStreepMap with their policy (https://operations.osmfoundation.org/policies/nominatim/) that blocked Pimcore headers. 

Can you investigate ?

May be if you don't send the extra headers (X-Pimcore-Csrf-Token, X-Pimcore-Extjs-Version-Major, X-Pimcore-Extjs-Version-Minor) it will be working ?

Thanks

### Expected Behavior

- Open an object with a location set and don't have the Popup error ! 
- Set a location and don't have the error.

### PR DESCRIPTION
**Pull request by robertSt7**
resolves #15661

### CODE REVIEW

File: bundles/AdminBundle/Resources/public/js/pimcore/helpers.js [hunk 1]
```diff
@@ -3288,3 +3288,12 @@ pimcore.helpers.treeDragDropValidate = function (node, oldParent, newParent) {
...
     return true;
 };
+
+pimcore.helpers.sendRequestWithoutDefaultHeaders = function (requestFunction) {
+    const defHeaders = Ext.Ajax.getDefaultHeaders();
+    Ext.Ajax.setDefaultHeaders(null);
+
+    requestFunction();
+
+    Ext.Ajax.setDefaultHeaders(defHeaders);
```
Comment (blankse) [inline bundles/AdminBundle/Resources/public/js/pimcore/helpers.js]:
```suggestion
    try {
        requestFunction();
    } finally {
        Ext.Ajax.setDefaultHeaders(defHeaders);
    }
```

**Comment by brusch** [comment]
I'm just wondering whether it would be better to just use vanilla JS instead: 
https://github.com/pimcore/admin-ui-classic-bundle/blob/a1c7fd93bf39b31374d9eb16eb5ff23c159d4e51/public/js/pimcore/startup.js#L518 

WDYT?

File: bundles/AdminBundle/Resources/public/js/pimcore/helpers.js [hunk 2]
```diff
@@ -3288,3 +3288,29 @@ pimcore.helpers.treeDragDropValidate = function (node, oldParent, newParent) {
 
     return true;
 };
+
+pimcore.helpers.sendRequestWithoutDefaultHeaders = function (
```
Comment (blankse) [inline bundles/AdminBundle/Resources/public/js/pimcore/helpers.js]: Why not just one object parameter like Ext.Ajax.request()?

File: bundles/AdminBundle/Resources/public/js/pimcore/helpers.js [hunk 3]
```diff
@@ -3288,3 +3288,30 @@ pimcore.helpers.treeDragDropValidate = function (node, oldParent, newParent) {
...
```
Comment (kingjia90) [inline bundles/AdminBundle/Resources/public/js/pimcore/helpers.js]:
```suggestion
// Sends an Ajax request, it is recommended to be used when doing simple calls or to third-party services, in contrast to Ext.Ajax.request which, by default, sends extra info (eg. custom headers) that are usually needed to be working within Pimcore interface.
pimcore.helpers.sendRequest = function (
```
suggesting to rename the function to a shorter name and add a comment or so, wdyt?

File: bundles/AdminBundle/Resources/public/js/pimcore/helpers.js (hunk 2 above)
Comment (robertSt7) [reply bundles/AdminBundle/Resources/public/js/pimcore/helpers.js]: Hi @blankse because of code quality I think we should communicate with the function which parameters are allowed and not just putting all in one object, where you can pass whatever you want.

Comment (blankse) [reply bundles/AdminBundle/Resources/public/js/pimcore/helpers.js]: You can use JSDoc to communicate the possible object keys.

Comment (kingjia90) [reply bundles/AdminBundle/Resources/public/js/pimcore/helpers.js]: Resolving: discussed in the daily and would not consider adding/using JSDoc yet, so will merge in the current state.
