### PR TITLE
Fix invalidating thumbnails on asset save

### LINKED ISSUE #15273: [Bug]: Pimcore invalidates all thumbnails as soon as you just press Save on the asset
### Pimcore version

10.5, 10.6

### Steps to reproduce

Have say 5 thumbnail configs, auto-formats + 1x, 2x, you come out to about 45 thumbnails per image.

If I go to Asset edit and just press Save (even without doing any changes), suddenly all of those thumbnails are considered out of date and will need to be regenerated. If you say import alt metadata to 10k images, **suddenly you have 500k thumbnails to generate** even though they should all still be up to date.

### Expected / actual behavior

Thumbnails should be considered **out of date if bytes in the thumbnail file would have changed** if we regenerated it compared to what we have now. In any other case, the thumbnail should be seen as up to date.

Edit: see here for more info why this is bad:
https://github.com/pimcore/pimcore/issues/15231#issuecomment-1572012136

### PR DESCRIPTION
**Pull request by dvesh3**
## Changes in this pull request  
Resolves #15273

### <samp>🤖 Generated by Copilot at 5a39246</samp>

This pull request adds a new `dataModificationDate` property and column to the `Asset` class and table, respectively, to track the last change to the asset data. It also updates the thumbnail processor to use this property for cache validation. The purpose of this pull request is to improve the performance and accuracy of the image thumbnail generation and caching.

### <samp>🤖 Generated by Copilot at 5a39246</samp>

> _Oh, we are the coders of Pimcore_
> _And we work on the assets galore_
> _We added `dataModificationDate`_
> _To make the thumbnails update at a faster rate_

### <samp>🤖 Generated by Copilot at 5a39246</samp>

*  Add a new column `dataModificationDate` to the `assets` table to store the timestamp of the last change to the asset data ([link](https://github.com/pimcore/pimcore/pull/15748/files?diff=unified&w=0#diff-30df47f9d518790f988ef83ee87bf7e0fa978c7c93cee0097e44a215d20cc7c6R1-R46), [link](https://github.com/pimcore/pimcore/pull/15748/files?diff=unified&w=0#diff-c624477d3d2ae554e390ee2b45c5f4c48c160471609aee1e4df2478ab395c4a8R36))
*  Add a new property `dataModificationDate` and its getter and setter methods to the `Asset` class to access and update the new column ([link](https://github.com/pimcore/pimcore/pull/15748/files?diff=unified&w=0#diff-867a334e4cc9a097b215afcb2b1f4949910cb2f2103a2cd997d8699d4d414fc9R159-R181))
*  Update the `setStream` method of the `Asset` class to set the `dataModificationDate` property and column whenever a new stream of data is set for the asset ([link](https://github.com/pimcore/pimcore/pull/15748/files?diff=unified&w=0#diff-867a334e4cc9a097b215afcb2b1f4949910cb2f2103a2cd997d8699d4d414fc9L1221-R1245))
*  Use the `dataModificationDate` property of the asset instead of the `modificationDate` property when checking the thumbnail cache validity in the `process` method of the `Processor` class ([link](https://github.com/pimcore/pimcore/pull/15748/files?diff=unified&w=0#diff-16840b1fd40929e8fda46a67eae733c84fc71dc91da6a38097ba58b5da0c321cL197-R197))

### CODE REVIEW

File: models/Asset.php [hunk 1]
```diff
@@ -155,6 +155,29 @@ class Asset extends Element\AbstractElement
      */
     protected $dataChanged = false;
 
+    /**
+     * @internal
+     *
+     * @var int|null
+     */
+    protected $dataModificationDate = null;
```
Comment (blankse) [inline models/Asset.php]:
```suggestion
    protected ?int $dataModificationDate = null;
```

File: models/Asset.php [hunk 2]
```diff
@@ -818,7 +858,7 @@ protected function postPersistData()
 
     /**
      * @param bool $setModificationDate
-     * @param bool $saveOnlyVersion
+     * @param bool $saveOnlyVersionn
```
Comment (blankse) [inline models/Asset.php]:
```suggestion
     * @param bool $saveOnlyVersion
```

File: models/Asset/Image/Thumbnail/Processor.php [hunk 3]
```diff
@@ -484,6 +400,118 @@ public static function process(Asset $asset, Config $config, $fileSystemPath = n
...
 
+    /**
+     * @param Adapter $image
+     * @param Asset $asset
+     * @param Config $config
+     * @param array|null $transformations
+     *
+     * @return void
+     */
+    private static function applyTransformations(Adapter $image, Asset $asset, Config $config, ?array $transformations)
```
Comment (blankse) [inline models/Asset/Image/Thumbnail/Processor.php]:
```suggestion
    private static function applyTransformations(Adapter $image, Asset $asset, Config $config, ?array $transformations): void
```

File: models/Asset.php [hunk 4]
```diff
@@ -155,6 +155,29 @@ class Asset extends Element\AbstractElement
...
+        return $this->dataModificationDate;
+    }
+
+    /**
+     * @param int|null $dataModificationDate
+     */
+    public function setDataModificationDate(?int $dataModificationDate): void
+    {
+        $this->dataModificationDate = $dataModificationDate;
+    }
```
Comment (blankse) [inline models/Asset.php]:
```suggestion
    /**
     * @param int|null $dataModificationDate
     *
     * @return $this
     */
    public function setDataModificationDate(?int $dataModificationDate): static
    {
        $this->dataModificationDate = $dataModificationDate;
        
        return $this;
    }
```

File: models/Asset/Image/Thumbnail/Processor.php [hunk 5]
```diff
@@ -250,6 +257,7 @@ public static function process(Asset $asset, Config $config, $fileSystemPath = n
                 $fileExists = true;
             }
         } catch (\Exception $e) {
+            Logger::warn($e->getMessage());
```
Comment (robertSt7) [inline models/Asset/Image/Thumbnail/Processor.php]: @dvesh3 I am not sure if we should add logging here. We should may get rid of the try and catch. What do you think?

Comment (dvesh3) [reply models/Asset/Image/Thumbnail/Processor.php]: we should still handle cases when there's `FilesystemException` from flysystem.

Comment (robertSt7) [reply models/Asset/Image/Thumbnail/Processor.php]: Then we can maybe ignore the exception when the file doesn't exist

Comment (dvesh3) [reply models/Asset/Image/Thumbnail/Processor.php]: how about we change the log level to debug? we do this for thumbnail generation as well.

File: bundles/CoreBundle/Migrations/Version20230814142319.php [hunk 6]
```diff
@@ -0,0 +1,48 @@
...
+    {
+        return 'Add `dataModificationDate` column to `assets` database table';
+    }
+
+    public function up(Schema $schema): void
+    {
+        if ($schema->getTable('assets')->hasColumn('dataModificationDate') === false) {
+            $this->addSql('ALTER TABLE `assets`
+                ADD COLUMN `dataModificationDate` INT(11) UNSIGNED DEFAULT NULL AFTER `modificationDate`;'
+            );
```
Comment (dkarlovi) [inline bundles/CoreBundle/Migrations/Version20230814142319.php:38]: Copy the current `modificationDate` so the values get populated? Alternatively, a command to populate it from the filesystem.

Comment (dvesh3) [reply bundles/CoreBundle/Migrations/Version20230814142319.php:38]: we don't want to have the duplicate info from `modificationDate` that increases the table size unnecessarily since the null check works at the moment. 

Also, adding a command is not useful since this needs to be run just once. If you like, you can provide a Gist of the script to populate the field from filesystem 😊

File: models/Asset/Image/Thumbnail/Processor.php (hunk 5 above)
Comment (dvesh3) [reply models/Asset/Image/Thumbnail/Processor.php]:
```suggestion
            Logger::debug($e->getMessage());
```

File: bundles/CoreBundle/Migrations/Version20230814142319.php (hunk 6 above)
Comment (dkarlovi) [reply bundles/CoreBundle/Migrations/Version20230814142319.php:38]: Functionally it's identical since the bug triggering will fill in the timestamp, but OK, I guess that's good enough too, this was meant as an optimization to avoid triggering it one more time after this bugfix getting deployed.
