### PR TITLE
provide controller results to template

### LINKED ISSUE #16447: [Bug]: Conroller Results are not sent to Template when using Pimcore Document Templates
### Pimcore version

11.x

### Steps to reproduce

- create a Pimcore Document with DefaultController::defaultAction() and set some Template ('/default/another-template.html.twig')
- give the ControllerAction an Attributes #[Template('/default/default.html.twig')] and return some data in the controller? (['testkey' => 123])
- print the testkey in both of your templates: {{ test }}
- now open your document, an error is thrown (variable testkey not set) till you remove the template in the pimcore document

### Actual Behavior

controller results are not provided for the template when using pimcore documents template setting

### Expected Behavior

controller results should be present in template

### PR DESCRIPTION
**Pull request by bitbirddev**
### Pimcore version

11.x

### Steps to reproduce

- create a Pimcore Document with DefaultController::defaultAction() and set some Template ('/default/another-template.html.twig')
- give the ControllerAction an Attributes #[Template('/default/default.html.twig')] and return some data in the controller? (['testkey' => 123])
- print the testkey in both of your templates: {{ test }}
- now open your document, an error is thrown (variable testkey not set) till you remove the template in the pimcore document

### Actual Behavior

controller results are not provided for the template when using pimcore documents template setting

### Expected Behavior

controller results should be present in template

### CODE REVIEW

File: bundles/CoreBundle/src/EventListener/Frontend/ContentTemplateListener.php [hunk 1]
```diff
@@ -91,14 +90,18 @@ public function onKernelView(ViewEvent $event): void
         );
     }
 
-    private function resolveParameters(ControllerArgumentsEvent $event, ?array $vars): array
+    private function resolveParameters(ViewEvent $event, ?array $vars): array
```
Comment (robertSt7) [inline bundles/CoreBundle/src/EventListener/Frontend/ContentTemplateListener.php]:
```suggestion
    private function resolveParameters(ViewEvent $event, array $vars): array
```
`array_merge` and `array_keys` doesn't accept null

File: bundles/CoreBundle/src/EventListener/Frontend/ContentTemplateListener.php [hunk 2]
```diff
@@ -70,7 +69,7 @@ public function onKernelView(ViewEvent $event): void
             return;
         }
 
-        $parameters = $this->resolveParameters($event->controllerArgumentsEvent, $attribute?->vars);
+        $parameters = $this->resolveParameters($event, $attribute?->vars);
```
Comment (robertSt7) [inline bundles/CoreBundle/src/EventListener/Frontend/ContentTemplateListener.php]:
```suggestion
        $parameters = $this->resolveParameters($event, $attribute?->vars ?? []);
```

**Review by robertSt7 — CHANGES_REQUESTED** [review]

File: bundles/CoreBundle/src/EventListener/Frontend/ContentTemplateListener.php [hunk 3]
```diff
@@ -91,14 +90,18 @@ public function onKernelView(ViewEvent $event): void
...
-        }
+        $mergedArray = array_merge(array_keys($controllerArguments), array_keys($controllerResults), array_keys($vars));
+        $duplicateKeys = array_unique(array_diff_assoc($mergedArray, array_unique($mergedArray)));
 
-        return $parameters;
+        if (empty($duplicateKeys)) {
+            return array_merge($controllerArguments, $controllerResults, $vars);
+        } else {
+            throw new \Exception('Duplicate keys found: '.implode(', ', array_values($duplicateKeys)).'. Please use unique names for your controller arguments, controller results and template variables.');
+        }
```
Comment (blankse) [inline bundles/CoreBundle/src/EventListener/Frontend/ContentTemplateListener.php]: I think this would be more readable
```suggestion
        if ($duplicateKeys) {
            throw new \Exception('Duplicate keys found: '.implode(', ', array_values($duplicateKeys)).'. Please use unique names for your controller arguments, controller results and template variables.');
        }

        return array_merge($controllerArguments, $controllerResults, $vars);
```

**Comment by robertSt7** [comment]
@bitbirddev Thanks a lot
