### PR TITLE
fix deadlock issues in classificationstore, fieldcollections and relations

### LINKED ISSUE #8228: [DataObject][Classificationstore] regular deadlocks when saving data objects with classification store data in a parallelized way
Deadlocks occur on tables `object_classificationstore_data_*` on a regular base when saving classification store data in a parallelized ways.

Maybe we can find ways to make locking more sophisticated to reduce deadlocks -> would improve performance of importing/updating classification store data.

### PR DESCRIPTION
**Pull request by hirakch**
fix deadlock issues in classificationstore, fieldcollections and relations

  
  

## Changes in this pull request  
Resolves #8228 

## Additional info  

Delete without having the data and insertion on the same table creates gap lock which causes deadlock for parallel processing on the same class

Also, created another PR to fix in 6.9 for legacy codes #11688

### CODE REVIEW

**Comment by dvesh3** [comment]
@hirakch please sign the CLA as this is your first PR in this repo. thanks!

**Comment by hirakch** [comment]
> @hirakch please sign the CLA as this is your first PR in this repo. thanks!

done

File: models/DataObject/Classificationstore/Dao.php [hunk 1]
```diff
@@ -64,7 +64,11 @@ public function save()
         $dataTable = $this->getDataTableName();
         $fieldname = $this->model->getFieldname();
 
-        $this->db->delete($dataTable, ['o_id' => $objectId, 'fieldname' => $fieldname]);
+        $dataExists = $this->db->fetchOne("SELECT count(*) c FROM `".$dataTable."` WHERE
+         `o_id` = '".$objectId."' AND `fieldname` = '".$fieldname."' ");
```
Comment (brusch) [inline models/DataObject/Classificationstore/Dao.php]:
```suggestion
        $dataExists = $this->db->fetchOne("SELECT o_id FROM `".$dataTable."` WHERE
         `o_id` = '".$objectId."' AND `fieldname` = '".$fieldname."' LIMIT 1");
```
Wouldn't it be faster to just fetch one column with a `LIMIT`?

**Review by brusch — CHANGES_REQUESTED** [review]

File: models/DataObject/Classificationstore/Dao.php (hunk 1 above)
Comment (hirakch) [reply models/DataObject/Classificationstore/Dao.php]: Updated the PR with the suggestion

**Comment by jdreesen** [comment]
Beware, this was merged into `10.x` but now added to the `10.3.5` milestone!

**Comment by brusch** [comment]
@jdreesen I'm just 🍒-picking it (not pushed yet), you were just to fast 😂
