### PR TITLE
[Web2print] Fix background PDF generation with wkhtmltopdf on OS X

### LINKED ISSUE #4022: [Web2print] Fix background PDF generation on OS X
I tried to generate PDF print previews on OS x which did not work. I checked the Web2print log and found this error:

> nohup: can't detach from console: Inappropriate ioctl for device

This is very easy to fix, a PR will be submitted soon

### PR DESCRIPTION
**Pull request by Ben305**
Fix "nohup: can't detach from console: Inappropriate ioctl for device" error when generating PDFs on OS x using wkthmltopdf

## Changes in this pull request  
Resolves #4022

### CODE REVIEW

**Comment by dpfaffenbauer** [comment]
ok, in my opinion: Pimcore doesn't support Mac OS as operating system, therefore Pimcore should not care about that. OSX also isn't a suitable server infrastructure to run Pimcore on.

BTW: I am also working on Mac and I never had issues with that before.

**Comment by Ben305** [comment]
I wouldn't use OS X in production, but seems suitable for me as dev environment. Chances to break anything with this bugfix are fairly small.

**Comment by dpfaffenbauer** [comment]
True, but thats not my concern. My concern is that this is another piece of code that has to be maintained and refactored as well some day. "just to support osx".

File: lib/Tool/Console.php [hunk 1]
```diff
@@ -410,6 +414,45 @@ protected static function execInBackgroundUnix($cmd, $outputFile)
...
 
+    /**
+     * @static
+     *
+     * @param string $cmd
+     * @param string $outputFile
+     *
+     * @return int
+     */
+    protected static function execInBackgroundDarwin($cmd, $outputFile)
```
Comment (brusch) [inline lib/Tool/Console.php]: This function is actually a 1:1 copy of `execInBackgroundUnix` except the `nohup` command. I guess it would be better to just add an additional parameter `$useNohup` to the existing method.

Comment (Ben305) [reply lib/Tool/Console.php]: Has been fixed
