### PR TITLE
Fix: Use LocaleServiceInterface instead LocaleService

### LINKED ISSUE #16215: [Bug]: Add support for decorating LocaleService again
### Improvement description

Decorating the [LocaleService](https://github.com/pimcore/pimcore/blob/11.x/lib/Localization/LocaleService.php) can be used to add new languages to Pimcore. In the current state this is not possible because in some places Pimcore uses the concrete Service instead of the [LocalServiceInterface](https://github.com/pimcore/pimcore/blob/11.x/lib/Localization/LocaleServiceInterface.php).

In the past this problem was already solved by https://github.com/pimcore/pimcore/pull/3021 but in preparation of Pimcore 11 (https://github.com/pimcore/pimcore/pull/13474) new type delcarations were added and now the concrete `LocaleService` is used again, which makes the decoration impossible.

### PR DESCRIPTION
**Pull request by blankse**
## Changes in this pull request  
Resolves https://github.com/pimcore/pimcore/issues/16215

### <samp>🤖 Generated by Copilot at f385e9d</samp>

Refactored document rendering to use an interface for locale service. This allows for better decoupling and testing of `DocumentRenderer` and `LocaleService`.

### <samp>🤖 Generated by Copilot at f385e9d</samp>

> _Oh we are the coders of the sea, me hearties_
> _We write the code that makes the documents shine_
> _We use `LocaleServiceInterface` for dependency_
> _And we test our code with every pull and line_

### <samp>🤖 Generated by Copilot at f385e9d</samp>

*  Replace `LocaleService` with `LocaleServiceInterface` in `DocumentRenderer` class to allow dependency injection and mocking ([link](https://github.com/pimcore/pimcore/pull/16216/files?diff=unified&w=0#diff-29ee94726c0bbd4602ec6202c94c2d68c557621d0e50f057b37efed3a299652aL23-R23), [link](https://github.com/pimcore/pimcore/pull/16216/files?diff=unified&w=0#diff-29ee94726c0bbd4602ec6202c94c2d68c557621d0e50f057b37efed3a299652aL46-R46), [link](https://github.com/pimcore/pimcore/pull/16216/files?diff=unified&w=0#diff-29ee94726c0bbd4602ec6202c94c2d68c557621d0e50f057b37efed3a299652aL54-R54))

### CODE REVIEW

File: lib/Document/Renderer/DocumentRenderer.php [hunk 1]
```diff
@@ -43,15 +43,15 @@ class DocumentRenderer implements DocumentRendererInterface
...
+    private LocaleServiceInterface $localeService;
 
     public function __construct(
         RequestHelper $requestHelper,
         ActionRenderer $actionRenderer,
         FragmentRendererInterface $fragmentRenderer,
         DocumentRouteHandler $documentRouteHandler,
         EventDispatcherInterface $eventDispatcher,
-        LocaleService $localeService
+        LocaleServiceInterface $localeService
```
Comment (robertSt7) [inline lib/Document/Renderer/DocumentRenderer.php:54]: @blankse Isn't this a BC-break, when someone extend from this class?

Comment (jdreesen) [reply lib/Document/Renderer/DocumentRenderer.php:54]: No, it's not, because it's a constructor: https://3v4l.org/vZnkL
If you change the method name in the example to something else, you'll get an exception (=BC break) but constructors have different rules (otherwise it wouldn't be possible to have additional dependencies in subclasses, for example).

Comment (blankse) [reply lib/Document/Renderer/DocumentRenderer.php:54]: @robertSt7 @jdreesen Its not a BC break. I tested it also with the old type hint to overwrite it. It works.

I noticed that the DocumentRender is also used directly. There is also a DocumentRenderInterface which should be used instead...

Comment (blankse) [reply lib/Document/Renderer/DocumentRenderer.php:54]: I created a additional PR for this for 11.2. Because we need a deprecation there: https://github.com/pimcore/pimcore/pull/16267

Comment (blankse) [reply lib/Document/Renderer/DocumentRenderer.php:54]: I created also a PR to deprecate the LocaleService aliases in 11.2 https://github.com/pimcore/pimcore/pull/16268

Comment (robertSt7) [reply lib/Document/Renderer/DocumentRenderer.php:54]: @jdreesen  & @blankse Thanks a lot for clarification

**Comment by robertSt7** [comment]
@blankse Thank you
