### PR TITLE
Fix mail settings error message - resolves#11588

### LINKED ISSUE #11588: [Improvement]: mail settings error message
### Improvement description

The error message in the following line seems a bit outdated:

https://github.com/pimcore/pimcore/blob/aa0ed48fd97757fc0b30bd2985eef2a237b373c6/lib/Mail/Plugins/RedirectingPlugin.php#L80

Should be something like: `Please update your system settings for 'pimcore.email.debug.email_addresses'`.

### PR DESCRIPTION
**Pull request by aryaantony92**
## Changes in this pull request  
Resolves #11588

### CODE REVIEW

File: lib/Mail/Plugins/RedirectingPlugin.php [hunk 1]
```diff
@@ -77,7 +77,7 @@ public function beforeSendPerformed(Mail $message)
         // additional checks if message is Pimcore\Mail
         if ($message->doRedirectMailsToDebugMailAddresses()) {
             if (empty($this->getRecipient())) {
-                throw new \Exception('No valid debug email address given in "Settings" -> "System" -> "Email Settings"');
+                throw new \Exception("Please update your system settings for 'pimcore.email.debug.email_addresses'");
```
Comment (dvesh3) [inline lib/Mail/Plugins/RedirectingPlugin.php]:
```suggestion
                throw new \Exception('No valid debug email address given in "Settings" -> "System Settings" -> "Debug"');
```
