### PR TITLE
Fix Scheduled Tasks

### LINKED ISSUE #10318: [Bug]: Scheduled Tasks
### Expected behavior

Can save a schedule task

### Actual behavior

Can not save a schedule task

### Steps to reproduce

1. Open https://demo.pimcore.fun/admin/login/deeplink?object_765_object
2. Save a new draft
3. Go to the Schedule tab and create a new item
4. Save only schedule tasks
5. Reload

### PR DESCRIPTION
**Pull request by blankse**
## Changes in this pull request  
Resolves #10318 

Also fix following issue:
The Pimcore\Maintenance\Tasks\ScheduledTasksTask can not set the active property to false.
So every maintenance execute will publish all active tasks again and again.

It is because the save method will generate a new id for every task and so the save of the task doesn't work.

### CODE REVIEW

File: models/Schedule/Task.php [hunk 1]
```diff
@@ -28,42 +28,42 @@ class Task extends Model\AbstractModel
     /**
      * @var int
      */
-    protected $id;
+    public $id;
```
Comment (brusch) [inline models/Schedule/Task.php]: I think we should leave them `protected` and use `getObjectVars()` instead, in the controller.

File: models/Document/Dao.php [hunk 2]
```diff
@@ -322,10 +322,16 @@ public function deleteAllPermissions()
 
     /**
      * Deletes all scheduled tasks assigned to the document.
+     *
+     * @param int[] $ignoreIds
      */
-    public function deleteAllTasks()
+    public function deleteAllTasks(array $ignoreIds = [])
```
Comment (brusch) [inline models/Document/Dao.php]: Should we maybe move this function to a trait, similar we do with `VersionDaoTrait`?

File: models/Asset.php [hunk 3]
```diff
@@ -1783,18 +1783,16 @@ public function setScheduledTasks($scheduledTasks)
...
-        if (is_array($this->getScheduledTasks()) && count($this->getScheduledTasks()) > 0) {
-            foreach ($this->getScheduledTasks() as $task) {
-                $task->setId(null);
-                $task->setDao(null);
-                $task->setCid($this->getId());
-                $task->setCtype('asset');
-                $task->save();
-            }
-        }
+        $scheduledTasks = $this->getScheduledTasks();
```
Comment (brusch) [inline models/Asset.php]: I think we should move the existing `ScheduledTasksTrait` to `Pimcore\Model\Element\Traits` and use it for all elements.

**Review by brusch — CHANGES_REQUESTED** [review]

File: models/Schedule/Task.php (hunk 1 above)
Comment (blankse) [reply models/Schedule/Task.php]: See https://github.com/pimcore/pimcore/pull/10320/commits/bbd11a4e66fe83da4271eef142e83e60b33ec852

File: models/Document/Dao.php (hunk 2 above)
Comment (blankse) [reply models/Document/Dao.php]: See https://github.com/pimcore/pimcore/pull/10320/commits/305e744f98535945e427f478b96ed5e513f540a6

File: models/Asset.php (hunk 3 above)
Comment (blankse) [reply models/Asset.php]: See https://github.com/pimcore/pimcore/pull/10320/commits/1f548009cd3c1b1357eaab98667609b3270b226e

File: models/Element/Traits/ScheduledTasksTrait.php [hunk 4]
```diff
@@ -59,20 +61,18 @@ public function setScheduledTasks($scheduledTasks)
         return $this;
     }
 
-    public function saveScheduledTasks()
+    public function saveScheduledTasks(): void
```
Comment (brusch) [inline models/Element/Traits/ScheduledTasksTrait.php]:
```suggestion
    public function saveScheduledTasks()
```
Adding the return type is a BC break.

**Review by brusch — CHANGES_REQUESTED** [review]

**Comment by brusch** [comment]
Well done - thanks a lot! 👍

**Comment by dasraab** [comment]
i think this is also an issue in v6.9.6 - at least i'm experiencing the same problem. scheduled task do not get set to active=false after they ran.
