### PR TITLE
[Data Objects] Fix API-saving unpublished with empty mandatory field throws exception

### LINKED ISSUE #6587: [Data Objects] API-saving unpublished with empty mandatory field throws exception
### Expected behavior
Saving unpublished data object via API with unset mandatory field should not throw ValidationException (just like when saving via the UI)

### Actual behavior
Pimcore\Model\Element\ValidationException is thrown if there is an empty mandatory field, even if data object is unpublished.

### PR DESCRIPTION
**Pull request by dvesh3**
## Changes in this pull request  
Resolves #6587

### CODE REVIEW

File: models/DataObject/Concrete.php [hunk 1]
```diff
@@ -78,7 +78,7 @@ class Concrete extends AbstractObject implements LazyLoadedFieldsInterface
     /**
      * @var bool
```
Comment (blankse) [inline models/DataObject/Concrete.php:79]:
```suggestion
     * @var bool|null
```
