### PR TITLE
[Bug]: Fixes "bin/console doctrine:migrations:migrate" error "The prefix option does not exist."

### LINKED ISSUE #16160: [Bug]: Console command "bin/console doctrine:migrations:migrate" fails with the error "The prefix option does not exist."
### Pimcore version

11.1.0

### Steps to reproduce

Actually I can't say who and why this happend. It's deep in the dependency injection somewhere. I'm glad for every hint where I can modify this befaviour.

The problem is that the command is not loaded as a real DoctrineCommand than as a LazyCommand, which will replaced later to the real DoctrineCommand. For this reason in \Pimcore\Console\Application::add the command is not recognized as DoctrineCommand and therefore the prefix option won't add. That causes the error.

### Actual Behavior

If you execute the console command "doctrine:migration:migrate" the command ends with an error:

>  The "prefix" option does not exist.

### Expected Behavior

The command works as expected.

### PR DESCRIPTION
**Pull request by kingjia90**
## Changes in this pull request  
Resolves https://github.com/pimcore/pimcore/issues/16160

## Additional info
Based on suggested solution on https://github.com/pimcore/pimcore/pull/16162#issuecomment-1808487067  and rebased https://github.com/pimcore/pimcore/pull/16162

### <samp>🤖 Generated by Copilot at bd3cccb</samp>

Support lazy commands in Pimcore console application. Fix `add` method to unwrap lazy command objects before adding them to the application.

### <samp>🤖 Generated by Copilot at bd3cccb</samp>

> _`add` method checks_
> _for lazy commands in spring_
> _unwrap them with care_

### <samp>🤖 Generated by Copilot at bd3cccb</samp>

*  Add support for lazy commands in the console application ([link](https://github.com/pimcore/pimcore/pull/16257/files?diff=unified&w=0#diff-f1b341f8c516eb5173d334d53d8890aecf4038817679a3ebebd734af044c6ea1R125-R128))

### CODE REVIEW

File: lib/Console/Application.php [hunk 1]
```diff
@@ -122,6 +122,10 @@ protected function getDefaultInputDefinition(): InputDefinition
 
     public function add(Command $command): ?Command
     {
+        if ($command instanceof LazyCommand) {
+            $command = $command->getCommand();
+        }
```
Comment (jdreesen) [inline lib/Console/Application.php]: Does this make all command non-lazy?

Comment (dvesh3) [reply lib/Console/Application.php]: Yes, this makes all doctrine commands non-lazy which shouldn't have have any impacts. This is the only solution we have at the moment to fix running the commands again.

Comment (dvesh3) [reply lib/Console/Application.php]: Also when calling `list` this initiates all commands including lazy ones so i would go with this fix.

Comment (jdreesen) [reply lib/Console/Application.php]: They haven't been lazy until `doctrine/migrations` `v3.6.1` anyway...

**Review by dvesh3 — APPROVED** [review]

**Comment by fashxp** [comment]
can confirm that is would also fix our platform version tests
