### PR TITLE
[Assets] Metadata Grid - fix 'ON' date filter

### LINKED ISSUE #5279: Assets List: Filter "IN" on CreationDate / ModificationDate field not working
### Expected behavior

Be able to use the "ON" filter on the modificationData/CreationDate filters to get the list of Assets created/modified for a provided date.

### Actual behavior
The filter "IN" doesn't works. Only the filters "Before" and "After" are currrently working

### Steps to reproduce

Pimcore V 6.3.1
Try to filter on "ON" Filter on the Asset List to get products created/modified for a provided date.
No results.

default_asset_list

asset_filter_in_not_working

Thanks in advance to fix it.

Regards,
Benjamin

### PR DESCRIPTION
**Pull request by dvesh3**
## Changes in this pull request  
Resolves #5279

### CODE REVIEW

File: bundles/AdminBundle/Helper/GridHelperService.php [hunk 1]
```diff
@@ -660,7 +660,14 @@ public function prepareAssetListingForGrid($allParams, $adminUser)
                     $language = str_replace(['none', 'default'], '', $language);
                     $conditionFilters[] = 'id IN (SELECT cid FROM assets_metadata WHERE `name` = ' . $db->quote($filterField) . ' AND `data` ' . $operator . ' ' . $value . ' AND `language` = ' . $db->quote($language). ')';
                 } else {
-                    $conditionFilters[] = $filterField . ' ' . $operator . ' ' . $db->quote($value);
+                    if ($filter['type'] == 'date' && $operator == '=') {
```
Comment (fashxp) [inline bundles/AdminBundle/Helper/GridHelperService.php]: can't we move this logic up to somewhere in between the lines 624-631 - then all date related filter logic would be together in one place.
