### PR TITLE
[Bug]: Fix locales-utf8 check on macOS under requirements check

### LINKED ISSUE #15505: [Bug]: locales-utf8 check on macOS results in error during requirements check
### Pimcore version

11.0.3

### Steps to reproduce

- Run ./vendor/bin/pimcore-install on a macOS Ventura 13.4.1 system with either the pimcore-skeleton or pimcore-demo.

### Expected / actual behavior

**Expected**:
The installer works for the locales that are on macOS Ventura 13.4.1.

**Actual Behaviour:**
The check that is currently run during installation checks for ['en.utf8', 'en_US.utf8', 'en_GB.utf8'], which are not present on the system, the notation of those locales are different on macOS -> ['UTF-8', 'en_US.UTF-8', 'en_GB.UTF-8']. This will therefore always result in a failed check and failed installation

These are available for macOS for en:
```
ls -la | grep en
drwxr-xr-x    8 root  wheel   256 Jun 15 12:08 en_AU
drwxr-xr-x    8 root  wheel   256 Jun 15 12:08 en_AU.ISO8859-1
drwxr-xr-x    8 root  wheel   256 Jun 15 12:08 en_AU.ISO8859-15
drwxr-xr-x    8 root  wheel   256 Jun 15 12:08 en_AU.US-ASCII
drwxr-xr-x    8 root  wheel   256 Jun 15 12:08 en_AU.UTF-8
drwxr-xr-x    8 root  wheel   256 Jun 15 12:08 en_CA
drwxr-xr-x    8 root  wheel   256 Jun 15 12:08 en_CA.ISO8859-1
drwxr-xr-x    8 root  wheel   256 Jun 15 12:08 en_CA.ISO8859-15
drwxr-xr-x    8 root  wheel   256 Jun 15 12:08 en_CA.US-ASCII
drwxr-xr-x    8 root  wheel   256 Jun 15 12:08 en_CA.UTF-8
drwxr-xr-x    8 root  wheel   256 Jun 15 12:08 en_GB
drwxr-xr-x    8 root  wheel   256 Jun 15 12:08 en_GB.ISO8859-1
drwxr-xr-x    8 root  wheel   256 Jun 15 12:08 en_GB.ISO8859-15
drwxr-xr-x    8 root  wheel   256 Jun 15 12:08 en_GB.US-ASCII
drwxr-xr-x    8 root  wheel   256 Jun 15 12:08 en_GB.UTF-8
drwxr-xr-x    8 root  wheel   256 Jun 15 12:08 en_IE
drwxr-xr-x    8 root  wheel   256 Jun 15 12:08 en_IE.UTF-8
drwxr-xr-x    8 root  wheel   256 Jun 15 12:08 en_NZ
drwxr-xr-x    8 root  wheel   256 Jun 15 12:08 en_NZ.ISO8859-1
drwxr-xr-x    8 root  wheel   256 Jun 15 12:08 en_NZ.ISO8859-15
drwxr-xr-x    8 root  wheel   256 Jun 15 12:08 en_NZ.US-ASCII
drwxr-xr-x    8 root  wheel   256 Jun 15 12:08 en_NZ.UTF-8
drwxr-xr-x    8 root  wheel   256 Jun 15 12:08 en_US
drwxr-xr-x    8 root  wheel   256 Jun 15 12:08 en_US.ISO8859-1
drwxr-xr-x    8 root  wheel   256 Jun 15 12:08 en_US.ISO8859-15
drwxr-xr-x    8 root  wheel   256 Jun 15 12:08 en_US.US-ASCII
drwxr-xr-x    8 root  wheel   256 Jun 15 12:08 en_US.UTF-8
```

And for UTF-8:

```
ls -la | grep UTF-8
drwxr-xr-x    3 root  wheel    96 Jun 15 12:08 UTF-8
drwxr-xr-x    8 root  wheel   256 Jun 15 12:08 af_ZA.UTF-8
drwxr-xr-x    8 root  wheel   256 Jun 15 12:08 am_ET.UTF-8
drwxr-xr-x    8 root  wheel   256 Jun 15 12:08 be_BY.UTF-8
drwxr-xr-x    8 root  wheel   256 Jun 15 12:08 bg_BG.UTF-8
drwxr-xr-x    8 root  wheel   256 Jun 15 12:08 ca_ES.UTF-8
drwxr-xr-x    8 root  wheel   256 Jun 15 12:08 cs_CZ.UTF-8
drwxr-xr-x    8 root  wheel   256 Jun 15 12:08 da_DK.UTF-8
drwxr-xr-x    8 root  wheel   256 Jun 15 12:08 de_AT.UTF-8
drwxr-xr-x    8 root  wheel   256 Jun 15 12:08 de_CH.UTF-8
drwxr-xr-x    8 root  wheel   256 Jun 15 12:08 de_DE.UTF-8
drwxr-xr-x    8 root  wheel   256 Jun 15 12:08 el_GR.UTF-8
drwxr-xr-x    8 root  wheel   256 Jun 15 12:08 en_AU.UTF-8
drwxr-xr-x    8 root  wheel   256 Jun 15 12:08 en_CA.UTF-8
drwxr-xr-x    8 root  wheel   256 Jun 15 12:08 en_GB.UTF-8
drwxr-xr-x    8 root  wheel   256 Jun 15 12:08 en_IE.UTF-8
drwxr-xr-x    8 root  wheel   256 Jun 15 12:08 en_NZ.UTF-8
drwxr-xr-x    8 root  wheel   256 Jun 15 12:08 en_US.UTF-8
drwxr-xr-x    8 root  wheel   256 Jun 15 12:08 es_ES.UTF-8
drwxr-xr-x    8 root  wheel   256 Jun 15 12:08 et_EE.UTF-8
drwxr-xr-x    8 root  wheel   256 Jun 15 12:08 eu_ES.UTF-8
drwxr-xr-x    8 root  wheel   256 Jun 15 12:08 fi_FI.UTF-8
drwxr-xr-x    8 root  wheel   256 Jun 15 12:08 fr_BE.UTF-8
drwxr-xr-x    8 root  wheel   256 Jun 15 12:08 fr_CA.UTF-8
drwxr-xr-x    8 root  wheel   256 Jun 15 12:08 fr_CH.UTF-8
drwxr-xr-x    8 root  wheel   256 Jun 15 12:08 fr_FR.UTF-8
drwxr-xr-x    8 root  wheel   256 Jun 15 12:08 he_IL.UTF-8
drwxr-xr-x    8 root  wheel   256 Jun 15 12:08 hr_HR.UTF-8
drwxr-xr-x    8 root  wheel   256 Jun 15 12:08 hu_HU.UTF-8
drwxr-xr-x    8 root  wheel   256 Jun 15 12:08 hy_AM.UTF-8
drwxr-xr-x    8 root  wheel   256 Jun 15 12:08 is_IS.UTF-8
drwxr-xr-x    8 root  wheel   256 Jun 15 12:08 it_CH.UTF-8
drwxr-xr-x    8 root  wheel   256 Jun 15 12:08 it_IT.UTF-8
drwxr-xr-x    8 root  wheel   256 Jun 15 12:08 ja_JP.UTF-8
drwxr-xr-x    8 root  wheel   256 Jun 15 12:08 kk_KZ.UTF-8
drwxr-xr-x    8 root  wheel   256 Jun 15 12:08 ko_KR.UTF-8
drwxr-xr-x    8 root  wheel   256 Jun 15 12:08 lt_LT.UTF-8
drwxr-xr-x    8 root  wheel   256 Jun 15 12:08 nl_BE.UTF-8
drwxr-xr-x    8 root  wheel   256 Jun 15 12:08 nl_NL.UTF-8
drwxr-xr-x    8 root  wheel   256 Jun 15 12:08 no_NO.UTF-8
drwxr-xr-x    8 root  wheel   256 Jun 15 12:08 pl_PL.UTF-8
drwxr-xr-x    8 root  wheel   256 Jun 15 12:08 pt_BR.UTF-8
drwxr-xr-x    8 root  wheel   256 Jun 15 12:08 pt_PT.UTF-8
drwxr-xr-x    8 root  wheel   256 Jun 15 12:08 ro_RO.UTF-8
drwxr-xr-x    8 root  wheel   256 Jun 15 12:08 ru_RU.UTF-8
drwxr-xr-x    8 root  wheel   256 Jun 15 12:08 sk_SK.UTF-8
drwxr-xr-x    8 root  wheel   256 Jun 15 12:08 sl_SI.UTF-8
drwxr-xr-x    8 root  wheel   256 Jun 15 12:08 sr_YU.UTF-8
drwxr-xr-x    8 root  wheel   256 Jun 15 12:08 sv_SE.UTF-8
drwxr-xr-x    8 root  wheel   256 Jun 15 12:08 tr_TR.UTF-8
drwxr-xr-x    8 root  wheel   256 Jun 15 12:08 uk_UA.UTF-8
drwxr-xr-x    8 root  wheel   256 Jun 15 12:08 zh_CN.UTF-8
drwxr-xr-x    8 root  wheel   256 Jun 15 12:08 zh_HK.UTF-8
drwxr-xr-x    8 root  wheel   256 Jun 15 12:08 zh_TW.UTF-8
```

### PR DESCRIPTION
**Pull request by kingjia90**
## Changes in this pull request  
Resolves https://github.com/pimcore/pimcore/issues/15505

### <samp>🤖 Generated by Copilot at 096e791</samp>

Improved locale check in `lib/Tool/Requirements.php` to support both Linux and MacOS formats of UTF-8 locale. This change is part of a pull request that fixes locale issues in pimcore.

### <samp>🤖 Generated by Copilot at 096e791</samp>

> _`pimcore` adapts_
> _to Linux and MacOS_
> _locale check in fall_

### <samp>🤖 Generated by Copilot at 096e791</samp>

* Fix locale check for MacOS and Linux formats ([link](https://github.com/pimcore/pimcore/pull/15612/files?diff=unified&w=0#diff-dfe29fe3b26573298372f467825b88de689af21021e590e9ab6868485cdde1c2L612-R623))

### CODE REVIEW

File: lib/Tool/Requirements.php [hunk 1]
```diff
@@ -609,10 +609,18 @@ public static function checkPhp()
             ]);
         }
 
+        $utfLocaleState = Check::STATE_ERROR;
+        if (
+            setlocale(LC_ALL, ['en.utf8', 'en_US.utf8', 'en_GB.utf8'])
```
Comment (dvesh3) [inline lib/Tool/Requirements.php]: This only checks the requirement. the actual usage is here https://github.com/pimcore/pimcore/blob/83142b53cfd5a791e3c6167470a66336fd03da22/lib/Console/Application.php#L59

File: lib/Console/Application.php [hunk 2]
```diff
@@ -55,7 +55,7 @@ public function __construct(KernelInterface $kernel)
         $this->setVersion(Version::getVersion());
 
         // we set locale to EN.UTF8 to not getting into UTF-8 issues, eg. when dealing with umlauts & escapeshellarg()
-        setlocale(LC_ALL, ['en.utf8', 'en_US.utf8', 'en_GB.utf8']);
+        setlocale(LC_ALL, ['en.utf8', 'en_US.utf8', 'en_GB.utf8']) ?: setlocale(LC_ALL, ['en.UTF-8', 'en_US.UTF-8', 'en_GB.UTF-8']);
```
Comment (brusch) [inline lib/Console/Application.php]:
```suggestion
        setlocale(LC_ALL, ['en.utf8', 'en_US.utf8', 'en_GB.utf8', 'en.UTF-8', 'en_US.UTF-8', 'en_GB.UTF-8']);
```

Comment (brusch) [reply lib/Console/Application.php]: This should do the trick as well 😊

**Review by brusch — CHANGES_REQUESTED** [review]

**Comment by dvesh3** [comment]
@rolfhermancoen could you please confirm if this fixes the locale issue for you on macOS? thanks!
