### PR TITLE
[Assets] Update children path on remote storage

### LINKED ISSUE #9367: Asset paths not updated after S3 setup
Expected Behaviour

If you move an asset folder with its content in the directory tree then the full path of the folder and the assets should be updated respectively 

Actual behaviour
If you setup S3 file storage and move an asset folder with its content in the directory tree then the full path of the folder is being updated but the full path of the the assets inside the folder does not change.

Example:
Original Pimcore X Asset Directory
 
image

Move /Hrs/Anw/sample.jpg => /Media/Images/Detail/Anw/sample.jpg

 
image

Expected full path: /Media/Images/Detail/Anw/sample.jpg

Actual path: /Hrs/Anw/sample.jpg

Steps to reproduce:

1. Right click on specific asset folder and select “Cut”
2. Right click on destination folder and select “Paste cut-out element”
3. Left click on specific asset in the moved folder and from the menu “copy full path to clipboard”

### PR DESCRIPTION
**Pull request by dvesh3**
## Changes in this pull request  
Resolves #9367

### CODE REVIEW

File: models/Asset.php [hunk 1]
```diff
@@ -1963,6 +1964,34 @@ public function clearThumbnails($force = false)
...
     }
 
+    /**
+     * @param string $oldPath
+     *
+     * @return array
+     *
+     * @throws \League\Flysystem\FilesystemException
+     */
+    private function updateChildPaths(string $oldPath)
```
Comment (brusch) [inline models/Asset.php]: Just moving the parent folder should be enough, right? Because all children of the parent will be moved anyway when calling `$storage->move()` for it, or what is the reason for that? 
If not we'd have to think about a more robust solution, because this only works for a certain amount of children (I'm just thinking about a folder with millions of assets in it 😁).

**Review by brusch — CHANGES_REQUESTED** [review]

File: models/Asset.php (hunk 1 above)
Comment (dvesh3) [reply models/Asset.php]: `$storage->move()` fails when you move a sub folder to another folder(S3 does not allow you to move directories), so this is required so that children of parent folder are also moved as well.
