### PR TITLE
fix: disable login throttling on AdminSessionAuthenticator #15671

### LINKED ISSUE #15671: [Bug]: 10.6 AdminSessionAuthenticator broken
AdminSessionAuthenticator keeps getting called on every request that is made when logged in. This triggers the Login Throttling and therefore some requests might failed with "too many login attempts". 

In Pimcore 11, this was changed to use normal form_login, I couldn't find the PR though and I am not sure if this can be fixed in a minor release.

Our solution was to increase the rate limit for the login, but this isn't the best solution to the problem.

### PR DESCRIPTION
**Pull request by youwe-petervanderwal**
## Changes in this pull request  
Resolves #15671

## Additional info
@dvesh3 @dpfaffenbauer I saw your discussion going on within the issue and was able to reproduce this bug. I also already noticed this issue on one of our production environments so for me fixing this had some priority. Decorating the rate limiter service can fix this bug. Because Symfony creates a rate limiter per firewall, these changes only affects the "pimcore_admin" firewall.

Tested with both "enable_authenticator_manager: true" as the legacy authenticator

### CODE REVIEW

**Comment by dvesh3** [comment]
Thanks @youwe-petervanderwal we'll take a look and most probably consider this for last bugfix release for 10.6.

File: bundles/AdminBundle/RateLimiter/AdminRequestRateLimiter.php [hunk 1]
```diff
@@ -0,0 +1,52 @@
...
+namespace Pimcore\Bundle\AdminBundle\RateLimiter;
+
+use Pimcore\Bundle\AdminBundle\Security\Authenticator\AdminSessionAuthenticator;
+use Symfony\Component\HttpFoundation\RateLimiter\RequestRateLimiterInterface;
+use Symfony\Component\HttpFoundation\Request;
+use Symfony\Component\RateLimiter\Policy\NoLimiter;
+use Symfony\Component\RateLimiter\RateLimit;
+
+/**
+ * Disables rate limit on the \Pimcore\Bundle\AdminBundle\Security\Authenticator\AdminSessionAuthenticator
```
Comment (dvesh3) [inline bundles/AdminBundle/RateLimiter/AdminRequestRateLimiter.php:28]:
```suggestion
 * @internal
 * Disables rate limit on the \Pimcore\Bundle\AdminBundle\Security\Authenticator\AdminSessionAuthenticator
```
so that we can easily kick it in later version.

File: bundles/AdminBundle/Resources/config/security_services.yaml [hunk 2]
```diff
@@ -36,6 +36,13 @@ services:
             version: '10.6'
             message: 'The "%service_id%" service is deprecated and will be removed in Pimcore 11.'
 
+    # Decorate RequestRateLimiter to skik rate limiting on the AdminSessionAuthenticator
```
Comment (dvesh3) [inline bundles/AdminBundle/Resources/config/security_services.yaml]:
```suggestion
    # Decorate RequestRateLimiter to skip rate limiting on the AdminSessionAuthenticator
```

**Comment by dvesh3** [comment]
The changes looks good to me. @dpfaffenbauer could you please confirm if this fixes the issue for you? thanks!

**Comment by dpfaffenbauer** [comment]
@youwe-petervanderwal @dvesh3 f*** yeah, that works! I would never have thought about fixing it that way. Very, very good job @youwe-petervanderwal. That is a 🍺 from me to you ;)

**Review by dvesh3 — APPROVED** [review]

**Comment by dvesh3** [comment]
@youwe-petervanderwal nice work 🥇 thank you very much! 💜

**Comment by dpfaffenbauer** [comment]
🎉

**Comment by youwe-petervanderwal** [comment]
Thank you too @dpfaffenbauer and @dvesh3 for the investigations in the issue report. That really helped me where to look for a solution.

And thanks for you kind words in the comments above :blush:
