### PR TITLE
[Bug]: Fix `pimcore_relations` editable displaying folders as variants

### LINKED ISSUE #17046: [Bug]: pimcore_relations does not accept more than one folder after reload in the back-end.
### Pimcore version

11.1.3

### Steps to reproduce

Create a relation (doesn't matter if it's a editable dialog box or not). Drag in two folder's and save & publish. Now the relation will show objects of both folders. If you reload the page in the back-end, you will only see the last added folder in the relation. At this moment it will still show objects of both folders. Now if you save & publish again while there is only one folder in the relation, it will only display objects of the last added folder.

### Actual Behavior

pimcore_relation only accepts one folder with objects.

### Expected Behavior

Should accept more than one folder.

### PR DESCRIPTION
**Pull request by kingjia90**
## Changes in this pull request  
Resolves https://github.com/pimcore/pimcore/issues/17046

### CODE REVIEW

**Comment by blankse** [comment]
Target branch should bei `11.2`

File: models/Document/Editable/Relations.php [hunk 1]
```diff
@@ -86,7 +86,7 @@ public function getDataEditmode(): array
             if ($element instanceof DataObject\Concrete) {
                 $return[] = [$element->getId(), $element->getRealFullPath(), DataObject::OBJECT_TYPE_OBJECT, $element->getClassName()];
             } elseif ($element instanceof DataObject\AbstractObject) {
-                $return[] = [$element->getId(), $element->getRealFullPath(), DataObject::OBJECT_TYPE_OBJECT, DataObject::OBJECT_TYPE_VARIANT, DataObject::OBJECT_TYPE_FOLDER];
+                $return[] = [$element->getId(), $element->getRealFullPath(), DataObject::OBJECT_TYPE_OBJECT, $element->getType()];
```
Comment (kingjia90) [inline models/Document/Editable/Relations.php]: Theoretically should be 
```suggestion
                $return[] = [$element->getId(), $element->getRealFullPath(), DataObject::OBJECT_TYPE_OBJECT, DataObject::OBJECT_TYPE_FOLDER];
```
to be consistent with the frontend
https://github.com/pimcore/admin-ui-classic-bundle/blob/1976b8f869ad450e1b3d2b9e4aebcc47f3487e7e/public/js/pimcore/document/editables/relations.js#L275
and reverting the bug cause
