### PR TITLE
Fix: Web2Print processor type error

### LINKED ISSUE #14328: [Bug]: Web2Print processor type error
### Expected behavior

Fix type error

### Actual behavior

image

### Steps to reproduce

- Go to Settings->Web-to-Print Settings
- Select for Tool: PDFreactor
- Save & reload
- Test the settings

### PR DESCRIPTION
**Pull request by blankse**
Fix https://github.com/pimcore/pimcore/issues/14328
Regression from https://github.com/pimcore/pimcore/pull/14208

### CODE REVIEW

File: lib/Web2Print/Processor/HeadlessChrome.php [hunk 1]
```diff
@@ -113,8 +113,8 @@ public function getPdfFromString($html, $params = [], $returnFilePath = false)
         $converter = new Converter($input, $output);
         if ($this->nodePath) {
             $converter->setNodePath($this->nodePath);
-        } else {
-            $converter->setNodePath(Console::getExecutable('node'));
+        } elseif ($nodePath = Console::getExecutable('node')) {
```
Comment (mattamon) [inline lib/Web2Print/Processor/HeadlessChrome.php:116]: Does this really change anything? The `$nodePath` can still be `true` and therefore will fail?

Comment (jdreesen) [reply lib/Web2Print/Processor/HeadlessChrome.php:116]: `Console::getExecutable()` returns `string|false`

**Comment by lukmzig** [comment]
Thank you for the fix @blankse
