### PR TITLE
[Bug]: Cleanup FC and Bricks Stores on lower-case DB Servers

### LINKED ISSUE #12101: [Bug]: Cleanup FC and Bricks Stores on lower-case DB Servers
Pimcore's cleanup tasks checks for tables like 'object_collection_%' and 'object_brick_%',  extrudes the brick/collection name from that and checks if the brick/collection in Pimcore exists. That doesn't work with Database Servers that are lower-case by default. Pimcore then logs "Fieldcollection 'coreshoptaxitem' not found. Please check table object_collection_coreshoptaxitem_cs_order_item".

Pimcore should rather ignore the case for this task.

### PR DESCRIPTION
**Pull request by robertSt7**
resolves #12101

### CODE REVIEW

File: tests/Model/DataObject/DefinitionModifierTest.php [hunk 1]
```diff
@@ -476,4 +476,22 @@ private static function getMethod($class, $name)
...
+            $checkVal = $classDef->getByIdIgnoreCase($id);
+
+            $this->assertNull($checkVal);
+    }
+
+    public function testGetByIdIgnoreCaseWithValidId()
+    {
+        $id = 'Inheritance';
+        $classDef = new ClassDefinition();
+        $checkVal = $classDef->getByIdIgnoreCase($id);
```
Comment (mcop1) [inline tests/Model/DataObject/DefinitionModifierTest.php:493]:
```suggestion
        $checkVal = ClassDefinition::getByIdIgnoreCase($id);
```

Comment (mcop1) [inline tests/Model/DataObject/DefinitionModifierTest.php]:
```suggestion
        $checkVal = ClassDefinition::getByIdIgnoreCase($id);
```

File: tests/Model/DataObject/DefinitionModifierTest.php [hunk 2]
```diff
@@ -476,4 +476,22 @@ private static function getMethod($class, $name)
 
         return $method;
     }
+
+    public function testGetByIdIgnoreCaseWithoutValidId()
+    {
+            $id = '-9999';
+            $classDef = new ClassDefinition();
+            $checkVal = $classDef->getByIdIgnoreCase($id);
```
Comment (mcop1) [inline tests/Model/DataObject/DefinitionModifierTest.php]:
```suggestion
            $checkVal = ClassDefinition::getByIdIgnoreCase($id);
```

**Review by mcop1 — COMMENTED** [review]
Since the method is static I would call it that way. What do you think?
