### PR TITLE
Fix: Return all possible types and subtypes for mime type

### LINKED ISSUE #14003: [Bug]: Mime type error when uploading a new image in ImageGallery object
### Expected behavior

Upload new image at imageGallery directly. 

### Actual behavior

Pimcore throws an error:

`
{"success":false,"message":"Mime type does not match with asset type: hotspotimage"}`

### Steps to reproduce

Add a new element in object imageGallery. Click on Hamburger-Menu and upload a new image. 
This happens on official pimcore demo site, too.

### PR DESCRIPTION
**Pull request by mattamon**
## Changes in this pull request  
Resolves #14003 

## Additional info  
`getTypeFromMimeMapping` does not return all subtypes for a mime type e.g. it return image for an hotspot image.
`getTypeFromMimeMapping` has now a third parameter which is the mapping itself which can be changed

### CODE REVIEW

**Comment by mattamon** [comment]
Are there any other subtypes like hotspot image that need to be accounted for?

File: models/Asset.php [hunk 1]
```diff
@@ -65,6 +65,40 @@ class Asset extends Element\AbstractElement
     use ScheduledTasksTrait;
     use TemporaryFileHelperTrait;
 
+    /**
+     * maps mimetype to type
+     *
+     * @internal
+     *
+     * @var array
```
Comment (blankse) [inline models/Asset.php]:
```suggestion
     * @var array<string, string[]>
```

File: models/Asset.php [hunk 2]
```diff
@@ -65,6 +65,40 @@ class Asset extends Element\AbstractElement
...
+        'document' => ['/msword/', '/pdf/', '/powerpoint/', '/office/', '/excel/', '/opendocument/'],
+        'archive' => ['/zip/', '/tar/'],
+    ];
+
+    /**
+     * maps mimetype to type
+     *
+     * @internal
+     *
+     * @var array
```
Comment (blankse) [inline models/Asset.php]:
```suggestion
     * @var array<string, string[]>
```

File: models/Asset.php [hunk 3]
```diff
@@ -431,24 +465,14 @@ public static function getTotalCount($config = [])
      *
      * @return string
      */
-    public static function getTypeFromMimeMapping($mimeType, $filename)
+    public static function getTypeFromMimeMapping($mimeType, $filename, $mappings = self::TYPE_TO_MIME_MAPPING)
```
Comment (blankse) [inline models/Asset.php]:
```suggestion
    public static function getTypeFromMimeMapping($mimeType, $filename, array $mappings = self::TYPE_TO_MIME_MAPPING)
```

File: models/Asset.php [hunk 4]
```diff
@@ -431,24 +465,14 @@ public static function getTotalCount($config = [])
      *
```
Comment (blankse) [inline models/Asset.php]:
```suggestion
     * @param array<string, string[]> $mappings
     *
```

File: bundles/AdminBundle/Controller/Admin/Asset/AssetController.php [hunk 5]
```diff
@@ -531,9 +531,9 @@ protected function addAsset(Request $request, Config $config)
         $type = $request->get('type');
         if ($type) {
             $mimetype = MimeTypes::getDefault()->guessMimeType($sourcePath);
-            $assetType = Asset::getTypeFromMimeMapping($mimetype, $filename);
+            $possibleAssetTypes = Asset::getTypeFromMimeMapping($mimetype, $filename, Asset::TYPE_WITH_SUBTYPES_TO_MIME_MAPPING);
 
-            if ($type !== $assetType) {
+            if (strpos($possibleAssetTypes, $type) === false) {
```
Comment (jdreesen) [inline bundles/AdminBundle/Controller/Admin/Asset/AssetController.php]:
```suggestion
            if (!str_contains($possibleAssetTypes, $type)) {
```

**Comment by brusch** [comment]
@mattamon but `hotspotimage` is not a type, what is it used for, wouldn't it be better to force for `image` in that case?

**Comment by mattamon** [comment]
@brusch when you upload an image to the gallery via the hamburger menu the "type" is [hotspotimage](https://github.com/pimcore/pimcore/blob/10.5/bundles/AdminBundle/Resources/public/js/pimcore/object/tags/hotspotimage.js) and the `getTypeFromMimeMapping ` method returns "image".

Should we change the type in the hotspotimage.js to image?

**Comment by brusch** [comment]
@mattamon I think we should change that in hotspotimage.js ...

File: bundles/AdminBundle/Resources/public/js/pimcore/object/tags/hotspotimage.js [hunk 6]
```diff
@@ -14,7 +14,7 @@
 pimcore.registerNS("pimcore.object.tags.hotspotimage");
 pimcore.object.tags.hotspotimage = Class.create(pimcore.object.tags.image, {
 
-    type: "hotspotimage",
+    type: "image",
```
Comment (brusch) [inline bundles/AdminBundle/Resources/public/js/pimcore/object/tags/hotspotimage.js]: @mattamon I'm wondering why this `type` has an effect on the asset upload, can you maybe share the details on that? Thanks :)

**Review by brusch — CHANGES_REQUESTED** [review]

File: bundles/AdminBundle/Resources/public/js/pimcore/object/tags/hotspotimage.js (hunk 6 above)
Comment (mattamon) [reply bundles/AdminBundle/Resources/public/js/pimcore/object/tags/hotspotimage.js]: Sure :) It was party of this issue https://github.com/pimcore/pimcore/issues/13000

In this PR https://github.com/pimcore/pimcore/pull/13726 we added the type to `assetSingleUploadDialog` in the helpers.js This was needed to check the type in the backend to make sure e.g. that you cannot upload a PDF to an image tag. 
In the backend we then check for the type https://github.com/pimcore/pimcore/pull/13726/files#diff-8a94426359af1cadbcb7fdeb7af5731ce2ac295a758ed07a38d36db9d5d85ff9R531 and if the type does not match we throw an exception. 

The hotspotimage extends the image so it uses the same functionality and that's why it is failing in the upload dialog.

Comment (brusch) [reply bundles/AdminBundle/Resources/public/js/pimcore/object/tags/hotspotimage.js]: @mattamon ah, ok, this comes from the inherited method from `image.js` 😉 
So we shouldn't change the type then in `hotspotimage.js` but we should just use hardcoded `image` here as the value: 
https://github.com/pimcore/pimcore/blob/4f476328570738270892bda7d785d21617012dbe/bundles/AdminBundle/Resources/public/js/pimcore/object/tags/image.js#L278 

Because this value doesn't have to do anything with the actual data-type, it just specifies the type expected for the upload ...

Comment (mattamon) [reply bundles/AdminBundle/Resources/public/js/pimcore/object/tags/hotspotimage.js]: Should we also rename it to `uploadType` then to make it more clear?

Comment (brusch) [reply bundles/AdminBundle/Resources/public/js/pimcore/object/tags/hotspotimage.js]: @mattamon makes sense, yes, maybe even `uploadAssetType` to be even more clear 😊

**Review by dvesh3 — APPROVED** [review]
