### PR TITLE
[Bug]: Objectbricks ManyToOneRelation throws warning if no relations are present. #9900

### LINKED ISSUE #9900: Objectbricks ManyToOneRelation throws warning if no relations are present.
### Expected behavior

Opening an object in the backend with an object brick that has a many-to-one relation without a relation should open.

### Actual behavior

When the object is opened and there is no relation present, the following error is presented.
`Warning: Undefined array key 0`

Happens cause relations can be empty but is not checked for empty on.
vendor/pimcore/pimcore/models/DataObject/ClassDefinition/Data/Objectbricks.php:251

### Steps to reproduce

Open an object in the backend that has an object brick with a many-to-one relation field that has no value.

### PR DESCRIPTION
**Pull request by weisswurstkanone**
Resolves #9900

### CODE REVIEW

File: models/DataObject/ClassDefinition/Data/Objectbricks.php [hunk 1]
```diff
@@ -247,7 +247,7 @@ private function getDataForField($item, $key, $fielddefinition, $level, $baseObj
             }
             $data = [];
 
-            if ($fielddefinition instanceof ManyToOneRelation) {
+            if ($fielddefinition instanceof ManyToOneRelation && count($relations) > 0) {
```
Comment (dvesh3) [inline models/DataObject/ClassDefinition/Data/Objectbricks.php]:
```suggestion
            if ($fielddefinition instanceof ManyToOneRelation && isset($relations[0])) {
```
