### PR TITLE
Fix snippet personalized content content cleanup

### LINKED ISSUE #4002: [Document] Delete Personalized Content on snippets
### Expected behavior
Personalized content on snippets get deleted on Clear content of current view / of selected Target Group after save & publish and reload.

### Actual behavior
Personalized content on snippets don't get deleted on Clear content of current view / of selected Target Group after save & publish and reload.

### Steps to reproduce

1. Create snippet and create some default content
2. Create Target Group and Global Targeting Rule
3. Edit Content for that Target Group, save the changes and reload
4. Edit Content for that Target Group again
5. Clear content of current view (or Clear content of selected Target Groups), Save and Publish and reload
6. Go back to the target group content and content is still there

### PR DESCRIPTION
**Pull request by dvesh3**
## Changes in this pull request  
Resolves #4002

### CODE REVIEW

File: bundles/AdminBundle/Controller/Admin/Document/SnippetController.php [hunk 1]
```diff
@@ -106,7 +108,31 @@ public function saveAction(Request $request)
         try {
             if ($request->get('id')) {
                 $snippet = Document\Snippet::getById($request->get('id'));
-                $snippet = $this->getLatestVersion($snippet);
+
+                // check if there's a document in session which should be used as data-source
+                // see also PageController::clearEditableDataAction() | this is necessary to reset all fields and to get rid of
+                // outdated and unused data elements in this document (eg. entries of area-blocks)
+                $snippetSession = Session::useSession(function (AttributeBagInterface $session) use ($snippet) {
```
Comment (brusch) [inline bundles/AdminBundle/Controller/Admin/Document/SnippetController.php]: @dvesh3 To avoid duplicate code we should move this function to `DocumentControllerBase` and use it in both `PageController` and `SnippetController`, that should be easily possible as far as I can see. 
Thanks!

Comment (dvesh3) [reply bundles/AdminBundle/Controller/Admin/Document/SnippetController.php]: done!
