### PR TITLE
Fix: Ceil():Argument #1 ($num) must be of type int|float, null given when uploading video

### LINKED ISSUE #15611: [Bug]: Ceil():Argument #1 ($num) must be of type int|float, null given  when uploading video
### Discussed in https://github.com/pimcore/pimcore/discussions/15601

<div type='discussions-op-text'>

<sup>Originally posted by **YaseeraCentric** July 24, 2023</sup>
ceil():Argument #1 ($num) must be of type int|float, null given  when uploading video using pimcore Video editable in pimcore version 11</div>

### PR DESCRIPTION
**Pull request by blankse**
Fix https://github.com/pimcore/pimcore/issues/15611

### CODE REVIEW

File: models/Document/Editable/Video.php [hunk 1]
```diff
@@ -1045,6 +1028,30 @@ private function getHtml5Code($urls = [], $thumbnail = null)
         return $code;
     }
 
+    private static function getDurationString(float $duration): string
```
Comment (robertSt7) [inline models/Document/Editable/Video.php]: Hi @blankse is there a reason why this function is static?

Comment (blankse) [reply models/Document/Editable/Video.php]: @robertSt7 No, the method doesn't need the object. We can move it in a helper so we can reuse it. Or do you prefer hold it private without static?

**Comment by YaseeraCentric** [comment]
is this fixed now?Actually i have to make the site live

**Comment by blankse** [comment]
@YaseeraCentric No, the PR is still open and not merged. When it is merged you have to wait for the next release. Should be the 3rd August.

Until then, you can manually patch the line of code.

**Comment by YaseeraCentric** [comment]
ok @blankse where do i have to make the change?

**Comment by blankse** [comment]
@YaseeraCentric `vendor/pimcore/pimcore/models/Document/Editable/Video.php`

**Comment by YaseeraCentric** [comment]
@blankse on which line on this file? and what change i have to make?

**Comment by blankse** [comment]
@YaseeraCentric See the "Files changed" tab in this PR:
https://github.com/pimcore/pimcore/pull/15621/files

**Comment by YaseeraCentric** [comment]
Thanks @blankse, working now.

File: models/Document/Editable/Video.php (hunk 1 above)
Comment (robertSt7) [reply models/Document/Editable/Video.php]:
```suggestion
    private function getDurationString(float $duration): string
```

@blankse You need an instance to call this function, because it is private. I think we should remove the static. What is your opinion about that?

Comment (blankse) [reply models/Document/Editable/Video.php]: @robertSt7 I changed it https://github.com/pimcore/pimcore/pull/15621/commits/7fbfc2a22af0102ca51a0cad64988828871707f3

**Comment by robertSt7** [comment]
@blankse Thanks for the PR :)

**Comment by YaseeraCentric** [comment]
may i update the pimcore now to get these changes? im currently having 11.6 version @blankse

**Comment by blankse** [comment]
@YaseeraCentric No, version 10.6.7 has not been released yet.

**Comment by YaseeraCentric** [comment]
did you make the changes in version 10? or it will be reflected in version 11 also? @blankse

**Comment by blankse** [comment]
@YaseeraCentric It will also be part of 11.0.6 and 11.1.0, but these are also not yet released.
