### PR TITLE
Fixing getClasses() in ReverseObjectRelation

### LINKED ISSUE #620: [Improvement]: Add admin async loading to reverseObjectRelation
### Description
There is at the moment an "Enable Async Load in Admin" option in ManyToManyObjectRelations but no such in ReverseObjectRelation. It would be nice to have async loading when there are many objects loading in grid.
There is also an issue I have in projects where an object with a reverse relation grid related to many objects takes a lot of time to load.

### Action
I am opening PRs in pimcore and admin-ui-bundle

### Screenshot
pimcore-async-admin

### PR's
https://github.com/pimcore/admin-ui-classic-bundle/pull/535
https://github.com/pimcore/pimcore/pull/17072

### LINKED ISSUE #17071: [Improvement]: Add admin async loading to reverseObjectRelation
### Description
There is at the moment an "Enable Async Load in Admin" option in ManyToManyObjectRelations but no such in ReverseObjectRelation. It would be nice to have async loading when there are many objects loading in grid.
There is also an issue I have in projects where an object with a reverse relation grid related to many objects takes a lot of time to load.

### Action
I am opening PRs in pimcore and admin-ui-bundle

### Screenshot
pimcore-async-admin

### PR DESCRIPTION
**Pull request by sl0wlydeadly**
## Changes in this pull request  
Helps resolving pimcore/admin-ui-classic-bundle#620

### CODE REVIEW

**Comment by sl0wlydeadly** [comment]
recheck

**Comment by sl0wlydeadly** [comment]
I have read the CLA Document and I hereby sign the CLA

File: models/DataObject/ClassDefinition/Data/ReverseObjectRelation.php [hunk 1]
```diff
@@ -199,7 +199,7 @@ public function getFieldType(): string
 
     public function getClasses(): array
     {
-        if($this->ownerClassId) {
+        if(!empty($this->ownerClassName)) {
```
Comment (blankse) [inline models/DataObject/ClassDefinition/Data/ReverseObjectRelation.php]: empty() is not needed. Attribute is always set.
```suggestion
        if ($this->ownerClassName) {
```

Comment (sl0wlydeadly) [reply models/DataObject/ClassDefinition/Data/ReverseObjectRelation.php]: I now added your suggested change. Also I think the $ownerClassId logic needs to be reevaluated. As far as I saw, it is only set in getOwnerClassId() and that if certain if conditions are met.

**Comment by fashxp** [comment]
@sl0wlydeadly now, actually just a bugfix remains in that PR, right? 
So can we update the title and description of that PR and change target to 11.3? 
Then it is ready to merge.

**Comment by sl0wlydeadly** [comment]
@fashxp Hmm I will take a closer look, it says it failed some tests although the tests had something to do with translations, not sure how it all connects. I will check it and test it some more.

**Comment by sl0wlydeadly** [comment]
The title also needs to be changed, after reevaluating it had nothing to do with enrichLayoutDefinition. I only had to work on the getClasses method

**Comment by fashxp** [comment]
> @fashxp Hmm I will take a closer look, it says it failed some tests although the tests had something to do with translations, not sure how it all connects. I will check it and test it some more.

failing tests are not related... when you just merge current 11.3 branch into your branch it should be fixed.

**Comment by fashxp** [comment]
> The title also needs to be changed, after reevaluating it had nothing to do with enrichLayoutDefinition. I only had to work on the getClasses method

jup, but the fix still seems to be necessary for the reverse relations to work properly...

File: models/DataObject/ClassDefinition/Data/ReverseObjectRelation.php [hunk 2]
```diff
@@ -199,7 +199,7 @@ public function getFieldType(): string
 
     public function getClasses(): array
     {
-        if($this->ownerClassId) {
+        if($this->getOwnerClassId()) {
```
Comment (sl0wlydeadly) [inline models/DataObject/ClassDefinition/Data/ReverseObjectRelation.php:202]: After testing and reviewing, I believe this is the best solution to keep the previous logic while safe calling ownerClassId so that it is not null.

**Comment by fashxp** [comment]
Now it looks good. Thx very much!!
